### ISSUE TITLE
Vibration on DualShok/ DualSense

### ISSUE THREAD

**Issue by wanted8x** [Ryochan7/DS4Windows#2439] opened 2022-06-29 20:40 UTC
Hi, can you Enable Vibration on DS4/DualSense Controller? ViGEmBus driver has become Update. 

Your Text: Disabled broken DS4 feedback support again. Can't have semi-nice things. Don't bring it up again until at least the next ViGEmBus driver update...

Thanks for your Time

**Comment by Masamune3210** [comment] 2022-06-30 01:00
Vibration has been back for some time now.....

**Comment by wanted8x** [comment] 2022-06-30 05:33
No, on last version 3.0.18 it doesnt work, in games. 
i use 3.0.10. this is only the version how it worked. 

Version 3.0.11 and up, has no Vibration

**Comment by wanted8x** [comment] 2022-06-30 05:42
Changelog from version 3.0.11; 
Disabled broken DS4 feedback support again. Can't have semi-nice things. Don't bring it up again until at least the next ViGEmBus driver update.

**Comment by wanted8x** [comment] 2022-06-30 13:21
On Bluetooth?? No, it worked only with USB Cable.

**Comment by wanted8x** [comment] 2022-06-30 13:52
Version 3.0.10 works great. 
Same config; with 3.0.11 and up it doesnt worked via BT. 
in both config is Virtual DS4 on 
its all same config with earlier version

**Comment by wanted8x** [comment] 2022-06-30 13:54
Okay then I'll keep using the old version

**Comment by wanted8x** [comment] 2022-06-30 14:03
In profile is Virtual DS4 enable, and it worked via BT in 3.0.10.
You can test it.

**Comment by Ryochan7** [comment] 2022-06-30 16:51
I believe I re-enabled the vibration routine for the virtual DS4 shortly before the rage quit with version 3.0.18. Been a while so I should double check and make sure that is the case.

Also, I just checked over the current ViGEmBus code and the root problem with DS4 vibration **has not been addressed**. It still looks like there is no way to retrieve the full output report payload so the features bytes from the report can be checked. That byte is necessary to determine if a payload should be considered a lightbar change, rumble motor change, or possibly both. I reported on the initial problem on the ViGEmBus repo back around February 2021 IIRC; the issue is still open on the ViGEmBus GitHub issue tracker.

On the plus side, it looks like the way notification data is sent to clients has changed so maybe the old notification queue in the ViGEmClient isn't really necessary for the most recent version of ViGEmBus (1.18.367.0). Would still keep it in as ViGEmBus 1.17.333.0 would still need it and it should not affect the behavior in the current release.

**Comment by wanted8x** [comment] 2022-06-30 18:42
Hmm Okay thanks for your time. 
I‘ll keep using the old version (3.0.10)

**Comment by Ryochan7** [comment] 2022-07-07 10:53
Never had that problem with the DualSense. Did you try rumble using something like the Test Rumble buttons or in some game? Using the Test Rumble buttons in the Profile Editor would help show if something is happening within DS4Windows itself or maybe if a ViGEm feedback notification thread has gotten stuck which has happened in the past.

**Comment by Ryochan7** [comment] 2022-07-07 11:04
I am pretty sure I am sticking with my decision to keep virtual DS4 rumble disabled going forward. The feature has never worked as intended. Can't even go about trying to fix it. It is rare to have an Open Source project with the Cathedral model but they clearly exists.

http://www.catb.org/~esr/writings/cathedral-bazaar/

**Comment by coolllman** [comment] 2022-07-08 03:17
Ds4 mode vibration work good on 3.0.10, with no any problem, why not let users choose?  Leave it off by default and add a warning about possible problems.

**Comment by Masamune3210** [comment] 2022-07-08 04:17
Because people either cant read or wont put the effort in, either way the outcome is the same. People ignore the warning, get annoyed that it isn't working, report a issue and take up time, or somewhat worse, go around trashing the program for it not working after it said it might not work

**Comment by reecespieces** [comment] 2022-08-03 14:43
I'm using the latest version of DS4Windows and the rumble did come back for me in a recent update.

It was pretty buggy with ViGEmBus 1.16.116.

I upgraded to the latest ViGEmBus and it's better but still some issues. Mainly noticing them in dolphin if I try to use both motors.

**Comment by nefarius** [comment] 2022-08-08 17:45
> Not my bug, I have no means to fix it, and the newest ViGEmBus driver did not address the problem.

Is fixed 👍

**Comment by Yohoki** [comment] 2022-08-08 18:30
Would like to clarify, before we get people saying "Nefarius said it's fixed! Why no working?"

The ViGEmBus driver is fixed. DS4Windows needs to be updated to support the new features. Please be patient. :)

Also, thanks for the update, Nefarius!

**Comment by nefarius** [comment] 2022-08-08 18:36
> Would like to clarify, before we get people saying "Nefarius said it's fixed! Why no working?"
> 
> The ViGEmBus driver is fixed. DS4Windows needs to be updated to support the new features. Please be patient. :)

Yes, that is a very important distinction! 😉 Plus the latest driver needs to circulate and be pushed to affected users etc. etc. etc.

In essence: **patience**.

**Comment by Ryochan7** [comment] 2022-08-16 21:54
Plenty of prerequisites going into possibly making the change. Need to go up the whole client SDK stack and add the custom changes that DS4Windows uses. Performance tests and probably other tasks before possibly adding the new feedback hook for applicable ViGEmBus versions; already know that later Fody versions used in ViGEm.NET kill performance significantly. Going to take a while especially since I haven't spent much time on this project lately. Been spending many hours biking every day.

Super Bummerman 2 (retsupurae)
https://youtu.be/OC1SzVR5zeo?t=320

**Comment by nefarius** [comment] 2022-08-16 22:17
> Been spending many hours biking every day.

Sounds like a healthy alternative to coding.

> already know that later Fody versions used in ViGEm.NET kill performance significantly.

If you'd tell me more about that I could improve upon it. Never gave Fody another look since its only involvement is loading the embedded native DLLs in memory, nothing more.

**Comment by Ryochan7** [comment] 2022-08-19 14:06
Getting around to working on those prerequisites. Rebased the custom changes on top of the current upstream ViGEmClient and ViGEm.NET code. Ended up finding a way to get Fody to behave better with a tweak to the ViGEm.NET proj file; stripping the IncludeAssets tag was a massive improvement and it is not needed for building or loading the built assembly. The library is more snappy than ever. Didn't need to do anything extra for ViGEmClient after the rebase.

https://github.com/Ryochan7/ViGEm.NET/tree/ryochan_v1.19-experimental
https://github.com/Ryochan7/ViGEmClient/tree/notification_queue_v1.19

Other than that, previously, I had experimented with the current ViGEmBus code to try to find out why output performance took a dive with 1.18. Looks like it was nothing wrong with the actual source code. Just unoptimized default Visual Studio build settings popping up again. Besides changing build settings for ViGEmBus, it would seem like build settings have to be changed for the local DMF copy used by the ViGEmBus project although I have not reverted DMF configuration back to ensure that is truly the case. With just compiler setting tweaks, the driver is faster than ever.

Now that the library issues are mostly resolved, getting around to playing with the new API can begin.

**Comment by nefarius** [comment] 2022-08-19 14:17
> Other than that, previously, I had experimented with the current ViGEmBus code to try to find out why output performance took a dive with 1.18. Looks like it was nothing wrong with the actual source code. Just unoptimized default Visual Studio build settings popping up again. Besides changing build settings for ViGEmBus, it would seem like build settings have to be changed for the local DMF copy used by the ViGEmBus project although I have not reverted DMF configuration back to ensure that is truly the case. With just compiler setting tweaks, the driver is faster than ever.

What does that actually mean in numbers? How do you benchmark? I've contacted the DMF authors about default build settings they recommended to stay on the defaults which I am inclined to believe because a) they have the telemetry data and b) my own benchmarks confirm that there is no human-noticeable difference whatsoever:

![image](https://user-images.githubusercontent.com/286631/185638515-4d3b6969-e77d-4b98-a4a4-2bfa2e9d6295.png)

**Comment by nefarius** [comment] 2022-08-19 14:20
> Ended up finding a way to get Fody to behave better with a tweak to the ViGEm.NET csproj file; stripping the IncludeAssets tag was a massive improvement and it is not needed for building or loading the built assembly.

**What** performance improved? Assembly load delay? Interop speed?

**Comment by Ryochan7** [comment] 2022-08-21 16:58
Update. Got an initial draft going that seems like it works like a direct connection. Both Witcher 3 and Streets of Rage 4 are working and displaying the proper lightbar color and vibrating. I don't know of any PC game that utilizes the DS4 lightbar flash feature but got that check implemented as well. Probably going to have to change how the feedback routine is performed for all DS4OutDevice classes to abstract the details more; the base class expects the use of DualShock4FeedbackReceivedEventHandler and that will no longer be valid with the new API.

Example patch (relies on other changes outside of the ControlService class):
https://gist.github.com/Ryochan7/7329c4355e38ccebe391a844717998ba

Also, got around to testing my hypothesis for the current ViGEmBus code. I reverted DMF to use the default Release build settings and rebuilt both DMF and ViGEmBus. Performance took a dive again even with ViGEmBus still using more optimized build settings. The build settings for DMF have to be changed so ViGEmBus can perform like it used to.

**Comment by Yohoki** [comment] 2022-08-21 20:38
Sounds like a great bit of progress. Thanks Nefarius and Ryochan for that work! Looking forward to seeing the changes. It's a feature we've been waiting to see for a while.

**Comment by Ryochan7** [comment] 2022-08-22 20:11
Here is a video attempting to show what I am experiencing regarding later versions of Fody and the use of the IncludeAssets tag

DS4Windows Fody Regression Demo:
https://www.youtube.com/watch?v=P28pEUh51O0

Maybe I will get around to showing off the differences I have been experiencing with the current ViGEmBus build. For now, here is a diff of the build setting changes made to the relevant projects in DMF; Visual Studio 2019 decided to make some other random changes as well.

https://gist.github.com/Ryochan7/afe6e72ea7c0b8ecc24b8f8aa5e1e0bd

Currently using the optimized version of the 1.19 ViGEmBus driver for testing as my computer runs super slow with the vanilla pre-release driver and 1.18 even without a mapper running. Can feel the difference just trying to navigate files in Windows Explorer.

**Comment by Ryochan7** [comment] 2022-08-23 21:13
Made a short video trying to demonstrate some performance differences when using the current pre-release 1.19 driver and the current experimental build. Besides just showing the impact of the driver in Windows itself, I used Streets of Rage 4 to demonstrate what behavior I am experiencing on my machine. Added timestamps for relevant sections

DS4Windows ViGEmBus 1.19 experimental build changes:
https://www.youtube.com/watch?v=tnlOCDD7GkE

**Comment by nefarius** [comment] 2022-08-24 14:29
Thanks for the videos, [here's a driver build with everything turned up to eleven](https://github.com/ViGEm/ViGEmBus/releases/tag/v1.20.432.0), happy testing.

Fody is technically not necessary, it's more of a convenience feature. We can ship around it by also including the client DLLs in the setup and placing them in the system directories where `DllImport` can pick them up without Costura.

Cheers

**Comment by nefarius** [comment] 2022-08-24 14:32
> Currently using the optimized version of the 1.19 ViGEmBus driver for testing as my computer runs super slow with the vanilla pre-release driver and 1.18 even without a mapper running. Can feel the difference just trying to navigate files in Windows Explorer.

This I can't really explain; the driver does quite literally "nothing" when just installed and nothing talks to it 🤔 but DMF is big, maybe something hiding in there, although should not be. Computers are stupid.

**Comment by Ryochan7** [comment] 2022-08-27 17:12
Draft 2. Not exactly what I thought I would do but it works. Now DS4OutDeviceExt has more control over the process and it can work with multiple output controllers. The first draft only worked for a single output controller.

https://gist.github.com/Ryochan7/7329c4355e38ccebe391a844717998ba

 Also found an oversight in the device unplug code with regards to not unhooking force feedback handlers. Probably not a real issue by the time an output device is disposed but probably should be unhooking prior anyway.

**Comment by nefarius** [comment] 2022-08-29 09:11
Uh oh, seems like we should do yet another build, user on my Discord noticed that the recent AppVeyor builds use the Windows 11 SDK with VS 2019 which produces regressions left and right, will rebuild with the SDK version clamped down.

**Comment by nefarius** [comment] 2022-08-29 13:08
Now it makes more sense why we see performance differences and other weird stuff; the AppVeyor builds are built against the wrong WDK/SDK version due to a build image upgrade, so I'm currently on a mission to clamp down the correct build settings and prepare new binaries *sigh*

**Comment by Ryochan7** [comment] 2022-08-29 20:10
Got a branch with the second draft code in place. Also got the new ViGEm.NET libraries included
as those are needed to access the new API calls from the pre-release 1.19 driver. Still need to do
some more testing and check out the updated pre-release 1.19 driver and compare it to version 1.17.333.0.

https://github.com/Ryochan7/DS4Windows/tree/awaitoutputbuffer_test

**Comment by Ryochan7** [comment] 2022-08-29 21:38
As for my previous concern with feedback handler removal at the OutputSlotManager, it is not a problem in the old code as the Disconnect call actually takes care of removing the feedback handlers already before the virtual controller is disconnected from ViGEmBus. The extra call now is a bit redundant but I think I am going to keep it in place.

**Comment by Kanuan** [comment] 2022-08-29 23:45
Because the newer version of ViGEmBus is required to fix the DS4 OutRep issue, how will you handle older ViGEmBus versions? 

Asking this because if you go to the "DS4Windows will only support ViGEmBus v1.9 going forward and everyone must update", it would be possible to re-introduce acquiring which XInput slot the controller is connected to when doing X360 emulation, since IIRC someone attempting make a PR for this in the past which was rejected because you had to also support vigembus v1.6 in which this feature was broken.

**Comment by nefarius** [comment] 2022-08-30 10:46
@Ryochan7 [new release published](https://github.com/ViGEm/ViGEmBus/releases/tag/v1.21.442.0) for testing, includes adjusted compiler settings for both DMF and the main project plus made sure to build against the correct WDK/SDK version (10.0.19041.0). Happy testing.

**Comment by Ryochan7** [comment] 2022-09-02 20:18
Installed and performed a small XInputChecker test with ViGEmBus 1.21.442 pre-release. Overall it seems like the major issues I had with later versions of ViGEmBus are gone. Need to perform more exhaustive tests and play some games. Although, so far performance seems much better now and it does outperform ViGEmBus 1.17.333.0 on my machine.

At this rate, the awaitoutputbuffer_test branch is likely done as it does what I want and it works in both Witcher 3 and Streets of Rage 4. Just need to make sure the internal feedback thread properly quits in all situations. Have not run into problems with recent tests since switching to using the timeout version of AwaitRawOutputReport.

At some point I need to get around to testing later versions of HidHide. Also, might want to try to offer some form of driver version checker in future DS4Windows releases.

**Comment by Kanuan** [comment] 2022-09-02 20:35
I've also made some quick tests with the `awaitoutputbuffer_test` branch and the infinite rumble issues were solved in the Hades games.

I did have a strange behavior in which the lightbar would be turned off if I went from Steam/Whatever App or game I was playing back to the desktop, a behavior that didn't happen if using the real DS4v2 under normal conditions, but this could be simply because some random app is picking only ViGEm's Wired DS4v1 (making the lightbar turn off) and not a BT DS4v2. Will do more testing to compare the behavior between using DS4Windows' Virtual DS4 in full pasthru versus using a real DS4v1 via USB

**Comment by Yohoki** [comment] 2022-09-03 04:03
Seems like the hop to the new ViGEmBus version is in a stable way and ready for testing! I'll make a build here tonight and see if I can help test a few games. I've only got v1/v2 DS4 controllers, but I'll test both wired and wireless on a few of the games I have.

A couple games I'll try out tonight/Tomorrow
- Detroit :Become Human
  - Lightbar issues reported. Lightbar should change color depending on character.
  - Also uses Gyro, but I don't remember that on PC... I mainly played it on PS4 though. So I don't actually know if pc has gyro.
- Assassin's Creed (Various, but Valhalla was reported)
  - Valhalla (and similar AC Titles) use Rumble and lightbar
- Emulators
  - A few emulators have rumble support. Specifically, I'vs seen Dolphin(inf Rumble) and Retroarch(no Rumble) mentioned in issues.
- Sekiro
  - Problem game in general
- Witcher 3
  - Rumble issues reported
  - Should support lightbar updates
- Biped
 - Inf Rumble issue
 
Too tired to continue scrolling through issues to find reported games that don't work in some way or another. I've got a decent list of games that I can test here, and several more that I remember having an issue. I'll scroll through my D Drive try a good 30 games or so with the test build and let you know if I notice anything weird.

----

Also... while reading a few issues to find games reported not working, Mika mentioned that he didn't know at the time if there were multiple versions of v1 controllers... I dunno if you guys know now, but I can actually answer that question because my wife broke her v1.... There ARE multiple v1 controller revisions. I bought a second v1 to replace my wife's controller, but tried to fit the custom front cover on the new one, and realized that the Launch-Day controller that came with the console was not the same internally to the one I bought a few years later. The touchpad and a few of the other internals on the top were now in the way of inserting the older front cover.

You guys have probably figured this out by now, and data-wise, they might be the same, I dunno. But if you didn't know, now you do. :)

**Comment by Kanuan** [comment] 2022-09-03 12:07
@Yohoki 

The new branch should have no effect in `Sekiro: Shadows die twice` since, from what I remember, the changes affect only the virtual DS4 usage and Sekiro requires virtual Xbox 360. Unless you were using DS4W's Virtual DS4 into Steam's controller support so Steam emulated a Xbox 360 to the game... but then you are asking for problems

In my tests with this game while using virtual Xbox360 everything worked perfectly fine considering that the game supports only XInput devices and that 95% of the people having problem with the controller not being detected were using a pirated version or trying to use Virtual DS4

Oh, and the game is from the FromSoftware developers, so what I commented in #2552 is probably valid for this game too

**Comment by Yohoki** [comment] 2022-09-03 15:26
@Kanuan Ya, I'm specifically looking for games that I remember having issues, or were reported having issues. Rumble's been a big thorn in the program for a while, might as well make sure it's done right or there's just going to be a bunch of "halp is borked" issues popping up again. But, I won't end up testing Sekiro now, anyway. It seems I have deleted it to clear up space...... what in the world was past me thinking???

I did get the test build running and vigem installed, but it looks like I need to restart my computer to actually get DS4 support working again, which I absolutely hate doing.... so I'll start testing in about 3 years when windows is done installing it's forced updates. XD

**Comment by Yohoki** [comment] 2022-09-04 02:40
Aside from a modded game, and Dolphin not supporting it, I've run into no problems so far with Rumble, Lightbar or Gyro on any of the games I've tested. I added some color codes to my above list to make it easy to see what's 🟢Working, 🔴Not Working, or has other 🟡Information.

Great work @Ryochan7 and @nefarius.

**Comment by Ryochan7** [comment] 2022-09-05 19:37
Couple of items to bring up. Related to the compatibility table, many PC games that claim DS4 input support open the controller as a DirectInput device rather than a raw HID device. In a majority of cases, that will mean no form of rumble support will exist; I think Rocket League opens the DS4 in DirectInput mode but it has been a while since I tested it. The DirectInput API has force feedback support and even Gamepad Tester can fire force feedback events for the DS4 when connected in DirectInput mode IIRC.

Also, found that old pull request regarding XInput slots. Looks like it was just a tweak to allow pulling the assigned XInput slot number from the command line. The reason for discarding the request was due to the feature being unreliable in ViGEmBus 1.16.112.0 and that was the minimum support version of the driver. That restraint technically still exists and I would not have a real use for said feature myself. Might try to implement something just to see if it would be worthwhile in the end.

https://github.com/Ryochan7/DS4Windows/pull/2070

**Comment by Kanuan** [comment] 2022-09-05 23:09
@Ryochan7 I've created a discussion regarding the Xinput slots since it's unrelated to the current issue. #2567

-------------

One thing that has come to my knowledge when testing the new branch : Windows' DWM / Windows.Gaming.Input.dll send a Output Report to detected DS4v1 controllers (BT or USB) to... turn off the lightbar. Because of _Windows logic_. So if anyone is testing and is wondering why the lightbar keeps turning off when switching apps/clicking on the taskbar, that's why.  More info here: https://github.com/libretro/retroarch-joypad-autoconfig/issues/852#issuecomment-1220880439

One side-effect of this is that it makes basically impossible to use a DS4v1 via BT in "normal mode" (without DS4Windows I mean). Once the DS4v1 receives the output report it will switch to Extended Mode and then some applications won't be able to detect user input anymore. Using DS4Windows this behavior is mitigated since the virtual DS4 is USB and thus is unaffected besides the lightbar being turned off

**Comment by Yohoki** [comment] 2022-09-06 17:56
> Couple of items to bring up. Related to the compatibility table, many PC games that claim DS4 input support open the controller as a DirectInput device rather than a raw HID device. In a majority of cases, that will mean no form of rumble support will exist; I think Rocket League opens the DS4 in DirectInput mode but it has been a while since I tested it. The DirectInput API has force feedback support and even Gamepad Tester can fire force feedback events for the DS4 when connected in DirectInput mode IIRC.

Looks like RL is free on epic, so I went ahead and checked that one for you as well. No changes there. Rumble still disabled, unfortunately. Also tried with D4W turned off and there's no rumble even with the game directly using the physical controller. So, that's not really a D4W or driver issue.... It's just straight up not supported by the game on PC. Don't think there's anything that can be fixed by you guys. Adding to my list as tested.

That did highlight another thing that I'll bring up in a separate topic, though.

**Comment by Yohoki** [comment] 2022-09-06 22:17
Noticed the first game that something is odd about. Biped. Updated my game list again.

- 🟡 D4W test branch with updated driver(v1.21.442.0) = Controller detected, no rumble.
- 🔴 D4W disbaled + Wireless Controller = No controller detected. (probably because I don't use official BT adapter, so not issue)
- 🟢 D4W disabled + wired controller = Controller detected + rumble.

**Comment by Ryochan7** [comment] 2022-09-15 02:12
It has been a few days but I figured I should update this. The test code has been merged into the master branch.

Also, RIP Mrs. Yohoki v1 DS4

**Comment by Yohoki** [comment] 2022-09-15 03:07
Aside from Biped, it's been working really well in any game I've tried. Haven't noticed any inf rumble popping back up anywhere. Lightbar seem to be supported in any game that already sends lightbar updates without d4w active. Haven't noticed any major input lag. Glad to see it making it into the main.

I wouldn't know where to begin debugging on Biped to see what's going on there, though. It's the only game I've tried that disables rumble when D4W is used, but enables it when D4W is turned off. All the other games are behaving identical whether it's virtual or HW DS4.

.

> Also, RIP Mrs. Yohoki v1 DS4

It will be missed. T.T

Wifey's Pink V1
11/15/13 - 9/6/22

**Comment by Kanuan** [comment] 2022-09-15 03:13
> I wouldn't know where to begin debugging on Biped to see what's going on there, though. It's the only game I've tried that disables rumble when D4W is used, but enables it when D4W is turned off

1. Test again but now [Running DS4Windows under a custom ".exe" name](https://docs.ds4windows.app/guides/ds4w-custom-name/)
    - Make 100% sure the custom .exe name is being used by checking on Windows' task bar -> **DETAILS** tab
1. If it's a Steam game:
    - Test with Steam PS Config. Support disabled
    - Test again with PS Config. Support enabled. Make 100% sure Steam is picking the Virtual DS4
1. If it's the gog's version just running with custom .exe name

**Comment by Kanuan** [comment] 2022-09-16 05:33
> What an odd thing, to check for DS4Windows, but not actually ban it.

This is _usually_ associated with using SDL2. Steam, Yuzu, CEMU, Dolphin I think in the latest versions, and some games all use SDL2 for controller support, and SDL2 itself will ignore DS4/DualSense controllers if it detects DS4Windows is running

**Comment by Yohoki** [comment] 2022-09-16 06:55
But those will usually ignore the controller completely right? Biped was only disabling rumble, but letting the inputs through. And even then, the x360 worked fine, not disabling anything if d4w was running.

That's why I thought it was odd... It was ONLY rumble that was affected. Not completely disabling controllers. Either way, it seems to be fine now with custom exe names.

**Comment by Kanuan** [comment] 2022-09-18 00:39
> It has been a few days but I figured I should update this. The test code has been merged into the master branch

Just one comment, I think you've merged the master branch into the AwaitOutputBuffer_test and not the contrary

**Comment by spookyrecharge** [comment] 2022-10-30 07:58
Can we at least have a toggle button for this somewhere in options like:
`Enable <=3.0.10 dualshock4 rumble support (warning: this may cause infinite rumble issue)`?
It sucks that we need two separate versions for the latest features and for working vibration on DS4

**Comment by spookyrecharge** [comment] 2022-10-30 08:08
Nvm, just realized that with the latest release version of ViGEmBus driver everything works as expected on the latest version of DS4Windows. I just didn't know that we ever need to update ViGEmBus driver manually (I'm always using DS4Updater to upgrade DS4Windows). 
Maybe add a possibility to upgrade ViGEmBus driver using DS4Updater? May be useful for someone too

**Comment by soredake** [comment] 2022-10-30 08:50
@spookyrecharge there is `ViGEmBus_Updater` task in task scheduler that will check for updates and prompt you to update if new version is found.

**Comment by nefarius** [comment] 2022-10-30 08:50
> 

ViGEmBus ships with an auto updater now so no need.

**Closed** 2022-11-12 20:29 UTC

**Comment by whoisalireza** [comment] 2022-12-20 21:54
Hey, can you add audio support for the Dualsense while connected via bluetooth? That would be extremely cool!

**Comment by nefarius** [comment] 2022-12-20 22:11
> Hey, can you add audio support for the Dualsense while connected via bluetooth? That would be extremely cool!

Kindly refrain from hijacking closed threads with unrelated topics, thanks.

**Comment by whoisalireza** [comment] 2022-12-20 22:13
> > Hey, can you add audio support for the Dualsense while connected via bluetooth? That would be extremely cool!
> 
> Kindly refrain from hijacking closed threads with unrelated topics, thanks.

Sorry, I was viewing this thread from the mobile app and didnt know any other way to comment. The app is not very helpful with this.

**Comment by kulkarni005** [comment] 2023-03-02 06:31
Just in case, if you are still struggling with activating vibration on ds controller.
**Enable Copycat** option from settings->device options->detected controller
