### ISSUE TITLE
strange keyboard and mouse behaviou rafter disconnection

### ISSUE THREAD

**Issue by apoklyps3** [Ryochan7/DS4Windows#1228] opened 2020-04-17 06:19 UTC
Whenever I disconnect the controller, I'm getting very strange behavour for my keyboard and mouse.
left mouse click closes tabs in my opera browser when I click them.
can't type any alphanumeric keys.
only thing that works is alt+tabbing a few times until things go to normal again.

Only thing i have changed is "hideDS4 controller" option because I need it for some games.

**Comment by mika-n** [comment] 2020-04-19 08:11
When a gamepad is disconnected then is DS4Windows app instance still running? 
And do you use DS4Windows macros generating artificial KB+mouse events? 
Try to create an "empty default profile" and use it while the gamepad is disconnected. The same effect?

In theory it could be that when a gamepad is disconnected, but a macro is still running then it could generate KB+M events for couple secs even after a gamepad disconnection. Anyway, DS4Windows app doesn't try to hijack keyboard or mouse, so not really sure what could cause something like this.

**Comment by apoklyps3** [comment] 2020-04-19 08:54
yes, I have macros that generate keyboard events.
But I have always had them, so not sure what happened. this started like a week ago

**Comment by apoklyps3** [comment] 2020-04-22 06:34
so, when using the default (unmodified) profile the problem dissapears.
problem is I need my macros. How could they still be running, they must be stuck or something??? because they are unused at least 10 minutes prior to disconnect.

**Comment by mika-n** [comment] 2020-04-22 08:52
Zip and attach the profile file and actions.xml macro file here.  See %APPDATA%\DS4Windows folder.

**Comment by apoklyps3** [comment] 2020-04-22 09:13
[Actions.zip](https://github.com/Ryochan7/DS4Windows/files/4515038/Actions.zip)

**Comment by apoklyps3** [comment] 2020-04-22 09:14
[DS4Windows.zip](https://github.com/Ryochan7/DS4Windows/files/4515043/DS4Windows.zip)

**Comment by mika-n** [comment] 2020-04-23 11:55
Tested the PES profile with those macros. Didn't see anything strange when a gamepad was disconnected.  Anyway, one theory which could interfere how KB works is that if WinOS thinks that some shift/alt key is still hold down but don't see how it could happen because DS4Windows always resets all keys back to default state if the macro doesn't have "keep key state" option set.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#special-action-record-macro-run-a-macro-options

Looks like you don't have "record delays" option set in macros. Some apps may be confused because keys are fired away "too fast" and the app may not be fast enough to process all events. Small delay between key down and up event usually helps to resolve those problematic apps. "Record delays" option records delay and let's you modify it in macro editor.

**Comment by apoklyps3** [comment] 2020-04-24 02:44
thanks. will try that.
but now that I think I about it I mostly use the non-macro actions,, the one that do one keyboard press.
would it be better to record them as macros also?

**Comment by apoklyps3** [comment] 2020-04-25 06:34
so, after playing with this further, I narrowed it down to the disconnect from bluetooth action.
this is causing the issue. any changes made recently in that section?

**Comment by mika-n** [comment] 2020-04-25 09:04
Hmmm... I hardly ever use those "toggle key" type of macros. Usually use just the record macros. Maybe there is a hidden bug in those toggle key macros where it leaves a key in "down" state if the gamepad is disconnected while the toggle macro is in active state. Default profile doesn't use any macros, but if you meant that you use default macro plus assign one of those toggle macros to this default profile then I don't understand why the bug would not trigger there. 

Normal "record macro" resets all keys back to default state when a macro is completed (if "keep key state" option is not set), but not 100% sure what would happen if the macro is active and a gamepad is disconnected in the "middle of the macro sequence".

**Comment by apoklyps3** [comment] 2020-04-25 10:25
correct. the default profile doesn't have any action activated, so maybe that's why haven't noticed the same behaviour there.
I deleted the disconnect action and re-done it manually: PS+options - disconnect bluetooth, this time with hold 1 second option.
Just connected the controller, didn't use any other macro, key simluatio and used the disconnect action. Same problem. So there's something there.

**Comment by apoklyps3** [comment] 2020-05-07 17:16
so from what I can tell if I use the classic disconnect option ( long press PS button) the issue can't be reproduced.
But if I use the PS+option special action it reproduce almost every single time... what gives?

**Comment by apoklyps3** [comment] 2020-05-11 02:44
This strange behaviour is e the same as if ALT key is stuck, but as mentioned it can't because a macro with Alt key is executed, it happens if even without as long I disconnect from BT using PS+options.

**Comment by mika-n** [comment] 2020-09-03 11:12
closed as "cannot re-produce". Hopefully the issue is gone by now in newer releases. One potential issue with simulated kbd and mouse events is when DS4Windows is run without "Run as Administrator" privileges. Without elevated privileges DS4Windows may have trouble sending simulated kbd/mouse events. Try running the app with "Run as Administrator" option.

**Closed by mika-n** 2020-09-03 11:12 UTC
