### ISSUE TITLE
Gyro triggers for Gyro Mouse Joystick mode does now working

### ISSUE THREAD

**Issue by Basfet** [Ryochan7/DS4Windows#1855] opened 2021-02-10 08:44 UTC
Gyro trigger for Gyro Mouse Joystick mode does now working ("Always On" mode permanently) for v2.2.4 and v2.2.5.
It's OK in v2.2.3.

**Comment by Ryochan7** [comment] 2021-02-10 18:38
Does **now** working? Good to know.

Also, duplicate of issue #1858 and fixed in code.

**Closed by Ryochan7** 2021-02-10 18:38 UTC
