### ISSUE TITLE
Connects as XInput #2 slot.

### ISSUE THREAD

**Issue by Erquint** [Ryochan7/DS4Windows#2991] opened 2023-06-22 19:22 UTC
**Describe the bug**
At some point in a Windows session, DS4W ceases to instantiate an `XInput slot #1` virtual device and instead will only ever instantiate an `XInput slot #2` virtual device from then on until a reboot of the session.

**To Reproduce**
Leaving DS4W running through a hibernation usually does it.
I'm using a Sony DS4 that is usually off when not in use with a corresponding Sony radio receiver dongle (DUALSHOCK®4 USB Wireless Adaptor), which stays plugged in at all times.

**Expected behavior**
An `XInput slot #1` virtual device is instantiated.

**Screenshots and Logs**
![image](https://github.com/Ryochan7/DS4Windows/assets/4364856/b3ad23cc-6e47-4c19-bdab-a203fdf425b6)
![image](https://github.com/Ryochan7/DS4Windows/assets/4364856/12f01e0e-6216-4f2c-92b1-0a3c55f985b6)
![image](https://github.com/Ryochan7/DS4Windows/assets/4364856/c3f052c2-9a42-4432-b5aa-63a2fa75e013)
![image](https://github.com/Ryochan7/DS4Windows/assets/4364856/145f59ab-5f3d-4a09-8eb6-398894ec6421)
![image](https://github.com/Ryochan7/DS4Windows/assets/4364856/f400209e-45ba-41f7-8383-a09aaf340f43)
![image](https://github.com/Ryochan7/DS4Windows/assets/4364856/8f27f45f-466c-4267-b3b7-e70934cc49bf)
```
06/22/2023 22:06:34: DS4Windows version 3.2.11
06/22/2023 22:06:34: DS4Windows Assembly Architecture: x64
06/22/2023 22:06:34: OS Version: Microsoft Windows NT 10.0.19045.0
06/22/2023 22:06:34: OS Product Name: Windows 10 Pro
06/22/2023 22:06:34: OS Release ID: 2009
06/22/2023 22:06:34: System Architecture: x64
06/22/2023 22:06:34: Running as Admin
06/22/2023 22:06:34: HidHide control device found
06/22/2023 22:06:34: DS4Windows not found in HidHide whitelist. Adding to list
06/22/2023 22:06:34: Output slot #1 has permanent type X360
06/22/2023 22:06:35: Starting...
06/22/2023 22:06:37: Using output KB+M handler: FakerInput 0.1.0.0
06/22/2023 22:06:37: Connection to ViGEmBus 1.21.442.0 established
06/22/2023 22:06:37: Searching for controllers...
06/22/2023 22:06:37: Using Exclusive Mode
06/22/2023 22:06:37: Plugging in virtual X360 controller (XInput slot #2) in output slot #1
06/22/2023 22:06:37: Found Controller: 00:00:00:00:00:00 (SONYWA) (Sony WA).
# Editor's note: DS4 is being manually powered on at this moment, prompting the following log entries.
# And 00:00:00:00:00:00 seems to be the mock address of the radio dongle that DS4W assigns to a local device.
06/22/2023 22:08:10: Associated input controller #1 (Sony WA) to virtual X360 Controller in permanent output slot #1
06/22/2023 22:08:11: Controller 1 is using Profile "XInput". Battery level is 37%
```

**Desktop:**
- Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
- OS: Windows 10 Pro. Version 22H2. Build 19045.2728. Experience Windows Feature Experience Pack 120.2212.4190.0.
  No idea why it says "2009" in the log.
- DS4Windows Version 3.2.11
- ViGEmBus 1.21.442.0 
- HidHide 1.2.128
- FakerInput 06/03/2021, 0.1.0.0
- .NET Runtime x64 6.0.16 installed.

**Additional context**
This has been an issue for so many years.
Why? Why is it still an issue?
```
Plugging in virtual X360 controller (XInput slot #2) in output slot #1
```
Why `XInput slot #2`?

I tried setting permanent output slots, but to this day I still have no idea what's even "permanent" to them if DS4W doesn't allow me to choose which output slot I want it to use.
I tried launching with Steam and NVidia Local Container (part of DVR that also likes to hog the handle) off.

**Comment by Ryochan7** [comment] 2023-06-23 16:50
> This has been an issue for so many years.
Why? Why is it still an issue?

Literally have been asking for suspend testing help for **YEARS**. Nobody with a properly working PC can be bothered to help me out. People just want to bitch while rewarding others with worse problems. I am not even allowed to enjoy my autism.

On a less tahxic note, double checked the code and DS4Windows is definitely doing its job. The log and screenshots show that it disconnects the virtual XInput controllers as intended and the code shows that any old references are definitely removed. This could simply be a case where some other program on your system still has a handle on an attempted disconnected controller; web browsers like Chrome and Brave exhibit this problem for sure but I bet even something like the Netflix app can probably do this. In that case, I would not call this a problem with ViGEmBus either but it is likely your own config that is the problem.

**Comment by Ryochan7** [comment] 2023-06-23 22:25
Tested my own hypothesis. Been testing suspend and DS4Windows has been working fine lately even after several sessions. Tried to do it while Brave was open (after using and then closing HTML5 Gamepad Tester) and then the XInput slot got skipped to use Slot 2 after resuming the PC.

My hypothesis was correct. So, this is most like your own fault.

**Closed by Ryochan7** 2023-06-23 22:25 UTC

**Comment by Erquint** [comment] 2023-06-27 23:56
> So, this is most likely your own fault.

My fault. 😅Alrighty then…

So if I were to interpret your suggestion: once the issue occurs — I am to terminate running processes and restart DS4W in turn until the issue ceases to occur, noting down the last process to have been terminated?

Couldn't diagnostics for this be built into DS4W, something akin SysInternals Handle?

**Comment by Kanuan** [comment] 2023-06-27 23:58
https://docs.ds4windows.app/troubleshooting/xinput-slots-order/

**Comment by Erquint** [comment] 2023-06-28 03:34
That link doesn't address any of my queries, really.
It's just a re-statement of the problem.
And I use CLI SysInternals Handle in my scripts rather than GUI Process Explorer.

I could help fill out those "to do" sections.
***
> Most common ofenders

- Steam.
  Hogs a handle even with the controller features "disabled".
- Nvidia Share | ShadowPlay.
  `nvcontainer.exe -s NvContainerLocalSystem`
  If the resident overlay is enabled in Geforce Experience, it hogs the handle in anticipation for usage of its remote *local* multiplayer feature, — the feature dubiously being named eponymously "Share".
  Being a service, it ends up showing the handle hog under the core "System" process.

> Usually innocent processes

- DWM.
  Desktop Window Manager. Core to Windows.
  Grabs the handle but never actually ends up interfering.

> Others

- Windows Store.
  It's inconsistent and inconclusive but does grab the handle sometimes.
***
Now, with the diagnostic tooling suggestion standing, I have another nagging thought…
Can we really not, with a kernelmode process, just break into Windows and manipulate the whole buisiness of XInput reservations directly?
