### ISSUE TITLE
Not connect after sleep

### ISSUE THREAD

**Issue by coolllman** [Ryochan7/DS4Windows#2602] opened 2022-09-23 10:02 UTC
**Describe the bug**
When output slots setting set on permanent, dualsense after sleep don't connect and only reopen ds4windows solve this, on 3.0.18 all works good.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony Dualsense
 - OS: [Windows 10 Pro Build 21H2]
 - DS4Windows Version 3.1.6

**Comment by Sgtbomber91** [comment] 2022-09-25 13:33
Same issue happening on Win11 after resuming from hybernate, manual process kill/restart is required to resume DS4Windows operation

- Controller Make and Model: Sony Dualshock 4 v2
- OS: Windows 11 Pro 21H2 (build 22000.1042)
- DS4Windows Version 3.1.6

**Comment by ceedveed** [comment] 2022-10-05 20:52
Controller Make and Model: Sony DS4 v1 using official Sony wireless USB dongle
OS: Windows 10 Pro 21H2
DS4Windows Version 3.1.6

Same issue. I had to revert to DS4Windows Version 3.1.0.
I think the issue is related to this item in version 3.1.1:
`Slightly tweaked Suspend and Resume power routines`


I have another system that **does not** have this issue, even though it is past 3.1.0:
Controller Make and Model: Sony DS4 v2 using bluetooth
OS: Windows 11 Pro 21H2
DS4Windows Version 3.1.4 (haven't updated yet to latest version, just did short testing)

**Comment by SurlyVagrant** [comment] 2023-01-24 22:20
I had something similar (#2491) that was fixed by updating the .net runtimes. Might be worth a try.

**Comment by soredake** [comment] 2023-07-18 05:45
Maybe same for me, seeing this:
![изображение](https://github.com/Ryochan7/DS4Windows/assets/5204968/6ed389d7-24cb-4e2c-9d92-89d0aa72e428)

**Closed** 2023-11-11 19:53 UTC
