### ISSUE TITLE
[Bug and suggested fix] Gyro mouse drifting due to controls list and gyro tab enabled simultaneously

### ISSUE THREAD

**Issue by Darthagnon** [Ryochan7/DS4Windows#1383] opened 2020-07-01 17:37 UTC
## Problem:
If Tilt Up/Tilt Down/Tilt Left/Tilt Right is set to mouse movement, and gyro is set to "Mouse" under the Gyro tab simultaneously, the tilt will make the mouse move and keep drifting in a moved direction. I was struggling to find why my mouse was drifting on all my profiles unless cloned from the Default for ages!

## Fix?
Move the Tilt control mapping to the Gyro tab? Then it would make sense, and noob users like me could easily see when controls are duplicated.

I can't help feeling that the Touchpad and controls lists would provide a better user experience if they were tabs on the right, e.g.
- Touchpad tab with the touchpad options arranged a bit less cramped within it, and... 
- a Buttons tab with the current buttons and mappings list - due to the greater available space, no scroll should be needed, and it would be much less finnicky to set button mappings (on touchpads, it's very easy to overscroll the tiny scrollbox currently used for button mappings.
Clicking the buttons on the DS4 preview on the left could activate the respective tabs on the right, and it would look and work real nice.

**Comment by Darthagnon** [comment] 2020-07-02 00:52
I've also noticed that multiple triggers for the Gyro (e.g. L2 and R2 simultaneously) don't seem to work, whereas single triggers do.

**Comment by Ryochan7** [comment] 2020-07-03 11:40
A combination of a few issues that I have only recently confirmed. The short story is that Gyro Mouse mode has actually been broken since DS4Windows 2.0. The biggest problem is that the Turn Behavior setting was mapped to the wrong property in the backend ViewModel. I have been getting back into using the DS4 Gyro somewhat recently so I did not know that I broke Gyro Mouse like I did until a few days ago; I suffered a hand injury in 2019 so I physically couldn't handle it until about the beginning of 2020.

Hopefully the main issues that you have described will be resolved in the next DS4Windows release.

**Comment by Darthagnon** [comment] 2020-07-09 22:31
I'm so sorry about your injury; glad to hear it's getting better! Thank you for making this amazing software!

PS. Just thought I'd share the profile and game I'm using atm to test the gyro with buttons:
- Game: https://krunker.io/ (browser-based fast-paced FPS, no downloads needed)
- Profile: attached, rename to .XML from .TXT [Krunker.txt](https://github.com/Ryochan7/DS4Windows/files/4899796/Krunker.txt)
- Controls:
 - L1: Jump (combo with R1 to move fast)
 - R1: Crouch
 - L2: Aim down ironsights (activates gyro to help with aiming)
 - R2: Shoot (I would set this to activate gyro, too, but 2 triggers for gyro bugged atm)
 - L-Stick: move, L3: toggle crouch
 - R-Stick: camera, R3: ironsights again
 - Arrow buttons: funny chat message macros
 - PS: F11 (fullscreen browser window)
 - /\: reload
 - O: spraypaint
 - [ ]: switch weapons
 - X: Jump again

**Closed** 2020-07-24 11:55 UTC

**Comment by Darthagnon** [comment] 2020-08-09 23:59
> EDIT: kinda unrelated/off-topic, but I've also noticed that multiple triggers for the Gyro (e.g. L2 and R2 simultaneously) don't seem to work, whereas single triggers do.

PSA for any future readers, I almost posted a bug report about "multiple triggers not working for gyro", but the solution is this:

Set ```Eval cond.``` to logical "OR". Now, if I'm holding R2 OR L2, the gyro is on. The default state is logical "AND", which would switch the gyro on only when holding R2 AND L2 simultaneously. Solved
