### ISSUE TITLE
Gyro mouse trigger always toggles when first connecting device

### ISSUE THREAD

**Issue by stealsfromhobos** [Ryochan7/DS4Windows#664] opened 2019-04-21 20:50 UTC
In my default profile, I have gyro mouse set to activate only _while_ have a single finger on the touchpad.  However, if I touch the touchpad once after connecting the controller, the gyro will stay on until I press it again as if it were set to toggle (which it is not).  This goes away if I switch back and forth between profiles or entering/exiting a profile's settings and will only last until I disconnect and reconnect the controller.  It happens even with a fresh profile with the gyro mouse set and regardless of what trigger or combinations of triggers I set.  This happens on both Bluetooth and USB connections.

I rolled back a few times and found the last version to not have this bug is 1.6.12.  Everything released after that version (currently on 1.7.5) behaves as I described above.   All versions tested used the same profiles and settings.  I'm also using an old DS4 controller if that matters.

**Comment by mika-n** [comment] 2019-04-23 12:06
Jep. There seems to be a bug how Mouse.toggleGyroMouse property is initialized during an initial profile loading (startup or hotplug event). 

The problem is that a profile is loaded and the LoadProfile method calls "SetGyroMouseToggle(device, temp, control)" method BEFORE the underlying control.touchPad[index] Mouse object has been created (ie. it is still NULL when LoadProfile is loaded). The mouse object is created after the initial profile is loaded.

I fixed this bug and submitted the fix along side of the new pull request with a new "Unload profile on regular trigger key release" feature. When Ryochan has a time to review it then he will hopefully include the fix and the new feature into the master branch to wait for the next release.

**Comment by Ryochan7** [comment] 2019-04-23 21:52
I have experienced this problem once but I cannot reproduce the problem again even after restarting the program multiple times. I do see the LoadProfile regression that looks like it was introduced with the Auto Profile controller hotplug fix in version 1.6.13.

**Comment by Ryochan7** [comment] 2019-04-24 02:14
The changes from mika-n have been merged. This problem should be fixed.

**Comment by uxlapogi** [comment] 2019-04-25 18:25
The issue is still present in 1.7.5

**Comment by mika-n** [comment] 2019-04-25 18:29
The fixed version is not yet released (only in devel version) but the next release should have it.

**Comment by Ryochan7** [comment] 2019-04-25 18:47
The problem is fixed in the current code. It won't be available in a build until version 1.7.6. A new build will come out by late Friday.

**Closed** 2019-04-27 20:47 UTC
Labels: bug
