### ISSUE TITLE
Gyro, lightbar passthru issues

### ISSUE THREAD

**Issue by stramner** [Ryochan7/DS4Windows#2405] opened 2021-08-05 11:02 UTC
**Describe the bug**
Gyro and light bar passthru don't seems to be working correctly, in Detroit Become Human, at least.

**To Reproduce**
1. Hide native DS4 in HidHide (exception for DS4Windows)
2. Use DS4 emulating profile in DS4Windows 
3. Enable passthru for gyro, lightbar
4. Play Detroit - Become Human

**Expected behavior**
Entering menu should change the led light to white, when playing a specific character, led should change to a specific light associated with the given character (light blue, blue, light yellow). Plus some scenes specifically change led color (eg light red). Instead, led stays off.
Gyro actions seem to work (jerk the gamepad up/down/left/right), with exception of tilting movement.
Expected behavior was confirmed by using native DS4 input and playing the game (the exact same .exe on the same PC).

**Screenshots and Logs**
Example of the tilting gyro action (which didn't work for me), with expected behavior, from early in the game - https://youtu.be/Yv8oTjn2kb0?t=113 (not my video)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Education Build 20H2
 - DS4Windows Version: 3.0.14
 - ViGEmBus Driver version: 1.17.333 (to be sure, I redownloaded the latest msi from official repo https://github.com/ViGEm/ViGEmBus/releases, uninstalled -> restarted PC -> installed -> restarted PC)

**Additional context** 
Passthru gyro does seem to work with RPCS3 gamedpad tester. 
I'm aware of one or two similar closed reports on the topic, but both were somewhat different. 
Note this is not something that particularly bothers me, as using native DS4 solved the issue for me completely, but I just want to report the existence of the bug.

**Comment by Kanuan** [comment] 2021-08-05 11:06
Lightbar passthru and DS4 emulation rumble are disabled on the latest versions because of an issue with the vigembus.

**Comment by Ryochan7** [comment] 2021-08-05 17:03
Lightbar passthru is a non-issue at this point. That is a driver problem that I cannot do anything about until a new ViGEmBus driver is released.

My main test for gyro passthru has been using the Gamepad Tester app in RPCS3. Not sure why it would work in that app but not in Detroit. I don't have the means to test it since I don't have that interactive movie. Are you sure the input DS4 is actually being hidden from the game when you try to play it?

**Comment by stramner** [comment] 2021-08-06 16:27
Video with readings, for the action that works - https://streamable.com/wdunlw - and for the action that doesn't - https://streamable.com/aq5hll. 

I won't pretend to know anything in depth, but I noticed is that the action that works only requires acceleration, while the one that doesn't requires position. However, it seems that readings react to both movements, so I have no idea why one works and the other doesn't. And I'm not aware of any other PC app that would utilize DS4 gyro actions like this game does (other than ds4windows or rpcs3's gamepad test, which both show raw values), so I have no idea if it's purely this game's issue or not.

**Comment by stramner** [comment] 2021-08-06 16:48
Video with readings, where "bad" action works, after swapping native/virtual visibility (now, native DS4 gamepad is not hidden, virtual DS4Windows gamepad is hidden, visible only by DS4Windows) - https://streamable.com/aw4yuw.

**Comment by Kanuan** [comment] 2021-08-06 20:53
I've tested gyro passthu by using Yuzu's native PS4 handler and it works as normal on Zelda BotW and Mario Kart. The strange think is that it worked even when gyro passthru was disabled. Don't know if Yuzu was somehow

**Comment by mika-n** [comment] 2021-08-07 09:26
unfortunately I don't have any PC games/apps supporting native DS4 gamepads and gyro functionality. Do you know any freeware apps/games/emulators/roms supporting ds4 gyro in PC?

**Comment by Masamune3210** [comment] 2021-08-07 16:20
Was going to say most emulators involving motion, but I'm pretty sure all of them use the UDP server

**Comment by Gianlucas94** [comment] 2021-08-07 22:45
I think the best game to test is the DOOM and DOOM II from gamepass pc. I tested the version 3.0.12 and the gyro passthru worked in those games

**Comment by Kanuan** [comment] 2021-08-08 16:38
I can confirm the issue. Tested with my DS4v2 connected by BT, all passtru options enabled and playing Detroit: Become Human through PS remote play (PS5). The exact same kitchen gyro part does not work with DS4windows/vigem but works when the controller is directly connected by cable.

**Comment by Ryochan7** [comment] 2021-08-08 17:14
Looking at the issue now in code and Hid Report Inspector. I think I can confirm there is a problem. The output index is off by 1 so Gyro and Touchpad support does not work as intended. The FieldOffset for wGyroX should be 13 not 12.

https://github.com/Ryochan7/DS4Windows/blob/jay/DS4Windows/DS4Control/DS4OutDevices/DS4OutDeviceExtras.cs#L53

**Comment by Ryochan7** [comment] 2021-08-08 17:17
Never mind. Not taking ViGEmBus adding the report ID byte to the final output into account. Hid Report Inspector shows that the byte alignment is correct.

**Comment by Ryochan7** [comment] 2021-08-08 17:22
The program is not promoted much but here is where to get a copy of Hid Report Inspector.

https://github.com/Ryochan7/HidReportInspector/releases/tag/v0.0.1

**Comment by Ryochan7** [comment] 2021-08-08 18:04
> I think the best game to test is the DOOM and DOOM II from GamePass PC.

I have a copy of Doom 2 on Steam. Didn't know they added Gyro Aim for DS4 in late 2020. Tested it out with Gyro Passthru enabled and Gyro Aim works in Doom 2.

**Comment by Kanuan** [comment] 2021-08-08 18:27
It seems that the time stamp that is used to help processing gyro data is not implemented on vigem or not correctly updated by DS4Windows?

## [DS4-BT - PS4 Developers Wiki](https://www.psdevwiki.com/ps4/DS4-BT)

![image](https://user-images.githubusercontent.com/24910442/128641923-655a10ef-782c-4677-b7c2-2cda30ba3981.png)

## ViGEm's DS4

![image](https://user-images.githubusercontent.com/24910442/128641881-b6b78caf-8c9a-44a4-b0cf-32aaeac6bab0.png)

## Real DS4v2 USB

![image](https://user-images.githubusercontent.com/24910442/128641889-43e442cb-131f-4fa1-9928-cfe652a4fb07.png)

**Comment by Ryochan7** [comment] 2021-08-08 19:16
Missed a copy step for the timestamp in the mapper.

**Comment by Gianlucas94** [comment] 2021-08-08 19:54
Thanks for your efforts! :D

**Comment by Gianlucas94** [comment] 2021-08-09 03:12
#2424 With this version the Gyro and Lightbar worked in Passtrhu mode in DOOM 2 with pyshical controller hidden.
I'll test in Days Gone and Death Stranding

**Comment by Kanuan** [comment] 2021-08-09 04:35
The gyro issue with Detroid was not fixed on version 3.0.16. 

One field that DS4Windows is not properly updating and that I've missed on my previous comment is field 7, which is the the field for the PS button, the Track Pad and a __counter that is increased by 1 per report__. DS4Windows does not increase the counter and may be the cause of the issue.

I took a quick look now and the other fields which differ (but probably are not related to the current issue) are:

- F7: Missing counter increase per report
- F30: missing info related to mic, usb, phone and battery
- F34: Counter that increases only if 1) Finger is in contact with the TP and 2) there is actual movement being registered on the TP
- F44-62: MSB needs to be "1" so the other groups of TP related fields are properly marked as disabled

I can't properly check right now if I'm not missing anything else. Will re-verify this tomorrow.

![image](https://user-images.githubusercontent.com/24910442/128660271-48af9a83-f5dd-418e-a091-1aaf24376516.png)

Fields F43, F47, F52, F56, F61 are also TP related counters but I have never seen a DS4 update any TP field that is not the first group (F34 to F42) so whatever.

@Ryochan7 if you implement any changes related to these fields (specially F7 which I think is the real culprit on the broken gyro in-game) just mention the commit here and I'll compile the version, test and then report back here so you don't have to release new DS4W versions that we are not sure are actually fixing the issue.

**Comment by Gianlucas94** [comment] 2021-08-09 04:38
So, in my little research.

Controller: **DS4V2 In bluetooth**
Emulated Controller: **DualShock4**

**Gyro PassThru** works well in version #2424. Tested in DOOM94 (Classic), DOOM II (Classic), Death Stranding. with the physical controller hidden or not.

**LightBar PassThru** worked in DOOM II, but only if the physical controller is not hidden. But in those other games didn't. When i hide the physical controller, DOOM II don't receive my inputs from DS4.

**Comment by mika-n** [comment] 2021-08-09 08:28
`LightBar PassThru worked in DOOM II, but only if the physical controller is not hidden. But in those other games didn't. When i hide the physical controller, DOOM II don't receive my inputs from DS4.`

The lightbar support in a virtual ds4 output controller is disabled on purpose because there are some nasty bugs/issues with that feature in the current version of the DS4Windows+ds4 output mode+ViGem combination. When you didn't hide the physical gamepad then you were just lucky lightbar worked in a game because it "accidentally" sent the light command to physical (or probably to both gamepads) but only physical device actually did something with the light command. Virtual ds4 gamepad simply ignores all lightbar and rumble events coming from a game until few issues are resolved.

**Comment by Gianlucas94** [comment] 2021-08-09 08:51
I understand, thx.

When you say rumble, you are saying that when i enable the DS4 Output mode i wont get any rumble? I ask this because the rumble is working when i use the DS4 Output mode.

**Comment by mika-n** [comment] 2021-08-09 08:58
Yes, rumble is also disabled in the latest version of ds4windows when a DS4Windows profile uses dualshock4 output mode. If it works then maybe the original physical gamepad is not hidden after all or profile is using xbox360 output mode? Or game does something "unofficial" and uses ds4 gamepad device as a raw device instead of "dinput hid device" (highly unlikely, but in theory possible)

**Comment by Gianlucas94** [comment] 2021-08-09 09:02
> Yes, rumble is also disabled in the latest version of ds4windows when a DS4Windows profile uses dualshock4 output mode. If it works then maybe the original physical gamepad is not hidden after all or profile is using xbox360 output mode? Or game does something "unofficial" and uses ds4 gamepad device as a raw device instead of "dinput hid device" (highly unlikely, but in theory possible)

Sorry, before wasn't hidden, i tested right now and didn't work. Thx

**Comment by Ryochan7** [comment] 2021-08-09 14:52
Bringing the discussion back to missing fields that might be relevant at some point.

> I took a quick look now and the other fields which differ (but probably are not related to the current issue) are:
>
> * F7: Missing counter increase per report
> * F30: missing info related to mic, usb, phone and battery
> * F34: Counter that increases only if 1) Finger is in contact with the TP and 2) there is actual movement being registered on the TP
> * F44-62: MSB needs to be "1" so the other groups of TP related fields are properly marked as disabled

F7 would be easy enough to add for all controller types. That counter would have to be faked for Switch Pro and JoyCon devices. Although, there is no routine to make a fake DS4 timestamp for those controller types. Not sure if that is needed right now.

F30 is probably not important. Going to continue to ignore that byte until it is deemed necessary

F34 is not updated since that data is not copied over. Changing that now. That field is not a part of the other Touch data. Not sure how much of a difference it will make for anything.

**Comment by Kanuan** [comment] 2021-08-09 16:53
> F30 is probably not important. Going to continue to ignore that byte until it is deemed necessary
> F44 - F63: Not sure that data is too important

I'm supposing you are against tying them to the real input report? I agree with you that those values are (for what is known) more or less useless and therefore don't need to be dynamically updated, but I think it would interesting to set them to their "usual" states statically _just in case_  something out there tries to verify them.

Make F30 always says 100% battery and that USB is connected

Mark F44, F48, F53 and F57 with their MSB bit as "1"

F60 - F63 are the designated CRC-32 bytes which would be 0 for a USB DS4 anyway

F62 is also "128" on my DS4v2 USB

https://user-images.githubusercontent.com/24910442/128660271-48af9a83-f5dd-418e-a091-1aaf24376516.png

**Closed** 2022-07-25 18:23 UTC
