### ISSUE TITLE
Won't re-connect when computer wakes from sleep

### ISSUE THREAD

**Issue by Kazserah** [Ryochan7/DS4Windows#3023] opened 2023-07-22 17:51 UTC
When my computer wakes, I go back to ds4windows and it says no controllers connected, i hit start, nothing happens (it still says start), so I have to close and re-open the program.

This was never an issue since the last update.

According to the log it says "ViGEm Device Plugin Failed. Likely an internal ViGEmBus problem" etc
![Screenshot_1](https://github.com/Ryochan7/DS4Windows/assets/99200664/fa8c4bae-684a-4ae2-9504-db9d672e527e)

**Comment by Ryochan7** [comment] 2023-07-23 01:09
I still have no idea is happening there. I do not use Sleep but this error has not occurred to me since finally getting it working on my PC.

On a side note, I see where that lock recursion is taking place. The lock is not released when ViGEmFailure is called. I need to fix that.

**Comment by Kazserah** [comment] 2023-07-25 06:28
I downgraded to the previous version and now everything is fine

**Comment by Kazserah** [comment] 2023-11-25 16:49
This is happening again with the latest version. Nothing has changed on my end.

**Comment by Ryochan7** [comment] 2023-11-26 21:51
Not much I can really do about it. Testing this scenario with ViGEmBus calls commented out always seemed to work IIRC. It was rare for me to be able to replicate the issue to start with. The only real way around the problem would be to have a very extended wait period on the Resume step (I think 3 minutes).

I will reopen this issue temporarily and see if I can run into the problem again. My ongoing hypothesis has been that the problem is something within ViGEmBus itself but there has been no way to verify it completely. I was gaslit for years about the infinite rumble problem in ViGEmBus and had to make workarounds in a custom ViGEmClient library. Only recently was I able to confirm and fix that problem on my end within the ViGEmBus driver code myself.

If something were found, it would not truly matter as I have no means to distribute a custom driver.

**Comment by Ryochan7** [comment] 2023-11-27 17:53
So far, I only have a better idea about where the process is failing. A request made by ViGEmBus times out before an LED packet is sent from the XUSB driver which would cause ViGEmBus to fire an event. The real error code does not propagated back up to the client as a target removal is done when the routine fails with any status. The error code from vigem_target_remove is propagated back up.

https://github.com/nefarius/ViGEmBus/blob/master/sys/EmulationTargetPDO.cpp#L691

https://github.com/nefarius/ViGEmBus/blob/master/sys/XusbPdo.cpp#L843

**Comment by Ryochan7** [comment] 2023-11-27 23:31
Only done a bit of playing around since the previous post. Interesting enough, changing the client code to just ignore the error results allows for XInput emulation to work. Not sure if imposing an additional wait period in the client code would be enough to work around the problem or maybe trying additional times.

There might be the case that the driver code that is supposed to signal the event is not executed. It would be much harder to try to diagnose that problem since WPP Tracing messages likely cannot be traced in a client that early.

One other thing to mention is that there are some odd times when this problem pops up outside of resuming from sleep.

**Comment by Kazserah** [comment] 2023-11-28 00:05
Thanks for checking it out. For the moment, I'm using 3.2.12 with VigEmBus version 1.22 and it's working fine atm, so I'll wait and see what else you find

Do you think you'll implement that code change?

**Comment by Ryochan7** [comment] 2023-11-28 15:30
Tested it multiple times and adding an extra wait period before the call (1 sec) is enough to make the process work every time on my PC. I do not want to add a wait period for every plugin event when not needed so I will have to test adding multiple attempts instead. At least this type of workaround would be doable in the client library although the problem does originate at the driver level. It would probably have be better if the entire process were written as a blocking call instead.

**Comment by Ryochan7** [comment] 2023-11-28 20:47
This would go faster if my PC would cooperate. Tested the multiple attempts method and it is confirmed to work on my PC. The second attempt is able to grab the signaled status and the virtual XBox 360 controller works as expected. I currently have the loop set to attempt up to 3 times. Hopefully that will be enough attempts to work around this issue and still allow for more severe errors to cause DS4Windows to disconnect from ViGEmBus.

**Comment by Ryochan7** [comment] 2023-11-29 22:02
Updated libraries. I'll get the update code out there shortly.

https://github.com/Ryochan7/DS4Windows/commit/49e889f77c12596144932764d3dab8478677574f

**Comment by Ryochan7** [comment] 2023-11-29 22:16
Updated ViGEmClient change

https://github.com/Ryochan7/ViGEmClient/commit/f6747cf673425d55eea8293d95d659cb08e98d59

**Comment by Ryochan7** [comment] 2023-12-10 18:56
Looks like this issue can be safely closed this time around. Not an ideal solution but at least the root problem is known and a workaround is in place.

**Closed by Ryochan7** 2023-12-10 18:56 UTC
