### ISSUE TITLE
Now officially only support Windows 10 and later. THANKS MICROSOFT

### ISSUE THREAD

**Issue by reyaz006** [Ryochan7/DS4Windows#1910] opened 2021-02-26 09:29 UTC
*sad face*
Is it related to [this](https://github.com/ViGEm/ViGEmBus/releases/tag/setup-v1.17.333)?

What are my options if I'm not planning to leave Windows 8.1 for now? If I try to update to 2.2.7 will it outright not work anymore? Because it will require new ViGEmBus 1.17.333 which won't install for me?

**Comment by Corgano** [comment] 2021-02-26 09:30
I think you already know your options. Don't update.

Just wondering windows 8 is getting pretty old, why are you sticking with it?

**Comment by reyaz006** [comment] 2021-02-26 09:46
>Just wondering windows 8 is getting pretty old, why are you sticking with it?

It's not really that old, just turned out less popular than Windows 7, while being actually a better version of it.
I have tons of stuff on it and moving it all would be a pain. Also I still don't consider Windows 10 good enough option for myself. Let's not discuss what's good or bad about it though. I use it often elsewhere on several PCs and I see how it performs.

I just want to know the details about how it interacts with ViGEmBus, could it still work with older version of it, etc.

**Comment by Corgano** [comment] 2021-02-26 09:51
I don't know the details of how it works. Honestly It worked fine for me before the change, on windows 7 and 8, so if it ain't broke don't update it. The biggest thing being added lately is ps5 controller support and some other controllers being supported. If that's not important to you then living in the past is perfectly fine.

**Comment by Ryochan7** [comment] 2021-02-26 12:41
This started with ViGEmBus moving to only supporting Windows 10 for future driver updates. Now, it is literally Microsoft's fault for changes to the driver signing and verification process as it is intentionally set up to only allow new driver signing for Windows 10. Can't find all the info I had beforehand but here are a couple of links. If you want to delve into working in kernel mode land in the current year, you have to be using Windows 10. Microsoft even gave the shaft to Windows 8.1 users despite that OS still technically being supported by the company.

https://docs.microsoft.com/en-us/windows-hardware/drivers/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates

https://www.ghacks.net/2020/11/30/reminder-supports-for-root-certificates-with-kernel-mode-signing-capabilities-ends-next-year/

**Comment by Ryochan7** [comment] 2021-02-26 12:55
With the last batch of Corona-bucks, I had looked into actually getting an EV code signing certificate so I could push out my own Windows drivers. Unfortunately, the money to pay the cost of the certificate is not the only barrier for pushing out Windows drivers. In order to get approved for an EV certificate or get put on the Microsoft Hardware Program, you have to be a part of an approved company or organization. So, like Nefarius, I would pretty much be forced to start my own company in order to have a chance to be allowed into that space.

**Comment by reyaz006** [comment] 2021-02-26 13:29
Sorry for possibly stupid questions. Even if the driver is signed for Windows 10, should it not work under Windows 7/8? I imagine the signature verification would fail if signature algo is unsupported by the platform, but does that signing process do something extra to make sure that a driver will not load under older Windows versions?

What about older versions of ViGEmBus? I've tried to run 2.2.7 and it didn't report any errors, though I haven't tried to connect the gamepad yet. Should it work as is? Or will it expect latest version of ViGEmBus in order to work properly? If it's a critical issue I'd expect at least some notification that my OS is no longer supported,

**Comment by Ryochan7** [comment] 2021-02-26 14:29
I assume you are still using ViGEmBus 1.16.112.0 then. For now, DS4Windows still works with it but there are already features that you would be missing out on as a consequence. DS4Windows 2.2.0 was the last release to take Windows 7 into consideration at all although I had publicly stated that I would no longer support Windows 7 previously. If DS4Windows breaks on Windows 7 in the future then that's the end of the line. The decision to stop caring about supporting Windows 8.1 is directly due to Microsoft's driver signing policy changes that take effect this year.

As far as I know, the driver signing requirements are different for each version of Windows so a driver has to be digitally signed differently for each version of Windows that the driver supports. Based on posts I have read from Nefarius, it does not seem like a driver signed for Windows 10 would directly work on older versions of Windows; not sure if there is a way to force one to install and run. Any driver signed before the root certificate expiration date will still work after the root certificate expires. The problem is being able to sign and push out future driver updates. Microsoft is now acting as the exclusive gate keeper in the process.

**Comment by mika-n** [comment] 2021-02-26 18:10
People should just accept the fact that at some point old hardware/software/gadget becomes a burden. Sometimes it may even limited what can be implemented and what not. But even if that is not the case then it is just an additional burden from a maintenance perspective. 10 years old product (Win7) cannot expect to be supported forever. 10 years in this business is a long time already. Those users should simply use the last version working in the environment unless they are willing to help to maintain the backward compatibility by committing their time and expertise to support development. Or if they cannot help with coding then financially supporting it to make it feasible.

**Comment by Ryusennin** [comment] 2021-02-26 23:11
Thankfully NASA still supports and updates Curiosity's OS.

Anyway, as afr as I can test, DS4W 2.2.7 still works correctly on Win7 + ViGEm 1.16.

**Comment by nefarius** [comment] 2021-03-04 18:13
Two major problems with OS version below Windows 10 from my point of view (and the decision to cut ties for my projects, which I didn't decide lightly):

## Modern frameworks

Under the hood Microsoft is doing a terrific job (no pun intended) to provide modern frameworks for driver developers to avoid common mistakes, hug amounts of duplicated and potential error-riddled code and new features.

For ViGEmBus's future (and the future of my sanity) I want (*need*) to build upon new frameworks like [Microsoft DMF](https://github.com/Microsoft/DMF) and [UDE](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-emulated-device--ude--architecture), which in turn **require** interfaces and libraries only present in Windows 10. Microsoft has not back-ported them to Windows 7 (or some even to Windows 8.x) so that's basically a touch choice: stick with "legacy" OS compatibility and sacrifice technologies that would greatly benefit the stability and future of the project? Well... eh 😅 

## Production signing

You might have seen this topic a few times here and there. It's nice to have code running on Windows 7 to 10 but it's of no use if the kernel refuses to load it. Now the history of driver signing requirements is long, complicated and probably deadly boring to most readers so I'll cut it short; if we ignore loopholes, there's only two options to get your driver to load on the typical gamers machine:

- you stick to Windows 10 exclusively and trade in like half an hour of your time for a tedious but manageable process uploading your driver to Microsoft to get it "attestation signed". This method is fairly quick and painless (if we ignore the... not ideal UI design of the submission website 🙄) and leaves you with a driver that will load on Windows 10 (and Server 2016/2019 although the official docs contain errors about that) even with Secure Boot on.
- you waste a day to a week of time and electricity and throw your driver into the [Windows Hardware Lab Kit](https://docs.microsoft.com/en-us/windows-hardware/test/hlk/), which requires a PC (or VM, but that's technically not allowed) **for each Windows edition and architecture** you want the driver to be qualified for and run the procedure every time you change one bit in the driver and want to ship an update. My current team size (1) is *not* a fan of this approach 😅 I did it for the last stable 1.16 version and it took me a week of tinkering and becoming very angry because the process ofc. isn't like clicking 2 buttons and waiting a few hours, it literally involves setting up a test lab. I want to focus on coding, not masochism 😬 

Hope I could give you some insights. I don't hate older OS's, they hate me 😆

**Comment by ukprinter** [comment] 2021-03-06 19:18
Does this explain why I can not see any controllers after installing DS4windows??

**Comment by nefarius** [comment] 2021-03-06 20:26
> Does this explain why I can not see any controllers after installing DS4windows??

We can't know that if you don't tell us details about your system and setup 🙂 kindly search the existing issues or open your own to not hijack this thread, thank you!

**Comment by Ryochan7** [comment] 2021-03-06 21:05
I still get emails every once in a while from people legitimately asking why DS4Windows does not support Windows XP.

It really is a hassle having to try to actively work against Microsoft's decisions. Them silently killing off Windows 8.1 support for driver projects with their most recent signing requirements doesn't help matters. I was hoping to finally look into diving into driver development for a bit but obstacles keep coming up. The VMulti fork will probably never truly exist except on my own computer; the `virtualkbm_refactor` branch of DS4Windows has support for it.

VMulti fork:
https://github.com/Ryochan7/vmulti

DS4Windows branch that can use the driver:
https://github.com/Ryochan7/DS4Windows/tree/virtualkbm_refactor

**Closed** 2021-03-19 15:06 UTC
