### ISSUE TITLE
"Hide DS4 Controller" mode not working even though no other application is having access

### ISSUE THREAD

**Issue by DELTAA1** [Ryochan7/DS4Windows#844] opened 2019-10-02 17:53 UTC
Just like it says in the topic: even with every nVidia, Steam or Microsoft overlay app closed, I still manage to get the exclusive access error while trying to hide my controller, any ideas why that may happen? It worked perfectly until today. 
![632f337de18e8496ef3c050cbf3dba7c](https://user-images.githubusercontent.com/56048827/66068647-43d8c400-e54e-11e9-95ab-8cbf86c07c27.png)

**Comment by mika-n** [comment] 2019-10-02 19:05
I guess you have seen the Wiki page (I assume because you had managed to dive in the deep end of a pool and used the ProcessExplorer tip): https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

The sad truth is that it is not always very clear which app has opened a handle to DS4 controller and therefore conflicts with the built-in HideDS4Controller option. I guess you have rebooted the PC and then tried to run DS4Windows BEFORE opening any other apps and before connecting the ds4 gamepad. When ds4Win is running and ready to use the gamepad then connect the ds4 pad and see what happens.

If you really cannot find the root cause (ie app holding a handle and therefore exclusive access to gamepad handle is forbidden by WinOS) then HidGuardian device driver is the alternative solution. It works because it can do its magic in kernel driver level before any user mode app can do anything.

**Comment by DELTAA1** [comment] 2019-10-02 21:13
Forgot to mention that HidGuardian doesnt work for me & I have no idea why - double controller is still present (at least in Fifa 20).

Eventually though I managed to get it working, seems that rebooting my PC while having both my Dualshock controller plugged in and DS4Windows started with Hidden mode (even though it doesnt work), then immediately starting DS4Windows after the reboot, helps. I guess that DS4Win saves the info about Hidden mode option being turned on even after turning off the pc, which helps a lot.

**Comment by Omniphantasm** [comment] 2019-10-12 00:43
Same issue, HidGuardian doesn't do jack for me, I've uninstalled and reinstalled both this and input mapper hundreds of times. 

Tried every voodoo ritual the internet suggested and exclusive mode just refuses to work.

**Comment by Ryusennin** [comment] 2019-10-12 15:14
HidGuardian perfectly works with DS4Windows, providing you're using the specific test installer here:

https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide

Make sure the AffectedDevices registry key is correctly set, then reboot. Don't mix with other versions from InputMapper etc, you're asking for trouble.

**Comment by mika-n** [comment] 2019-10-12 17:34
@Omniphantasm  You probably don't have correct AffectedDevices system registry settings in HidGuardian settings (ie. HidGuardian settings, not DS4Windows settings). 

The "Test Installer" of HidGuardian linked above adds proper values for official Sony DS4 gamepads, but if you have some 3rd party compatible gamepad then you have to list the correct device identifier in AffectedDevices system registry setting. HidGuardian uses AffectedDevices registry setting to identify those devices (fex gamepads) it should hide from other apps. If AffectedDevices setting doesn't match the hardware ID of your controller then HidGuardian doesn't hide the physical controller.

Here are couple posts which might help you to understand how HidGuardian works and how to identify the hardware ID of  a device in WinOS DeviceManager.
https://github.com/Ryochan7/DS4Windows/issues/669#issuecomment-487302990
https://github.com/Ryochan7/DS4Windows/issues/720#issuecomment-499097172

What kind of controller you have? What do you see in DS4Windows Logs tab page? Do you have the latest official DS4Windows with HidGuardHelper.exe tool (should be in the same folder with DS4Windows.exe file)?
https://github.com/Ryochan7/DS4Windows/releases

**Comment by Omniphantasm** [comment] 2019-10-12 17:36
DS4, just randomly started working this morning.

Damned if I know why but it seems to be consistent so I'm just going to leave it alone since it seems to be stupidly finicky.

**Comment by mika-n** [comment] 2019-10-17 12:11
I haven't tested HideDS4Controller option without admin privileges (the app asks for those if DS4Windows was not started using "Run as administrator" option or not launched via a TaskScheduler job using elevated privileges). Feel free to test it.

About HidGuardian. You can tweak HidGuardian settings on the fly, Just whitelist Steam process in HidGuardian sysreg settings (see HidGuardian system registry settings. There are AffectedDevices and Whitelist settings). You can either create a script to maintain the list of Whitelisted process IDs (ie. process id of Steam process is different everytime you reboot a PC or quit/restart the Steam client).

Whitelisted processes can see the original physical controller. DS4Windows app uses HidGuardHelper.exe tool to modify this HidGuardian sysreg entry on the fly using the current DS4Windows process ID. You could do the same for Steam process by using your own scripts or HIDer tool if you are lazy and don't want to create the script yourself.
https://github.com/samehb/HIDer

**Comment by ceedveed** [comment] 2019-12-30 01:42
Is Microsoft Edge open (windows and background processes)? It seems to interfere with exclusive mode.

**Comment by EvanIsGod** [comment] 2020-01-08 08:21
IF YOU HAVE AN NVIDIA CARD: Disable the in-game overlay on GeForce Experience, close GeForce Experience, go to task manager > services > and look for NvContainerLocalSystem. Right click, press Stop.

IF YOU HAVE A REDRAGON BRAND KEYBOARD/MOUSE: close the Redragon hub app. Don't know why this craps it out, but if Redragon is open, it kind of holds your controller hostage for WHATEVER reason.

**Comment by kalogs** [comment] 2020-01-21 13:40
I would just like to add to this just for the sake of information gathering:

I have been using DS4Windows for a long time(Since early Jays2Kings), and have not had any problems with exclusive access to my BT connected controller(DS4) for months or maybe even years now, and I have never run it as administrator nor used HidGuardian.

Yesterday it got an update and it still worked fine.
I put my computer to sleep, and a few hours ago when I wake it up and start DS4Windows again, it began complaining about exclusive access, not even a reboot solved it.

After closing programs and stopping services even remotely plausible, I was for the first time forced to run it as administrator, which solved the problem.

Maybe this will revert in a minute, month or never, seems a bit arbitrary at times, but I guess that is Windows in a nutshell(sigh).

Good luck and happy hunting!

**Comment by grasmanek94** [comment] 2020-06-14 10:55
For me it's always MicrosoftEdge.exe and MicrosoftEdgeCP.exe which are suspended / in the background. Make sure to kill these before aquiring exclusive locks.

**Closed** 2020-08-06 16:05 UTC
