### ISSUE TITLE
Windows 10 Insider Preview (Build 21322.1000) unable to properly remove the emulated(?) controller.

### ISSUE THREAD

**Issue by SwigS-27** [Ryochan7/DS4Windows#1926] opened 2021-03-05 21:59 UTC
This has been an issue for a few insider builds now, when connecting a Dualshock 4 or Nintendo Switch Pro controller and either: 
1. Close DS4Windows
2. Disconnect the controllers
3. Stop the Service

Doing any of these three things causes Windows 10 to not act properly.
Many applications that use HID Controllers no longer open (e.g. Yuzu, Muse Dash, etc)
While others crash when trying to configure certain things (e.g. Ryujinx)
Windows is no longer able to add or remove any devices correctly anymore. So plugging in a Keyboard, USB, Capture Card, etc. no longer works. And it'll still think a keyboard or controller is still connected even when it isn't.

The only fix for this is to restart Windows. This seems to not just affect DS4Windows but also BetterJoyForCemu. So it might be related to the drivers. As the "HID-compliant game controller" that shows up in settings gets stuck on a "Driver Error" after doing one of the things mentioned above and is unable to be removed.

Below is a video that hopefully at least shows some of what happens.
https://youtu.be/Kt5EG-jMS84

**Comment by Ryochan7** [comment] 2021-03-05 23:10
I can only hope the issue gets fixed before that Windows build goes public. It really sounds like Microsoft messed things up.

**Comment by DaRkL3AD3R** [comment] 2021-03-22 04:49
This is extremely interesting to me as I experienced something _semi_ related a few years ago. Basically something would go haywire with my keyboard and its software, and this would completely lock up the USB HID controllers like you're experiencing. Any programs that tried to interface with these drivers would completely lock up and freeze, or outright crash, again like you're seeing. The solution was to unplug my keyboard and the problem went away, for a few days, before showing up again.

The bizarre thing is, I am running the exact same hardware, keyboard and software version too, and this issue no longer happens. I really have no idea what resolved it, but if you want to see this bug in action and wonder if it's related, see my video of it here: https://www.youtube.com/watch?v=e9D3mYd80L4

**Comment by mbc07** [comment] 2021-04-14 07:49
Just a heads up, this issue was caused by a Windows bug which got fixed on Insider Preview build 21332 from early March. It no longer happens since then...

**Comment by Ryochan7** [comment] 2021-05-19 17:17
That is good news. Especially with the recent Windows update, I am going to assume that the initial problem has been resolved so this issue can be closed.

**Closed by Ryochan7** 2021-05-19 17:17 UTC
