### ISSUE TITLE
DS4 vibration won't stop

### ISSUE THREAD

**Issue by Aethyrion** [Ryochan7/DS4Windows#1805] opened 2021-01-24 12:56 UTC
Starting from version 2.2.0, DS4 vibration won't stop after being triggered for the first time until DS4Windows is stopped or the controller is turned off. Problem noticed while using Dolphin emulator with any game. Still present in version 2.2.2.

Problem not occuring in 2.1.23 and earlier.

Windows 10 x64
Bluetooth DS4 connection
ViGEmBus 1.16.112.0

Possible duplicate: https://github.com/Ryochan7/DS4Windows/issues/1730

**Comment by mika-n** [comment] 2021-01-24 22:39
You should install the latest VigemBus 1.17.333 version when using the the 2.2.x DS4Windows version.
https://github.com/ViGEm/ViGEmBus/releases

**Comment by Zenjir0** [comment] 2021-01-30 00:57
I too have this issue. I was going to try and update ViGEmBus to see if it fixed the issue, but it does bring up the idea of: Shouldn't DS4Windows either prompt or auto update ViGEmBus for the user? I think prompt is probably the best option.

**Comment by dante3732** [comment] 2021-02-15 13:27
Have some issue, in PCSX2 berserk and in Cemu zelda breath of the wild. I update on last vigem and it not help.
I downgrade version to january 2020 and i think it work fine.

**Comment by Ryochan7** [comment] 2021-02-15 18:50
Short summary before I close this duplicate issue. The issue actually came back from the update to ViGEm specifically the ViGEmClient library used for full DS4 emulation; that update corresponds with DS4Windows 2.2.0.

From version 2.2.0 Changelog:
> Import newer ViGEm.NET libraries for ViGEmBus 1.17.333.0 extended support
> Allow passthru of Touchpad and Gyro to output virtual DS4. Requires ViGEmBus 1.17.333.0 and Windows 10

https://github.com/Ryochan7/DS4Windows/releases/tag/v2.2.0

The old notification queue that had been used was removed by Nefarius thinking it was not needed anymore. Testing has shown that it is still needed at the client library level. Some experiments so far seem to indicate that the current proposal fixes the infinite rumble issue again. The change will likely be included in the next version of DS4Windows.

Closing this issue as a duplicate of issue #1730

**Closed by Ryochan7** 2021-02-15 18:50 UTC
