### ISSUE TITLE
Ds4windows no longer works on my windows10 18.03

### ISSUE THREAD

**Issue by grysor** [Ryochan7/DS4Windows#368] opened 2018-07-30 00:36 UTC
Hello
I have a desktop pc ,I was under windows10 pro 64bits and until version 17.09 Ds4windows worked perfectly, it always detected my controller sony dualshock 4 V2 and I could play my games final fantasy 15 windows edition and the witcher 3 everything was fine.
Then I updated my windows10 to version 18.03 yesterday
and now, whenever I run Ds4windows, it detects more my controller and tells me: "no controllers connected" :(
-I specify that I always use the official USB cable of the original dualshock 4.
-I have tried several times to reinstall ds4windows and reinstall by settings in ds4windows, the ds4 driver
-But nothing to do the problem is still there
-By despair, I installed another software: scp toolkit last Update: 2017-12-18 by sourceforge website
and it perfectly detects my dualshock 4 V2 and works very well in my games
-How to fix this problem with ds4windows? Thanks in advance

**Comment by jonaaa20** [comment] 2018-07-30 00:41
First of all, this isn't a problem with the DS4Windows, it works fine here on 1803.

Okay, what you can do? Reinstall your windows and reinstall the drivers(VIGem or SCP), if the scp doesn't work, try the vigem build...

If you used hidguardian, reinstall it too.

**Comment by grysor** [comment] 2018-07-30 20:51
Hello jonaaa20 thank you for your help
I reinstalled the SCP drivers and it still does not work again
I then installed the ViGEm version as you indicated by this link: http://ryochan7.xyz/ds4windows/test/DS4Windows_1.5.1_ViGEm_x64.zip
-but he always tells me "no controllers connected" :(

last solution, the one you suggest me: hidguardian. But I do not know or download it? And I do not know the process to install it
Thank you in advance for your answer

**Comment by TristanYoung** [comment] 2018-07-30 23:50
How to install HIDGuardian
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian---Install-and-Setup-Guide

There is also an HIDGuardian filter driver installer written by Ryochan7, but I haven't actually seen it or used it.  The instructions I wrote work well, and I haven't had time to track down the filter driver installer, so I haven't gone on the hunt.

If someone wants to post the link to it, I'd be greatly appreciated.

**Comment by grysor** [comment] 2018-07-31 01:28
Hello TristanYoung  
thanks for your help and your HIDguardian link :)
I installed HDguardian by following the instructions of your link in C: \ Program Files
-then I started Ds4windows. I still have: "no controllers connected"
I reinstalled the scp driver then rebooted my pc but my controller is still not detected.
-I tried the version ViGEm but it does not change anything, the problem is still the :(
-if i plug my controller into a different USB port on my pc the problem always there

-Here are several logs of my ds4windows and my device manager if you detect something that is wrong:
[log.txt](https://github.com/Ryochan7/DS4Windows/files/2243383/log.txt)
[loggem.txt](https://github.com/Ryochan7/DS4Windows/files/2243384/loggem.txt)
![screenscp](https://user-images.githubusercontent.com/35570935/43432137-91bf2396-9471-11e8-8b74-7c5dbd4e9e18.png)
![mygestionnaire](https://user-images.githubusercontent.com/35570935/43432144-9bec5d66-9471-11e8-8478-79ae3c110a13.png)
![gest periph](https://user-images.githubusercontent.com/35570935/43432160-b4455a48-9471-11e8-9e76-c77fef8cbd07.png)

**Comment by grysor** [comment] 2018-07-31 01:53
otherwise, my controller is always connected to my pc.When I open "devices and printers", the xbox 360 controller for windows is not in it. On the other hand, if I launch the software scp toolkit, it detects well with my controller, the xbox 360 controller for windows appears as on my screenshot surrounded in blue color ...

![inkedperipheriques et imprimantes_li](https://user-images.githubusercontent.com/35570935/43432835-122bd562-9475-11e8-954a-c66cf766eaab.jpg)

**Comment by grysor** [comment] 2018-07-31 02:07
I realized that by unplugging my controller dualshock 4 V2 and then re-connecting, my pc recognizes it as "wireless controller" surrounded in red on my screenshot and here are the properties:
![gest periph printers](https://user-images.githubusercontent.com/35570935/43433343-31e87ff2-9477-11e8-9009-e905c94e8f32.png)

**Comment by grysor** [comment] 2018-07-31 23:24
help me please 😭

**Comment by grysor** [comment] 2018-08-02 14:40
Hello TristanYoung
thank you for your help 😊
I followed all the methods you indicated to me
For the usb drivers I visited the website asus, the manufacturer of my motherboard asus Z97-A, but I have all the latest drivers and they have not been out for at least 3 years ...
I also do a search for drivers by the very very good software Driver booster 5 but I have all the latest drivers update.
-I then followed all your steps from 1 to 14
-In step 15: "Press and hold the PS and OPTIONS buttons simultaneously until the lightbar starts to flash", when I do this, nothing happens in my windows and my lightbar does not flash in blue ...
-Also, the problem is that every time I unplug and re plug my dualshock 4 v2, it appears every time in "Everything else" automatically, and not in "Bluetooth - Mice, keyboards, pens, or audio and other kinds of Bluetooth devices " 😞
see my screenshot surrounded in purple color
-And when I select " Bluetooth - Mice, keyboards, pens, or audio and other kinds of Bluetooth devices " it searches it searches but never detects my controler dualshock 4 which is well plugged in. I tried others usb ports and tried again and my controller is never detected in "Bluetooth - Mice, keyboards, pens, or audio and other kinds of Bluetooth devices" 🙁

Under 17.09, ds4windows perfectly detected my dualshock4 each time.
Then I made the update on August 26 , 2018 under 18.03 and at 7:47 the update was finished and since then, Ds4windows no longer detects my dualshock4
I think windows changed me drivers, and the problem comes from there ...
-Here is the event observer, usb section with the date or I finished the update I think the problem comes from there, but I am not a computer specialist and am lost ...
![inkedinkedperipheriques bluetooth_li](https://user-images.githubusercontent.com/35570935/43591021-b104df4a-9672-11e8-9faa-52edd7dc6d89.jpg)

"If you lived in Ottawa, Canada - I'd say let's meet up" 😄 no i live in france world champion 😆

**Comment by TristanYoung** [comment] 2018-08-03 01:35
Let's keep the world champion stuff out of this ;)  If you're referring to sports, I am not a sports fan.

I'm running the same version of Windows 10 as you - v1803, not a problem. But it could be some sort of driver or stack update that broke DS4Windows functionality but not mine.  I had a Windows 10 update (from the insider preview fast ring) break the bluetooth driver support for my Cirago SCR based bluetooth radio, and ended up buying an ioGear Broadcomm based bluetooth radio to get things working again.  Microsoft fixed the issue, but after reading a post that SCR radios aren't recommended, I decided to keep using my ioGear radio.  I figured the issue in my case was due to an updated driver, or negative changes in the bluetooth stack.

If you can, revert to the previous version of Windows (v1709) that worked properly for you, and verify that DS4Windows still works.  If it does work, then there seems to be an issue that Windows 10 1803 update introduced.  If it doesn't work anymore on v1709, then I doubt it's a Windows version issue.  

Have you tried older versions of DS4Windows?  I always keep 10 or so older versions hanging around, and you can download older versions from this website.  If you can find a version that works, it might be useful to know which one.  Then all the changes that happened since that version can be audited for issues.

I wish it was easier to diagnose.

Regarding pressing OPTIONS + PS, it should only flash white after holding the buttons for about 5 seconds during pairing I believe.

Have you tried clicking on the Wireless Controller under Everything else, and then click on Remove Device, and then try to re-connect it the way I mentioned?  It shouldn't matter, as I've tried it with multiple options, and it always loads correctly.

**Comment by grysor** [comment] 2018-08-04 02:59
hello TristanYoung thank you for your help
revert to version 17.9 will be complicated for me, I do not know how to do and afraid of possible bugs then ... I do not prefer, sorry ... but that's certain, ds4 worked perfectly in 17.09 for me

-For your question: "Have you tried older versions of DS4Windows?"
-Yes, I tried a few days ago a dozen old versions of ds4windows going back to the beginning of 2017 and nothing worked for me :(

otherwise, I remembered that the 25/07/18 the day before or I did the update under 18.03, I made a search for drivers by the software: Driver easy, because the screen mirroring did not work on my pc
-And driver easy updated these 3 drivers:
-intel ethernet connection i218-v
-nvidia high definition audio
-Intel 9 Series Chipset Family SATA AHCI Controller

I wonder if this last updated driver did not "broken" Ds4windows?

Otherwise, for HIDguardian I installed a few days ago, it seems that I did not succeed to install it correctly :( because on this video, at 2:20 in the registry it has the folder HIDguardian:
https://www.youtube.com/watch?v=WJHxTgMngvY
But I do not have it!
it is said that HIDguardian should be installed here:
"For x86 32bit Windows: C:\Program Files (x86)
For x64 64bit Windows: C:\Program Files
Simply copy and paste one of the above listings to the address bar in File Explorer "

-My windows10 is 64bit but I do not have:  C:\Program files!
-Ryochan7 had to make a error because the 64bit version only has   C:\Program Files (x86)
-So I had installed HIDguardian in C:\Program Files (x86)

And it may be why it does not appear in my register as on the video?

**Comment by TristanYoung** [comment] 2018-08-04 07:01
I understand your apprehension about reverting Windows to an earlier version.  You should make backups before a significant update, because updates can toast your system - it happened to me recently - totally screwed it up, with no way to undo the mess.  Also makes it easy to try different versions when they are backed up.

The only way we can discount the Windows v1803 upgrade is to verify it against the older version, find other people who are having the same issue on v1803, or wait to see if it gets fixed in a future Windows version.  There aren't many people joining this bug thread, so it's probably limited to your machine.

Ok, so trying older versions of DS4Windows didn't help.

I wouldn't use Driver Easy.  Checking for, and updating drivers isn't hard.  In most cases, you can bookmark the drivers on the manufacturer's websites, keep a list of latest-version info, and compare.  I'm hugely distrustful of programs that claim to fix things, or make life easy. It makes you download and install the updates yourself, which is most of the work,  I'm not saying this is causing issues, just mentioning that it's unneeded.

The drivers you updated wouldn't cause the issue you're having.  They are network, audio and storage devices, not HID/controller devices.
-intel ethernet connection i218-v
-nvidia high definition audio
-Intel 9 Series Chipset Family SATA AHCI Controller

It doesn't matter where you install DS4Windows, and depending on how you're installing HIDGuardian, it doesn't necessarily matter where you install HIDGuardian.  The Program Files and Program Files (x86) folders mean nothing.  It's merely way to separate 32bit and 64bit versions of programs.

Honestly, I don't think you should have HIDGuardian installed until you get the controllers working properly in DS4Windows without it.  HIDGuardian is only for exclusive mode. It is not a requirement of DS4Windows.  Once things are working again, then I'd install HIDGuardian.

I don't know why HIDGuardian is not appearing in your registry as per the video.  When I return to my studio later tonight, I'll export my HIDGuardian registry branch, and post it.  You can then download it, click on the file, and import it into your registry - maybe that will help.

I know these sorts of issues can be annoying.  I may be missing something.  I'm much better at fixing physical machines I can get my hands on, and have had good experiences with remoting into distant machines to effect changes.

**Comment by grysor** [comment] 2018-08-04 15:25
thank you for these details 🙂
EDIT: I'm sorry I was wrong:  Hidguardian is fine in my register exactly the same place as on the youtube video at 2:20!
-But on the other hand, on the video, in "Parameters" it has the line:
"AffectedDevices" and
(standard)
-But I do not have those lines ☹️
-I just have: (by default)
-Maybe that's why ds4windows does not work anymore I do not know?
In the meantime, I use the software scp toolkit to play my games and my dualshock 4 works perfectly with him ... but I like him less because in the task manager he uses about 15% of memory and 15% of the processor when it is started, while Ds4windows him, did not use anything and it's better...

**Comment by TristanYoung** [comment] 2018-08-05 01:29
You are missing the whitelist entries.

You can try this:
1. Run DS4Windows as Administrator
2. Click on the Settings tab
3. Click on Write HIDGuardian Device List

Administrator privileges are required for DS4Windows to modify the registry.

Alternatively, you could try importing my HIDRegistry branch:

[HIDGuardian Registry.zip](https://github.com/Ryochan7/DS4Windows/files/2259955/HIDGuardian.Registry.zip)

Unzip the above file, extract the contents, and then open the .reg file and import into your Registry.  This one works for me and the DS4 controllers currently available for purchase (to the best of my knowledge).

I don't think you have to reboot after, so do it anyways.

Let me know how that works for you.

**Comment by grysor** [comment] 2018-08-06 00:33
hello :) I did what you indicated me:
"Run DS4Windows as Administrator
  Click on the Settings tab
  Click on Write HIDGuardian Device List

Administrator privileges are required for DS4Windows to modify the registry"

-Then I imported your HIDGuardian branch
I made a double click on it and it came into my register immediately, thank you

-Then I rebooted my computer
but my dualshock 4 is still not detected by ds4windows :(

here is what i get after import into my registry in hidguardian, enum and parameters:
![hidguardian](https://user-images.githubusercontent.com/35570935/43691713-ca19bedc-9920-11e8-8e7e-6cc309184f95.png)
![hid enum](https://user-images.githubusercontent.com/35570935/43691715-d3dfe31a-9920-11e8-8d57-36253e06b489.png)
![hid parameters](https://user-images.githubusercontent.com/35570935/43691718-d9bd916a-9920-11e8-851f-ae7e34ca8a79.png)


i think i'm going to abandon until a next windows10 update that can maybe fix the problem if a lot of people have complained ...

thanks for your help

**Comment by TristanYoung** [comment] 2018-08-06 06:49
Hello,

I don't know if you'll get this resolved by waiting for a new version of Windows.  It's working just fine in Windows 10 v1803, and there doesn't seem to be anyone else is saying they are having the same problem, so it seems unique to your particular setup.

You had it working in a previous version of Windows.  I know you don't want to revert back to that version to see if it works, which I can appreciate, but it can help track down the problem. If reverting doesn't solve the problem, then you could have malfunctioning hardware or a corrupted Windows installation - just some examples.  Updating to whatever next version of Windows probably won't help you in those cases.

Windows 10 v1803 + DS4Windows  - with and without HIDGuardian works very well on my setup.  I freshly installed mine a few weeks ago, after a catastrophic Windows 10 update went ugly.

Sorry, I'm all fresh-brained in the morning, but only have time to get on the forums in the evening. By this time, my brain slows down, but I like to help out when I can.  Sorry I couldn't be much help.

**Comment by grysor** [comment] 2018-08-06 22:16
hello,
I think that it is possible that I solve my problem by uninstalling drivers or by modifying values ​​in the register by doing regedit, but it will have to be for that expert and I am rather novice :(

can you tell me if you also have a dualshock 4 like me?
-on a youtube video a person has dualshock 4 and in his device manager, in human interface device, he has:
HID-compliant game controller
in blue on my screenshot :
![periph](https://user-images.githubusercontent.com/35570935/43743428-15f4157c-99d6-11e8-91a7-2aa8a1aa27aa.png)

-But the problem is that I do not have HID-compliant game controller :(
Here is my device manager and what I have in the same place as him:
![my periph](https://user-images.githubusercontent.com/35570935/43743496-6814048e-99d6-11e8-8556-e8f562f6db2d.png)

- Can you tell me, if you unplug your controller, if then "HID-compliant game controller" disappears from your device manager, and if you reconnect, HID-compliant game controller reappears?

On this 2nd screenshot, the person has his controller dualshock 4 which appears in peripherals and printers with these 2 things:

HID-compliant game controller
+
USB Input Device
![controller](https://user-images.githubusercontent.com/35570935/43743534-91e1911e-99d6-11e8-80ee-3ee637f75e39.png)

-And the problem is that I do not have HID-compliant game controller + USB Input Device! :(
-I've just :
-Wireless controller libusbK USB Devices which is from ScpToolkit (which I'm happy because my dualshock 4 is detected :)
and
-USB composite device

and I'm sure it's because I do not have these 2 things that my dualshock 4 is not detected by ds4windows :( 
if an expert goes through here and can find what's wrong ...

**Comment by RedKage** [comment] 2018-08-09 08:25
From what I see here, your DS4 pad is not detected correctly by your Win 10 as an input device.
It detects it as a sort of audio output device (by the looks of the icon) in the screenshot you provided.
Could be because DS4 v2 have the jack audio port which works and is detected (which is not the case for my DS4 v1)

You did not even have HIDGuardian before the win update so the issue is definitely not there.
Using HIDGuardian will just add a new layer of potential issues instead.

Your issue is that as long as Win 10 does not detect your pad as a real "Wireless Controller" type device, you are simply screwed. I think.

What about, reinstalling the xbox360 controller drivers?
http://www.microsoft.com/accessories/en-gb/d/xbox-360-controller-for-windows
Maybe this will help your Win 10 to better detect your pad, as a pad.

Another idea: what about trying to uninstall+delete the driver of your weird "Wireless Controller"?
So that Win 10 reinstalls the proper one.

Hey, just saw another thing: your wireless controllers are located inside the "libusbK USB device"
This is part of the Scp driver kit tools thingy.
BUT, you have installed the ViGEm build of DS4Windows, which is not using the Scp drivers anyway.

So that's maybe another thing which can cause you issues.
If you are using the Scp drivers like you are right now, use the default DS4Windows build.
If you are using the ViGEm drivers, use the DS4Windows ViGEm build.

**Comment by grysor** [comment] 2018-08-09 23:34
Hello RedKage
thank you for your help and all your suggestions 🙂
-Yes, it's a loud speaker icon that I have and named wireless controller
-By cons I do not remember if under 17.09 I had this same icon or not ...
one thing is sure, with this same controller, ds4windows detected it perfectly well hundreds of times when I was under 17.03 and 17.09 and my games worked perfectly well with.

-Yesterday I changed usb cable from my dualshock 4 to try, but the problem is still there.
-I have a second controller dualshock 4 V2 new too.I unplugged the first, then I plugged the second and unfortunately the icon that appears is the same, this loud speaker named wireless controller 🙁 and ds4windows does not detect it either :(

"You did not even have HIDGuardian before the win update so the issue is definitely not there."
-Yes exactly, I did not have HIDguardian either under 17.03 or under 17.9

"What about, reinstalling the xbox360 controller drivers?
http://www.microsoft.com/accessories/en-gb/d/xbox-360-controller-for-windows
Maybe this will help your Win 10 to better detect your pad, as a pad."
-thanks for your link.I installed it.I took the windows7 64bits version
once installed I got this message:
![message affiche juste apres l install de x360](https://user-images.githubusercontent.com/35570935/43926603-229947d2-9c2b-11e8-9143-69468b48c68f.png)
-before selecting one of the 2 answers on the screen, I launched ds4windows 1.5.3 in administrator
-Unfortunately I still have: No controllers detected .I have reinstalled the ds4 drivers by ds4windows settings but controller still not detected
-I then tried with ds4windows ViGEm version but controller not detected

-For your idea:
"what about trying to uninstall+delete the driver of your weird "Wireless Controller"?
So that Win 10 reinstalls the proper one."
-I had already tried.But I just redo it :  once the loud speaker icon is uninstalled, nothing happens.Ds4windows still does not detect my controller. I rebooted and restarted ds4windows but still the same problem.
-By cons I do not understand what you indicated me :  " + delete the driver "
-How to uninstall this driver? or find it? which one is it please?

"If you are using the Scp drivers like you are right now, use the default DS4Windows build.
If you are using the ViGEm drivers, use the DS4Windows ViGEm build."
-I have both :) Ds4windows 1.5.3 and ds4windows ViGEm build, like that when I test modifications on my pc to try to solve my problem,I test the 2 ds4windows...

-otherwise yesterday I tried one thing:
I have 3 other generic controllers. I plugged them one by one into one of the USB ports of my zalman z11 neo computer case. Then when I go to my device manager, there is:
"HID-compliant game controller" that appears in: Human Interface Device
-and when I go in: peripherals and printer, there is more icon loud speaker that I have but a game controller icon
-Here is a screenshot with all my 3 controllers connected all at the same time in: peripherals and printer:
 ![mes 3 controllers](https://user-images.githubusercontent.com/35570935/43930403-7d2001c4-9c39-11e8-9f62-1e94ad870ef2.png)

-And when I unplug my 3 generic controllers, the 3 : HID-compliant game controller disappear in my device manager.

-otherwise,I forgot to specify, my 2 dualshock 4 V2 are 200% official, I checked the serial numbers behind, and other details on the controller that proves that they are authentic 200% and they are new and only 3 months old.

-otherwise my config pc:
i7 4790, msi gtx 1060 gaming X 6go, 2x8go ram gskill trident X 2133mhz, motherboard asus Z97-a, keyboard roccat ryos mk pro, mice sabre laser rgb, power supply cooler master g550m

and i have all the microsoft net framework up to date and microsoft visual c+ and runtime up to date. i'm sure it's the maj of windows that broke everything for my controller and ds4windows ...

**Comment by RedKage** [comment] 2018-08-10 08:02
When I talked about uninstall+delete I meant this:
http://prntscr.com/kgxsn9
http://prntscr.com/kgxsr7
There is a checkbox to effectively remove the driver as well as removing the device.
In the screenshots above I selected a random device on my PC to show you the 'remove driver option'
Ideally, you'd need to find your strange "audio speaker gamepad" in the device tree, and then try to remove+uninstall it.

But at this point, I'm afraid I have no more ideas.
To me it feels like something is broken in your Win 10 install.
Possibly some drivers related. :/

**Comment by grysor** [comment] 2018-08-11 02:36
thank you for your suggestion :)
I went there, as you can see on my screenshot, but in "video controllers, audio and games" and "audio inputs and outputs" there is no strange "audio speaker gamepad" ...
![audio](https://user-images.githubusercontent.com/35570935/43987191-44248c48-9d1d-11e8-96ac-d49a97f64b46.png)


otherwise, I have several times for several days and again at the moment uninstalled the loud speaker icon named wireless controller by going in the properties as on my screenshot.
But I would like to know: my icon is named: "composite USB device" as you can see on my screnshot. And you, is your controller also named: "composite USB device" or otherwise?
![inkeddesinstal icone_li](https://user-images.githubusercontent.com/35570935/43987209-9b767826-9d1d-11e8-8d12-535482505955.jpg)


Once I uninstalled the icon, as in my screenshot, I went to my device manager.
- here a screenshot just before I uninstall the icon
![before desinstall](https://user-images.githubusercontent.com/35570935/43987217-b91d40da-9d1d-11e8-99e9-e97fae0f8080.png)

-After having uninstalled it, on the 3 "composite USB device" there were only 2 left, the one highlighted in blue on my screenshot had been uninstalled.

I do not know how to "transform" my "composite USB device" which is my dualshock 4 into "HID-compliant game controller"

-and if I plugged my dualshock 4 into another pc then I noted the HID \ VID which is in "hardware ID numbers" as on my screnshot, then I pasted this HID \ VID into HIDguardian in my registry?maybe my dualshock 4 would be detected next?
![hidvid](https://user-images.githubusercontent.com/35570935/43987306-2512f7b6-9d1f-11e8-9126-46e1a78862a2.jpg)
or it would take the help of an expert to know where is in the windows registry the file or folder that "manages my dualshok 4, who has registered and I go there and adds the HID \ VID of my dualshock 4...

if an expert goes through here ... I will regularly check here to see if someone found me a solution one day, we never know :)

**Closed** 2018-11-28 00:44 UTC
