### ISSUE TITLE
DS4 not detecting the controller. Controller not connecting via USB.

### ISSUE THREAD

**Issue by headrotz** [Ryochan7/DS4Windows#2946] opened 2023-05-16 22:26 UTC
Is anyone having this problem?
When I tried to plug in my ps4 controller, the light shines orange and then fades out after a second. The cable that I'm using isn't damaged or broken. I've tried many other cables, which didn't work. DS4 can't even find my controller because of this problem. Does anyone have a fix to this? I've tried to connect it to Bluetooth, I've tried to change the USB ports, and I tried to make it recognize the controller via control panel

**Comment by tonebacas** [comment] 2023-05-26 17:25
Can you post your log? Just to keep it clear, do a full system reboot, launch DS4Windows and plug in your controller. Then go to the Log tab in DS4Windows, hit the export button, save the log and share it here.

**Comment by ryz** [comment] 2023-05-26 19:06
@DistractionRectangle Thank you, this worked! I was going crazy trying to troubleshoot this issue as everything was working perfectly before.

**Comment by DistractionRectangle** [comment] 2023-05-27 15:40
Digging into this, it seems that Profiles.xml is initialized differently depending on whether it's run in portable mode or saving config under AppData.

Here's the Profiles.xml generated by first run when running the program and saving under AppData: [Profiles.xml](https://github.com/Ryochan7/DS4Windows/files/11582355/Profiles.txt)

And here's what is generated by first run when you choose to start it in portable mode: 
[Profiles.txt](https://github.com/Ryochan7/DS4Windows/files/11582359/Profiles.txt)

Notable differences: The portable mode version has a self closing `<CustomSteamFolder />` tag, and 

- DualSenseSupportSettings
- SwitchProSupportSettings
- JoyConSupportSettings

All have `Enabled` property set to `False`

Manually editing the Profiles.xml to match the one generated by first run when saving under AppData and restarting DS4Windows fixes the issue, my dualsense is now detected. This seems to confirm the bug is in generating Profiles.xml, which explains why upgrading older versions already running in portable mode works.

**Comment by Ryusennin** [comment] 2023-05-28 20:38
Since that bug was seemingly introduced in 3.2.0, it might be another casualty of the switch to XmlSerializer.

**Comment by headrotz** [comment] 2023-05-29 02:45
@tonebacas Sorry for the wait, I wasn't on for a while. There's the logs.
[logs.txt](https://github.com/Ryochan7/DS4Windows/files/11587755/logs.txt)

**Comment by headrotz** [comment] 2023-05-29 02:58
> 
I'm not sure what to do. Can you help me?

**Comment by headrotz** [comment] 2023-05-29 02:58
> Digging into this, it seems that Profiles.xml is initialized differently depending on whether it's run in portable mode or saving config under AppData.
> 
> Here's the Profiles.xml generated by first run when running the program and saving under AppData: [Profiles.xml](https://github.com/Ryochan7/DS4Windows/files/11582355/Profiles.txt)
> 
> And here's what is generated by first run when you choose to start it in portable mode: [Profiles.xml](https://github.com/Ryochan7/DS4Windows/files/11582359/Profiles.txt)
> 
> Notable differences: The portable mode version has a self closing `<CustomSteamFolder />` tag, and
> 
> * DualSenseSupportSettings
> * SwitchProSupportSettings
> * JoyConSupportSettings
> 
> All have `Enabled` property set to `False`
> 
> Manually editing the Profiles.xml to match the one generated by first run when saving under AppData and restarting DS4Windows fixes the issue, my dualsense is now detected. This seems to confirm the bug is in generating Profiles.xml, which explains why upgrading older versions already running in portable mode works.

@DistractionRectangle Sorry, I'm not sure what to do. Can you help me?

**Comment by DistractionRectangle** [comment] 2023-05-29 03:15
@headrotz Exit out of ds4windows (if shouldn't appear in the taskbar/tray, it must be completely stopped). Then replace the contents of Profiles.xml found in the same folder as DS4Windows.exe with [this](https://github.com/Ryochan7/DS4Windows/files/11582359/Profiles.txt). If you want to use the file directly, you have to rename the extension to xml, for whatever reason github won't let me upload xml files to comments.

Another way to get portable mode to work is to exit out and delete the folder for your current install, then install+launch v3.1.12 [per my previous comment](https://github.com/Ryochan7/DS4Windows/issues/2946#issuecomment-1565526949)

Last option is to delete then reinstall, opting to save to AppData during setup and just not use portable mode.

**Comment by headrotz** [comment] 2023-05-29 16:32
> @headrotz Exit out of ds4windows (if shouldn't appear in the taskbar/tray, it must be completely stopped). Then replace the contents of Profiles.xml found in the same folder as DS4Windows.exe with [this](https://github.com/Ryochan7/DS4Windows/files/11582359/Profiles.txt). If you want to use the file directly, you have to rename the extension to xml, for whatever reason github won't let me upload xml files to comments.
> 
> Another way to get portable mode to work is to exit out and delete the folder for your current install, then install+launch v3.1.12 [per my previous comment](https://github.com/Ryochan7/DS4Windows/issues/2946#issuecomment-1565526949)
> 
> Last option is to delete then reinstall, opting to save to AppData during setup and just not use portable mode.

The problem is the controller. It doesn't connect to control panel, so there's no way to fix it even tho I tried detecting the controller. I don't know how to fix it. I probably have to downgrade the firmware.

**Comment by DistractionRectangle** [comment] 2023-05-30 16:27
@headrotz If you setup hidhide before, it may very well be hiding your other controller from the system/control panel. By design it either hides it from everything not in the whitelist (or if you invert it to be a blacklist, hides it from everything in the list). 

Probably worth checking. If you have access to another computer you can also use that see if the issue is the controller or with the computer.

**Comment by DistractionRectangle** [comment] 2023-06-12 20:49
@headrotz , if you're satisfied that this was a hardware problem on your end you can close this out. I spun out my interpretation of this issue into #2963 which has already been addressed.

**Closed** 2023-10-01 17:25 UTC
