### ISSUE TITLE
Trojan:Win32/Zpevdo.B detected in v3.0.1 via Chocolatey

### ISSUE THREAD

**Issue by ThoAppelsin** [Ryochan7/DS4Windows#2040] opened 2021-04-06 16:18 UTC
I was updating my packages via Chocolatey today including ds4windows and then got this from Windows Defender:

![image](https://user-images.githubusercontent.com/6666524/113743264-291b7880-970c-11eb-91e4-ce6f51a527e9.png)

I then have promptly uninstalled the package. I can only hope that no damage was done.

What are you up to people!?

**Comment by Masamune3210** [comment] 2021-04-06 20:14
False positive, if it actually was anything malicious you would hear more people whining, don't ya think?

**Comment by mika-n** [comment] 2021-04-06 20:27
Öööö? Ever heard of false alarms in Win Defender? And here WinDefender doesn't complain anything, so don't know what you are up to

**Comment by ThoAppelsin** [comment] 2021-04-06 20:43
I have been using ds4windows since around mid April 2020, not once I had this sort of false positive. I have probably updated every second new version notice or so (must be every 1-2 weeks given how frequent it gets updated), each time via Chocolatey.

Defender did not complain once for the past 20 rounds of update. What changed this time around?

**Comment by Masamune3210** [comment] 2021-04-06 20:58
virus engines work off of unknown heuristics so we can never know for sure what caused the engine to think that this build for some reason is malicious or not

**Comment by mateusmedeiros** [comment] 2021-04-07 05:04
Considering what has been said already and the fact that this software probably has some functionality overlap with malwares (for benign purposes), it probably is a false positive.

However, one thing that can help in the future is to publish in the  assets or release description (I think description would probably the more quick and easy) a checksum of each file just to make sure the chocolatey package don't have a malicious version in there or who knows, maybe the person could have even been victim of a MitM attack or something.

I downloaded here the release from github and ran a ˋsha256sumˋ on it and got ˋc6f95a239fe1b33e3525f87c7ce4532aa98edc9e9bf679ac106d318064fd05aeˋ. So if that file on the OP's computer has the same hash, then we know that it almost certainly is a false positive.

**Comment by nefarius** [comment] 2021-04-07 11:06
[A good read on the topic on false-positives and why it is *not* the job of the accused software to clear their name](https://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/) 😉

**Comment by Ryusennin** [comment] 2021-04-07 13:32
"What are you up to people!?"

We're all trying to hack your rig, obviously.

Anyway, Windows Defender triggers a lot of bullshit. Wrappers/injectors like Reshade, dxvk, dgVoodoo, RTSS, even system utilities from NirSoft will regularly be flagged as "severe".

**Comment by mateusmedeiros** [comment] 2021-04-07 14:36
One of the main problems is that anti-virus softwares usually make too much assumptions behind the scenes without telling shit to the user. They also prefer to go overboard instead of "underboard". AKA false positives are better than false negatives.

Now, they do have a rationale for these decisions (be them good or bad), but the consequence is still the same.

If they try to detect malwares by an exact comparison, then any malware maker can easily escape those protections by regularly changing slightly the code / binary. So they do everything based on (sometimes shitty) heuristics to try to detect a malware even if it's different, and how loose they define these heuristics is basically what makes it generate more or less false positives.

When we have software related to games in general that tend to have a lot of hooking into processes, intercepting hardware input or output and stuff like that, the anti-viruses usually go trigger-happy and this is the result.

I don't use any anti-virus except the ones the OS force me to exactly because of that. It's a PITA. But I'm a developer, so I can see the aforementioned rationale of making all these invisible assumptions in the form of these heuristics without the user knowing and just saying "this be virus", "this be not virus" because it's what most people without a developing background would understand and care about.

**Comment by JohnFlowerful** [comment] 2021-04-08 04:10
I pulled these from chocolatey's page for these packages:
[DS4Windows_3.0.1_x64.zip (bd756386b0d8)](https://www.virustotal.com/gui/file/bd756386b0d8ca778275f9fe58a5ae26e141de5d649dd20d7744ad06035a29a3/detection/f-bd756386b0d8ca778275f9fe58a5ae26e141de5d649dd20d7744ad06035a29a3-1617604084)
[DS4Windows_3.0.1_x86.zip (c6f95a239fe1)](https://www.virustotal.com/gui/file/c6f95a239fe1b33e3525f87c7ce4532aa98edc9e9bf679ac106d318064fd05ae/detection/f-c6f95a239fe1b33e3525f87c7ce4532aa98edc9e9bf679ac106d318064fd05ae-1617557665)
Conversely...
[DS4Windows_2.2.15_x64.zip (e16b37104d2e)](https://www.virustotal.com/gui/file/e16b37104d2e921656c36a40dbd16298acc0f8466c8dfeae827293363adc0ac9/detection/f-e16b37104d2e921656c36a40dbd16298acc0f8466c8dfeae827293363adc0ac9-1616695246)
[DS4Windows_2.2.15_x86.zip (e1b9cb098a2d)](https://www.virustotal.com/gui/file/e1b9cb098a2d7dd8c1435964e5ab84501dc26e74131f9d3ad3a45fb21749a8bf/detection/f-e1b9cb098a2d7dd8c1435964e5ab84501dc26e74131f9d3ad3a45fb21749a8bf-1616701205)

Likely caused by the .net upgrade: https://github.com/Ryochan7/DS4Windows/commit/112298e410188b810c7e9eb11d3ab59d066e6744

Either way, your system probably installed the x64 flavour.

**Comment by Ryochan7** [comment] 2021-04-14 20:42
I am going beyond calling these false positives and just calling it **Extortion** for not paying for a signing certificate.

It is funny VirusTotal pretty much has no complaints for the x64 archives but has much more complaints about the x86 archives. With the 3.0.2 archives, now VirusTotal only complains about the DS4Updater.exe file. Also, just adding application icons to some of the supplemental programs got rid of many issues from past archives.

**Comment by nefarius** [comment] 2021-04-15 13:23
> I am going beyond calling these false positives and just calling it **Extortion** for not paying for a signing certificate.

I had Defender flag a **signed DLL I just compiled** with some random "Trojan.XXX" name, I recompiled and signed again, clean 😒

**Comment by mateusmedeiros** [comment] 2021-04-15 19:08
> I am going beyond calling these false positives and just calling it **Extortion** for not paying for a signing certificate.
> 
> It is funny VirusTotal pretty much has no complaints for the x64 archives but has much more complaints about the x86 archives. With the 3.0.2 archives, now VirusTotal only complains about the DS4Updater.exe file. Also, just adding application icons to some of the supplemental programs got rid of many issues from past archives.

That serves also to show how stupid these heuristics may be. I mean, come on. "Well, it doesn't have icons, so it must be a malware!". Like WTF.

**Comment by mika-n** [comment] 2021-04-17 10:14
closed as "fake false", there is nothing DS4Windows app itself can do about how certain "fake virusscanner" service reports "fake news" about "fake viruses"

**Closed** 2021-04-17 10:14 UTC

**Comment by Ryochan7** [comment] 2021-05-23 02:00
Related post regarding my assumption about anti-virus engines just flagging unsigned files.

https://github.com/Ryochan7/DS4Windows/issues/2161#issuecomment-846488505

It looks like there is much more of a reason to have gotten an OV Code Signing certificate than just the new KB+M driver. Not sure what I am going to do once the certificate expires next year though.

**Comment by nefarius** [comment] 2021-05-23 08:57
How unfortunate, and lazy alike, signed or unsigned can't help to distinguish malicious intent, it is supposed to provide the user with an easy way to validate **authenticity and integrity**, nothing more, nothing less. Sad that the AV "scene" contributes to this lie that signed binaries are in a general sense safer than unsigned. As with many things in IT: it depends 😐

**Comment by Ryochan7** [comment] 2021-05-23 18:56
Not a very open source friendly requirement to impose on mostly hobby projects. If it weren't for Corona-bucks, I probably would not have had the funds to pay for a code signing certificate. Not sure what will happen next year.

I almost have the UMDF virtual KB+M driver ready; it is mostly a UMDF port of vmulti. That was the whole reason I paid for a code signing certificate.

**Comment by nefarius** [comment] 2021-05-24 08:24
Crowdfunding or alternatives? I don't see why **you** should carry the sole burden for something literally only the user-base profits from.
