### ISSUE TITLE
Available XInput ports are being "used up" after bluetooth adapter reconnecting on Win7 with Steam running

### ISSUE THREAD

**Issue by aetx** [Ryochan7/DS4Windows#105] opened 2017-08-12 19:52 UTC
When Steam is running and the bluetooth adapter is disconnected and then reconnected DS4Windows can no longer plug in the X360 Controller with the used port. When changing to a different port it works again. But the port selected when the bluetooth adapter was disconnected and then reconnected does not work until a reboot.

It does not seem to matter whether the gamepad is connected during this or not.
If Steam is closed before disconnecting/reconnecting the adapter, the problem does not appear.

Hardware:
 - DS4 (2016)
 - Asus BT400

A part of the log follows
```
Connection to Scp Virtual Bus established
Searching for controllers...
Using shared Mode
Found Controller [..] (BT)
Plugging in X360 Controller #1
X360 Controller # 1 failed. Using DInput only mode
Controller 1 is using Profile "Gaming"
```

If this is not a bug of DS4Windows, I apologize and want to ask where the bug should be filed instead.

**Comment by shinra358** [comment] 2017-08-14 01:22
sounds like the old version. are you sure you are using ryochan's version?

**Comment by aetx** [comment] 2017-08-15 19:09
Originally, I installed the version from ds4windows.com (so Jays2Kings version(?)) and the DS4 Driver it installs after starting. But I have switched to Ryochan's version afterwards by overwriting the executables. During testing I have uninstalled and reinstalled the DS4 Driver/VBus Driver.

What slightly confuses me is, that the Hotkeys/About page says "Jays2Kings Build (Version 1.4.87)" even though I downloaded it from the Releases page of this fork.

To be sure I have uninstalled the VBus Driver via the Settings page, downloaded the current release of this fork, and run that (installing the driver again). The problem remains.

So I assume I am running Ryochan's version, if there is not something hiding from the first version.

**Comment by shinra358** [comment] 2017-08-15 21:58
delete everything and just download ryochan's version.

**Comment by aetx** [comment] 2017-08-15 22:18
Still exhibits the same problem.

**Comment by Ryochan7** [comment] 2017-08-16 21:40
I have not had a problem with XInput ports for some time. I will check the probem on my end and see if I can replicate the error.

**Comment by Ryochan7** [comment] 2017-09-24 03:37
The controller id mapping in Scp Virtual Bus is not the same as the XInput controller number exposed to the system. I can use a physical Xbox 360 controller and a virtual Xbox 360 controller at the same time with no problems. Also, I think Steam uses DLL injection for creating virtual Xbox 360 controllers when launching games so I wouldn't think there should be any conflict even if somehow you have Xbox 360 remapping support enabled in the Steam client. The only time you should run into this kind of problem is if you are running multiple programs that use the Scp Virtual Bus driver.

As it is, this works on my system and there is no use case to test. I am closing this issue.

**Comment by OptimalJew** [comment] 2017-10-14 14:55
Just started having the same issue. Moved from 1.4.96 to 1.4.97, and toggled off 'Hide DS4 Controller' to troubleshoot a rumble issue, and from then on out I've been stuck in dinput mode with xinput port 1 with an identical message as aetx in the log. It also appears that this broke exclusive mode on that port, as re-enabling it has no effect. Moving to xinput port 2 "fixes" it, but I don't know if that's a real solution or if this is going to happen again, and I'll have to continue to jump ports.

Don't think it's Steam, since I haven't opened it in weeks.

**Comment by Ryochan7** [comment] 2017-10-14 20:33
In the worst case scenario, I think that either disabling and then re-enabling the SCP driver or rebooting your computer should be enough to work around the problem. You should not have to uninstall and then reinstall the SCP driver.

The change to the Hide DS4 Controller option was supposed to help with exclusive mode problems and make sure that the controller scan was performed at the proper time. It seems like the controllers don't unplug from the SCP Virtual Bus in time before the next connection to the bus is started. It works on my system but my computer is fairly old (built around late 2012 I think) so maybe the time in between is just long enough. I guess I can try to add an extra delay and see if that helps.

**Comment by OptimalJew** [comment] 2017-10-15 05:09
More testing: Disabling/re-enabling the SCP driver doesn't fix it, neither does that paired with a restart, nor all of the above with uninstalling the gamepad itself via devices and printers, and then initiating a new bluetooth pair.

Uninstalling the SCP driver > reinstalling it > connecting via BT is the only thing I've found that works (and strangely, doesn't seem to require a restart) until the next time I disable and then re-enable 'Hide DS4 Controller' and then I can consistently reproduce port 1 becoming "occupied" and getting locked into dinput only mode until I go through the above procedure.

Let me know if there's anything else you'd like me to test.

**Comment by OptimalJew** [comment] 2017-10-16 10:04
In additional testing, eventually the xinput ports aren't being properly freed in 1.4.95 as well. Moving up a port does not actually free the previous one, and will get locked down as well. Currently, ports 1, 2, and 3 are "occupied" and put me into dinput mode.

I'm honestly at a loss as to why this is happening.

**Comment by Ryochan7** [comment] 2017-10-18 06:38
The only thing that I have to test is a build with an additional sleep time added to the service stop routine.

https://drive.google.com/open?id=0B6yGHDx0CFzDNVhiS1FtS05qTXM

**Comment by OptimalJew** [comment] 2017-10-18 22:01
Testing that version, I can still reproduce it by toggling exclusive mode when 'Disconnect from BT when stopping' is enabled. Also whenever BT gets disabled by the idle disconnect timer, OR just right clicking the BT icon with this version and manually closing it will 100% cause it to improperly disconnect and lock up an xinput port. Basically just disconnecting BT by any means. Stopping/starting the service doesn't fix it. Removing the controller in device manager and control panel, restarting, and then pairing it again doesn't fix it. Same solution as before where nothing but uninstalling and reinstalling SCP driver (temporarily) frees up the ports.

Tested both 1.4.95 and 1.4.96, and only the idle disconnect seems to sometimes cause it (although I had the lightbar get stuck red on latency spikes a few times last night on 1.4.95), while 1.4.97 fails to properly disconnect it and locks up an xinput port every single time.

**Comment by OptimalJew** [comment] 2017-10-28 14:07
Tested with 1.4.98, and it's still broken. Here's an exact breakdown of what happens.

**1.4.98**
![1](https://user-images.githubusercontent.com/31424143/32135088-1cdb4b1e-bbc7-11e7-9cea-c43cc141ae1c.png)

And here's the same process on 1.4.96, which is the last version that's at least semi-functional for me (I say semi-functional because using 'Disconnect from BT when stopping' and 'Idle Disconnect' both fail to free up an xinput port, while at least right clicking the BT icon in the application works as intended).

**1.4.96**
![2](https://user-images.githubusercontent.com/31424143/32135089-1f91f5ec-bbc7-11e7-9217-baa68ad2b130.png)

**Comment by Ryochan7** [comment] 2017-10-28 19:37
That is some odd behavior from your BT adapter. Why is the controller disconnecting right after connecting? Looking at the log, it really looks like the next hotplug event probably occurs before the old DS4Device instance has a chance to fully unplug the virtual Xbox 360 controller from the ScpVBus. Some extra locking probably needs to be done to prevent that from possibly happening.

**Comment by OptimalJew** [comment] 2017-10-28 21:17
Using this adapter: https://www.amazon.com/gp/product/B007Q45EF4/ with Broadcom drivers (6.5.1.2501) on Win7 64, which I believe is the last version that was distributed on Broadcom's website before they moved to windows update only. It initially strike me as odd that when pairing, it would instantly disconnect and then connect properly, but besides that it "worked" so I just assumed that was intended behavior.

**Comment by OptimalJew** [comment] 2017-10-29 22:13
This could help explain why pairing my DS4 connects > disconnects > connects. I can reproduce this each time: Upon rebooting and starting DS4Windows, before even attempting to pair, it appears to instantly detect my BT adapter as an actual controller, and then disconnects it.

![1](https://user-images.githubusercontent.com/31424143/32148901-4e6284ce-bcd3-11e7-9481-975e518ce738.png)

If I close the app and then start it again, it does not until the next time I reboot, but pairing the controller still does the same connect > disconnect > connect.
![2](https://user-images.githubusercontent.com/31424143/32148905-5bb1a506-bcd3-11e7-9913-f4106b171c00.png)

**Comment by shinra358** [comment] 2017-11-04 14:53
This wasn't a big problem for me before until none. I guess adjustments
being made in this thread has somehow kinda broken this again.

**Comment by reecespieces** [comment] 2017-11-10 15:10
So I kind of made my own issue related to this because I didn't see this first (sorry).

OptimalJew is seriously onto something. Every version 1.4.96 or earlier works fine.

Anything newer than 1.4.96, and I get `X360 Controller #1 Failed` re-installing the SCP driver temporarily fixes it, but it is reoccurring.

**Closed** 2018-06-04 15:57 UTC
