### ISSUE TITLE
Bluetooth controller detected, but none of the button works

### ISSUE THREAD

**Issue by servantfox** [Ryochan7/DS4Windows#840] opened 2019-09-28 11:05 UTC
![image](https://user-images.githubusercontent.com/55915389/65815487-bda54080-e222-11e9-82e5-19dd3827f519.png)

Also, in the controllers tab, I only see partial of the information.

This controller works well with Steam in-game controller. So I'm not sure what I'm missing here.

**Comment by Ryusennin** [comment] 2019-09-28 17:09
Maybe you're missing a genuine DualShock 4?

Please provide more information. Operating system, program version, controller model...

**Comment by servantfox** [comment] 2019-09-29 00:55
OS: Windows 10 build 18362
DS4WINDOWS version: 1.7.17
Controller Model: CUH-ZCT2U Dual Shock not sure whether it's genuine or not since received from someone.

Extra info:

1. Connecting the controller via USB cable does shows up the full information on Controller tab, and able to configure the color of the LED light on the controller:
![image](https://user-images.githubusercontent.com/55915389/65824158-c0417d80-e296-11e9-9131-64e20dcba5af.png)
 
2. If I un-tick "Hide DS4" option, there will be 2 controllers in the control panel:
![image](https://user-images.githubusercontent.com/55915389/65824140-3ee9eb00-e296-11e9-803e-3171a09d67d5.png)

The "wireless controller" is able to detect my inputs, while "XBOX360 For Windows" are not.
If I were to Hide DS4, only "XBOX360 For Windows" will show up, but again it won't able to detect my output if connected to Bluetooth.

P/S: *"XBOX360 For Windows" is able to get inputs if I were to connect with USB cable instead of Bluetooth*

**Comment by mika-n** [comment] 2019-09-29 19:01
Please see the following post. Download the zip file there and run the debug version of DS4Windows.exe executable (replace existing ds4windows.exe with the version in the zip file. Re-use all other files from an official release).
https://github.com/Ryochan7/DS4Windows/issues/839#issuecomment-536330527

Run the debug version at first without connecting the gamepad.
Open Logs tabpage in DS4Windows application.
Plug-in the gamepad and see debug messages in Logs tab page (do this for both BT and USB connection and generate different log files by closing the DS4Windows app and re-launching it when changing gamepad connection type).
Press "Export" button to export the log content to TXT file and please post the txt result here.

Have you tried the gamepad in PS4 console? Does it work in PS4 console over BT connection with touchpad and gyro support? There are some "wanna-be" DS4 gamepads in Ebay/Alibaba which look like genuine DS4 gamepad, but are some 3rd party fake Chinese copies.

**Comment by EvgenyW3** [comment] 2019-10-02 17:01
I have exactly the same issue when trying to connect my ps4 gamepad to Windows 10 installed on Parallels VM sharing MacbookPros built-in bluetooth

**Comment by mika-n** [comment] 2019-10-03 12:39
@EvgenyW3 Did you try to run the debug version of DS4Windows linked in the following post? Just replace the existing DS4Windows.exe file with this debug version (or rename the debug EXE to a differerent name). 
https://github.com/Ryochan7/DS4Windows/issues/839#issuecomment-536330527

What do you see in Logs tab page of DS4Windows when you run the debug version and plugin the controller?

**Comment by boycad** [comment] 2019-10-29 05:53
As above, I have the same issue: DS4Windows shows conflicting information on controller connected via onboard bluetooth; controller does not respond as expected- barely at all, actually.  Behaviour is normal when connecting via usb.

This is with a new controller,  bought via Amazon.  I can provide links to the vendor pages if it is suspected to be a fake, but for what its worth, all appropriate labels and packaging are in place.

Windows 10 pro v1903
bluetooth controller is some onboard Intel model, on an Asus B450 mb

Is this thread still being watched, and if so, shall I run the diagnostic version and post the log results, as suggested above?

**Comment by mika-n** [comment] 2019-10-29 06:37
@boycad  Please run the linked "DS4Windows_DeviceDetectDebug.zip" version. At first install the latest official version (https://github.com/Ryochan7/DS4Windows/releases) and then unzip the debug zip file into the same folder. Then run DS4WindowsDebug.exe app and open Logs tabpage of the app. Finally connect the controller using BT and see what do you see in Logs tabpage. Export the content of Logs tabpage into a text file. Then disconnect the controller, close the app (some debug messages are shown only for the first connected controller) and re-launch the debug app. Then do the same while using USB connection.

**Comment by boycad** [comment] 2019-11-03 09:11
This comment: #839 (comment)

I downloaded the linked, copied the .exe across to the DS4W install folder, repleced the existing .exe, left clike run as admin...

UAC query window pops up, but the program apparently fails to launch...

Am I doing something wrong?

**Comment by mika-n** [comment] 2019-11-03 09:28
@boycad  Please download the debug version from the following DS4Windows download link because the debug versions linked directly in #839 post are obsolete and old versions. Download also the latest official DS4Windows version and extract the debug ZIP file into the same folder because the debug ZIP file has only DS4WindowsDebug.exe executable. It re-uses all other files from the official version.

https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems
https://github.com/Ryochan7/DS4Windows/releases

The problem of using an old version of debug executable may be that the Microsoft.Win32.TaskScheduler.dll assembly file may be wrong version (if EXE and this Microsoft assembly files are not in sync then the result would be exactly what you are experiencing). That's why it is best to download the latest official version because then the debug version is in "sync" with all other files.

I have to edit the #839 post remove those old debug versions and just leave the link to the Troubleshooting doc page of DS4Windows.

**Comment by boycad** [comment] 2019-11-03 09:32
Got it.

**Comment by boycad** [comment] 2019-11-03 09:57
Here are three text files from the debug logs:
[debug3_bt connect_bug as described.txt](https://github.com/Ryochan7/DS4Windows/files/3801374/debug3_bt.connect_bug.as.described.txt)
[debug2_usb connect (success).txt](https://github.com/Ryochan7/DS4Windows/files/3801375/debug2_usb.connect.success.txt)
[debug11.03_run1_no controller.txt](https://github.com/Ryochan7/DS4Windows/files/3801376/debug11.03_run1_no.controller.txt)

Is that about right?

**Comment by mika-n** [comment] 2019-11-03 10:16
Okey. Thx for the debug log files. The "debug3_bt_connect_bug as described.txt" file has some interesting warnings and errors. 

The BT connected gamepad sends an identification claiming that it is an official Sony DS4 revision2 game pad and MAC address is successfully read (some 3rd party controllers have problems providing the MAC address in a standard DS4 format, but your controller seems to be OK at this point):
`2019-11-03 1:56:04 AM: DEBUG: readSerial. Trying to read serial# from VendorID=0x054C, ProductID=0x09CC, Version=0,
`
However, after negotiating the connection and reading the MAC address of the gamepad, DS4Windows app needs to do so called "DS4 mode switch" with BT connected gamepads. This is where problems start. By default BT connected DS4 gamepads are in "PC-friendly mode"  and the gamepad sends only normal button and stick activity (ie. no touchpad, no rumble, no gyro support in PC). 

PS4 console sends also this mode switch command to the gamepad and that is what DS4Windows application does also in order to fully utilize those extra features of DS4 gamepad over BT in PC (Note! USB connection doesn't need this mode switch because DS4 gamepad always sends data for those extra features also in PC and not just in PS4 console scenario).

In your case this "mode switch" command and gyro calibration handshaking in BT seems to fail. CRC32 check of the sent and received BT data packet is invalid and that's why DS4Win app rejects some incoming BT data packets.
```
2019-11-03 1:56:04 AM: DEBUG: RefreshCalibration. getCalibrationData and DS4ModeSwitch. conType=BT  dataType=5
2019-11-03 1:56:04 AM: DEBUG: RefreshCalibration. ERROR. readFeatureData failed. conType=BT dataType=5 LastErrorCode=0
2019-11-03 1:56:04 AM: DEBUG: RefreshCalibration. ERROR. Calibration failed. tries=0 validCrc=False recvCrc32=0 calcCrc32=644264512
```

Later on various warning and error messages are result of this failing "mode switch" commands. 

Hmmm... The key question here is why this DS4 mode switch in BT mode fails? 
- DS4Windows supports both the original rev1 and newer rev2 (introduced with PS4-Pro console) DS4 gamepads. VID/PID information of your controller indicates that it is rev2 controller.  But are there now some mysterious rev3 gamepads on the market? To my knowledge Sony has released only those two revisions of DS4 gamepad. And now when PS5 is on its way Sony will never release any new DS4 gamepad revisions.
- Is your BT dongle or BT drivers in Windows somehow buggy and it fails to handle the extra data DS4 gamepad sends after the mode switch? It does triple the size of BT HID data packet because there is loooots of new information (gyro, touchpad, rumble etc etc).
- Does this gamepad work over BT in PS4 console? Is touchpad and gyro working with some PS4 games supporting those features?

At this point I would recommend you to test the gamepad in PS4 console because it would tell us if the gamepad itself works with those extra features. If those extra features work in PS4 console then the problem must be in PC side. Is this BT driver or WinOS BT net stack problem?
- Try installing all the latest WinOS updates and BT device drivers.
- Try the gamepad in some other PC using DS4Win app and a different BT dongle/internal chipset. If the gamepad works there then the problem must be in your PC BT drivers/chipset.
- Some bug in DS4Win app? Well, don't know where it would be in this case (why crc32 check fails?). It is very difficult to debug without having an actual hardware having this problem.

I recommend you to try the above mentioned diagnosing tricks (PS4 console, other PC, driver updates).

**Comment by boycad** [comment] 2019-11-03 11:36
okay.

Trying the pad on different devices is going to take some time.  I dont have a PS4, and my other device is a Chromebook.  I suppose I could try to install it in a Linux container.  Eventually, I should be able to arrange to use a friends PS4.  I know one person who has one.  That will probably be something like a month ;p

Its a good idea though.

I'll go through the drivers.  

Some more information: 

-The track pad works in usb mode

-Two separate devices show up in the Windows BT window, when the pad connects via bt.  One says "Xbox Controller", the other says "Wireless gamepad".  Is that normal?

-I have had other bt problems.  One of my keyboards wont cooperate.  Other bt peripherals work flawlessly.

-Intel Wireless Bluetooth did update just now... through device manager

-'Wireless Controller' bluetooth entry (in device manager) has a really old dated driver (2006-06-21), but does not update

That helps. Thanks.
I'll post back if I figure anything out.

**Comment by mika-n** [comment] 2019-11-03 12:21
> -The track pad works in usb mode

Jep. USB is easier for PC because DS4 gamepad doesn't need the "mode switch" in usb mode.


> -Two separate devices show up in the Windows BT window, when the pad connects via bt. One says "Xbox Controller", the other says "Wireless gamepad". Is that normal?

In my environment (Windows 10 64bit) BT device list shows just one "Wireless Controller" device when DS4 is connected over BT. 

However, JOY.CPL ControlPanel gamepad configuration screen may show two devices (the original physical controller and a virtual output controller created by DS4Windows) if you haven't hidden the physical controller device from all apps (except DS4Win app). This is so called "exclusive/HideDS4Controller" option in DS4Win settings. Or alternative way to hide the physical controller is to install HidGuardian tool (not supplied with DS4Win app, HidG is a separate app created by Nefarious).
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

> -'Wireless Controller' bluetooth entry (in device manager) has a really old dated driver (2006-06-21), but does not update... Its hardware id is BTHENUM\Dev_D02796A9120B

Maybe you could try to use some another external BT usb dongle in case the built-in BT device in your PC is somehow unable to handle "extra traffic" caused by DS4 mode switch and DS4 native HID data packets. In this case you should somehow disable the internal BT chipset and use just the external usb bt dongle.

**Comment by boycad** [comment] 2019-11-04 03:59
> One says "Xbox Controller"

oh its gone now.  Still updating.  Im also on Win10 x64.

**Comment by boycad** [comment] 2019-11-12 06:33
Everything that could be updated has been, but the behaviour is still the same.

The "Xbox 360 Controller for Windows" pip is back in the Bluetooth screen.  I can upload a screen snip of what that looks like, if you like.

Your troubleshooting advice is good.  But Im not likely to have a chance to try any of those things for a while.  Probably the best thing to test would be to connect my ds4 controller to an actual Playstation.  I might be able find one to try it on eventually.

I'll keep thinking about this, but for now I shall just thank you for help and leave it alone. 

hasta luego,
-bc

**Comment by boycad** [comment] 2019-11-20 14:15
I thought your update might have had a crack at this problem tried, but no luck.  
1.7.22: re-paired, and the behaviour seems the same.

**Comment by mika-n** [comment] 2020-08-29 07:43
closed as "the gamepad is incompatible in BT mode or BT dongle chipset is not up to the task to handle DS4 native mode" (ie. ds4 native mode vs pc-friendly mode of BT ds4 gamepad).

**Closed by mika-n** 2020-08-29 07:43 UTC
