### ISSUE TITLE
Multiple joysticks when connecting through Bluetooth

### ISSUE THREAD

**Issue by a-Marino** [Ryochan7/DS4Windows#3094] opened 2023-09-24 16:35 UTC
**Describe the bug**
I have made a reddit post about this 
https://www.reddit.com/r/DS4Windows/comments/16qj1fy/ds4_detects_8_controllers_only_one_conected/
Since last update when connecting the joystic via Bluetooth it detects 8 controllers instead of one

**Screenshots and Logs**
![image](https://github.com/Ryochan7/DS4Windows/assets/70865138/ea88079f-9401-4472-a121-45e45c89ffeb)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 
 - OS: Windows 11 Pro 
 - DS4Windows Version 3.2.15

**Comment by Ryochan7** [comment] 2023-09-24 19:02
A BT connected DS4 works fine for me when emulating a DS4 v.1. Can you share the profile you are using? Also, are you using reWASD or Parsec?

**Comment by a-Marino** [comment] 2023-09-24 19:11
[Default.zip](https://github.com/Ryochan7/DS4Windows/files/12709465/Default.zip)
Sure, this is the profile im using, and no im not using any other program.
It worked fine until i updated to the last build of DS4

**Comment by Schiemanskie** [comment] 2023-09-25 09:31
I am having the same issue with Win10 as well. Everything went fine until upgrade on .15 - it is the same wether I am using USB Connection or Bluetooth.

Desktop (please complete the following information):

Controller Make and Model: Sony DS4 v.1
OS: Windows 10 Pro
DS4Windows Version 3.2.15

Log Attached:
[log.txt](https://github.com/Ryochan7/DS4Windows/files/12713584/log.txt)

**Comment by z0han4eg** [comment] 2023-09-25 11:16
Same

**Comment by Ryochan7** [comment] 2023-09-25 16:52
https://github.com/Ryochan7/DS4Windows/commit/244ed4e81a5aa646947058acec6f9a0ece853b02

From what I can see, there was only one major difference between the two virtual device checks. The original used the CM_LOCATE_DEVNODE_PHANTOM flag when looking for parent devices in the CM_Locate_DevNodeW call. The SetupAPI is still being used in the new version with the DIGCF_PRESENT flag being used for SetupDiGetClassDevsW. It works on my end but it is not exactly equivalent.

Looks like adding the DIGCF_PROFILE flag is required as well to search through the equivalent list of devices. Otherwise, the parent instanceId will be returned as an empty string and the device check will stop therefore declaring a device to be a physical device; the original check operated in a similar manner.

https://github.com/Ryochan7/DS4Windows/blob/244ed4e81a5aa646947058acec6f9a0ece853b02/DS4Windows/DS4Control/ScpUtil.cs#L1271

I am going to assume that is the core problem. If not then I do not really care. It works for me and nobody is going to help me so why bother.

CM_Locate_DevNodeW
https://learn.microsoft.com/en-us/windows/win32/api/cfgmgr32/nf-cfgmgr32-cm_locate_devnodew#cm_locate_devnode_phantom

SetupDiGetClassDevsW
https://learn.microsoft.com/en-us/windows/win32/api/setupapi/nf-setupapi-setupdigetclassdevsw#digcf_profile

**Comment by cxj05h** [comment] 2023-09-25 20:20
I also had the same issue and reverted to the previous version. 
I saw this would happen for me when I went to test the buttons on XinputChecker. Almost like that triggered the multiple inputs.

**Comment by fercho2346** [comment] 2023-09-25 20:45
same issue here with the  3.2.15 update. 
in my case if i switch the ds4 as a virtual device triggers these "multiple usb controllers", it doesn't happen when setting the virtual controller as an XBOX360 one.
Sony DS4 V.2 - Win 11

**Comment by nyakze** [comment] 2023-09-26 03:10
Happens for me in wired mode as well on 3.2.15

**Comment by iitzRichie** [comment] 2023-09-26 04:35
> [244ed4e](https://github.com/Ryochan7/DS4Windows/commit/244ed4e81a5aa646947058acec6f9a0ece853b02)

> I am going to assume that is the core problem. If not then I do not really care. It works for me and nobody is going to help me so why bother.

Is it a major issue? No. But still kind of a shitty attitude to have about it in all honesty 🤷‍♂️.

**Comment by Ryochan7** [comment] 2023-09-26 21:02
https://github.com/Ryochan7/DS4Windows/commit/f9338f2889276295f917db7dbd6eb3f9f3ce4991

There's several hours spent trying to get a VM working properly that I will not get back.

**Comment by nyakze** [comment] 2023-09-27 00:39
> [f9338f2](https://github.com/Ryochan7/DS4Windows/commit/f9338f2889276295f917db7dbd6eb3f9f3ce4991)
> 
> There's several hours spent trying to get a VM working properly that I will not get back.

Thank you! I don't really get the attitude though. It's a responsibility of the user to report a bug. I have zero clue about coding, so...

**Comment by iitzRichie** [comment] 2023-09-27 09:18
> I'm think its a major issue since controller acts like there are 10 connected controllers used simultaneously. If it was just an UI bug - w/e, I don't give a fuck

I think it is just a UI bug though? I'm not experiencing any unusual behavior/my controller physically not working as intended. The other controllers popping up aren't even assigned a profile. Don't get me wrong, it's still not an excuse for the Dev to ignore it though.

**Comment by nyakze** [comment] 2023-09-27 09:29
> I think it is just a UI bug though? I'm not experiencing any unusual behavior/my controller physically not working as intended. The other controllers popping up aren't even assigned a profile. Don't get me wrong, it's still not an excuse for the Dev to ignore it though.

No, it physically changed behavior, my macros were executed 3 times instead of 1

**Comment by iitzRichie** [comment] 2023-09-27 21:03
This looks to be fixed in v3.2.16. Despite their initial poor attitude, I do appreciate the Dev fixing it 👍.

**Comment by Ryochan7** [comment] 2023-10-01 18:02
The root problem was an issue with the USB interface for the fake DS4 device created by ViGEmBus. The parent instance id could not be grabbed as no device would be found despite it existing. The initial device scanning method worked for every other device in the chain when using the proper instance id. Looks like the migration to CfgMgr32 was not due to a recommendation from Microsoft but out of necessity due to issues with how the virtual DS4 device was created. Found a method that worked by looking at Microsoft's docs and trial and error.

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/porting-from-setupapi-to-cfgmgr32.md#get-a-property-from-a-specific-device

Literally not my fault. I just wanted the DS Square button to map to Xbox X button faster.

**Closed by Ryochan7** 2023-10-01 18:02 UTC
