### ISSUE TITLE
I only can use one controller at time

### ISSUE THREAD

**Issue by Rune-Walsh** [Ryochan7/DS4Windows#762] opened 2019-07-15 15:26 UTC
I always used ds4windows, the issue now is that I updated to the version with VIGemBus and now i Only can play with one controller at time. I use one DS4 and one xbox one controller.

If I use together with steam, the ds4 controller is working but xbone is not.
If I close steam, xbone will work but ds4 will not.

I've tried reinstalling but nothing is working.

**Comment by Ryochan7** [comment] 2019-07-16 19:50
I will have to give this a try in a little bit. I have an old beat up Xbox 360 controller that I can use for testing. You should still be able to use a real Xbox 360 controller alongside a virtual Xbox 360 controller fine.

**Comment by Ryochan7** [comment] 2019-07-18 06:31
I can now confirm that this is indeed a problem. There are times when both controllers want to use XInput slot 1 so only one controller is usable. The real Xbox 360 controller becomes usable after unplugging the DS4. Unfortunately, this problem is not due to DS4Windows but something to do with the ViGEmBus driver. I don't remember encountering this kind of problem with the older 1.14.3.0 (?) driver. You might want to talk to Nefarius about this problem.

https://github.com/ViGEm/ViGEmBus

**Comment by Ryochan7** [comment] 2019-07-18 07:31
Played around with an older version of ViGEmBus (1.14.1.0); there appears to be no valid links to version 1.14.3.0 anymore. I didn't run into that problem with that version of the driver. However, I uninstalled that driver and installed 1.6.112.0 again and I cannot re-produce the problem. I guess this will be something to keep an eye on.

**Comment by hexolite** [comment] 2019-07-20 09:27
I have the same problem... I don't know what to do...

**Comment by Rune-Walsh** [comment] 2019-07-25 00:06
> 
> 
> Played around with an older version of ViGEmBus (1.14.1.0); there appears to be no valid links to version 1.14.3.0 anymore. I didn't run into that problem with that version of the driver. However, I uninstalled that driver and installed 1.6.112.0 again and I cannot re-produce the problem. I guess this will be something to keep an eye on.

thank you for looking into this problem. Yes,  I'm pretty sure the problem is within vigembus, I'll try to contact him. 

I will use an older version of ds4windows for now. Thank you again

**Comment by Rune-Walsh** [comment] 2019-08-03 17:50
I have tried olders versions of ds4windows and I still have the same problem, I'm going nuts here.

I removed everything of any olders installations and nothing, Am I doing something wrong?

**Comment by mika-n** [comment] 2019-08-06 14:21
If the problem is in ViGem driver then going back to older DS4Windows doesn't help unless you go all the way down to DS4Windows V1.6.14 https://github.com/Ryochan7/DS4Windows/releases/tag/v1.6.14 version. That is the last version using the veeeery old ScpVBus driver instead of newer ViGem gamepad driver.

Everything after DS4Windows V1.6.14 release uses ViGem gamepad driver. The vigem driver version and DS4Windows app version are independent of each other. 

So, are you trying to use older version of DS4Win app version or just VigEm driver version?

**Comment by Ryochan7** [comment] 2019-08-06 14:49
I have not had the time to look into this again. Unfortunately this problem is not caused by any DS4Windows code but likely something within the ViGEmBus driver. I did not find a way to consistently reproduce the problem so there isn't really anything that I could report that would help fix the problem.

**Comment by Ryochan7** [comment] 2019-08-17 03:34
Will have to file this as won't fix. Kat get out of there. That place is tahxic. Praise AEG

**Closed by Ryochan7** 2019-08-17 03:34 UTC

**Comment by Rune-Walsh** [comment] 2019-08-17 06:22
what happened?

**Comment by Ryochan7** [comment] 2019-08-17 17:37
Trying to provide fixes to legitimate problems is tahxic behavior in Equestria apparently.
