### ISSUE TITLE
Emulated DS4 get not Rumble

### ISSUE THREAD

**Issue by SiTWulf** [Ryochan7/DS4Windows#2562] opened 2022-09-04 17:55 UTC
Using a DualSense to emulate a DualSock4 for Marvel Spider-Man get not working Rumble.
Testing in a DSX Emulated DualSock4 rumble works

Emulating a X360 for the same game Rumble Works, but need to emulate DS4 to get GamePad icons

**Comment by Kanuan** [comment] 2022-09-04 18:04
Rumble is currently disabled when using DS4Windows' Virtual DS4 because of an issue that the dev is attempting to fix. No ETA for when this will be fixed though

**Comment by Yohoki** [comment] 2022-09-04 18:04
[[Notice] Read this before posting a new Discussion or Issue ticket requesting help (Troubleshooting tips)](https://github.com/Ryochan7/DS4Windows/issues/1196)


>- Try to use search by keyword -functionality to find existing duplicate tickets.
>
>- Since the V3.0.11 version rumbling is disabled on purpose when a profile uses dualshock4 output controller type (there are few nasty bugs which need to be resolved until this feature can be re-enabled). But, rumbling does work when the profile uses xbox360 controller mode.

**Comment by Yohoki** [comment] 2022-09-05 02:14
Long story short, It's a driver issue. If you want rumble support in DS4Windows RIGHT NOW, use [version 3.0.10](https://github.com/Ryochan7/DS4Windows/releases/tag/v3.0.10). Keep in mind, this is an **older version** and **there are bugs** in the Rumble support and **Features are missing**. **You will receive NO support for issues on this version**, especially regarding rumble issues.

But, if you don't mind waiting for the fix, the driver has finally been fixed by their dev, so DS4Windows is being worked on to support the new driver. There is no release date, because it's a single person (for the most part) working to develop it on his own free time. Be patient and it will come out soon™️

**Comment by Ryochan7** [comment] 2022-09-05 02:32
> Using a DualSense to emulate a DualSock4 for Marvel Spider-Man get not working Rumble.
Testing in a DSX Emulated DualSock4 rumble works

DSX uses ViGEmBus as well so it would suffer from the same flawed rumble and lightbar issues that DS4Windows used to before virtual DS4 rumble was disabled; it would definitely fail to work in Witcher 3 as it also uses the lightbar and the events can conflict. I didn't test DS4 emulation support in DSX but it fails to interpolate stick axes properly for Xbox 360 emulation so that makes the app useless to me.

The problem is being worked on and it is almost resolved. Still testing an updated DS4 output reader routine in DS4Windows and Nefarius is working on getting a new release ViGEmBus driver ready. Maybe I will get around to finally playing through Witcher 3 but probably not.

**Comment by SiTWulf** [comment] 2022-09-05 03:49
Actually the best solution would be not to emulate DS4 having a DualSense, but unfortunately it is not possible yet.
I did not know that there were problems with Witcher 3 and DS4Windows, whenever I have played Witcher 3 it has been emulating X360 in DS4W.

For example, to play Marvel Spider-Man with the DualSense, what I do is connect it via USB and in Auto Profiles setting "Turn off temporaly DS4W" and everything really works, but if I feel a little down and want to play with the controller wireless without connect it by usb, there is no other way than to emulate the DS4 to at least have the button icons.

I know perfectly well that it is not the best solution, but it is something that has saddened me when I have read that it does not work and that it may never be able to work.
For me, DS4Windows was and is a program that I am very fond of, it has allowed me to configure automatic profiles and create macros to make options for some MODS without having to use the keyboard and do everything from the gamepad, but when I realized that I did not have rumble in the Marvel Spider-Man intrigued me and decided to test it, so I bought the DSX on Steam to see and I was able to verify that the rumble in it worked perfectly, so I thought it was a mistake perhaps with all the changes it is undergoing DS4Windows, I assure you that I was completely unaware of that error with Witcher 3, since I have always used DS4Windows to emulate an X360 gamepad, until the new games have support for DS4 and DS controllers, which I have begun to try to test it like this.

I hope that Ryochan7 will be able to fix it before I end up abandoning the project, something that would make me very depressed, as I have used DS4W for years, and I love it very much and it makes me very sad that I have to use new programs (like DSX) to be able to play to these games compatible with sony controllers.

Please excuse me then for posting this bug, which everyone seemed to know about but me, please accept my apologies for it. I would love to help, but unfortunately I don't know anything about this topic, at most I could be a tester.

Once again, my sincerest apologies.

**Comment by Ryochan7** [comment] 2022-09-05 18:59
Extra note. The game natively supports SIAPI. Steam Input is likely going to be the primary means to configure the controller.

https://www.pcgamingwiki.com/wiki/Marvel%27s_Spider-Man_Remastered#Input

**Comment by rafa21k1** [comment] 2022-09-08 10:16
If you want vibration in dualsense emulating a DS4 use version 3.10.0, if the game has the DS4 buttons mapped it will show them, if it doesn't have them it will only show the xbox ones (you must use a mod for this case or get used to it)

For my part I have not had problems with the vibration in DS4 mode, I use it even with steam in bigpicture mode without problems

**Comment by Ryochan7** [comment] 2022-10-14 04:15
Purchased DSX on Steam again and can confirm that the DS4 rumble behavior in Witcher 3 is wrong. DS4 Lightbar Passthrough does not match what is happening in game (frequently goes black) and rumble frequently does not rumble or stops abruptly.

**Comment by Yohoki** [comment] 2022-10-15 19:38
Version 3.1.6 has Rumble re-enabled for you. The DLL file has a bug in it, so it needs replaced to work more reliably. Other than that, tests have been positive. If you'd like to continue using DS4Windows, these are the newest instructions to get you a *mostly* up-to-date version that supports rumble over BT or USB:

* Make sure you're on [DS4Windows v.3.1.6](https://github.com/Ryochan7/DS4Windows/releases/tag/v3.1.6) (**NOT 3.1.7**)
 
* Download and overwrite [this DLL](https://ci.appveyor.com/api/buildjobs/4wf4s2hnuo3fb7t3/artifacts/bin%2Fnet6.0%2FNefarius.ViGEm.Client%2FNefarius.ViGEm.Client.dll) in the DS4Windows directory

Because of the bugs in the packaged DLL, Ryochan has disabled rumble again. Nefarious has made a PR (#2634) to address the issues related to the rumble bugs some users reported. If this doesn't get re-enabled, 3.1.6 is the newest version to support it (and it does so very well IMO)

**Comment by IceLancerSR** [comment] 2022-10-23 14:27
> Version 3.1.6 has Rumble re-enabled for you. The DLL file has a bug in it, so it needs replaced to work more reliably. Other than that, tests have been positive. If you'd like to continue using DS4Windows, these are the newest instructions to get you a _mostly_ up-to-date version that supports rumble over BT or USB:
> 
> * Make sure you're on [DS4Windows v.3.1.6](https://github.com/Ryochan7/DS4Windows/releases/tag/v3.1.6) (**NOT 3.1.7**)
> * Download and overwrite [this DLL](https://ci.appveyor.com/api/buildjobs/4wf4s2hnuo3fb7t3/artifacts/bin%2Fnet6.0%2FNefarius.ViGEm.Client%2FNefarius.ViGEm.Client.dll) in the DS4Windows directory
> 
> Because of the bugs in the packaged DLL, Ryochan has disabled rumble again. Nefarious has made a PR (#2634) to address the issues related to the rumble bugs some users reported. If this doesn't get re-enabled, 3.1.6 is the newest version to support it (and it does so very well IMO)

This. 
Just wanted to mention that dll wont work out of box if one just copy and replace file. Because windows is blocking dll.
Right click on new dll->properties and at bottom right corner will be "unblock" dll.

**Comment by Yohoki** [comment] 2022-10-23 17:23
Good to know. I did not have this problem on Win10

**Comment by Masamune3210** [comment] 2022-10-23 17:24
Either its a bug or they have decided to get more stringent in 11, but yeah it tends to trigger more

**Comment by Billybishop** [comment] 2022-11-18 05:53
Okay on a side note, why isn't Sony paying you? It's a shame that a multi-B$ company can't shell out the time, or contracts, to provide the development and support for this themselves. This is coming from the fact that I'm trying to use their PlayStation Plus streaming application on Windows- I have a Nintendo Switch Pro and Xbox Series controller and can't use either of them from the PC to properly play with PS+. I also read that PS5 controllers are not compatible as well! They really do not care about properly taking care of their peripherals. This whole dance they're doing, acting as if they're this poor whittle old indie company with mere pennies in their pockets, unbelievable. This narrative is getting old.

**Comment by Billybishop** [comment] 2022-11-18 06:08
https://ci.appveyor.com/api/buildjobs/4wf4s2hnuo3fb7t3/artifacts/bin%2Fnet6.0%2FNefarius.ViGEm.Client%2FNefarius.ViGEm.Client.dll

this link no longer works, what version/build should i be looking for to replace the net6 nefarius dll with?

**Comment by IceLancerSR** [comment] 2022-11-18 06:30
> 

You dont need that any more. Latest version has fixed and working rumble

**Comment by ArsenicBismuth** [comment] 2023-01-01 22:29
@IceLancerSR Idk which version you are using, but mine is still not working. You only have rumble when emulating Xbox. And based on this and the other issue, I see no updates regarding this yet.

**Comment by IceLancerSR** [comment] 2023-01-01 22:34
> @IceLancerSR Idk which version you are using, but mine is still not working. You only have rumble when emulating Xbox. And based on this and the other issue, I see no updates regarding this yet.

This isnt your social facebook to use downvotes to express ur issues.

**Comment by ArsenicBismuth** [comment] 2023-01-01 22:43
@IceLancerSR Idk, seem like being misleading at least warrants getting one. And who are you to policy a GitHub feature lmao.

**Comment by IceLancerSR** [comment] 2023-01-01 22:44
> @IceLancerSR Idk, seem like being misleading at least warrants getting one. And who are you to policy a GitHub feature lmao.

You are the only one thats misleading your self
And hell of a way to start new year. Proves past year didnt grow u at all
off u go

**Comment by Ryochan7** [comment] 2023-01-02 01:15
Stopping this before it goes further

**Closed by Ryochan7** 2023-01-02 01:15 UTC
