### ISSUE TITLE
Repeat while held isn't working anymore

### ISSUE THREAD

**Issue by tigurand** [Ryochan7/DS4Windows#1701] opened 2020-12-27 14:13 UTC
I have a macro set to repeat while held. It was working before but it's not working anymore. I think it's after version 2.1.20, I'm not sure, but it was working fine around early December.

**Comment by Ryochan7** [comment] 2020-12-27 17:27
Assuming this is another macro failure caused by the introduction of the DualSense Mute button. That addition threw off the index numbers of the input controls and some arrays were not changed to account for the change. Hopefully it is fixed with the most recent commit. It will be a few days before a new DS4Windows build is released.

**Comment by Ryochan7** [comment] 2021-01-19 21:33
Just released version 2.2.2 today. A little bit longer than a few days. Hopefully some of the changes were worth it.

**Closed by Ryochan7** 2021-01-19 21:33 UTC
