### ISSUE TITLE
Persistent device?

### ISSUE THREAD

**Issue by reyaz006** [Ryochan7/DS4Windows#874] opened 2019-10-28 19:16 UTC
Problem:
In both wireless and wired modes, the device may disconnect and the game may not always discover it again after it's connected again.
- If you need to recharge the gamepad during the play (wireless -> wired).
- If you are distracted while using wireless for too long and have to either restart the game or alt-tab into it.
- If you need to switch into a different USB port while wired.

Suggestion:
Is it possible to create a persistent emulated device that is always connected for games that can read it, but only pass the needed input data to it while it's actually connected to the driver?

I'm using wireless mode. In Rocket League, I sometimes need to switch the fullscreen mode in order to let the game see the DS4 in X360 mode, after it was disconnected and reconnected. In BloodRayne 2 (Dinput/DS4 mode) I didn't find any other way except restarting the game and losing some progress in the process.

**Comment by mika-n** [comment] 2019-10-28 20:31
Hmm... Interesting idea.  It should be possible from a technical side with those virtual output controllers (xbox360 or dualshock4 mode) as long DS4Windows app itself is not restarted or stopped. If DS4Windows app itself is closed then it would loose all virtual controller objects it may have created because there is no any pooling background service holding those output controller objects.

But, as long DS4Windows process is kept running then it could hold a pool of output controller objects even when a physical controller was briefly disconnected. Each gamepad (at least official sony ds4 gamepads) has a unique MAC identifier. The pool of output controllers could remember the previous MAC identifier and whenever the same gamepad is re-connected it would re-use the output controller from this connection pool. Maybe DS4Windows should close those "standby" virtual output controllers after a defined X secs/minutes/hours idling period. 

This could work and would be a simple solution to those accidental disconnections and re-connection cycles.

**Comment by Ryochan7** [comment] 2019-10-29 19:43
The majority of DirectInput only games that I know of do not support any form of controller hotplugging; I believe that later versions of the DirectInput API supported hotplugging. A consequence of that is the controller has to be connected at game launch and a lost controller connection requires restarting the game in order for it to see a new device connection.

It would probably be possible to add some class to manage the assigned output slots so an output device can be persistent. Besides helping with DirectInput games, maybe that type of behavior would help with some issues people post about the FIFA games.

**Comment by TVsIan** [comment] 2019-11-22 20:40
This would be super useful for my current setup, a console-style gaming PC using 4 DS4s. I've been using lightbar colors to indicate controllers 1-4, but they'll periodically reassign themselves to different xinput IDs if the profiles change or they get disconnected. So it'll keep the lightbar color I have set for one player, but the controller will be linked to a different one.

If it were to create a persistent device on connect, and always reassign a controller to that same device when reconnecting (at least until you close DS4Windows), it would likely solve that issue.

It's mostly a cosmetic issue, but some games seem to be picky about only using xinput device #1, and once in a while the controller will wind up on #2 (usually if I try to swap between USB and bluetooth) and I'll have to restart DS4Windows to get it back.

**Comment by Ryochan7** [comment] 2019-11-28 16:09
I have only gotten around to playing with adding a delay to plugging and unplugging. There is also a minor check for open output slots (relative to the program). Additional wrapper classes will probably be needed to allow for persistent output controllers to be flagged.

**Comment by coherent-software** [comment] 2019-11-30 19:15
I think this is similar to the issue I'm having. Was going to create a thread but just found this.

When DS4 connects, I have two devices in Windows: "Wireless Controller" and "Xbox 360".

When playing a game, it sees both controllers. If anything is done like power cycling, the game always selects "Wireless Controller" and I have to go into settings to switch to "Xbox 360".

It would be great if "Wireless Controller" was completely hidden from all applications except DS4Windows, but I'm not sure that's possible.

Thanks for your work!

**Comment by mika-n** [comment] 2019-11-30 19:54
@coherent-software  See the following wiki doc page about hiding the original physical controller. If the "Hide DS4 Controller" option doesn't work or after disconnect/connect cycle the exclusive lock no longer work (because some app hijacked the connection) then HidGuardian driver tool is the best way to hide the physical controller from all apps (except DS4Windows).
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

And #844 may also be useful discussion to learn more about how HidGuardian works.

**Comment by coherent-software** [comment] 2019-11-30 20:31
Thanks @mika-n I've tried that option in the past but what really solved the problem was restarting my computer so that DS4Win could take exclusive control properly. I only see the one X360 device now.

Cheers!

**Comment by mika-n** [comment] 2019-11-30 21:00
Do you mean that your tried HidGuardian or exclusive mode (=hideDS4Controller option)? Those are alternative solutions. HidGuardian is a WinOS kernel driver level solution and it should not require reboots even when a gamepad is disconnted and re-connected in the middle of the game. Anyway. The persistent device (or gamepad connection pooling) in DS4Windows app is something which would solve many issues caused by gamepad disconnections.

**Comment by coherent-software** [comment] 2019-11-30 21:43
@mika-n I tried both methods and both have actually failed for me.

With exclusive mode, it shows only the X360 device. However, disconnecting and reconnecting the gamepad causes it to stop functioning properly. The device shows but it behaves strangely, like the right joystick moves the mouse...even outside of the game application. This doesn't fix itself unless the computer is restarted.

So after that I tried turning off exclusive mode and installing HIDguardian as you linked and I'm having the same issue...it works fine until the gamepad power is cycled. I made sure to update to the latest DS4Win and used the test installer linked.

**Comment by coherent-software** [comment] 2019-12-01 03:42
So now even after uninstalling HIDguardian and re-installing DS4Windows everything is completely screwed. The left stick is panning the camera when it shouldn't and the right stick is moving the mouse. I didn't change anything in my profile. If I kill DS4Win and plug in with USB, everything is fine.

What can I check to get back to the way it was working before this fiasco? Sorry for hijacking this thread...

**Comment by mika-n** [comment] 2019-12-01 12:04
Post the content of Logs tab page and a profile file.

**Comment by coherent-software** [comment] 2019-12-01 18:01
[DS4LOG.txt](https://github.com/Ryochan7/DS4Windows/files/3908538/DS4LOG.txt)
[ProfileFiles.zip](https://github.com/Ryochan7/DS4Windows/files/3908541/ProfileFiles.zip)

Here are the files. Thanks.

**Comment by mika-n** [comment] 2019-12-01 18:52
Default and Isaac profiles have "zero" deadzone in LS and RS stick axis. Try setting a small deadzone (start from 0.05 and work it up there). You can use ControllerReadings tab page in a profile editor to test when a deadzone is big enough (but not too big because then you would loose precision).

LS/RS stick is hardly ever completely stable in a hardware level or after releasing the stick it doesn't always return to exactly the same center position. Dust/Spring wear out/AnalogStick causes this behaviour in a hardware level, but that's why usually LS/RS stick should have a small deadzone. DS4Windows allows to use zero deadzone, but it depends on games how it works. If game doesn't have any built-in deadzone then you may see spinning camera/game character keeps drifting to some direction etc.

Some games have built-in deadzone and zero deadzone in DS4Windows doesn't cause any visible side effects, but other games don't have any built-in deadzone (which is good because then you can use DS4Windows to tweak the size of deadzone). 

Also, your profiles have "Flush HID" option set. It is a legacy option and not recommended these days, so try to untick this option. It may lead to lost gamepad events if there are incoming events in a HID queue when the queue is flushed (and any messages there dropped silently).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#gamepad-inputs-seem-to-be-sometimes-lost-especially-when-i-press-several-buttons-at-the-same-time

**Comment by coherent-software** [comment] 2019-12-01 19:54
I completely started from the ground up with a new default profile and had the same issue.
After exploring the profile a bit, I changed the controller from Xbox 360 to Dualshock 4 and...it seems to work properly now.
So now I can use exclusive mode with my original profiles and everything seems to be good. The only difference I see is the game only shows "Wireless Controller" instead of an Xbox 360 device now.
Going to test with some other games now.

**Comment by coherent-software** [comment] 2019-12-01 20:00
Tried another game which was working previously, and it's erratic. However it works properly when I change the controller to Xbox 360.
Seems like there's something wrong on a deeper level. Maybe a registry setting.

**Comment by Ryochan7** [comment] 2019-12-01 20:30
Changing controller output type won't make a difference regarding obtaining exclusive access. The output device is created after the real DS4 is opened. However, when using HidGuardian and the default AffectedDevices list from the test installer, HidGuardian will hide a virtual DS4 from other apps.

I never liked the original build idea of the implicit dead zone for the sticks. When doing direct mapping to an Xbox 360 controller, it might be useful at times to not have DS4Windows enforce a dead zone and just rely on the game's dead zone. Dead zones for LS and RS are required when mapping to KB+M though.

It would probably be useful to have profile templates to handle the base cases but that would be horrible to implement in the current build. The way it even deals with setting up a default profile is pretty bad. The WPF build is much better in the way it is structured. Implementing profile templates might be feasible.

**Comment by mika-n** [comment] 2019-12-01 20:30
A new default profile may also have zero deadzone in LS/RS axis, so check those anyway. 

Are LS/RS axies working properly in ControllerReadings tab page (in a profile editor)?
Are LS/RS working properly in JOY.CPL controlPanel gamepad applet and all buttons are registered OK? 
What do you see in JOY.CPL gamepad list? Do you see one or two controllers listed in JOY.CPL screen?

DS4Windows app doesn't use any registry settings. Maybe you should try to delete (copy/zip in a backup location) all xml files in %APPDATA%\DS4Windows\folder (ie. the the root config folder and not just profile subfolder). DS4Windows will create all missing files using default settings when yo launch it after cleaning the config file folder structure. There has been cases where some veeeery old config files have had some left over settings from an old version and this has caused weird problems in a newer version.

**Comment by coherent-software** [comment] 2019-12-01 22:01
Changed deadzones to 0.1, no change.

LS/RS and L2/R2 are all fine in ControllerReadings of profiles.

JOY.CPL: I see only the Xbox 360 controller as exclusive mode is working.
In this window, the right stick is moving the mouse, the X button is selecting OK. Left/Right on the left joystick change the selected tab. L2/R2 change the Z axis reading. Share changes focus between OK and Cancel. When I close DS4Windows and plug in with USB, everything works fine in JOY.CPL

%APPDATA%: I completely cleared this folder and started over with DS4Win and the same problems are happening.

HidGuardian DOES work but regardless of this being installed or DS4Win being exclusive or not, the same problem is happening. No errors in the log.

I'm starting to wonder if HidGuardian has messed something up which isn't uninstalled with the rest of it.

**Comment by coherent-software** [comment] 2019-12-01 22:05
Changed dead zones to .05 and unchecked flush hid as you recommended with no changes.

**Comment by coherent-software** [comment] 2019-12-01 22:43
I've cleared everything to do with hidguardian from my system32/drivers and the registry and the same issue is still happening. Not sure what to do now.

**Comment by coherent-software** [comment] 2019-12-01 22:58
After exploring the processes, it's Steam causing these issues. At this point I'm unable to run DS4 and Steam at the same time, where I was able to before.

**Comment by coherent-software** [comment] 2019-12-01 23:11
Here's how to fix the issue in Steam. Hope it helps someone else:

- Open Big Picture
- Select the settings gear at the top
- Select Base Configurations -> Desktop Configuration
- Press X (Square) to "Browse Configs"
- Select Recommended -> Disabled then press A (Cross) to import
- Press X (Square) to apply

So after all of this I can now use DS4Win in exclusive mode without Steam interfering, and can still play Steam games with my DS4 gamepad as a Xbox controller.

**Comment by mika-n** [comment] 2019-12-02 20:53
This sounds nasty. There has been reports in the past about how Steam gamepad configuration and re-map rules have screwed up things but in those cases Steam gamepad configuration was explicitly used to re-map keys. Thx for reporting a solution. Have you checked SteamClient Settings/ControllerSettings screen also without entering big picture mode? There it should be possible to set if Steam can hijack a controller and re-map keys.

Also be aware of the following nasty feature of Steam client if a profile uses dualshock4 output type:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

**Comment by Ryusennin** [comment] 2019-12-03 00:33
I have always disabled all Steam controller settings (including X360) since none of their remapping features are needed if you use DS4Windows.

**Comment by Ryochan7** [comment] 2019-12-06 15:56
Did a minor persistent device test in FIFA 19. It does clear up the issue with mixed controls in-game. However, menus still act wonky due to the presence of the DS4 controller.

**Comment by reyaz006** [comment] 2019-12-14 19:56
Shouldn't "Hiding DS4" solve that?

**Comment by Ryochan7** [comment] 2019-12-14 20:11
Partially. The problem is there is no way for the old Exclusive Mode routine to activate on hotplug while FIFA is running. Using HidGuardian is pretty much required to be able to handle hotplug events while the game is running. That does matter to some people.

It has been a commonly mentioned problem. Now that there was a way to test it, I gave it a quick try. The structure of the test patch for a persistent device is not good. A different design needs to be considered.

**Comment by reyaz006** [comment] 2020-01-19 15:59
So are there plans to provide some guide for people who would like to use this mode? I'm not sure what HidGuardian exactly is, but if it's a part of ViGEm software then it should be easier to provide an option to install them together? Or does it still need additional implementation in DS4W?

Another game I played recently can't handle DS4 disconnect (1001 Spikes). After it connects again, either the game just crashes or DS4 starts to act as a controller for Player 2.

**Comment by mika-n** [comment] 2020-01-19 17:38
Plans = Yes. Timetable = No.

**Comment by Ryochan7** [comment] 2020-01-20 01:39
The big problem is that I had not used HidGuardian regularly. As it is, vanilla HidGuardian does not do what I want. I have contributed some changes to the project to get it closer to what I would want but the old changes still required sacrificing input responsiveness.

Only more recent discoveries have removed that compromise and I have only started using HidGuardian recently; the use case is actually for the Touchmote project rather than DS4Windows. If I had the option then I would probably distribute a custom HidGuardian driver for use in DS4Windows. However, easy driver deployment is pretty much behind a paywall which costs around $300 USD to sign a driver that Windows won't interfere with.

Source code of custom version that I have used:
https://github.com/Ryochan7/HidGuardian/tree/gottagofast

As for the persistent device proposal, nothing has been done since my last post here and I don't even have the test patch anymore. This idea is more a "nice to have" feature but I am not heavily motivated to try getting something made right away.

**Comment by Erquint** [comment] 2020-03-29 08:26
I second the original proposal nonetheless.

**Comment by reyaz006** [comment] 2020-06-19 21:24
I wanted to create a separate issue but decided to just leave some feedback and questions here, since this is all hopefully related.

1. So, new version 2.1.3 includes "HidNinja" feature. I'm not too sure what it's all about since I didn't find any documentation. My guess is that it's a step closer to the solution to this very issue. If possible, I'd like to know if it works and how can I start using it. I didn't install the new ViGEmBus, do I need it?

2. There is a small bug with displaying of lists with non-English content here:
![image](https://user-images.githubusercontent.com/6751344/85180004-fa223c00-b28a-11ea-9c25-0fdcf816b41d.png)

3. It seems there are games where DS4W breaks DS4 support. I'm pretty sure it's known but really couldn't find a proper word for it, so couldn't find any workaround. Example: Shovel Knight Treasure Trove. It supports DS4 natively (can confirm), but it only works without DS4W active. If DS4W is running - the game acts like no controllers are plugged. Sure, possible solution would be to switch to Xbox 360 (Xinput) mode, but I'd like to know if this can be solved in a different way, since I'd like to have DS4W manage my DS4 and have the native DS4 icons displayed in-game.
I've tried disabling Hide DS4 setting, but it didn't change anything. Could it be that HidNinja can somehow help with such cases too?

**Comment by mika-n** [comment] 2020-06-24 13:54
HidNinja is a tool to configure certain system registry settings used by HidGuardian device driver tool. 
AffectedDevices sysreg entry lists which gamepad devices are monitored by HidGuardian tool and hidden from games. Only certain processes are allowed to see the device (WhiteListed processes). DS4Windows is one of the tools allowed to see the "affected" device because otherwise it could not do the "physical -> profile remapping rules -> virtual output controller" thing. DS4Windows automagically whitelists itself, so there is no need to set anything in Processes tab page in HidNinja tool, but the same tool can be used to control other apps also if necessary. However, AffectedDevices should list DS4 gamepad identifiers in order to hide the physical ds4 gamepad from games.

Once the AffectedDevices sysreg entry is setup manually or via HidNinja tool then there is no need to touch that setting anymore (the value is persistent between reboots).

The "topic 3" in your post is probably because of non-functioning exclusive mode (=Hide DS4 Controller option) or if you use HidGuardian then it is not properly setup (note! There is no need to use both HideDS4Controller option AND HidGuardian tool at the same time because those are alternative ways to do the same thing).

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by reyaz006** [comment] 2020-06-28 08:43
I don't have HidGuardian yet.

>Or if you use Steam client to launch games then because of stupidity in Steam to actively ignore DS4 gamepad devices in certain cases. One workaround is to rename DS4Windows.exe app to something like DS4WApp.exe (and DS4WApp.exe.config file).

Okay this is what actually worked. But I went further and discovered that it's not Steam. It's the game that disables DS4 support if DS4Windows.exe is running. Possibly better solution is to find the "DS4Windows.exe" string inside the ShovelKnight.exe and change it, which worked for me.

Thanks.

**Comment by mika-n** [comment] 2020-06-28 08:55
Aaah. Thanks for reporting that in that case it was the game itself doing the stupid _"hey, let's disable automagically some fancy apps user may use"_ feature withing the game code instead of providing user an option to do it or not to do it.

Anyway, sometimes Steam client does thing like of stupidity also, but not just with DS4Windows.exe but with other "customized" gamepad apps (InputMapper, x360ce, AHK etc....).

**Comment by Ryochan7** [comment] 2020-06-28 09:25
> 2. There is a small bug with displaying of lists with non-English content here:
>    ![image](https://user-images.githubusercontent.com/6751344/85180004-fa223c00-b28a-11ea-9c25-0fdcf816b41d.png)

Been looking for this post but I couldn't find it. I think I have found a way to work around the issue. Hopefully the text encoding problem will be fixed in the next version of HidNinja.

**Comment by Ryochan7** [comment] 2020-06-28 09:37
> I don't have HidGuardian installed yet.
> 
> > Or if you use Steam client to launch games then because of stupidity in Steam to actively ignore DS4 gamepad devices in certain cases. One workaround is to rename DS4Windows.exe app to something like DS4WApp.exe (and DS4WApp.exe.config file).
> 
> Okay this is what actually worked. But I went further and discovered that it's not Steam. It's the game that disables DS4 support if DS4Windows.exe is running. Possibly better solution is to find the "DS4Windows.exe" string inside the ShovelKnight.exe and change it, which worked for me.
> 
> Thanks.

Maybe the game is using the SCAPI to enable controller support in the game? If that is the case then the problem would actually be with the Steam client as the game will depend on it to provide the controller event data.

**Comment by reyaz006** [comment] 2020-06-28 13:30
>Maybe the game is using the SCAPI to enable controller support in the game? If that is the case then the problem would actually be with the Steam client as the game will depend on it to provide the controller event data.

I've tried playing a game without Steam - same issue. More importantly, the game code has a specific place where it checks whether or not there are running processes named DS4Windows.exe and InputMapper.exe. I don't know if it's a part of some 3rd party middleware. But it seems to me the logic was "_these applications map a DS4 controller to act like Xbox controller, so let's disable DS4 support in case they are active and allow user to play as a Xbox controller user_". Which doesn't make sense to anyone who knows about DS4 hide option and DS4 mode.

>Anyway, sometimes Steam client does the same stupidity also, but not just with DS4Windows.exe

That "sometimes" would need clarification. With certain games only or with certain settings only? I've played many games on Steam so far and didn't have such problems. However I have Steam Input disabled so I wouldn't expect Steam to do anything about DS4Windows.

**Closed** 2020-08-06 15:56 UTC
