### ISSUE TITLE
Random PC Reboots

### ISSUE THREAD

**Issue by MobbingAllDay** [Ryochan7/DS4Windows#1987] opened 2021-03-23 20:25 UTC
**Describe the bug**
I have steam controller supports all off. Load up DS4Windows with PS5 controller via Bluetooth. I load it up as playstation 4 controller btw in settings.. I'll play a game forawhile then pc reboots put of nowhere. Controller is hooked up externally to USB type-c to keep it charged. My PC did this before and I stopped using the program. Went to use it again today and the problems came back. I was playing red dead online for like 3 hours btw. I keep checking temperatures to see if everything is fine but I don't notice anything wrong.

**Comment by Ryochan7** [comment] 2021-03-23 20:42
Likely a duplicate of issue #1940. Unfortunately, it is likely a driver problem that is not due to DS4Windows code

**Comment by MobbingAllDay** [comment] 2021-03-23 21:39
No Bluescreen of death. Just restarts. But do you think its a driver issue that gets installed with DS4?

**Comment by tamodolo** [comment] 2021-04-09 11:09
I'd start looking for hardware fails because it seems the case. If it's a software fail you'll get a blue screen that dump what is in the ram and then reboot. A total cold reboot (black screen then reboot) is caused commonly by hardware fail.

commom motives: Your PC is overclocked? When did you last cleaned your PC? Did you check bad conections? And the list goes on. This can mean you ram gonne bad too. Run a stress test on it.

**Comment by cartist** [comment] 2021-04-11 22:10
Hi, I have a similar issue, possibly connected. No overclocking on my Rig. Happened when using the controller via bluetooth. Playing the game fine. Paused and switched to windows to google something, controller loses connection. I reconnect and boom BSOD. Reproduceable everytime I am ingame and the controller disconnects and reconnects.

**Comment by Ryochan7** [comment] 2021-04-11 22:23
Can never be given the most basic info I need to attempt to diagnose anything (ViGEmBus version). I am outright going to only have DS4Windows work with ViGEmBus 1.17.333.0 for the next release. The app will refuse to connect to ViGEmBus otherwise. That breaks Windows 7 support but I don't care anymore.

**Comment by Ryochan7** [comment] 2021-04-14 21:08
Other posts make it seem more likely that other software is the culprit.

**Closed** 2021-04-14 21:08 UTC
