### ISSUE TITLE
DS4Windows will not start minimized

### ISSUE THREAD

**Issue by ceedveed** [Ryochan7/DS4Windows#514] opened 2018-12-09 20:54 UTC
I've tried both Program and Task as startup options. I've tried checking and unchecking the Start Minimized option. I'm on Windows 10 x64 using 1.5.18.
Startup on boot works fine.

Any tips?

**Comment by Ryochan7** [comment] 2018-12-10 11:39
I can confirm that Start Minimized no longer works. The problem seems more due to the Form_Resize method than anything else. I have tried some fixes that would correct the issue but application performance has been impacted by each one. This issue might remain unresolved if I cannot find a cooperative change.

**Comment by Kenzeira** [comment] 2018-12-13 10:08
I found a temporary workaround: 
-Uncheck Start with Windows Options  and check Start Minimized and Minimize to Taskbar. 
-Create a new Task Sheduller to start DS4Windows and in "Actions" Make a new action pointing to yours DS4Windows.exe and in "Add arguments" (optional) insert: "cmd.exe /C start /MIN" (without the quotes).
-In "Triggers" Tab add a new one with "At log on" and "Any user"
 I delayed mine in 10 sec after logon (optional).
Hope this help.

**Comment by bronnel** [comment] 2018-12-14 13:54
I can confirm too that start minimized is not working

**Comment by Ryochan7** [comment] 2018-12-15 04:10
Although the workaround isn't what I wanted, this problem has been fixed in the current code. A new release should get published fairly soon.

**Comment by Kenzeira** [comment] 2018-12-15 10:06
Guys, the sugestion i gave above it's just a little quick fix to users from current version and doesn't want the window popup on Windows logon. Not an oficial fix. It's working fine for me here.
But i'm glad we'll see a oficial fix on next release.

**Closed** 2018-12-20 21:21 UTC
