### ISSUE TITLE
Stable red light and no vibration

### ISSUE THREAD

**Issue by tj234454432** [Ryochan7/DS4Windows#1152] opened 2020-03-15 17:49 UTC
So i have this problem with my new controller were at random times my controller will just change to a red and light and the vibration stops working 
the only time i know a red light is suppose to occur is when my latency is over 20ms or my battery is low but even when no of those things are happening it still happen.
Iv also had multiple ps4 controller both version 1 and 2  and this has never happened but Iv noticed that when ds4 is closed this never happens so im not sure if its a hardware problem or software

**Comment by mika-n** [comment] 2020-03-19 10:14
are you using usb connection? Check the cable connection to make sure there are no temporary connection issues. Well, this should be shown in a logfile.

Try testing bluetooth connection to isolate the issue to either USB or BT connection (or in both).

**Comment by tj234454432** [comment] 2020-03-20 16:16
it only happens over bluetooth connection

**Comment by mika-n** [comment] 2020-03-21 12:19
Maybe you should run a debug version to see if the debug logfile shows more info.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

But, if this happens only over BT then it is still difficult to say if it is gamepad or BT receiver  or app issue.
- Make sure there are no other BT devices connected and near-by when testing
- Shutdown all background services and apps which might use gamepad (floods the BT communication line)

**Comment by tj234454432** [comment] 2020-03-22 00:23
should i be looking for something exact in the log file?

**Comment by mika-n** [comment] 2020-03-22 06:38
The whole thing

**Comment by tj234454432** [comment] 2020-03-25 02:56
[log.txt](https://github.com/Ryochan7/DS4Windows/files/4378749/log.txt)

**Comment by tj234454432** [comment] 2020-03-25 02:59
i removed all Bluetooth devices beside the controller and play until the light changed
it changed around 9:20 to 9:55

**Comment by mika-n** [comment] 2020-03-25 07:19
This is a fatal error and DS4Windows force closes a connection to the gamepad. The error happens while PC tries to send data to the gamepad over BT. 
`03/24/2020 21:22:40: DEBUG: sendOutputReport. ERROR. writeOutput failed. Force quiting output thread. LastErrorCode=1167
`

However, already before the fatal error there was warning messages about latency issues. This is usually a sign of BT communication issues between the PC and the gamepad. Some BT chipsets/drivers/PCs are not up to the task to read AND at the same time to write data over BT communication line. Somehow the BT chipset drops a ball when pushed too much. Because of the nature of the gamepad it needs to be read several times a second and every now and then some data needs to be sent out to the gamepad while data is also read from the gamepad. 
`03/24/2020 19:56:02: Controller 1's latency over 10ms
`

Try different "BT poll rate" in DS4Windows settings to see if it helps.

Using the debug version you can if the "read part of BT communication line" works better if you temporarily disable writing data to the gamepad. You loose lightbar and rumble support when write-out is disabled, but this tells us if the BT chipset or drivers you have in PC are simply too "incompatible" with high frequency usage scenarios. The gamepad usage needs fast BT chipsets/driver stack. 

Anyway. To disable "write data" part of DS4Widnows app and DS4 gamepad, modify following option in DS4WindowsDebug.exe.config file (use Powered by Notepad high tech and see existing entries at the end of the file).
`  <add key="Debug_SendRumbleLightbarData"      value="false" />`

If you need the lightbar and rumble support then set "SendRumbleLigthbarData" option back to TRUE and try tweaking the following buffer value. Try increasing it one by one to see if certain value makes the PC work better with DS4 BT device.
`  <add key="Debug_HidDSetNumInputBuffers"      value="2" /> `   

Note! Stop DS4WindowsDebug.exe app everytime you modify this config file (changes are seen only at the app launch time).

**Comment by tj234454432** [comment] 2020-03-26 03:22
i do need the lightbar and rumble support so should i still test this method 
<add key="Debug_SendRumbleLightbarData" value="false" />

**Comment by mika-n** [comment] 2020-03-26 06:05
Yes

**Comment by tj234454432** [comment] 2020-03-27 00:43
BT poll rate doesn't help

**Comment by tj234454432** [comment] 2020-03-27 00:43
[log.txt](https://github.com/Ryochan7/DS4Windows/files/4390833/log.txt)

**Comment by tj234454432** [comment] 2020-03-27 00:51
is it possible for the high latency state to become stuck because from what Iv noticed through the log every time my problem occurs its always after a random latency spike?

BTW after disabling the write data how will i know if the read part of BT communication line works?

**Comment by mika-n** [comment] 2020-03-27 07:13
The logfile you provided is NOT from the debug app. Please download the DeviceDetect debug version from the following link and extract the zip file into the same folder where you have DS4Windows installed at the moment. Then run DS4WindowsDebug.exe executable after modifying the DS4WindowsDebug.exe.config file as described above.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

When you disable the "write out data" feature, you can confirm that the "read in data" feature still works if DS4Windows app can read DS4 gamepad button/stick/touchpad events (use ControllerReadings tab page of DS4Windows app and button remap rules work in games (through the virtual output driver created by DS4WindowsDebug+ViGem).

**Comment by tj234454432** [comment] 2020-03-27 15:27
[log.txt](https://github.com/Ryochan7/DS4Windows/files/4394376/log.txt)

**Comment by tj234454432** [comment] 2020-03-27 15:27
controller still works with writing data disabled

**Comment by mika-n** [comment] 2020-03-27 20:26
The gamepad should work without "write data" feature. Only lightbar and rumble doesn't work. Anyway, the BT communication line is still reporting low latency even when write-data feature is disabled.

It seems that the BT chipset or driver you have in the PC is not up to the task. 

You could try to disable gyro calibration feature also (ie. false value both in GyroCalibration and SendLigthbarRumbleData options in DS4WindowsDebug.exe.config file)
`  <add key="Debug_GyroCalibration" value="false" />
`

Having FALSE in both of these options makes the DS4 gamepad to behave a bit differently in PC over BT. The gamepad sends a lot less data to PC and therefore it uses less BT resources. However, gyro, touchpad, lightbar and rumble doesn't work but it tells us if the BT chipset/driver you have is capable to handle the traffic with less data.

Some people have reported similar issues with BT dongles and sometimes re-installing/updating BT drivers have fixed the issue. Sometimes the only option has been to use USB connection or to purchase another BT usb stick (hoping it has better chipset and drivers).

You could also disable the "Flash lightbar at high latency" option in DS4Windows settings if occasional latency is OK and you don't want the ligthbar to warn about it. 

Sorry. But there is not much to do in DS4Windows side if the issue is in BT chipset/driver in the PC.

**Comment by tj234454432** [comment] 2020-03-27 22:48
i dont mind the light randomly changing to red but it sucks the vibrations stop.

i think its the Bluetooth no doubt but im just wondering why this has never happened before as iv said before iv had multiple controllers both v1 & 2 and this a never happened
i even tried a different controller today and it worked fine

**Comment by Ryusennin** [comment] 2020-03-28 18:05
Is this a genuine DualShock 4?

**Comment by tj234454432** [comment] 2020-03-28 21:32
i would like to think so but im not totally sure 
is their way to verify?

**Comment by tj234454432** [comment] 2020-03-28 21:36
iv found a fix kinda
going into setting and changing high latency to 20ms fixing the light and vibration problem but something weird happens when its changed and i still  get lag

**Comment by tj234454432** [comment] 2020-03-28 21:40
![Capture1](https://user-images.githubusercontent.com/45494727/77834444-29f1f580-711b-11ea-966d-3c95fb997d54.JPG)
![Capture](https://user-images.githubusercontent.com/45494727/77834445-2b232280-711b-11ea-82d9-c59edd70d489.JPG)

**Comment by tj234454432** [comment] 2020-03-28 21:46
is their a way to see my latency real time?

**Comment by mika-n** [comment] 2020-03-28 21:49
Keep the "Logs" tabpage in DS4Windows open. If you have two monitors then you can keep it open in another screen while playing.

**Comment by tj234454432** [comment] 2020-03-28 22:08
> Is this a genuine DualShock 4?

just searched it up seems fake

**Comment by tj234454432** [comment] 2020-03-29 00:47
changing flash light bar at high latency to 20ms fixes the problem but only in the debug version

**Comment by mika-n** [comment] 2020-03-29 11:17
Hmmm.... There really shouldn't be any differences how the latency and "flash at high latency" feature behaves in the official and debug version. 
Do you mean that high latency is fixed with the debug version while you have re-enabled SendLightBarData and GyroCalibration options back to default TRUE value? Strange.....

**Comment by tj234454432** [comment] 2020-03-29 13:36
yes all debug values are back to default

**Comment by tj234454432** [comment] 2020-03-29 14:53
> changing flash light bar at high latency to 20ms fixes the problem but only in the debug version

scratch that its not fixed

**Comment by tj234454432** [comment] 2020-03-29 15:44
it seems like it the controllers fault so ill leave it at that but can i get some suggestion on how to reduce the latency

**Comment by mika-n** [comment] 2020-03-29 19:42
Driver updates in PC. No other BT devices connected while you use the gamepad. Or use USB cable connection. Sorry, no magical "one click" solution which is guaranteed to work.

**Comment by tj234454432** [comment] 2020-03-29 19:58
thanks for help

**Closed** 2020-03-29 19:59 UTC
