### ISSUE TITLE
Inconsistent Lightbar Color Change on DualSense

### ISSUE THREAD

**Issue by mrtostados** [Ryochan7/DS4Windows#1638] opened 2020-12-08 10:25 UTC
**Describe the bug**
It seems that profiles will only allow one button in the profile to change the color of the lightbar. I'm not sure if this is intentional to avoid conflicting signals going to the lightbar with simultaneous button presses or it is, in fact an issue. Sometimes, setting a button to change the color doesn't work at all. Furthermore, the flashing option for the lightbar color does not appear to function. Also, more broad, but any part of the interface with a color picker tends to reset its value to pure white at random.

**To Reproduce**
Steps to reproduce the behavior (for me):
1. Select a profile
2. Select a button on the gamepad (in this case, R2)
3. Check "change lightbar color" and select desired color (green, here)
4. Select desired mapping (in my case, RT)
5. Close the mapping window
6. Click apply
7. Pull R2 and lightbar color changes to green
8. Repeat 2-6, but with L2, red, and LT, respectively
9. Pull L2 and observe no change, pull R2 and lightbar turns green again
10. Repeat 2-6, but with square, orange, and X
11. Press square and the lightbar becomes orange; pull L2, nothing happens; pull R2, nothing happens
12. Admit defeat

**Expected behavior**
I was expecting L2 to at least work. Even after successes with other buttons, L2 still wouldn't change the lightbar color. I was also expecting multiple buttons to be able to change the lightbar color, but that may have been a silly expectation.

**Desktop:**
 - Controller Make and Model: Sony DualSense (model CFI-ZCT1W)
 - OS: Windows 10 Home v. 10.0.18363 build 18363
 - DS4Windows Version 2.1.19

**Additional context**
I know DS4Windows is very much a work-in-progress, what with updating a program 5 years, so the bugs don't surprise me. I just appreciate you devs doing the public a service by getting it up and running again.

**Comment by Ryochan7** [comment] 2020-12-08 15:56
I almost never used the Extras portion of the button mapping routine. It worked as expected the last time I had tested it. Only one active button will change the lightbar color at a time but multiple extras should be mappable in a profile. For L2 and R2, I believe the trigger has to be at least at half pull in order for the Extras settings of the binding to take affect.

You do not mention it in the post but I will assume you are using the DS using a Bluetooth connection. That behavior was likely a side effect of a different problem that does has a workaround in the DS4 device class. With the DS4, any change to the haptic state will send multiple output reports to the DS4 controller to attempt to ensure that the change will take affect. There is no such workaround with the DualSense device class because it was not known whether such a workaround was necessary at the time.

Anyway, a better solution has been added in commit c18e779df3bbee60f78dd5785f67cebce3c6c5ad for DualSense support that should be included in version 2.1.20. Some testing has to be done but a similar change will likely be added to the DS4 device class.

**Comment by mrtostados** [comment] 2020-12-08 16:53
> For L2 and R2, I believe the trigger has to be at least at half pull in order for the Extras settings of the binding to take affect.

Believe me, I tried every possible method of manipulating the L2: half pulls, full pulls, fast taps, slow taps --- no dice.

> You do not mention it in the post but I will assume you are using the DS using a Bluetooth connection.

I usually use wired so I can jack my headset directly into the controller. Also, latency. I tried it both wired and not. Should've mentioned that in my post. My bad.

> Anyway, a better solution has been added in commit [c18e779](https://github.com/Ryochan7/DS4Windows/commit/c18e779df3bbee60f78dd5785f67cebce3c6c5ad) for DualSense support that should be included in version 2.1.20.

Now, this is great news. I'm sure it (or a soon-to-be-released build) will remedy this problem. I totally understand that DS4Windows was never designed to support DualSense (let alone be functional nearly 5 years after its last release in its original format), so I'm not expecting miracles in the slightest. Currently, the program allows me to do everything I *need*, it's just some of the fun stuff like cool lights and complex macros that aren't really supported, and that's something I can *totally* wait on.

**Comment by Ryochan7** [comment] 2020-12-08 19:41
Confirmed the lightbar color reset in the Binding window. It looks like the **Change Light** settings is not enabled when bringing up the window a second time although the chosen lightbar color is still present then. Once the window is closed when **Change Light** is disabled, the window will proceed to reset the lightbar color to White before closing.

**Comment by mrtostados** [comment] 2020-12-08 20:48
Precisely the behavior I was experiencing in that respect. I really appreciate you taking the time to investigate the issue!

**Comment by Ryochan7** [comment] 2020-12-14 20:01
The original problem is fixed. Also, the output workaround that I mentioned in a previous post was removed in a most recent update. Now the DS4 device class and DualSense device class output data in a similar fashion.

**Closed by Ryochan7** 2020-12-14 20:01 UTC
Labels: bug
