### ISSUE TITLE
Lightbar coming on

### ISSUE THREAD

**Issue by shogunreaper** [Ryochan7/DS4Windows#47] opened 2017-05-28 05:37 UTC
I think this is a bug, or maybe it some setting i'm missing

I keep my lightbar turned off to save battery (i also don't want a flashing light at night in my room), but when the controller is turned off and then plugged into usb for charging the lightbar turns orange and continues to flash until i unplug it.

it doesn't seem to happen when i plug the controller in while it's on.

**Comment by InfinateXtremer** [comment] 2017-05-28 11:07
It's not a bug. It's what ds4 does when it's turned off and you plug it in for charge, if i remember right it stops flashing when it's done charging.

**Comment by shogunreaper** [comment] 2017-05-28 12:44
how can i turn it off?

**Comment by InfinateXtremer** [comment] 2017-05-28 19:58
Sadly you can't, but you can use a micro usb cable that supports data transfer so you can use ds4 wired with ds4windows

**Comment by shogunreaper** [comment] 2017-05-28 20:27
not sure what you mean, i use bluetooth for this.

this is just when i plug it in for charging.

**Comment by InfinateXtremer** [comment] 2017-05-28 22:15
If your pc is open and you're charging ds4 on pc and  you can use ds4windows without bluetooth, so when you're about to charge your ds4, close it, plug it in, than press ps button, it should automatically show up on ds4windows connected using usb and if you disabled lightbar on ds4windows it should charging without light

Other than that if you really want to disable lightbar it you can open ds4 and probably cover lightbar pins inside.

**Comment by shogunreaper** [comment] 2017-05-28 22:21
not sure why its not possible, i didn't have this problem on Jays2Kings's version.

**Comment by Ryochan7** [comment] 2017-05-29 03:03
Was the relevant HID controller device still counted as disabled? DS4Windows leaving a device disabled is the only time I have ever encountered the lightbar not activating upon plugging a DS4 into a USB port on a Windows system. Is the device still usable from the Windows Game Controller settings when this happens?

**Comment by shogunreaper** [comment] 2017-05-29 04:07
> only time I have ever encountered the lightbar not activating

the problem i'm having is that it IS turning on the lightbar when i specifically have it turned off in the settings. (all sliders are at 0)

> Is the device still usable from the Windows Game Controller settings when this happens?

no because its turned off via idle disconnect. (the controller is still seen but no buttons work until i turn back on)

**Comment by Ryochan7** [comment] 2017-05-30 21:57
That is the only scenario that I can think of when the behavior would be different between the two versions. All I can say is that it works as expected on my system. Having the sliders set to 0 in a profile will make sure that the lightbar is blanked as soon as the DS4 is detected by DS4Windows.

**Comment by shogunreaper** [comment] 2017-05-30 22:04
and the light does stay off... in all situations EXCEPT when the controller is off before plugged in.

its some sort of charging indicator, because when the controller is charged the light turns off.

**Comment by randu1459** [comment] 2017-06-26 01:46
Just to reiterate what Ryochan7 and InfinateXtremer have said: the orange lightbar is a charging indicator provided through the hardware. If you turn the controller off and plug it in using plain charging USB cable, the DS4 will show the orange lightbar as an indication that it is being charged. What Ryochan7 and IfinateXtremer are suggesting is to leave the controller connected to DS4Windows using a data cable. As long as it's connected to DS4Windows and not turned off, it should actively charge and continue to use your settings. With the DS4 controller turned off and not connected to DS4Windows, there's nothing allowing DS4 to control the lightbar.

If you're still having trouble setting their suggestion up, I'd be glad to assist!

**Closed** 2017-07-24 23:12 UTC
