### ISSUE TITLE
After disconnecting via PS+L1+R1, keys bound to PS/L1/R1 are no longer sent

### ISSUE THREAD

**Issue by xndc** [Ryochan7/DS4Windows#474] opened 2018-10-31 10:17 UTC
1. Bind L1 and L2, for example, to LMB
2. Disconnect controller via PS+L1+R1
3. Note that LMB is still held down after disconnecting, have to click to reset it
3. Reconnect controller
4. Note that neither L1 nor L2 send LMB presses anymore
5. Note that stopping and restarting DS4Windows via the "Stop" button doesn't fix this
6. Note that switching profiles doesn't fix this

DS4Windows has to be restarted to fix the stuck key(s).
This isn't specific to the mouse buttons. I have the same issue with the PS button and Esc.

Bindings that emit XInput events work as expected.

**Comment by Ryochan7** [comment] 2018-11-01 17:40
Tested this with a BT connection and I am experiencing similar issues. The routine works mostly fine when using a Sony Wireless Adapter connection. The reset routine looks like it does not work as intended. Not a big surprise with the old code base. I will look into this a bit but I will likely file this as won't fix.

**Comment by Ryochan7** [comment] 2018-11-08 06:15
This problem should be fixed in version 1.5.15.

**Closed by Ryochan7** 2018-11-08 06:15 UTC
