### ISSUE TITLE
In Version 3.2.10 Dualshock 4 emulation from my DualSense doesn't work.

### ISSUE THREAD

**Issue by mosesmakaka** [Ryochan7/DS4Windows#2930] opened 2023-05-04 13:53 UTC
### Discussed in https://github.com/Ryochan7/DS4Windows/discussions/2922

<div type='discussions-op-text'>

<sup>Originally posted by **Ryochan7** May  1, 2023</sup>
OSC server changes, gyro jitter compensation

.NET Runtime x64
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.16-windows-x64-installer
.NET Runtime x86
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.16-windows-x86-installer

* Added jitter compensation routine for Gyro Mouse
* Move output handler init and disconnect calls to ControlService Start and Stop routines
* Added extra exception handling for tray notification failure
* Use DetermineConnectionType in PostInit of DS3Device. Contribution by **SunnyQeen**
* Fixed a crash when open device options with null option. Contribution by **SunnyQeen**
* Add InterpretingOscMonitoring Option. Contribution by **xAdler**
* Added some OSC translation strings. Contribution by **xAdler**
* Added OSC monitoring message interpreting. Contribution by **xAdler**
* Added OSC trigger control. Contribution by **xAdler**
* Added additional mapping checks in ProfileDTO MapFrom routine
* Changed how macros are saved from binding window. Do not reset shift trigger
* Support Horipad 4 FPS. Contribution by **markguleno**
* Fixed custom led mode. Contribution by **MatrixDJ96**

<hr /><em>This discussion was created from the release <a href='https://github.com/Ryochan7/DS4Windows/releases/tag/v3.2.10'>Version 3.2.10</a>.</em></div>

**Comment by mosesmakaka** [comment] 2023-05-07 13:14
I came to realize the problem lies with the PS Remote Play app for PC. There is a change in code that I think Sony has disabled dualshock 4(which is what DS4 windows emulates) even if you are using a DualSense controller via bluetooth. I might be wrong so anyone with a DualShock 4 controller try connecting it to PS5 through PS Remote Play for PC via USB and check if it works. If not, then that is what Sony did and we need a DS4 windows update that at least addresses DualSense controllers.

**Comment by Ryochan7** [comment] 2023-05-07 14:55
Duplicate of #2868

Recent updates to PS Remote Play send extra control requests that the virtual DS4 cannot recognize so the app ignores the controller. Not sure if that was done on purpose to break virtual controller compatibility or not. Either way, the problem lies with the ViGEmBus driver that powers the virtual DS4 and that driver has to be updated to restore compatibility.

https://github.com/ViGEm/ViGEmBus/issues/172

**Comment by mosesmakaka** [comment] 2023-05-21 18:00
So we just wait?

**Comment by Ryochan7** [comment] 2023-05-21 18:42
With the current drama going on, I have no idea. DS4Windows might be stuck on the last pre-version 2.0 driver for all I know.

**Comment by Ryochan7** [comment] 2023-06-23 19:44
No point leaving this issue open anymore. It will not get resolved.

**Closed by Ryochan7** 2023-06-23 19:44 UTC
