### ISSUE TITLE
The rumble doesn't stop after starting in game.

### ISSUE THREAD

**Issue by Redn2000** [Ryochan7/DS4Windows#642] opened 2019-04-02 02:28 UTC
I have the most recent update, ver 1.7.2, which had fixed an issue with the touch pad cancelling the rumble. The issue now, however, is that rumble doesn't seem to stop at all until stopping and starting DS4's connection to the controller. I've tested with 2 controllers while playing a game on Dolphin and the issue persists regardless of profile or controller.

**Comment by Ryochan7** [comment] 2019-04-02 03:00
Duplicate of #616. This is an inherit issue with the way force feedback states are reported in ViGEmBus. Nefarius is trying to fix it through a client library update but it might end up requiring an updated driver to fix.

**Comment by Redn2000** [comment] 2019-04-02 03:16
If it's patience I need, then that's no problem. You guys have been putting out some great updates and support, so I'm willing to wait if need be. If the time does arise for a driver update, will that be packaged with an update, or will we need to scope it out ourselves?

**Comment by mika-n** [comment] 2019-04-02 06:35
I test compiled the ViGemSDK Client driver (vigemclient.dll) with the proposed fix to this issue. I had experienced similar issue in ETS2 truck simulator when a truck run over kerbs but it didn't happen always, so it was a bit difficult thing to test. Therefore I'm not quite 100% sure yet if the vigemclient fix really fixes the problem. I have to try to find some app where this rumble bug is reliably duplicated and easy to test whether the new client library helps.

**Comment by mika-n** [comment] 2019-04-02 15:00
The new ViGemClient doesn't seem to fix this issue or it is not enough to place the new DLL in the same folder with DS4Windows (althought processExplorer shows that DS4Win app loads the DLL from that folder).

I don't have any Dolphin images but looks like that the rumble motor sometimes gets stuck in Dolphin controller setup screen also. It is easy way to test this issue. If I set controller emulation to use MotorL or MotorR and press TEST rumble button in Dolphin setup screen then sometimes the rumble gets stuck and won't stop until I go to DS4Windows settings and press "Test rumble" button there (DS4Windows finally sends a new rumble 0 event). The issue seems to happen more often if I press the "TEST" button while I press DS4 buttons. If I don't press any DS4 buttons or move sticks then Dolphin rumble test doesn't get stuck that often.

![DolpinRumbleTest](https://user-images.githubusercontent.com/35538525/55412604-70485f00-5570-11e9-81d8-4f6312c467af.png)

**Comment by Ryochan7** [comment] 2019-04-02 15:32
Compiling the vigemclient dll is only one step. You still have to compile the vigem.net class library. The C library is embedded in the compiled .net class library. That class library is what DS4Windows uses.

Thanks for highlighting an easy way to reproduce the rumble problem.

**Comment by Ryochan7** [comment] 2019-04-02 15:37
Also, I should mention that the posted commit does not fix the problem. Threads can get woken up out of order when multiple events are sent at the same time.

**Comment by mika-n** [comment] 2019-04-03 07:23
Aah okey. I was wondering why my laptop originally didn't have VigemClient.dll file anywhere. That explains it (it's exported DLL funcs are embedded inside the Nefarius.VigemClient.dll .NET managed library).

Hmmm... Could it be possible to add a sequence counter to a data package VigemClient sends to a registered notification method in client application (ie. DS4Windows)? 

Now the data pkg has MotorLeft/MotorRight/LedIndex values, but if there would be an event sequence number also then DS4Windows could simply ignore rumble requests if a sequence number is less than a previously processed package. Of course assuming VigemClient creates those callback notification events in correct order and sometimes only forwards events to registered clients in wrong order. 

This way DS4Windows client would not send out rumble commands to a physical controller if a game sent that specific rumble request before already processed "rumble 0" request (or any other request). This workaround could miss few rumble effects if it was sent in wrong order but I think the result would be less annoying than "stuck" rumble motor (ie. game sent Rumble-50 and Rumble-0 commands in this order to Vigem driver but VigemClient forwarded those events to a registered DS4Win client app in wrong order). ViGemClient should keep track of these sequence numbers per registered client because it is the only place where it creates those events in correct order (hopefully in correct order. If Vigem device driver notifies rumble requests to VigemClient in wrong order then this theory doesn't work)

**Comment by reecespieces** [comment] 2019-04-03 19:51
Yes. I've noticed this too and it's the only thing stopping me from using the ViGEM builds.


I've found that in dolphin the vibration loop will occur every time a vibration happens in game as long as you bind both motors with the OR clause. If you only bind 1 motor, then the vibration does stop.

**Comment by Ryochan7** [comment] 2019-04-04 16:12
I have given up for now and disabled force feedback support in version 1.7.3. Other rumble functions in DS4Windows are still usable. This is not a problem caused by DS4Windows but the client library being used to interact with the ViGEmBus driver.

**Comment by teijiIshida** [comment] 2019-04-04 16:18
Any idea when the force feedback will be re-enabled in the future? I love force feedback and have no problem (at least on the games I played), so I reverted back to 1.7.2 but missed out all of the new changes in 1.7.3.

**Comment by apoklyps3** [comment] 2019-04-05 13:36
yeah...I'd rather have the rumble bug(it stops after a minute or so) than have it completely removed

**Comment by Ryochan7** [comment] 2019-04-05 16:49
This seems like a no win scenario. There would be massive complaints either way. Commenting the hooks out was easier for me so I opted to do that. Bringing back the hardware timeout would have required editing the repeat out and then testing it.

**Comment by mika-n** [comment] 2019-04-06 12:14
I created a pull request to workaround this stuck rumble motor issue using "brute force stop timer technique" (ie. ViGem driver has lost the rumble-0 event and client never receives it). 

The fix is not perfect but at least it guarantees that rumble motor is not permanently stuck in rumble state. In the worst case scenario, a rumble effect in a game is not exactly how it was designed because the motor is stopped too early but I think it is less annoying than stuck rumble motor. However, usually games keep on sending rumble events several times within 2 secs, so player often doesn't see anything unusual. Only when rumble-0 event is lost then the latest rumble effect may run 2 secs too long.

**Comment by nefarius** [comment] 2019-04-09 18:47
@mika-n I shall try your Dolphin route now, thanks for the summary.

**Comment by Ryochan7** [comment] 2019-04-19 11:28
Version 1.7.4 is now out and this problem should be resolved.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.7.4/DS4Windows_1.7.4_x64.zip

**Closed by Ryochan7** 2019-04-19 11:28 UTC
