### ISSUE TITLE
Virtual Mouse and Keyboard Drivers (Valorant )

### ISSUE THREAD

**Issue by TheLadForTheJob** [Ryochan7/DS4Windows#1629] opened 2020-12-04 14:14 UTC
Hi, I was wondering if there was a way you could add a virtual mouse and keyboard driver like rewasd does so that games like valorant that block emulated inputs could work? I know it might be a bit of a big ask.

**Comment by Ryochan7** [comment] 2020-12-04 18:00
That pretty much is what the discussion in issue #943 is about. If you check out the code in the virtualkbm_refactor branch, the work is almost completely done. The big problem is that the changes require a custom, updated version of the VMulti driver. Windows requires drivers to be properly digitally signed and that feature is behind a pay wall. I think the going rate when I looked at it last was around $200 USD. I don't have the means to pay the fee so there is nothing to do at this point.

https://github.com/Ryochan7/DS4Windows/tree/virtualkbm_refactor

**Comment by Ryochan7** [comment] 2020-12-10 16:25
It is confirmed that this is a problem with the current build of Cyberpunk 2077.

https://reddit.com/r/SteamController/comments/kaca39/cyberpunk_2077_has_blocked_all_virtual_inputs/

**Comment by Ryochan7** [comment] 2021-01-08 20:11
Thanks to the discovery of the tool SignHackTool, I might consider looking into this again. It might not help out other people but it at least allows me to not have to run Windows in Test Mode anymore. Now I have a way to install my custom HidGuardian and VMulti driver normally. In theory, those drivers could work on other systems but it might not be a good long term plan in regards to support.

https://github.com/thehlopster/SignHackTool

**Comment by Ryochan7** [comment] 2021-01-09 21:41
I guess at some point I will probably have to officially hard fork VMulti.

**Comment by TheLadForTheJob** [comment] 2021-01-10 13:15
Great to see the progress man! You could possibly make like an experimental
download, where you are warned of "using it at your own risk".

**Comment by Ryochan7** [comment] 2021-02-02 23:34
Too many hoops for the most part. Also, it would not work in Valorant no matter what as Windows would have to run in Test Mode. The game actively refuses to run if it detects that Windows is running in Test Mode.

The fake driver signing process using SignHackTool does not work on some systems apparently. It would have been nice to eliminate some of the hoops for pushing driver changes. If I would want to be able to release a proper driver now, it looks like I would have to set up a small legal company via an LLC or sole proprietorship.

**Comment by Ryochan7** [comment] 2021-04-28 16:05
Some recent discussion in the HID-Wiimote issue tracker got me thinking about this again. I have not looked at the vmulti code in a while but attempting to port the driver to UMDF might be worth looking in to. I would hope there is no obstacle other than time for getting it to work. There would be far fewer hoops to jump through to get a functional installable driver if vmulti could be converted to a UMDF driver.

https://github.com/jloehr/HID-Wiimote/issues/5

**Comment by TheLadForTheJob** [comment] 2021-04-28 17:16
Im not very knowledgable in this field, but from what i read, it sounds
promising. Fingers crossed everything goes to plan, wish you the best of
luck.

**Comment by Ryochan7** [comment] 2021-04-28 19:36
Going to likely be using info gathered from Nefarius for the most part. The major resource will be the DsHidMini driver since it is a UMDF driver.

https://github.com/ViGEm/DsHidMini

From a brief look at the current vmulti code, it looks like the current vmulti code does utilize calls only available to KDMF drivers. Maybe there is a way to work around it but the current code cannot be ported straight to UMDF.

https://github.com/Ryochan7/vmulti

**Comment by Ryochan7** [comment] 2021-04-29 16:30
Seeing the many reasons I have tried to avoid driver development. Confused by a lot of it.

Based on the little bit of work done so far, it looks like making a functional virtual KB+M driver is possible using UMDF. The vhidmini2 project seems like it will be the main reference for such a project; also seeing several portions of code that are used in the current vmulti code. Changed the code a bit to expose a virtual KB using the same HID report descriptor in my vmulti fork. Don't have a way to interact with it yet since I don't understand how to pass data to the device properly.

https://github.com/microsoft/Windows-driver-samples/tree/master/hid/vhidmini2

**Comment by Ryochan7** [comment] 2021-04-30 13:52
Made some very minor progress. Finished last night with finally getting a packet successfully processed and having the virtual keyboard hold down the Q key. Took the minor victory and stopped there for the night. At least that confirms the idea should be feasible.

**Comment by TheLadForTheJob** [comment] 2021-04-30 19:17
Awesome, thanks for the update!

**Comment by Ryochan7** [comment] 2021-05-01 21:03
Update. Got a virtual mouse working. Ended up porting the vmulti library work that I did previously to interface with the new driver. Got WPP Tracing somewhat figured out so I can somewhat debug what is happening in the driver now. Now everything is at a point where I can actually test out performance using my small Steam Controller mapper.

As it is, even in an unoptimized Debug state, using a UMDF driver and libraries is faster for sending virtual KB+M events than using SendInput. Performance would likely be much better when using more optimized Release settings.

**Comment by Ryochan7** [comment] 2021-05-03 16:28
Less of an update this time. Got some multimedia keys working. Those have to be exposed through a second HID collection and that is the way it works with my real keyboard. Currently, 16 keys are supported and they are split into two bytes. I should probably change that a bit as my real keyboard exposes more key codes and uses almost 3 bytes in its HID collection for multimedia and power keys; there are 3 bits of padding at the end. Also, the library should likely be changed to unify the key codes and maybe pass the used key values as an uint rather than 2 separate bytes.

The next real challenge is obtaining the OV Code Signing Certificate needed to sign the driver so it can be properly installed on other people's machines **without using Test Mode**. The verification process is a lot less strict for an OV Code Signing Certificate and luckily user-mode drivers can get away with only needing that level of certification; a EV Certificate is required for all kernel-mode drivers and the verification process for obtaining an EV Certificate was the biggest hurdle before.

It looks like a one year OV Certificate can be obtained for around $100 USD. That is currently doable.

**Comment by Ryochan7** [comment] 2021-05-03 17:14
Starting to backup progress. No driver code yet as it is still a mess. As you can see, most of it is just a port of my vmulti related forks

C++ library for interfacing with driver
https://github.com/Ryochan7/FakerInputDll

C# library for using C++ routines
https://github.com/Ryochan7/FakerInputWrapper

**Comment by Ryochan7** [comment] 2021-05-04 04:16
Trimmed code and got the driver code in a new project

https://github.com/Ryochan7/FakerInput

**Comment by Ryochan7** [comment] 2021-05-05 14:00
Got an order for an OV Code Signing Certificate going now. Hopefully the verification process won't take too long.

I am not going to worry about making DS4Windows work with the test driver until after this whole process is complete. There is also no timeline for when DS4Windows will support the new driver.

As for driver progress, none has been made since the last update. I was holding off on it but I might need to add an absolute mouse style device to the collection of virtual devices; reWASD does not provide support for one in its driver. I also still need to work out what extra codes the multimedia keyboard should expose.

**Comment by Ryochan7** [comment] 2021-05-06 20:08
Absolute mouse support has been added. Other than that, I have evaluated installer systems. It looks like using either Inno Setup or Wix (using Wix#) will fit the bill. No progress on the certificate yet.

**Comment by Ryochan7** [comment] 2021-05-09 20:24
Got some correspondence but still going through the process of getting that checkmark. Too bad that I will be away from my Windows PC most of this coming week. There is no chance for a driver release this week no matter what unfortunately.

Also, I should have looked into it before but I need to nail a support target for UMDF. For now, UMDF 2.0 will be the baseline for compiling. According to the Microsoft docs, UMDF 2.0 support is only available for Windows 8.1 and later. Again Windows 7 users get the shaft.

https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/umdf-version-history

**Comment by Ryochan7** [comment] 2021-05-12 13:39
The certificate has supposedly been granted. Can't do anything about it until Monday since I am away from home. Will have to get some form of installer ready next week. I am leaning towards using Wix.

I was using the driver on my system with a Steam Controller mapper to play some Might and Magic 6. I might finish the game this time.

**Comment by Ryochan7** [comment] 2021-05-17 01:42
Okay. Dog sitting is over. Now back at home.

**Comment by Ryochan7** [comment] 2021-05-17 21:21
Don't think I'll get back into this later. All I can report is that I now have the certificate and I can sign and install the driver without warning prompts popping up. Windows accepts the certificate and I could install the driver outside of Test Mode; still using Test Mode right now for my customized HidHide.

**Comment by Ryochan7** [comment] 2021-05-19 15:05
Not really liking Wix. Had to do a lot of searching for getting some features to work since the official documentation is not good. Anyway, I finally have a test installer that does its job. It still needs testing for a lot of scenarios. Not sure about what the update process would be like. MSI should supposedly perform an uninstall of the previous version before running the install for a new version but I am not so sure.

I am already finding some inherent limitations with the driver infrastructure if multiple applications would be used for KB+M support; I am only expecting DS4Windows to work with it ever and I don't expect other mappers to try to use it at the same time. As it was with vmulti, virtual keyboard and mouse state are stored in the client library code and the whole state is sent to the virtual device in one shot. A more versatile approach would have to be to send individual updates for new events and then have the driver context update the virtual device state accordingly. Not really going to worry about it now but it is something to consider in the future.

Also, people might not care but I finally beat Might and Magic 6 last night. I will probably replay Might and Magic 7 as I got lost and quit when I played it previously.

**Comment by Ryochan7** [comment] 2021-05-19 17:41
Finally tested running Windows with TESTSIGNING off and Windows still loads the driver and it works. I had to uninstall my custom HidHide to properly test this as my custom version would have to run in Test Mode.

**Comment by Ryochan7** [comment] 2021-05-19 19:41
Finally changed some project titles and uploaded the current installer code

https://github.com/Ryochan7/FakerInputSetup

**Comment by turgayozgur** [comment] 2021-05-19 20:04
Hi @Ryochan7, thank you for your awesome work. I am wondering how you interact with the driver. How did you say "press on Q button" to the driver? Can you give any code example or something?

**Comment by Ryochan7** [comment] 2021-05-19 20:14
I don't have any sample code up yet. I am only using the driver in my small Steam Controller mapper which I have not posted an update for yet either. That program uses a C# wrapper for sending keyboard and mouse events to the driver.

https://github.com/Ryochan7/FakerInputWrapper/blob/master/FakerInputWrapper/KeyboardReport.cs

**Comment by Ryochan7** [comment] 2021-05-19 21:49
Messy commit but here is one.

https://gitlab.com/ryochan7/steam-controller-test/-/commit/a22e960f560273425773f3a25fda11f25ee98924

Short pseudo sample

```
// Import namespace from FakerInputWrapper.dll assembly
using FakerInputWrapper;

// Library connection object and Keyboard report object
private FakerInput fakerInput = new FakerInput();
private KeyboardReport keyboardReport = new KeyboardReport();

// Connect to FakerInput system device
fakerInput.Connect();

// Set KeyDown for Q key in report
keyboardReport.KeyDown(KeyboardKey.Q);

// Send report to virtual keyboard
fakerInput.UpdateKeyboard(keyboardReport);

// Set KeyUp for Q key in report. Removes key from state
keyboardReport.KeyUp(KeyboardKey.Q);

// Send updated report to virtual keyboard
fakerInput.UpdateKeyboard(keyboardReport);

// Reset virtual keyboard state and send to device. Pretty sure I added a method to reset the state object.
// Just opted to use a blank report instance here
fakerInput.UpdateKeyboard(new KeyboardReport());

// Close connection to system device and free memory
fakerInput.Disconnect();
fakerInput.Free();
```

**Comment by turgayozgur** [comment] 2021-05-19 21:59
Thank you. I have checked it out. I should try with my own implementation.
Does the driver have to be digitally signed?

**Comment by Ryochan7** [comment] 2021-05-19 22:06
There is no public release of the driver yet. You can compile the driver on your end if you want. You would have to run Windows in Test Mode and install the driver with devcon.exe though.

The installer is mostly finished at this point. I still wanted to look into the multimedia keyboard HID collection again and maybe alter some values before I consider the driver finished. Trying to get some last API breaking changes done before I have to worry about compatibility problems between driver updates.

**Comment by Ryochan7** [comment] 2021-05-28 07:04
Been a while since the last update. Haven't had much of a chance to push out some driver changes. Finally got API version checks somewhat implemented.

The more important update is that the `virtualkbm_refactor` branch has been updated to the latest code base and can now use FakerInput rather than VMulti. One obvious refactor that I would want to do is perform a single sync call for all device reports rather than perform one for each KeyUp or KeyDown event. Even with that, using the driver is snappier than using SendInput. 

https://github.com/Ryochan7/DS4Windows/commit/c0bb0ad9a23de38c32b9ca6d51ff2adcdda67501

A public test installer for the driver should get published soon.

**Comment by Ryochan7** [comment] 2021-05-28 17:27
A bit early but here it is. I am just going to upload the current installer to Google Drive for now. Later installers will be posted to GitHub. The current driver is marked as version 0.0.0.1 and should be considered an early BETA. The driver version will likely get bumped up to 0.0.1 once integration in DS4Windows has been completed. Very few changes will likely happen in between those two versions though.

FakerInput_0.0.0.1_x64.msi
https://drive.google.com/file/d/1DdgeBHr_ehi31jm5jeAGuDZpMglwuLU5/view?usp=sharing

This version of the driver is signed. That means you **do not** need to run Windows in Test Mode. You will have to compile DS4Windows with the `virtualkbm_refactor` branch code to use it currently. Also, you would have to launch DS4Windows with the cmd arguments `-virtualkbm fakerinput` to work with the driver. Otherwise, SendInput will be used. The Log will show which KBM event handler is being used. A cmd override will still be available later but DS4Windows should be changed to attempt to find and connect to FakerInput first if available.

**Comment by Ryochan7** [comment] 2021-05-31 02:31
I think this is about ready to merge to the `jay` branch. DS4Windows now has a working download for the driver installer. Some minor mapping changes have been made. Also, the pre-release driver installer is now on GitHub.

https://github.com/Ryochan7/FakerInput/releases/download/v0.0.0.1/FakerInput_0.0.0.1_x64.msi

**Comment by Ryochan7** [comment] 2021-05-31 04:38
The merge has been done. So this ended up being about a one month long experiment all together. Not sure when I will get around to making a new DS4Windows release yet. Pretty sure there are some other posted issues I have not addressed yet because I was too busy working on the driver experiment.

https://github.com/Ryochan7/DS4Windows/commit/12d413002279a84a7ee481dd650e538ba35a838c

**Comment by Ryochan7** [comment] 2021-06-02 21:38
For anyone who might be trying this early, I just introduced a breaking change to the driver. I had to update the driver exposed VID and PID since it still contained the same values from the vhidmini2 project; the new values should be safe. There has been a commit to DS4Windows to change the driver search with the updated info.

https://github.com/Ryochan7/DS4Windows/commit/4be23f3e775e7f7a1fd6ff3142d22f232590689e

I don't plan on releasing a newer pre-release driver installer so I would recommend that you use a previous commit of DS4Windows. I am hoping to finally decide to get version 0.0.1 of the driver out there soon.

**Comment by TheLadForTheJob** [comment] 2021-06-03 00:39
so how exactly would i go about trying this early?

**Comment by Ryochan7** [comment] 2021-06-03 02:27
You would have to compile DS4Windows from the current Git code. I ended up posting a new pre-release installer. I would probably wait until the next DS4Windows release before trying out the driver though. Ended up having to use the pre-release window to break compatibility. Not going to have the luxury once version 0.0.1 is released.

The breakage originally started from me wanting to test the Upgrade path routine for the installer file. I had to change some aspects of the build script for the installer and I spotted the VID and PID oversight. The driver already had a unique GUID associated with the driver and for the WPP trace provider.

There are a couple of limitations that I have come across with UMDF that I am just going to have to live with. Not being able to change the exposed device instance path of the child devices kind of stinks especially due to how Windows handles the defaults. It is doable when making a KMDF driver and I see the portion of vmulti that takes care of that task. The necessary IRP request does not get passed down to UMDF drivers.

**Comment by Ryochan7** [comment] 2021-06-04 03:03
I cannot be bothered to worry about it much more. Version 0.1 of the driver is out. Probably going to release a new version of DS4Windows soon. 

https://github.com/Ryochan7/FakerInput/releases/tag/v0.1.0

https://github.com/Ryochan7/FakerInput/releases/download/v0.1.0/FakerInput_0.1.0_x64.msi
https://github.com/Ryochan7/FakerInput/releases/download/v0.1.0/FakerInput_0.1.0_x86.msi

**Comment by Ryochan7** [comment] 2021-06-04 20:59
Likely a big mistake but DS4Windows 3.0.7 is now out. This issue can now **finally** be considered resolved.

https://github.com/Ryochan7/DS4Windows/releases/tag/v3.0.7

**Comment by TheLadForTheJob** [comment] 2021-06-05 15:11
Absolutely brilliant job, done some messing about with settings and holy
shit it is way better than rewasd. Really appreciate all the work you put
into this man and all the best to you in the future!

**Closed** 2021-07-03 03:02 UTC

**Comment by Ryochan7** [comment] 2021-07-26 16:20
Looks like a recent Valorant update broke this. Fantastic. Found out about an issue from a recent reWASD tweet.

The game will now only work with the primary mouse input. It will actively lock any other exposed mouse devices for use even in Desktop mode. The main workaround now is to unplug your real mouse so the game will leave the virtual mouse device usable. It looks like you can do this after the game is already loaded. It looks like reWASD tried to work around the Valorant update by using an Interception style driver to re-route events to the primary mouse device event queue. That is a very slow approach and it didn't work out for me when I tried it in the past. So much pain.

https://twitter.com/reWASDmapper/status/1414623086029119491

https://github.com/oblitum/Interception

**Comment by TheLadForTheJob** [comment] 2021-07-26 16:23
I think this has been happening for some time. Not sure if the bug you're
talking about is a different one than I'm thinking about but try moving the
gyro mouse while the game is loading up and keeping your main mouse
completely still.

**Comment by Ryochan7** [comment] 2021-07-26 16:31
The first tweet from reWASD about the Valorant update was dated May 25 so it technically became an issue right before the driver was officially released; what great timing on Riot Games part (maybe on purpose?). The Riot Vanguard service is the culprit and it is a deliberate "security" feature. There is no bug.

I am not sure if that would work. I can give it a shot.

**Comment by TheLadForTheJob** [comment] 2021-07-26 16:35
Yeah I always just moved the gyro while starting the game and it
consistently works. Haven't played much recently but I believe that is how
the game decides which mouse is going to be the active one. They seem to
have a specific device to be your 'default' which is the one that gets
whitelisted if you don't move any mouse during launching. If you move
another device then the 'default' gets overridden. That's my guess as to
how the system works at least.

**Comment by Ryochan7** [comment] 2021-07-26 16:54
Rebooted and tested the theory. It does work. It still stinks that the real mouse won't work even when you alt-tab out of the game and enter Desktop mode. That is pretty invasive.

**Comment by TheLadForTheJob** [comment] 2021-07-26 16:56
Yeah I had to rebind some keybinds When setting it up and it was a terrible
experience. At least it "works" tho.
