### ISSUE TITLE
nacon revolution unlimited does not work!

### ISSUE THREAD

**Issue by asp0909** [Ryochan7/DS4Windows#856] opened 2019-10-18 02:18 UTC
Buy a nacon revolution unlimited, and I have been surprised that it does not work with DS4 ... I have tested it by cable and with its wireless USB receiver, and it does not work in any way ... I am doing something wrong, or definitely not is it compatible? .. it would be great if you can make it work with ds4 please, since it is a very good controller.............

Revolution Unlimited Pro Controller (Vendor: 146b Product: 0d08)

DS4  Version 1.7.17

[log.txt](https://github.com/Ryochan7/DS4Windows/files/3742157/log.txt)

**Comment by mika-n** [comment] 2019-10-18 06:26
Try the following test build with an experimental Nacon Revolution Unlimited support.  Just replace the DS4Windows.exe file in your current installation with the file in ZIP file. Re-use all other files.

[DS4Windows_NaconRevolUnlimitedTest1.zip](https://github.com/Ryochan7/DS4Windows/files/3742519/DS4Windows_NaconRevolUnlimitedTest1.zip)

**Comment by asp0909** [comment] 2019-10-18 15:19
Hello Friend
 .exe does not work. does not start ds4

**Comment by mika-n** [comment] 2019-10-18 15:34
Sorry. Accidentally the prev version was a debug build which doesn't work out of the box. Here is a version which should work and contains also the latest version of Win23TaskScheduler library used by the latest devel version.

[DS4Windows_NaconRevolUTest2.zip](https://github.com/Ryochan7/DS4Windows/files/3744662/DS4Windows_NaconRevolUTest2.zip)

**Comment by asp0909** [comment] 2019-10-18 16:06
gyroscope ok
buttons and levers ok
rumble ok
touchpad ok
hide ds4 controler does not work
Lightbar Batery has some bugs.
the basics are great ... thank you very much friend ... can I continue updating ds4 to the following versions or should I keep the exe that you gave me?

**Comment by mika-n** [comment] 2019-10-18 16:20
Okey. Great. 

HideDS4Controller issue probably doesn't have anything to do with this the new gamepad type. The issue is probably something to do with general exclusive mode issues. See the following page for more info: https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Lightbar colors and Battery readings are often a bit of a problem with non-official DS4 gamepads. It is difficult to fix and debug that issue with an actual hardware, so I guess those issues won't be fixed because it is not a show stopper anyway.

You can continue to use the supplied test version until the next official release contains that support. Just keep eye on releases web page and "What is New" changelog text there. When you see that a new release mentions that it supports Nacon Revolution Unlimited gamepad then you switch back to the official version. The version you now have is based on official V1.7.17 version with an additional support for the new controller type.
https://github.com/Ryochan7/DS4Windows/releases

**Comment by asp0909** [comment] 2019-10-18 16:24
udp server does not work ...
I will continue testing and say it here

**Comment by mika-n** [comment] 2019-10-18 16:48
hmmm... UDPServer feature should be identical in the test version as the official release. I just tested UDPServer using the test version and it worked just fine (used PadTest tool to connect to the UDP server). How did you test it? Did you get some errors in DS4Windows Logs tabpage when UDP server was enabled? Have you checked using "netstat -na" shell command to verify that the configured UDP port goes to listen state?

**Comment by asp0909** [comment] 2019-10-18 17:12
I have tried it with the udp port of the citra emulator, and there is no response from the touchpad,

I have also tested the gyro function for the cemu emulator, and there is no answer

**Comment by mika-n** [comment] 2019-10-18 17:28
Try testing with the "PadTest_1011.zip" tool (part of CemuHook toolkit).
https://cemuhook.sshnuke.net/padudpserver.html

Here UDPServer works with official DS4 gamepad, but if touchpad and gyro works in DS4Windows in a normal way (ie. you can map those axies) then it should work with UDPServer also. Do you get any gyro response with PadTest tool? Remember to set the same UDP port you have in DS4Windows settinsg and tick "Request data 1" (or 2) option to read data from controller 1.

**Comment by asp0909** [comment] 2019-10-19 00:21
hi......
and started dsu controller test and does not detect the nacon controller, also tested my dualshock 4 and if it detects it well ... then the controller nacon revolution. can't get the udp server function ... I must also tell you that the modified .exe you gave me, has problems at the start of windows, a white screen appears and the window cannot be minimized

**Comment by asp0909** [comment] 2019-10-19 00:30
![Captura](https://user-images.githubusercontent.com/29218473/67135282-c499f000-f1dd-11e9-9a3a-2ff114e73196.PNG)

**Comment by asp0909** [comment] 2019-10-19 00:32
look ... the controller below is the nacon..and you can see that it doesn't register id

**Comment by mika-n** [comment] 2019-10-19 10:17
Try to run a new version of "DS4Windows_DeviceDetect8.zip" debug version. This debug version now tries to support NaconRevolutionUltimate gamepad also, but while it is trying to use the game pad there will be tons of debug log messages in DS4Wnidows Logs tab page. Please provide the content of that log file.

https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

The missing ID is a clear sign of problem how the non-official gamepad communicates with a PC. It is not 100% identical as an official DS4 gamepad or other 100% compatible devices. 

Some custom gamepad manufactures have a nasty habit of supporting DS4 protocol on PS4 console, but when the gamepad is connected to a PC then the gamepad reverts back to so called "PC-friendly gamepad" mode. This mode doesn't do all things in the same way as an official DS4 gamepad when connected to a PC. In practice the gamepad sends a bit different data packets to PC or the gamepad doesn't switch to communicate in "PS4 mode" the same way as DS4 gamepad does in PC.

The "DeviceDetectDebug" version linked in the DS4Windows Wiki page tells us more details about the gamepad communication protocol.

I'm sure there would be a way to support these nasty "PC-friendly only" gamepads in PC but because those may need some non-standard (compared to DS4 gamepad) initializations routines in PC it may be a difficult to do it without having an actual hardware. Someone with one of those nasty gamepads should debug this issue.

**Comment by asp0909** [comment] 2019-10-19 15:54
hello mika

this is the log

[log.txt](https://github.com/Ryochan7/DS4Windows/files/3746869/log.txt)

**Comment by mika-n** [comment] 2019-10-19 16:38
```
19/10/2019 10:45:45 a. m.: DEBUG: readSerial. Trying to read serial# from \\?\hid#vid_146b&pid_0d08&mi_03&col01#7&29addd37&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
19/10/2019 10:45:45 a. m.: DEBUG: readSerial. Reading serial# from InputReport buffer Len=64
19/10/2019 10:45:45 a. m.: DEBUG: readSerial. ERROR. Failed to read serial# as HID FeatureData. Using a dummy MAC code
19/10/2019 10:45:45 a. m.: DEBUG: findControllers. idx=1 IsValidSerial=True  Serial=00:00:00:00:00:10
19/10/2019 10:45:45 a. m.: DEBUG: findControllers. idx=1 Using device \\?\hid#vid_146b&pid_0d08&mi_03&col01#7&29addd37&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  metainfo.name=Nacon Revol Unlimited
19/10/2019 10:45:45 a. m.: DEBUG: findControllers. idx=1 OK. DS4Win uses the device as input source
```

The log file confirms that there are issues in the handshaking process of the Nacon Revolution Unlimited controller. The log file shows an error message when DS4in app tried to read a gamepad MAC identifier (the ID shown in DS4Win Controllers lists). This is usual symptom in those nasty "PC-friendly only" controllers which don't behave in PC exactly the same way as an official DS4 gamepad.

However, the debug version tries to do additional things with those controllers. For example, it uses a dummy MAC identifier and tries to handle incoming data packets a bit differently if the debug version detects that the gamepad doesn't send standard DS4 data packets to PC.

If you run the debug version without the another DS4 gamepad (I guess you are using Sony WA BT adapter device) and try to press buttons and move stick axis of the Nacon gamepad then are there any additional messages in a logfile? It is best to run these tests using just one controller at the time (ie. use just Nacon gamepad) because otherwise the logfile shows messages from two controllers and it just makes the interpretation of the logfile more difficult.

**Comment by asp0909** [comment] 2019-10-19 17:04
sorry...look!
[new_log_nacon_only.txt](https://github.com/Ryochan7/DS4Windows/files/3746965/new_log_nacon_only.txt)

**Comment by mika-n** [comment] 2019-10-19 17:13
Hmmmmm... When you open "Controller Readings" tab page in profile editor then do you see any activity when you press buttons and move sticks?  If not then the gamepad must have a different communication logic in PC than standard DS4 gamepad. In that case the gamepad is not supported by DS4Windows app unless someone with the same kind of gamepad debugs it and tries to find out why and how the gamepad communication differs from standard DS4 gamepad. Sorry.

**Comment by asp0909** [comment] 2019-10-19 17:16
in "Controller Readings" the nacon controller responds well and everything works

**Comment by mika-n** [comment] 2019-10-19 17:34
Okey. But now I'm a bit confused what is the actual problem. Can you map buttons and axies in DS4Win profiles and can  you see the re-mapped output in Joy.cpl controlPanel or in html5gamepad.com webpage?  
Can you use touchpad of the controller to move a mouse (if you have "use touchpad for mouse" option enabled)?
Is gyro showing any activity in ControllerReadings tab page? And can you re-map gyro axies to buttons or use "Gyro steering wheel emulation" feature to re-map gyro to left or right stick?

Or did you mean that just the UDP server feature doesn't work with Nacon gamepad controller but it works with an official Sony DS4 gamepad?

**Comment by asp0909** [comment] 2019-10-19 17:42
in html5gamepad.com does not recognize the controller ... but, in ds4 controller readings apparently it shows normal operation readings ... gyro and touchpad function does not work in emulators,

**Comment by asp0909** [comment] 2019-10-19 17:46
the gyro and touchpad function works well assigned to the windows mouse ... what does not work is udp server

**Comment by asp0909** [comment] 2019-10-19 17:58
new data ... with the .exe device detected ... now udp server works perfect in emulators ... the mac is detected as 00.00.00 but it seems to work

**Comment by mika-n** [comment] 2019-10-20 12:20
> new data ... with the .exe device detected ... now udp server works perfect in emulators ... the mac is detected as 00.00.00 but it seems to work

What do you mean by "with the .exe device detected"?  Do you mean the latest DS4Windows_DeviceDetectDebug9.zip app version linked in the following web page?
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

And when you said that MAC is detected as "00.00.00" do you mean that emulator shows that macid value or DS4Windows? In DS4Windows the MAC should be 00.00.00.00.10 if the gamepad didn't report the MACID properly. That 00.00.00.00.10 is just a dummy random code and not a real mac identifier.

Are you using USB or BT connection with Nacon gamepad controller? I guess you use USB cable connection. Does the gamepad work over BT connection (using the DeviceDetectDebug9 version)?

Anyway. It is a bit strange if the previous debug version and Nacon gamepad didn't work with UDPServer because there has not been any major changes in UDPServer functionality for ages. The latest DS4Windows_DeviceDetectDebug9 has exactly the same UDPServer code than all other previous debug versions. 

The official release of DS4Windows does NOT have Nacon Revolution Unlimited Pro support (yet, so it explains why that that version doesn't show any activity over UDPServer with NaconRevolUEPro controller.

**Comment by asp0909** [comment] 2019-10-20 19:05
hi....

All tests are on BT adapter.
the mac 00.00.00 of the nacon controller is shown in everything the control detects

**Comment by asp0909** [comment] 2019-10-27 03:24
hello

gyro function does not work in cemu emulator
ds4 v1.7.20
I also understood that the hide function is necessary for this controller, and it is not working ... if there is any alternative to activate hide controller, please tell me, it is necessary!

**Comment by mika-n** [comment] 2019-10-27 09:19
> gyro function does not work in cemu emulator ds4 v1.7.20

But does the NaconRevolUPro work in DS4Windows app and as locally in your PC? Can you see the "xbox360 gamepad controller" (virtual output controller) in JOY.CPL controlPanel applet? Run joy.cpl command or click "Control Panel" link in DS4Windows Settings tab page. Can you see any activity in ControllerReadings tab page of DS4Windows?

What do you see in Logs tab page?

Did you get cemu to work with DeviceDetect debug version of DS4Windows? The UDPServer functionality is 100% identical in the debug version and in the official version. 

Download the "PadTest_1011.zip" file from CemuHook web site and test UDPServer connection to DS4Windows app by using this test app. Does it work? Remember to tick "Request Info" AND "Request data" checkboxes for the correct controller# in PadTest app (or tick them all).
https://cemuhook.sshnuke.net/padudpserver.html


Anyway. One potential issue may be that the NaconRevolUPro doesn't return any real MAC device identifiers (or at least it cannot be read by using the same technique as with official ds4 gamepad). The end result is zero 00:00:00:00:00:00 MAC addresss. Maybe Cemu ignores devices with undefined MAC addresses? I will try to look into it. The problem is that I don't have CEMU (or I can download the app, but don't have any emulator images to test run it. Are there any demo images available somewhere?).


> I also understood that the hide function is necessary for this controller, and it is not working ... if >there is any alternative to activate hide controller, please tell me, it is necessary!

Please read through the following Wiki page. It explains the exclusive mode and talks about an alternative solution if you cannot get exclusive (=HideDS4Controller option of DS4Windows app) mode to work in your PC. The alternative solution is to uncheck HideDS4Controller option AND to install HidGuardian device driver.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#ds4windows-logs-tabpage-complains-that-exclusive-mode-failed-what-it-means-and-what-to-do-now

HidGuardian installer:
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer

However, because you have a custom DS4 gamepad controller you have to tweak AffectedDevices sysreg entry of HidGuardian driver to make it to recognize your custom controller (=different hardware VID/PID identifier than an official ds4 gamepad. By default HidG looks for official ds4 gamepads only). Here is a post which briefly explains what is this AffectedDevices sysreg entry in HidGuardian and how to tweak it to enable/disable a physical gamepad to be recognized (or not to be recognized) by the hidg driver.
https://github.com/Ryochan7/DS4Windows/issues/669#issuecomment-487302990

**Comment by mika-n** [comment] 2019-10-27 19:38
@asp0909   Please try the latest DeviceDetectDebug version (DS4WindowsDebug.exe). 

This new debug version is based on V1.7.20 official version, but it has a new feature for those gamepads which don't return a valid MAC address or the address cannot be read in the same way as with an official DS4 gamepad. 

The MAC address will be based on device type, HID (usb) channel and port number. This logic is not universally unique between the same kind of controllers, but it does generate unique values at runtime even when more than one identical gamepads are connected at the same time. The generated MAC address remains the same between re-connections as long you connect the gamepad into the same USB port or BT receiver. This makes it possible to use link-to-profile feature, calibration of 360-steeringWheelEmulation is bind to a certain gamepad and UDPServer doesn't report the gamepad as in "disconnected" state.

So, please download the linked debug ZIP file and run the DS4WindowsDebug.exe executable and please provide the logfile. Does this version work with Cemu and UDPServer?
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by asp0909** [comment] 2019-10-27 20:06
Hello Friend
and installed the latest Device Detect Debug version that you told me and now ...
gyro ..... ok
udp .... ok
mac id .... ok
It is almost perfect now just need to hide the original nacon driver because it gives many problems .... so that the controller can use all its functions. it must be connected in dualshock 4 mode to the pc ... since in simple mode, it is only xnput and gyro and touchpad are turned off ... then the following is the hide option ... the rest I think is ok
![Captura](https://user-images.githubusercontent.com/29218473/67640892-50410a00-f8cb-11e9-8cc2-bad844c84f8b.PNG)

**Comment by asp0909** [comment] 2019-10-27 20:08
now a mac id is generated .... before it only gave 00.00.00.00..seo nothing

**Comment by asp0909** [comment] 2019-10-27 20:12
look ... it's great!

![Anotación 2019-10-27 151147](https://user-images.githubusercontent.com/29218473/67640989-3522ca00-f8cc-11e9-99b9-2e385f815de9.png)

**Comment by asp0909** [comment] 2019-10-27 20:28
I must learn to use HIDGardian

**Comment by mika-n** [comment] 2019-10-27 21:47
Okey. Sounds great. I will test this new MAC generation logic for problematic gamepads to verify if the value remains the same after PC is rebooted or does it stay the same only until PC is rebooted the next time. 

There must be someway to read the MAC address from these non-official DS4 gamepads also, but for some reason DS4 logic doesn't work with all 3rd party gamepads. At least all gamepads with BT connection should have a unique MAC address. But for now the usb channel/port logic does the trick good enough until better solution is found. You should continue to use the latest debug version until this new logic of generating missing MAC addresses is pushed into the official version.

If you have problems with HideDS4Controller option (if it doesn't work then it is PC environment specific issue and nothing can be done in DS4Windows side except those tips listed in Wiki documentation page). The alternative way of using HidGuardian is 100% guaranteed way to do it, but does require installation of additional HidGuardian device driver tool. And you have to manually add the required VID/PID hardware ID in AffectedDevices sysreg entry. You can see the hardware ID from the debug logfile and from DeviceManager.

**Comment by asp0909** [comment] 2019-10-27 21:58
mika..you can hide the original controller ... but it is no longer recognized by ds4 windows..ha ha ha ... it is confusing for my hidgardian

**Comment by mika-n** [comment] 2019-10-27 22:09
HidGuardian works basically using two sysreg entries: 
AffectedDevices = List of device VID/PID hardware IDs which will be monitored by HidGuardian and hidden from all apps EXCEPT from processes listed in WhiteList sysreg entry
Whitelist = List of process IDs HidGuardian lets to see the physical controller device. The process ID of DS4Windows should be listed here.

Naturally the process ID is different each time you reboot and re-start DS4Windows app, so you cannot list a fixed value in Whitelist sysreg entry. How to solve this? That's why DS4Windows installation folder has HidGuardHelper.exe app. DS4Windows calls this HidGuardHelper.exe each time the ds4win app is launched and the helper app adds the current process id of DS4Windows to Whitelist sysreg entry.

So, when you have launched DS4Windows then check HidGuardian Whitelist sysreg entry to see if the ds4win process ID is listed there. If not then there is something wrong in your environment. Maybe some permission issue and HidGuardianHelper.exe app fails to update the sysreg Whitelist entry?

**Comment by GroundMeat** [comment] 2019-12-15 13:53
DS4Win is also not detecting my Revolution Unlimited. I've tried uninstalling and installing the controller's drivers a few times, and it still doesn't work. Had to go through device manager, since just going into hardware, has Uninstall Device greyed out: 
![EWMMwRQ 1](https://user-images.githubusercontent.com/58891891/70863642-2ba2ff00-1f18-11ea-93b4-f7b9236a990e.png)

Don't know if having two instances has anything to do with that, I only have 1 controller:
![oMQJbEr 1](https://user-images.githubusercontent.com/58891891/70863649-3eb5cf00-1f18-11ea-93de-d3ea3014f952.png)

I also tried [DS4Windows_NaconRevolUTest2.zip](https://github.com/Ryochan7/DS4Windows/files/3744662/DS4Windows_NaconRevolUTest2.zip) as stated above, and it doesn't detect the controller either.

I've also turned off the Dualshock 4 support on Steam, and still nothing.

**Comment by mika-n** [comment] 2019-12-15 15:47
You can froget teh "DS4Windows_NaconRevolUTest2.zip" test version. The following Wiki page has a link to DeviceDetect debug version which generates a detailed log messages in DS4Windows Logs tab page.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by GroundMeat** [comment] 2019-12-15 16:05
Thanks, that Debug version actually found the controller. Here's the log from it.
[Log1.txt](https://github.com/Ryochan7/DS4Windows/files/3965124/Log1.txt)

**Comment by GroundMeat** [comment] 2019-12-15 16:06
Thanks, the debug version actually found the controller, and the trackpad even worked. Here's the log
[Log1.txt](https://github.com/Ryochan7/DS4Windows/files/3965127/Log1.txt)

**Comment by mika-n** [comment] 2019-12-15 16:23
Okey. Sounds great. Do you know if the gamepad has all or just some special features of an official DS4 gamepad? Lightbar/rumble motors/touchpad/gyro?  

Well, touchpad seems to be supported as you said, but how about other special features? Which one of those work or is even supported in the gamepad? 
How about normal buttons and LS/RS/L1/L2 analog sticks and triggers and normal buttons?

You seem to have two gamepad type of devices. The first one is vid/pid B58E/9E84 device, but it doesn't respond to any read and write messages DS4Windows gamepad tries to do with it. Eventually this gamepad is then dropped (force quite output thread indicates this).

```
2019-12-15 11:03:20 AM: DEBUG: EnumerateDS4. HID#17 Path=\\?\hid#vid_b58e&pid_9e84&mi_03&col02#8&3b55b712&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant headset  VID=0xB58E  PID=0x9E84  Usage=0x5  Version=0x100
2019-12-15 11:03:20 AM: DEBUG: EnumerateDS4. HID#17 unknown gamepad device. It may not be DS4 compatible, but trying to use it as potentially DS4 compatible gamepad device
2019-12-15 11:03:20 AM: DEBUG: sendOutputReport. ERROR. writeOutput failed. Force quiting output thread. LastErrorCode=1
```

The second gamepad seems to be the one working and has a nacon VID identifier 146B. The product ID is 0D10. Connection type seems to be USB. Is there BT support in the gamepad? How the debug log looks like with BT connection?

```
2019-12-15 11:03:20 AM: DEBUG: EnumerateDS4. HID#19 Path=\\?\hid#vid_146b&pid_0d10&mi_03&col01#7&2ec06ebc&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant game controller  VID=0x146B  PID=0x0D10  Usage=0x5  Version=0x100
2019-12-15 11:03:20 AM: DEBUG: EnumerateDS4. HID#19 unknown gamepad device. It may not be DS4 compatible, but trying to use it as potentially DS4 compatible gamepad device
```

Anyway. The official version doesn't support this variation of Nacon gamepad yet, but you can continue to use the debug version until the support is added to the official version. Just keep eye on "What's new" lines in releases page.
https://github.com/Ryochan7/DS4Windows/releases

Do you have a link to some online store to this gamepad? What is an official model name for the gamepad? DS4Windows already support number of Nacon Revolution gamepads, but the one you have seems to be yet-another Nacon variation. DS4Windows already supports Nacon Revolution v1, Revol v2, Revol v3 and Revol Unlimited Pro gamepads. I wonder what is the brand and model name of this PID 0x0D10 gamepad.

**Comment by GroundMeat** [comment] 2019-12-15 16:50
Can confirm that the Gyro does work. The controller doesn't exactly have a lightbar, but when I do change the color on DS4Windows, the controller equivalent changes too. The rumbles also work properly, from testing on DS4Windows.

The reason I thought it was supported is because of the [1.7.20 changelog](https://github.com/Ryochan7/DS4Windows/releases/tag/v1.7.20).

As for a link to an online store, [bought it from Amazon Canada](https://www.amazon.ca/Revolution-Unlimited-Wireless-Controller-Nacon/dp/B07NDCL3XB/ref=sr_1_1?keywords=Nacon+Unlimited&qid=1576428264&sr=8-1)

Here's the [Official Site](https://uk.nacongaming.com/product/revolution-unlimited/)

**Comment by mika-n** [comment] 2019-12-15 17:29
The change in V1.7.20 does add support to "Nacon Revolution Unlimited Pro" gamepad, but you seem to have a different revision of the gamepad. For example the log dump you provided shows a bit different HID/VID/PID identifiers, so Nacon must have released different revisions under the same model name.

Anyway. I will create a code change and pull request for the revision you have and make a note about it that it is a different revision of the same gamepad model.

The gamepad seems to have both USB and BT connections. Have you tried both connections types in PC? In some cases the gamepad identifier is different between USB and BT devices. Also, there seem to be different modes like "PS4 mode", "PS4 Advaned Mode" and "PC Advanced Mode". Those also may send different HID/VID/PID information (I have no idea how those modes of this Nacon gamepad are selected. Switch in the gamepad or some client app configuration thing?).

**Comment by mika-n** [comment] 2019-12-15 18:12
@GroundMeat  Created a code change for your Nacon device. Steam/Linux libSDL seems to refer to the gamepad as Nacon Revolution Infinite model name, so I used that name in the pull request. Keep eye on that name in releases/WhatsNew web page to see when the official release supports it. Until then you can keep using the debug version.

@Ryochan7  Ping about pull request.

**Comment by GroundMeat** [comment] 2019-12-15 21:20
Ahh, I pretty much use the controller wired. Only time I used its BT Dongle for Wireless was to try it out when I first got the controller. I've had the Nacon Revolution Pro V2 as well, and that one had the three modes, "PS4", "PS4 Advanced" and "PC" as well. The first is just a regular dualshock 4, the second is a dualshock 4 that you can customize with their software, and the third makes the controller into an Xinput controller. I believe the original Nacon Revolution didn't have the "PC mode". They were added from V2 onwards.

The mode I used the debugger detected the controller was "PS4 Advanced", just so I can have use of the handle buttons that where I mapped the face buttons.

Thanks, will keep an eye on the update.

**Closed** 2020-03-10 02:21 UTC
