### ISSUE TITLE
The Xbox 360 Virtual Controller has "No Driver Installed" after Turn off/Disconnect the ds4 Controller

### ISSUE THREAD

**Issue by OSRAGAMER** [Ryochan7/DS4Windows#1906] opened 2021-02-25 06:09 UTC
**Describe the bug**
from this Saturday, if i Disconect, or the idle time turn off the controller or random disconect, the Xbox 360 Virtual Controller change to a "No Drivers Installed", in this point, **the whole pc cant recognize new devices**, for example, if i disconect the Bluetooth dongle or the keyboard are no change in the Device Manager, and when reconnect dont recognize the device again, i cant restart or shutdown the pc, only a Forced Restart works, DS4Windows Crash moments later
i notice about this when i dont hear the "Disconnected Device" sound of windows, 
i try to fix this, reinstalling everything, DS4Windows to 2.2.1,Desactivate everything in HIDNinja, Uninstalling Vigem Bus from the respective Github repository, remove all non Present Devices, restart in Secure Mode, Delete Steam, really i get so streesed i dont know whats happening bro,

**To Reproduce**
1-Open DS4Windows
2-Conect the Controller/USB or BT
3-Stop the DS4Windows, 
4-done, 
now the Virutal Xbox 360 Controller still present and has no drivers, the pc is Stuck

**Expected behavior**
well, check the Virtual Xbox 360 Controller of DS4Windows, maybe is bugged

**Screenshots**
![image](https://user-images.githubusercontent.com/73681619/109109469-ffc60080-76fa-11eb-948f-026ff3ada223.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.1 (CUH-ZCT1)
 - OS: [Windows 10 Pro Insider Preview 21322.1000]
 - DS4Windows Version [2.2.1] /2.2.7 At Bug noticed 

**Additional context**
help bro

**Comment by Ryochan7** [comment] 2021-02-25 06:27
Ran into this same issue about a week ago. Unfortunately, the problem lies with ViGEmBus and I don't know what the root cause is. The only course is to reboot Windows. You will encounter a BSOD on shutdown.

https://github.com/Ryochan7/DS4Windows/issues/1597#issuecomment-779407414

Duplicate of issue #1597

**Comment by OSRAGAMER** [comment] 2021-02-25 07:02
Wow its my problem, just the same,

to avoid the "Stuck device state" whit "Use DInput Only" Ds4Windows works and not crash. 
i cant restart, keeps in the "Restarting" Screen, 

well i in line whit this issue.

**Comment by OSRAGAMER** [comment] 2021-02-27 04:55
Hi, maybe is not VIGEM Bus related, im not sure now
in my try to play in my pc, i delete everything, Vigem/Ds4windows, i use Rapr and i still find Vigem drivers, i delete to,
so i think is no Vigem and DS4windows trace present now,

i connect my GlapPlay and fine it start and ok, only wired, by this i dont use it,
but when i disconnect, i lose all my USB Devices, lights of the keyboard, mouse, BT Adapter are off, 
so i Force restart. and i open the device manager,  i connect the controller/disconnect and i get the same symptoms, 
because my glapplay are installed like a Xbox Controller, i have the same Bug,

![image](https://user-images.githubusercontent.com/73681619/109375855-a1795900-7885-11eb-98be-d02d91b4794b.png)

well i more confused, i cant play whit ANY controller if are emulated like a Xbox Controller, if i buy a Xbox Controller i will get the same Bug, im so streesed bro.

**Comment by OSRAGAMER** [comment] 2021-02-27 05:52
HI, i have good news, 
the controller is working OK, connect and disconect normal, 
and the emulated controller desconecct and reconnect normal,

**i change the driver to the emulated controller**

![image](https://user-images.githubusercontent.com/73681619/109376745-5ca4f080-788c-11eb-9d19-d70d250d2a3f.png)

i suppose i have the firts one installed, so for me, i chose that one are named in English, are four drivers there but i dont Know if is normal, 

Now, we can sai, its Not DS4windows Bug????

Now works like a charm.

**Closed** 2021-03-03 04:23 UTC
