### ISSUE TITLE
Crash Log

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#188] opened 2018-01-08 21:25 UTC
I would like to request that the program outputs a crashlog in the exe directory if ds4windows is not in the system program files directory. If it is, I would like for the crashlog to be put at the root of the drive that ds4windows is on.

Ive seen quiet a few silent crashes lately so that would help in helping you figure out the issue.

**Comment by Ryochan7** [comment] 2019-11-20 17:17
Almost two years later and I am just now looking into this. I am looking into adding NLog into DS4Windows to add some better form of logging support. NLog seems to work fairly well in the WPF build but it looks like some core portions of DS4Windows would have to be changed to better facilitate logging. Logging would not make it into the current Windows Forms build.

As for the root problem, there are event hooks that can be used to catch an unhandled exception that crashes the application. That event hook can probably be used to write some messages to a log file before the process gets killed.

**Comment by Ryochan7** [comment] 2019-11-20 19:30
Just double checked and confirmed that this is doable using NLog. NLog also provides log file rotation and file size caps as core features which saves me a lot of work. It looks like DS4Windows 2.0 could have some form of logging support.

**Comment by Ryochan7** [comment] 2019-12-01 21:27
Actually this came in handy already. Having the logs helped me diagnose the issue with early app shutdown that was fixed in the recent WPF beta.

**Comment by Ryochan7** [comment] 2019-12-26 07:16
Version 2.0.0 has been released. Having access to a crash log has already come in handy for a user while testing the WPF beta builds.

**Closed by Ryochan7** 2019-12-26 07:16 UTC
