### ISSUE TITLE
Updated DS4 Windows - Special Actions won't load

### ISSUE THREAD

**Issue by Mister-Curious** [Ryochan7/DS4Windows#2853] opened 2023-03-05 06:36 UTC
**Describe the bug**
I mistakenly updated my DS4Windows and it wrote over my older working version (I use the program folder method for a portable version, not the %appdata% method. So my old data was overwritten). Fortunately I had an older backup with the Actions intact (I believe this is the 'Actions.xml' file), but when I migrate that file into the updated directory nothing shows up.

My last version of DS4Windows was old (3.0.18), so I am not sure if since that version was released that there has been a new method of implementing Special Actions? I REALLY need to get this working, as there was years of work making those actions.

Any help or insight is appreciated!

**To Reproduce**
1. Update to latest version of DS4Windows
2. Click on any profile
3. Select Special Actions
4. See all actions missing. 

**Expected behavior**
Previously saved Special Actions be available in latest version of DS4Windows after updating. 

**Screenshots and Logs**
N/A

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 22H2
 - DS4Windows Version 3.28

**Comment by Ryusennin** [comment] 2023-03-05 09:39
Duplicate of #2775

Special actions are problematic since release 3.2. The new XML parser used for reading/saving settings is finicky and some adjustments need to be done (about empty tags for example).

**Comment by Mister-Curious** [comment] 2023-03-05 11:43
@Ryusennin Thanks for weighing in. Are you sure this is a duplicate though? I had a read through that thread... but Im not trying to make new actions and save them. What I am trying to do is load my previously created Special Actions. In any case, I am not sure if there was a fix for this, or is this something we can look forward to? I reverted backed to 3.0.18 for the time being.

**Comment by Ryochan7** [comment] 2023-03-05 16:41
It is a duplicate. The loading portion is what was primarily broken. That issue with processing Delay tags has been fixed in the code but no new release has been put out yet. Been going on other tangents. Still have some other tasks to get done before a new release can be made.

**Comment by Mister-Curious** [comment] 2023-03-05 20:34
Thank you @Ryochan7 for confirming the issue. I will keep an eye on future update release notes looking for any mentions of the Special Actions fix.

**Closed** 2023-03-05 20:36 UTC

**Comment by Mister-Curious** [comment] 2023-03-11 18:35
Thank you for the speedy patch. Can confirm that 3.2.9 is now loading Special Actions.
