### ISSUE TITLE
can't change language

### ISSUE THREAD

**Issue by Chen-Leon** [Ryochan7/DS4Windows#2683] opened 2022-11-07 06:15 UTC
can't change language

**Comment by Yohoki** [comment] 2022-11-07 07:29
Please use the search bar. This issue has been reported.

Duplicate of https://github.com/Ryochan7/DS4Windows/issues/2639

**Comment by Chen-Leon** [comment] 2022-11-07 09:01
OK Thank's

**Closed** 2022-11-07 09:01 UTC
