### ISSUE TITLE
Legacy ps4 support broken..... I think?

### ISSUE THREAD

**Issue by Pylon69** [Ryochan7/DS4Windows#2019] opened 2021-04-02 12:47 UTC
I'm actually in possession of 3 controllers. 2 of which I've been using for centuries. Both of which are entirely unrecognised by the latest update.
rollbacked to:  https://github.com/Ryochan7/DS4Windows/releases/tag/v2.2.14
I went through your 2 updates before and they showed exact results. I can't use my old controllers at all.
I gave you hassle with rumble. Now I believe net 5.0 might be at fault for some reason. I'm not a buffon though. 
That's your journey.... 

1.) Plug in old model controller(I'll attached pictures and make a video soon)
2,) Hear windows, aswell as see controller be rogocnised.
3.) Bluetooth and cable result in the same misfortune 

**Expected behavior**
I plug it in and have fun

**Screenshots**
https://files.catbox.moe/2lines.mp4 (180mb)
https://files.catbox.moe/8e535w.mp4 (90mb~)
Sorry for the bandwidthlets like me.

**Desktop (please complete the following information):**
 - Red : Controller Make and Model:
 - Gold: 
 - Black: 
 -  
 - OS: Win10 latest
 - DS4Windows Version 3.00.(Broken)
 - DS4Windows_2.2.14_x86(this is the working one)
 

**Additional context**
Honestly. I think the fault lies in something involving 5.0 NET.
Sorry for the hassle but I think this is a pretty big problem. I'll Help where ever I can if need be.

**Comment by ChaosOrdeal** [comment] 2021-04-02 13:40
Me, too.  PS4 controllers do not connect in v3.0

**Comment by Ryusennin** [comment] 2021-04-02 14:24
I have 4 controllers (one v1 and three v2) and none of them are detected by DS4W 3.0. Might be an issue with HidG and/or exclusive mode.

"I'm not a buffon though.
That's your journey...."

Poetry?

**Comment by Ryochan7** [comment] 2021-04-02 18:02
Duplicate of #2018

That issue has been fixed

**Closed** 2021-04-08 15:58 UTC
