### ISSUE TITLE
(v2.0.1) certain keys stop macro recording

### ISSUE THREAD

**Issue by nr1995** [Ryochan7/DS4Windows#978] opened 2019-12-28 22:41 UTC
I don't think this is specific to v2.0.1
or even necessarily a bug,
but when you're recording a macro,
certain keys will stop you.  I'm thinking in this case of [space] in particular.
I don't think anything should be able to stop your recording,
other than clicking “Stop”.
I'm not even sure how to add a space into the recording,
or if it's even possible.

**Comment by mika-n** [comment] 2019-12-28 23:58
Confirmed. The problem is that focus stays on "STOP" button and when you press a space button then it will actually click the stop button. You can verify this by starting a recording and pressing TAB key to move the focus to an another component and then pressing space button. The space button no longer stop the reconding but it does what is under the new focus. TAB and ENTER keys are also a bit problematic because the recording window handles those as normal "window control keys".

This is a bug/limitation of recording window. If you really really really need to enter those special chars into a macro (before the bug is fixed) then you have to modify macro sequence in XML config files using Notepad.

**Comment by nr1995** [comment] 2019-12-29 00:32
Is it the kind of thing that the dev is likely to _want_ fixed?
And beyond that, to _try_ and fix?
I don't know much about this kind of thing,
but there must be some way to just disable [Tab] and [Enter] in the window, right?
Even killing the key entirely would arguably be favourable to this.

**Comment by mika-n** [comment] 2019-12-29 11:04
Want. yes. Try, yes. When? When there is enough time to look into this issue. Meanwhile "Powered by Notepad" technology can be used as a workaround to enter SPACE char into a macro sequence.

**Comment by nr1995** [comment] 2019-12-29 12:50
Didn't mean to offend,
just wanted to know what category this fell into.

**Comment by Ryochan7** [comment] 2019-12-31 07:42
This issue has been fixed in version 2.0.2. It took a while to find a fix but the code behind it is actually fairly minor.

**Closed** 2019-12-31 17:27 UTC
