### ISSUE TITLE
Exclusive mode warning with 2.0.5

### ISSUE THREAD

**Issue by subz6972** [Ryochan7/DS4Windows#1071] opened 2020-01-24 23:48 UTC
I have this warning with 2.0.5 when pressing PS button :
 
![image](https://user-images.githubusercontent.com/57925334/73111388-785ff980-3f0a-11ea-9c91-74dfa5f91924.png)

Then if i use stop and start the warning doesnt appear ... it appears only when using PS button

Never had that warning with previous ones

**Comment by mika-n** [comment] 2020-01-25 15:14
See the following page. Maybe "PS" button triggers "xbox" button event it this causes Windows to open a connection to the gamepad? Anyway, exclusive mode is sometimes a bit tricky because of non-DS4Windows related issues.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by subz6972** [comment] 2020-01-25 16:12
I have the same problem with 2.0.6 so i reverted to 2.0.4
No "xbox" event is launched with "PS" button and I dont see any conflict through Process Explorer between DS4Windows and another app.
In my case DS4Windows.exe processes are using \Device\00000012 and \Device\0000015f in any version of DS4Windows but exclusive mode seems only to work with 2.0.4 or previous ones.

**Comment by Ryochan7** [comment] 2020-01-25 17:37
I didn't change anything with the routine so I am just going to assume that it is some .NET Runtime moon magic at play.

**Comment by xperia64** [comment] 2020-01-26 02:24
@subz6972 Have you checked Process Explorer before starting DS4Windows? (e.g. exiting it or hitting the stop button, then turning on/connecting your controller?) I didn't see any conflicts while DS4Windows running, but before DS4Windows took the controller, I saw dwm.exe using it.

Could there be some sort of new race condition somewhere?

I'd also be interested to see if instead of immediately failing on the first exclusive open attempt, waiting for a short delay and trying to open it again (since exclusive mode seems to work for me when stopping and starting DS4Windows without disconnecting the controller; I guess dwm.exe closes it when something else tries to open it?)

**Comment by subz6972** [comment] 2020-01-26 11:38
@xperia64 Yes i tried that but no processes used by DS4Windows are in conflict before turning on the controller or stopping DS4Windows.

The problem happens with PS button on (or Options/PS for off then PS on) --> i have the Warning message and the exclusive mode is not working , 
However, if i press stop then start in DS4Windows after PS on (and the Warning), the **exclusive mode works** ... until i press Options/PS and PS on again ... weird.

**Comment by hieutrungd** [comment] 2020-01-27 19:14
Quite peculiar, I have identical symptoms and workarounds.

**Comment by Viscerous** [comment] 2020-01-27 19:15
Quite peculiar, I have identical symptoms and workarounds.

**Comment by mooms06** [comment] 2020-01-27 23:17
I've also this issue since a few versions, still there on 2.0.6.

Windows 10 1909, DS4 v2 on Bluetooth.

Closing all applications will not fix the issue.

It's very annoying, the only workaround is to sign out from Windows or restart the computer, then immediately after the logon, connect the DS4.

**Comment by RealStaticVoID** [comment] 2020-01-28 11:31
Just wanted to say,that running ds4w as admin fixed the problem :)

**Comment by mooms06** [comment] 2020-01-28 12:34
I'm running it as a task, so it's already as admin.

**Comment by mika-n** [comment] 2020-01-28 15:00
> I'm running it as a task, so it's already as admin.

There has been cases where Task/Scheduler launched DS4Windows have had some issues Does it make a difference if you run DS4Windows using "run as administrator" option via FileExplorer?

**Comment by mooms06** [comment] 2020-01-28 15:05
No, it makes no difference:

![image](https://user-images.githubusercontent.com/25405517/73275829-fdd3fa00-41e7-11ea-9fe3-cadf798ed37f.png)

**Comment by Ryochan7** [comment] 2020-01-28 15:07
Found the offending commit. The change in application shutdown made the second DS4Windows instance error out upon exit. The first instance would see that error code and not attempt to open the device in exclusive mode.

https://github.com/Ryochan7/DS4Windows/commit/489d13d02f74ec6da29c8cbb51d7b71e14e8d739

**Comment by subz6972** [comment] 2020-01-28 15:15
> 
> 
> Just wanted to say,that running ds4w as admin fixed the problem :)

Yes it does work ... but Admin rights prevent 'Run at startup' option working as a Program

**Comment by Ryochan7** [comment] 2020-01-28 20:26
This issue is important enough to push a patch release early. I'll get a build out later tonight.

**Comment by mooms06** [comment] 2020-01-29 10:56
2.0.7 didn't solve the issue.
First connection (at computer startup, after the update) was OK, but next were not:


> 01/29/2020 11:51:53: DS4Windows version 2.0.7
> 01/29/2020 11:51:53: Starting...
> 01/29/2020 11:51:53: Connection to ViGEmBus 1.16.112.0 established
> 01/29/2020 11:51:53: Searching for controllers...
> 01/29/2020 11:51:53: Using Exclusive Mode
> 01/29/2020 11:51:53: UDP server listening on address 127.0.0.1 port 26760
> 01/29/2020 11:52:13: Found Controller: A4:53:85:93:BA:6D (BT) (DS4 v.2)
> 01/29/2020 11:52:13: Plugging in X360 Controller for input #1
> 01/29/2020 11:52:13: Controller 1 is using Profile "Default"
> 01/29/2020 11:52:38: Unplugging X360 Controller for input #1
> 01/29/2020 11:52:38: Controller 1 was removed or lost connection
> 01/29/2020 11:52:45: Found Controller: A4:53:85:93:BA:6D (BT) (DS4 v.2)
> 01/29/2020 11:52:45: Plugging in X360 Controller for input #1
> 01/29/2020 11:52:45: Controller 1 is using Profile "Default"
> 01/29/2020 11:52:45: Warning: Could not open DS4 A4:53:85:93:BA:6D exclusively. You must quit other applications like UWP apps (Netflix), Steam, Uplay, NVIDIA IN-GAME before activating the 'Hide DS4 Controller' option. For more info check https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
> 01/29/2020 11:52:56: Stopping X360 Controllers
> 01/29/2020 11:52:56: Closing connection to ViGEmBus
> 01/29/2020 11:52:56: Unplugging X360 Controller for input #1
> 01/29/2020 11:52:56: Controller 1 was removed or lost connection
> 01/29/2020 11:52:56: Stopping DS4 Controllers
> 01/29/2020 11:52:56: Stopped DS4Windows
> 01/29/2020 11:52:56: Closed UDP server
> 01/29/2020 11:52:58: Starting...
> 01/29/2020 11:52:58: Connection to ViGEmBus 1.16.112.0 established
> 01/29/2020 11:52:58: Searching for controllers...
> 01/29/2020 11:52:58: Using Exclusive Mode
> 01/29/2020 11:52:58: UDP server listening on address 127.0.0.1 port 26760
> 01/29/2020 11:53:03: Found Controller: A4:53:85:93:BA:6D (BT) (DS4 v.2)
> 01/29/2020 11:53:03: Plugging in X360 Controller for input #1
> 01/29/2020 11:53:03: Controller 1 is using Profile "Default"
> 01/29/2020 11:53:03: Warning: Could not open DS4 A4:53:85:93:BA:6D exclusively. You must quit other applications like UWP apps (Netflix), Steam, Uplay, NVIDIA IN-GAME before activating the 'Hide DS4 Controller' option. For more info check https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by subz6972** [comment] 2020-01-29 11:04
2.0.7 is working fine for me, even after several reboots : 

![image](https://user-images.githubusercontent.com/57925334/73351438-42ff3700-428f-11ea-9313-84e637129cb0.png)

**Comment by mika-n** [comment] 2020-01-29 11:14
@mooms06  @subz6972  How do you launch DS4Windows app? 
"Run at startup" DS4Win option set or unset? Program or Task option? 
Manually from FileExplorer/BAT/CMD batch file on desktop? 
With or without "run as administrator" option?  
Start minimized/MiminizeToTaskbar option set or unset?

Maybe the way how DS4Windows is launched has something to do with the issue.

**Comment by Viscerous** [comment] 2020-01-29 12:23
2.07 seems to be working fine for me and my friend so far. Using regular start-up as program, no elevation.

**Comment by subz6972** [comment] 2020-01-29 13:44
> 
> 
> @mooms06 @subz6972 How do you launch DS4Windows app?
> "Run at startup" DS4Win option set or unset? Program or Task option?
> Manually from FileExplorer/BAT/CMD batch file on desktop?
> With or without "run as administrator" option?
> Start minimized/MiminizeToTaskbar option set or unset?
> 
> Maybe the way how DS4Windows is launched has something to do with the issue.

A classic way : Run At Startup, Run as Program, Without admin rights, Start minimized & Minimize to Taskbar unticked

**Comment by mooms06** [comment] 2020-01-29 16:25
> 
> 
> @mooms06 @subz6972 How do you launch DS4Windows app?
> "Run at startup" DS4Win option set or unset? Program or Task option?
> Manually from FileExplorer/BAT/CMD batch file on desktop?
> With or without "run as administrator" option?
> Start minimized/MiminizeToTaskbar option set or unset?
> 
> Maybe the way how DS4Windows is launched has something to do with the issue.

I don't see any "run as administrator" option.

![image](https://user-images.githubusercontent.com/25405517/73375520-31805400-42bc-11ea-85c7-4d3b91c7eb19.png)

**Comment by xperia64** [comment] 2020-01-30 01:23
2.0.7 works for me just fine now.
Not running at startup.

**Comment by mooms06** [comment] 2020-01-30 12:27
I still have the issue in 2.0.8. 

![image](https://user-images.githubusercontent.com/25405517/73449327-30eec880-4363-11ea-88e6-ebc5654f6db1.png)

I only have one controller plugged, is it normal that the system see two controllers ?

![image](https://user-images.githubusercontent.com/25405517/73449594-cd18cf80-4363-11ea-99f4-2c56799b211a.png)
![image](https://user-images.githubusercontent.com/25405517/73449630-e588ea00-4363-11ea-85a5-d010ebcac914.png)

Here are the running processes
![image](https://user-images.githubusercontent.com/25405517/73449394-554aa500-4363-11ea-9be7-b6469710ee34.png)
![image](https://user-images.githubusercontent.com/25405517/73449419-64315780-4363-11ea-8277-e8b17877be61.png)

**Comment by mooms06** [comment] 2020-01-30 12:42
I tried a complete uninstall, including ViGem, restarted, installed DS4Windows & ViGem, restarted: still the same issue...

The first connection is successful if it's made right after the logon, but not the following next.

![image](https://user-images.githubusercontent.com/25405517/73450728-4addda80-4366-11ea-9dac-2e2c0045d93b.png)

**Comment by mooms06** [comment] 2020-01-30 12:46
I've killed Edge and Cortana from Process Explorer, now the issue is gone...I don't use either one...

**Comment by mika-n** [comment] 2020-01-30 13:23
The wiki doc page does mention Edge process as one potential "gamepad stealer". However, the wiki page is no way near a complete list because at any day new potentially problematic app may popup.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

I guess Edge supports gamepad controls and when it runs it queries through available gamepads and opens a connection when it detects one. 

HidGuardian tool is another way to hide the original controller but it requires an additional driver installations (not part of DS4Windows app package).

**Comment by Volkaru** [comment] 2020-02-01 20:33
I'm also having this issue still. I have checked with process manager and the only things using my controller are dwm.exe and DS4. I was using version 1.7.4 without issues. Updated to 2.0.8 and now I'm unable to access Exclusive mode. Running as a task. I've disabled all Nvidia gamestream/overlay services, I've also never used Edge, and have checked if it's active in any way.

**Comment by mika-n** [comment] 2020-02-01 20:46
DWM.EXE is a DesktopWindowManager and there has been few reports that it sometimes steals the gamepad and prevents exclusive mode in DS4Windows app (ds4win app should be the first app using the gamepad in order to be able to make an exclusive lock on the physical gamepad device).

Recent versions of DS4Windows have tweaked delays of connect/disconnect gamepad and maybe these new delays are in your environment "too long" and gives enough time for dwm process to kick in and steal the gamepad when you connect it.

Any difference if you run DS4Windows like this:
- Disconnect all gamepads
- Launch normally via FileExplorer using "run as administrator" option (ie. don't run it automatically on system boot via RunAs-Task or TaskAs-Program option).
- Wait for DS4Windows app to start
- Now connect the gamepad (while DS4Windows app is already running)

**Closed** 2020-03-29 21:23 UTC
