### ISSUE TITLE
Odd Issue: Latency Spikes over XInput Sony Dongle when Screen Recording

### ISSUE THREAD

**Issue by vvilkommen** [Ryochan7/DS4Windows#81] opened 2017-07-01 03:28 UTC
This may not be a DS4Windows issue, but I am having a problem. When I start screen recording a game (via MSI Afterburner), my DS4 encounters incredible lag spikes rendering it unusable. Inputs either don't register at all or get "stuck" (as if the DS4 has been turned off with that button held), all the while the lightbar flashes red like crazy. Once I stop screen recording, the DS4 happily returns to normal, latency under 8 or so ms.

Has anyone else experienced this?

**Comment by randu1459** [comment] 2017-07-01 05:27
Although it doesn't sound like this is the case for you, it may be worth checking the settings on your USB hub controller. Check out hostiphur's comment from [a latency issue logged for Jays2king's DS4Windows repo](https://github.com/Jays2Kings/DS4Windows/issues/62#issuecomment-226668486).

This greatly improved the latency with my desktop PC and an off-brand Bluetooth dongle. I'm sure something was causing it to power down, but I could not find any obvious reason.

**Comment by Ryusennin** [comment] 2017-07-01 20:10
I'm occasionally recording game sessions through AMD Crimson ReLive (in 1080p60 no less), and I don't have any controller lag issue. Worth noting is that my DS4 is always working in USB mode on the PC (I keep the Bluetooth pairing for the PS4).

**Comment by Ryochan7** [comment] 2017-07-01 21:07
Just tested this using OBS to record while playing Street Fighter 4. It works fine on my system. I don't not know if there would be any possible change in performance when using MSI Afterburner instead. Playing around with power management settings might be worth a try. I always use the "High Performance" power plan so the change that was suggested in the other post might not have any real effect on my system. Also, which version of DS4Windows are you currently using? I would like to know if the version is 1.4.80 or later.

**Comment by vvilkommen** [comment] 2017-07-01 22:02
Thanks for the link, randu!

I did check my settings, power management is and was on high performance with as much set to never throttle and 100% as possible.

I'm on WIndows 10
DS4w is 1.4.83
I'm on Sony Wireless Adaptor for DS4 (plugged into USB3 port just in case lol)

I'm starting to wonder if the issue lies with XIGNCODE3 somehow. I don't have this latency issue at all on another game I play that does not use XIGNCODE3, everything else the same.

**Comment by vvilkommen** [comment] 2017-07-02 04:56
Was messing around earlier and noticed something even more peculiar: if I start a screen record (via MSI afterburner still) of the game the ds4 latency spikes to unusable, sometimes even dropping the controller completely (have to psx button it back on) -- just as in the OP -- however, if I alt tab to any other program (even while MSI continues to screen record the game) the ds4 behaves normally. Alt tab back to the game? Latency hell again.

At this point I do not think this is a DS4Windows issue, but I'm hoping someone out there may be clever enough to figure out what is going on.

In any case, how would I test latency spikes without DS4windows running? I'd like to try some things.

**Comment by Ryochan7** [comment] 2017-07-03 08:54
Have you had any luck resolving this problem? I have not tried MSI Afterburner yet due to other experiments. The reason I asked about version 1.4.80 was because that was the version when the last major performance bump was introduced in DS4Windows. The changes made with that version consequently decreased the overhead from running the app. After some fiddling around, some decent changes have been made that seem to make DS4Windows run smoother. Can you give a test version a try and see if you have better luck with that version?

https://drive.google.com/open?id=0B6yGHDx0CFzDbmdBOTRDWjNHWUU

**Comment by vvilkommen** [comment] 2017-07-03 09:18
Unfortunately, the google drive build is still affected. 

Thanks for continuing to look around! I will test more things on my end, too.

**Comment by Ryochan7** [comment] 2017-07-04 08:28
I have tried to capture with MSI Afterburner while playing Blade and Soul and I experience the same latency issues. However, the problem also affects keyboard and mouse inputs. The most recent version of OBS has a Game Capture option that can work with the game rather than having to reply on Display Capture. While using OBS in Game Capture mode, inputs work just fine while recording.

I tried a few other games and Blade and Soul is the only game that I had problems with when using MSI Afterburner for recording. At this point, I am going to assume that the problem is with the process that MSI Afterburner uses to hook into the game.

**Comment by vvilkommen** [comment] 2017-07-04 18:38
It's certainly nice to know I'm not crazy! It is odd that keyboard and mouse inputs are being affected for you as I haven't had it quite that bad. I will try to see if I can find the specific tweak or setting that seems to be the culprit.

In the meantime, I could also use OBS as you are. Do you happen to know a way to make OBS add an fps counter to an arbitrary corner of the screen, say... upper right? 

Thank for going the extra mile to help calm my sanity, by the way! Blade and Soul is not the tiniest game one could download...

**Comment by vvilkommen** [comment] 2017-07-11 16:50
Update: I think I've found the what, but I don't quite get the why. I put the Sony USB Adaptor on a long USB extender and held it as far away from the computer as possible, then I connected my wireless mouse, which was previously on the USB extender, directly to the computer and fired up MSI Afterburner.

Perhaps a coincidence, as MSI Afterburner screen captured, the DS4 continued along happily as if nothing were happening, not a latency spike in sight even after a minute or so (spikes historically happened in seconds). Something interesting happened as well... my wireless mouse's latency, which was previously unaffected (while itself connected to the USB extender), went crazy! I could barely use it for how laggy it was. I remembered that you said you were able to reproduce the lag in your DS4, but your keyboard and mouse inputs were also affected. Were they wireless or wired? Were they connected directly to the computer? Test for yourself to verify, if you have a rather long USB extender hanging around. If you are using internal Bluetooth antenna, maybe you can't play with that, but you can try to extend the Sony Adaptor.

If you can duplicate the relief, I think I can flag this issue as closed; however I'd like to get another USB extender to test one more thing. 

Also, do you AMD?

**Comment by Ryusennin** [comment] 2017-07-12 22:47
I remember people having connectivity issues on PS3 between the BT DualShock 3 and the Sony Pulse wireless headset which used a (not BT) dedicated dongle. Specifically the sound of the headset would lag or  disconnect randomly while using the DS3 in BT mode. Many players observed noticeable improvements by plugging the Pulse dongle on a USB extender, supposedly to keep it away from the console.

**Comment by Ryochan7** [comment] 2017-07-15 01:51
I use a cheap wireless Logitech keyboard and mouse combo. My processor is an AMD FX 6200 @ 3.82 GHz. Also, this problem occurs regardless of whether DS4Windows is running or not.

Although moving the BT or Sony dongle to a USB extended might help in some situations, I would not worry about doing it for this scenario; maybe I will give it a try just out of curiosity. Since the problem does not occur when using Game Capture in OBS, it is a non-issue for me. One other scenario to test is if the problem occurs when the SCP Virtual Bus is not installed.

**Comment by Ryochan7** [comment] 2017-07-24 23:36
Finally tested this with Scp Virtual Bus uninstalled. The delay is still present when using just keyboard and mouse. The delay exists even when looking down at the ground to ensure the framerate stays at 60 fps no matter what.

That is enough testing of this issue. Since the problem is not caused by DS4Windows, this issue can be closed. It looks like the real workaround to this problem is to grab the most recent version of OBS. The most recent version has a game capture mode that works with Blade and Soul and does not cause any input delay while it is recording.

**Closed by Ryochan7** 2017-07-24 23:36 UTC
