### ISSUE TITLE
disconnecting randomly

### ISSUE THREAD

**Issue by AlbertZoto** [Ryochan7/DS4Windows#1353] opened 2020-06-17 00:01 UTC
Hello guys, I hope you can helpe wit soome problems I've been having with my controller. 

After a couple of hours the controller gets disconnected over an over again.

A guy called mika-n told me to use DS4WindowsDebug so I can share my log file, so that's what I did. I you have any advice I will really appreciate it. This issue started almost at the end of the log file.

Thank you very much!

[debuglog160620.txt](https://github.com/Ryochan7/DS4Windows/files/4789644/debuglog160620.txt)

**Comment by mika-n** [comment] 2020-06-17 08:52
The root cause of disconnection seems to be failing "writeOutput" process. DS4Windows app not only read events from a gamepad, but also writes (=sends) data to DS4 gamepad. DS4 mode configuration in BT, lightbar and rumble support requires this. 

If this writeOutput process fails then DS4Windows app thinks that the gamepad was unexpectedly disconnected or battery died or the pad is out of BT range.
`06/16/2020 18:48:00: DEBUG: sendOutputReport. ERROR. writeOutput failed. Force quiting output thread. LastErrorCode=1167`

Could be that DS4Windows is a bit too aggressive and should wait a bit longer before giving up the connection after write failure, but because the app is experiencing those issues then there really are some BT connectivity problems in the first place.

There is one thing you could try to see if writeOutput is a single point of issue or if there are general BT communication issues. There is "Enable Output data to DS4" option in a profile. Try unticking this option and test if the connection stays alive more consistently. Lightbar and rumble is gone when this option is unticked, but it would tell us a bit more about the issue.

**Comment by AlbertZoto** [comment] 2020-06-17 16:40
Thank you @mika-n, I will make some tests and then tell you how it worked.

Greetings!

**Comment by Newtype14** [comment] 2020-07-09 15:18
I've been having the exact same problem as AlbertZoto. Same error. I can confirm that disabling the "Enable Output data to DS4" option prevents disconnection from happening. Did a playthrough of Dark Souls Remastered with the option ON and kept losing connection after a while. Did another playthrough with the option OFF and never lost connection. But yeah... you lose lightbar support and vibration, which makes using DS4Windows unnecessary in that case.

**Comment by mika-n** [comment] 2020-08-29 08:46
closed as "some DS4 gamepads/BT dongles/BT chipsets/PCs" are incompatible and cannot keep up the fast paced read-write data cycle over BT.

**Closed by mika-n** 2020-08-29 08:46 UTC
