### ISSUE TITLE
PS5 Dualsense no vibration when emulating DS4 after 2.2.10 update

### ISSUE THREAD

**Issue by rjruardy** [Ryochan7/DS4Windows#1946] opened 2021-03-13 01:46 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version [e.g. 2.1.5]

**Additional context**

**Comment by TheMasterDingo** [comment] 2021-03-13 02:27
Same problem here

**Comment by Ryochan7** [comment] 2021-03-13 05:08
Duplicate of #1935

**Closed by Ryochan7** 2021-03-13 05:08 UTC
