### ISSUE TITLE
Macros on the touchpad

### ISSUE THREAD

**Issue by HerptyDerpoty** [Ryochan7/DS4Windows#440] opened 2018-09-30 08:26 UTC
This bug nearly made me off myself.
I was trying to do a macro to do kicks in ds1/2/3 but every time i set a touchpad input to a macro rebinding at all would break, i could not change any of the default inputs. i could change rumble settings and makes the touchpad a mouse (but not bind mouse clicks) and the only way i could find to fix this was to remove the VBUS driver, uninstall both the 360 controller and the wireless controller driver in device manager, restart my pc and reinstall everything.
also yes i tried toggling on and off hide ds4 controller
steaming being open or closed didnt matter.

**Comment by Ryusennin** [comment] 2018-09-30 16:49
Something's obviously going horribly wrong with your setup. I'm using macros on the touchpad without any issue at all to duplicate the Start and Select buttons in various emulators, or to reproduce the snapshot/capture function of the PS4 via the Share button.

Make sure your touchpad buttons are *unbound* and you create your macros through the Special Actions tab, otherwise you're asking for trouble.

**Comment by Ryochan7** [comment] 2018-10-01 19:12
Something sounds horribly wrong. I will have to test macros on the touchpad later. Personally, I don't use the macro system as it is broken by design.

**Comment by Ryochan7** [comment] 2018-10-02 05:51
Can you share the profile that you are using? Macros work okay with touchpad controls on my end.

**Comment by Ryusennin** [comment] 2018-10-02 16:38
The only serious caveat I have found in the current macro system is that it's a bit unintuitive, because it's possible to associate macros to a button through both the button mapping screen and the special actions tab. On my setup, using the button mapping screen will lead to conflicts or weird behaviours.

In my opinion, it would probably be best to somehow forbid the creations of macros through the button mapping screen.

**Comment by Ryochan7** [comment] 2018-10-02 18:52
Having per profile macros and per installation macros in Special Actions can be a bit counter intuitive. Both work on my end though. I mainly don't like how rigid the macro system is and that the default behavior causes output controls to be pressed and released in quick succession. That type of behavior has been a problem for a few people that have tried to make macros work for some use cases. Here is an example regarding OBS but I also remember someone having issues with a Rayman game (Legends?).

https://github.com/Ryochan7/DS4Windows/issues/343#issuecomment-414093485

A better type of assignment system is available in antimicro but trying to make something like that with the static nature of the DS4Windows code would be almost impossible. It would probably be easier and more worthwhile to start from scratch.

**Comment by Ryusennin** [comment] 2018-10-02 20:52
It never occured to me that macros associated via the mapping screen were linked to a profile, but of course that makes sense. I don't know why it acts wildly on my end though, but it doesn't really matter since I prefer the global special actions.

I agree that creating macros is not always easy. For my screenshot macro for example (which uses the built-in screenshot function of Radeon Live), I definitely encountered those timings issues you pointed to, and I had to manually tweak the timings because the recorded ones produced by the Radeon shortcut (Shift+Alt+S) were way too short and oftentimes the macro would not work at all. Adding 100ms between those triggers fixed the issue.

**Comment by HerptyDerpoty** [comment] 2018-10-03 11:42
I bind the macros in the profile editing and the default action is replaced by "macro", I haven't tested this much because currently my c drive is taking a nose since so reboot times take minutes, I'd be more then happy to reproduce this, is it possible that it's because I'm on 7 I used to have scarlet crush but I wanted built in rebinding and it was being extremely jank with it's Bluetooth driver when trying to pair my ds4, in all honesty it could be done super specific thing about my ancient 7 install (bordering 7 years) while sfc says nothing is missing something is horribly wrong with my windows install (it stopped producing minidumps 2 years ago) I'd format it but I need to make a system to replace its cobbled together functions (it runs a ton of diy smart home stuff) and I have no clean way to separate these functions right now, and I'm honestly lazy about it, but it seems the computer is forcing my hand

**Comment by Ryusennin** [comment] 2018-10-03 13:17
For what it's worth, I'm also on Win7-64 and I never had to reinstall it since 2009.

**Closed** 2018-11-28 00:42 UTC
