### ISSUE TITLE
DS4Windows Not autostarting on boot

### ISSUE THREAD

**Issue by jusseppe88** [Ryochan7/DS4Windows#700] opened 2019-05-12 15:53 UTC
Hello,
wanted to let you know that with the latest version of DS4Windows I have problems making it start with windows. I tried setting it up from the Program itself (both as program and task), tried manually creating a Scheduled task with Windows Scheduler but nothing.
I am running Windows 10 1809.

Anybody else has this issue or is there any known solution?

thank you

**Comment by DrConflict** [comment] 2019-05-14 15:21
I have the exact same problem.

**Comment by fenglidon** [comment] 2019-05-18 05:10
1. ![Image of Yaktocat](https://i.imgur.com/CUfquFl.jpg)

2. Delete " -m"
![Image of Yaktocat](https://i.imgur.com/JoF7QZm.jpg)

**Comment by DrConflict** [comment] 2019-05-18 14:03
@fenglidon I have no idea how you got to that screen since everything is in
Mandarin. I checked the .exe properties but could not change anything like
"-m". Thanks for the suggestion though.

**Comment by Ryochan7** [comment] 2019-05-19 03:01
All that the "-m" flag does is minimize the main window at startup. I can give autostart a try again and see if anything has changed. It shouldn't have but I haven't tested it since around version 1.7.0.

**Comment by fenglidon** [comment] 2019-05-19 04:24
Link path is "C:\Users\Your User Name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup"

And Delete " -m" not just "-m"

The version I am using is 1.7.8

Sorry for my poor English ^ ^"

**Comment by Ryochan7** [comment] 2019-05-19 20:32
I tested both methods and they both work on my system.

**Comment by Wolfybrz** [comment] 2019-05-26 04:39
There's a simple way to fix this: 
Be sure to run DS4windows as administrator and activate "Run as Task", open Task Scheduler (Start->Run: taskschd.msc)

- Find a task called "RunDS4Windows"
- Click on "Properties" then select "Triggers" tab
- Click "New" and select "when logging in" from dropdown and set it to "Any User"
- Click "Ok" restart your system

Its working fine for me in Windows 10 1809.

**Comment by jusseppe88** [comment] 2019-05-27 19:06
I tried but I get this error which is related to the Run with highest priviliges option:
![image](https://user-images.githubusercontent.com/50551533/58435957-42405080-80c3-11e9-8732-37bee7cf0f52.png)

**Comment by mika-n** [comment] 2019-05-27 21:23
Usually the "arguments are not valid" error message in TaskSchduler is thrown if path to an executable or "Start in folder" options in Actions tab page are wrong (missing file or path) or user doesn't have permissions to a specified executable or path.

Please remember that if there are empty space chars in file or path names then you need to enclose the file reference with double quote chars. For example "c:\program files\ds4win\ds4windows.exe".

What do you have in Actions tab page?

**Comment by Wolfybrz** [comment] 2019-05-28 16:30
Is "Run with highest priviliges" checked in general tab? If you changed the program paths recently you can delete the task and redo the "Run as Task" on ds4windows again, so the task will be created with the current path.

You'll need administrative previledge to make this work.

**Comment by jusseppe88** [comment] 2019-05-28 18:00
I've fixed the privileges error by changing the user to SYSTEM, but it still doesn't start on boot anyway... this is what I have in the Actions tab:
![image](https://user-images.githubusercontent.com/50551533/58500805-3c11a900-8183-11e9-8eb2-a5c3f3405166.png)

**Comment by Wolfybrz** [comment] 2019-05-28 18:15
Weird... the command line is correct, I can't see any unnecessary space on it.

Does Windows Account has a password set? If not, try adding one account with defined password, since even "System user" can't fix it.

**Comment by mika-n** [comment] 2019-05-28 18:49
The app path has a special char "&". How about if you try to use the DS4Win app from a folder without this special char? It wouldn't be the first time when Windows does something crazy with specal chars.

**Comment by jusseppe88** [comment] 2019-05-28 20:53
tried moving it also to a short and simple folder such as "D:\Programs\DS4Windows" but still no luck..
at the end I have bound the application to run through a programmable keyboard key. Better than nothing :-)

**Comment by Ryochan7** [comment] 2019-07-02 19:18
One other major possibility is that the DS4Windows.exe executable file set to Run As Administrator. That would cause autostart to fail when using either version of Run At Startup. With Run As Program, the issue is due to a Windows security feature.

Unfortunately, the Run As Task option actually runs an instance of DS4Windows which then launches the Task. That detail was needed beforehand because app performance was worse when launching the Task directly at login. I have tried to change that option to have Windows run the Task directly but app performance suffered towards the last few code changes. It would be nice to get rid of the Startup link for the Task option but it will continue to be used for now.

**Comment by Ryochan7** [comment] 2019-09-14 18:30
I will give this another try soon. I am not very hopeful though.

**Closed** 2019-12-01 21:55 UTC
