### ISSUE TITLE
Are macros poorly implemented or am I doing something wrong?

### ISSUE THREAD

**Issue by Bawhady** [Ryochan7/DS4Windows#1547] opened 2020-10-30 12:53 UTC
I'm trying to setup a simple autorun macro, but for some reason, toggle macro is only available to macros that involve the keyboard...? I just want a simple option that lets me setup toggle macro for any key, in this instance I just want to setup so that the "Share" button on the DS4 toggles the LS-up action. In the wiki it states that the keep keystate option should sort of let me do this but its clearly not working. I cannot cause the release action of the button, it simply stays in its active state causing the character to forever run forwards until I disable the macro (can also bug where the keystate remains like that until DS4 is completely turned of). 

An easy fix for this would just to have the toggle macro option be applied to controller buttons as well, I'm not sure why it isnt and I'm not sure why there are 2-3 different UI's for buttonmapping/macros that all have distinct differences but are used for almost the exact same purpose. Basically now I have to make a special action that states "Share" will generate a key down action of "LS-up" with they "keep key state" enabled, then I have to make a second special action that generates a key up action. Not only is this janky to setup, but it could be solved very easily by just having the option to set a macro that simply toggles the repetition of a controller button. 

Again though, tell me if I'm doing something wrong

**Comment by Ryochan7** [comment] 2020-10-30 16:20
The answer is yes. Macros are poorly implemented and have too many flawed assumptions to begin with. There is no really good way to try to make the system better without breaking the system; the big issue is the restricted format used for serializing macros to the profile. I don't use macros in any of my profiles. The system is just left in for backwards compatibility with older profiles.

**Comment by mika-n** [comment] 2020-10-31 14:40
The macro editor and engine comes from the veeeeery old version of DS4Windows and it is already stretching beyond its capabilities. The macro engine would need a complete re-write (not likely to happen in the current version and code base).

Anyway. The keep key state option does leave all buttons to the last state set by the macro. So, if the last state is "key down" and keep state option is enabled then the key remains in "key down" state even after the macro is completed. If you untick the keepState option then macro  engine will reset all keys back to default state even when the macro doesn't explicitly send "key up" event.

Another option you may need is the "synchronized run" in case you keep firing different macros (or the same macro again). When this option is set then the macro engine makes sure that the previous macro is completed before firing on the next macro. Without synchronizedRun option two macros may run side by side (interleaved).

**Comment by mika-n** [comment] 2020-11-23 09:47
closed as "not a bug but implementation feature"  (until someone finds energy to re-write the whole macro engine)

**Closed by mika-n** 2020-11-23 09:47 UTC
