### ISSUE TITLE
Games are detecting ds4 as keyboard instead of Xbox 360

### ISSUE THREAD

**Issue by bonethugsgoat** [Ryochan7/DS4Windows#554] opened 2019-01-23 02:53 UTC
Hard to explain but I been having this off and on issue for months, where as games don't detect my ds4 as a Xbox 360 controller but as a keyboard then buttons are all messed up yet I have xbox 360 enabled in the controller panel of ds4windows. only thing that fixes it is deleting ds4windows and downloading it again but it randomly switches back to detecting it as keyboard after a while, is there any way to fix this?

**Comment by Ryochan7** [comment] 2019-01-25 00:30
This has been brought up before but I cannot reproduce the problem. Unfortunately, if I cannot reproduce the problem then it does not exist to me. The only advice I have for now is to check your Steam settings in BPM. Make sure that Xbox Configuration Support, along with PlayStation Configuration Support, is disabled.

Recently Valve changed the Steam client to enable Xbox Configuration Support by default. That would cause any game launched outside of Steam to use the desktop KB+M profile. That change adversely affects any third party controller mapper.

Other than that, I would need your profiles and special action files in order to provide any help; the log might be helpful as well. Another helpful item would be a video showing the problem happening on your system.

**Comment by zenmetsu** [comment] 2019-02-05 19:09
I might be having a similar problem.  I've noticed that my controller will sometimes get into a state where games do not detect it.  DS4Windows sees the controller, and in fact, when I go to calibrate the controller in windows, I can see the accelerometer inputs and analog inputs just fine.  The condition appears to get triggered when I leave the controller on and it shuts down due to low battery.  Upon re-establishing power (USB to wall charger, not PC), it gets into this weird mode.  The touchpad on the controller controls the mouse just fine, but none of the other buttons or analog sticks get picked up by games.  A reboot always fixes this problem.

You implicate Steam.  I will try killing the Steam client next time this happens and see if there is any effect.

**Comment by Ryochan7** [comment] 2019-02-06 21:15
I will check the dead battery case sometime but I have not been able to reproduce this problem on my end from either unplugging a controller or using the Disconnect BT special action. I have provided builds with some keyboard emulation routines disabled but the issues continued to persist. I have tried other people's profiles and they have worked fine for me. My only assumption can be that the problem is outside the control of DS4Windows. I will probably need someone to debug DS4Windows on their machine in order to help correct this kind of problem.

**Comment by zenmetsu** [comment] 2019-02-06 22:02
Thanks.  I'll be more than happy to troubleshoot this if you tell me what you need.  Is there a debug build that I should run?

**Comment by bonethugsgoat** [comment] 2019-02-07 15:34
Welp I'm still having this issue and been spending days trying to get it to work, I don't even have anything else open, I've pretty much given up at this point, I don't even use Steam with the program nor is there any point since Steam has built in ds4 support anyway, oh well just gonna an L on this one.

**Comment by Ryochan7** [comment] 2019-02-07 16:44
The main route of attack would be load the project in Visual Studio and run DS4Windows with the debugger. Just posting a build with trace messages enabled would probably not help that much.

I would like to know what is causing problems for some people. I can't help fix a problem that I cannot reproduce myself though. I tried to rule out the internal KB+M emulation in the program since I was not able to implement a proper keyboard event reset routine due to slowdown in the code base. Stripping that out did not seem to help people anyway so a better event reset routine probably wouldn't help either.

**Comment by Ryochan7** [comment] 2019-02-07 20:59
The dead battery case seems to work the same as unplugging the controller. I did find one odd problem from experimenting though. If you change profiles as the controller battery dies, the proper Xbox 360 controller unplug event will never get executed. The profile loading routine places an action in the device's thread event loop which won't get executed. That problem could lead to a stray virtual Xbox 360 controller being exposed until another unplug routine is run while switching profiles.

**Comment by zenmetsu** [comment] 2019-02-07 21:50
I will look into setting up VS on my machine.  My dev work is all linux, so this will be a new thing for me.  This problem is annoying enough that I don't mind putting another dev environment up if it means that this could possibly get resolved.

**Comment by zenmetsu** [comment] 2019-02-09 18:06
I just updated to 1.6.10 and found myself stuck in this situation again.  I have two PS4 controllers on two separate systems, and I'm seeing the same behavior.  I'm still working on getting VS set up on one of the two systems, but I can say that I ran into an issue where vibration was not working, but everything else was.  I disconnected/reconnected controller to see if it would resolve, and it did not.  I stopped DS4Windows, relaunched, saw the update to 1.6.10 so I allowed that to install.  After relaunching on 1.6.10, i'm stuck in the mode where only the touchpad/mouse is being recognized again.  

Not sure if that will help you narrow down the issue or not.

**Comment by zenmetsu** [comment] 2019-02-13 17:52
Thanks for the tidbit of info.  I found that I can kill Steam when I am in this state and the controller starts working again after I disconnect and reconnect it.  I actually got a pop up this morning about DS4 failing to get exclusive access, not sure if that was added recently or not.

**Comment by Ryochan7** [comment] 2019-02-14 20:09
That popup has been available since this fork existed. It only pops up if the DS4Windows window is not in focus though. There is also a log message that is written if DS4Windows fails to obtain exclusive access. Unfortunately, there is nothing shown in the main controller listing showing if exclusive access was obtained or not. It wouldn't be difficult to implement something to show the status of exclusive access but I am just paranoid that changing the DS4Form would introduce application slowdown.

**Comment by bonethugsgoat** [comment] 2019-02-20 14:47
One month later and I STILL can't get it to work, I've literally done EVERYTHING even reinstalled Windows, I'm done, thanks anyway.

**Comment by mika-n** [comment] 2019-02-20 15:11
When you re-installed DS4Windows then did you delete all existing profile files in case there are some profile with invalid mappings? If you install the app then your local %APPDATA% folder may still have old config and profile files left behind.

Anyway, it is a bit difficult to debug this issue here because for example I have never seen such a behavior you described. Maybe only compiling a special debug version which would output mapped input-output sequences in a logfile could help here. Anyway, at this point I would assume the issue is with wrong/invalid profile file mappings.

**Comment by Ryochan7** [comment] 2019-02-20 20:19
On 2019/01/24

> Other than that, I would need your profiles and special action files in order to provide any help; the log might be helpful as well. Another helpful item would be a video showing the problem happening on your system.

And then nothing. Almost one month later and you STILL can't get past step one. All your posts summed up is equal to The thing don't work. I literally can't do ANYTHING with that vague non-information.

At this point, I am going to mark this issue as invalid and close it. This might as well be considered a [PEBCAK](https://www.urbandictionary.com/define.php?term=PEBCAK).

**Closed by Ryochan7** 2019-02-20 20:19 UTC
