### ISSUE TITLE
Update 2.2.7 breaks DualSense Trigger usage.

### ISSUE THREAD

**Issue by Serfrost** [Ryochan7/DS4Windows#1899] opened 2021-02-23 22:12 UTC
**Describe the bug**
Triggers work correctly on a DualSense with 2.2.6 after a downgrade; testing 2.2.7 results in the issue returning where triggers will not work, even on the Gamepad Tester website.

**Desktop:**
 - Controller Make and Model: DualSense CFI-ZCT1W
 - OS: Windows 10 Pro Build 20H2 (10.0.19042 Build 19042)
 - DS4Windows Version 2.2.6 | 2.2.7

**Additional context**
Shouldn't require any additional steps to have it occur. Please note that the triggers appear to work within DS4Windows itself, but not within games or the gamepad tester website. Joypad Control Panel also results in no detection.

**Comment by ionzxp** [comment] 2021-02-24 15:20
2.2.7 somehow change trigger two stage mode into normal. I've changed back to disabled then triggers works.

**Comment by Serfrost** [comment] 2021-02-24 15:26
@ionzxp Good catch.

**Comment by Ryochan7** [comment] 2021-02-24 16:09
duplicate of #1888

**Closed by Ryochan7** 2021-02-24 16:09 UTC

**Comment by Serfrost** [comment] 2021-02-24 16:11
My bad, given the title I had no idea that was about the same issue.
