### ISSUE TITLE
This app has NEVER WORKED AT ALL for me compared to the one it's based on.

### ISSUE THREAD

**Issue by PiMPSoFT** [Ryochan7/DS4Windows#2464] opened 2022-07-11 03:22 UTC
This app has NEVER WORKED AT ALL for me compared to the one it's based on by Jays2Kings. The problem is no matter if its my dev machine or a fresh install of Windows with EVERY Microsoft Runtime released since 2000ish this program constantly tells me it needs a runtime to work regardless of the fact I just installed it. Ill stick with the old one even if its not updated cuz it at least works.

**Comment by Masamune3210** [comment] 2022-07-11 03:30
.....then what was the point of this issue, other than for you to whine? It works perfectly fine for others, so I don't know what to tell you exactly

**Comment by PiMPSoFT** [comment] 2022-07-11 04:23
Sorry, my issue is as follows

Why am I prompted every time this app launches to install a specific runtime only once installed, feel like its Groundhog Day & when relaunching AFTER the runtime install & reboot told to repeat the exact same steps?

And I actually was hoping for help after some well deserved criticism, not useless banter. No matter the setup it just fails so I think the dev *might* wanna know that there are repeatable issues specifically with the runtimes. If thats not good enough Ill just use Jays2Kings version since it works.

**Comment by marlop352** [comment] 2022-07-11 04:33
If you don't post your windows version, DS4Windows version and what runtime DS4Windows is complaining about how do you expect the dev to try and reproduce the issue?
And if you are trying to run version 3.1.0 did you install the runtime linked on the release notes?
I personally never had DS4Windows complain about a missing runtime unless the runtime was not installed.

**Comment by Masamune3210** [comment] 2022-07-11 04:37
That's not how criticism works, if you don't build any foundation it's just going to get washed away. Randomly showing up in a repo and complaining that it's never worked and expecting people to be clairvoyant about what you are talking about is not going to get good results no matter where you go

**Comment by PiMPSoFT** [comment] 2022-07-11 05:01
> 

Windows 10 Pro Fresh install with latest Windows Updates and I believe I mentioned it has never worked. I have been trying to use this on 2 different desktops, both similar configs & a laptop, all running Win 10 pro or better with all updates & whatever runtime it tells me 2 with no luck, it just DOESN'T work like the one it's based on cuz when opening it all I see is a prompt to install another runtime. And no matter what runtime the app uses same result. 

It just gets confusing cuz I thought the Jays2Kings version was the one updated when the notice came lol but it wasn't the original DS4Windows (Jays2Kings version) that was updated unfortunately. 

This is also the only app that gives grief about runtimes not working, funny how its like that? Anyway the devs should know it has repeatable issues at least on my 2 Alienware Aurora (R6 & R7) desktops with WIN10 & WIN11 Pro installs, one I actually just setup today due to a hardware upgrade. Do with the info what u will, I'm done playing with this when the original app works without bloated runtimes. Good luck with the app.

**Comment by Dschogo** [comment] 2022-07-11 09:08
As stated in the recent (yesterday) update (3.1.0) u need net runtime 6 
[https://github.com/Ryochan7/DS4Windows/releases/tag/v3.1.0](https://github.com/Ryochan7/DS4Windows/releases/tag/v3.1.0)

Not sure but the previous versions used to need .net 5: should be that [https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.17-windows-x64-installer](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.17-windows-x64-installer)

If that still doesnt work, you can try to run "All-In-One-Runtimes" (just search it on google). 

After the runtime install, restart DS4 (exit it before in the extended taskbar icons) or kill it via taskmanager. 

`without bloated runtimes` - Net framework isnt bloated and probably other software will rely on it anyway

**Comment by tamodolo** [comment] 2022-07-11 11:01
This seems to be caused by modifications made on Windows. If you installed a windows from any source that is not https://www.microsoft.com/pt-br/software-download/windows10 than the chances are you're running Windows with custom settings or modified parts.

This also can be caused by some "unlock" tools (if you know what I mean) that changes Windows default behavior.

Some other tools like Windows Tweaks also can change a list of settings that interfere with default Windows behavior.

For short, if you don't know what you're doing, just stick with this windows version and don not modify it: https://www.microsoft.com/pt-br/software-download/windows10

This issue can be closed without action as @PiMPSoFT only used this as a mean to cause havoc. Next time create a propper issue report with every possible information you can track (including screenshots and logs) for properly handle the issue and correct it if the flaw is indeed from DS4Win.

Also, @Ryochan7, it is good to see you back. You are very wellcome!

**Comment by mooms06** [comment] 2022-07-11 21:37
DS4Windows 3.1.0 and up needs .NET 6.0 runtime, that can be downloaded here:
https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime?cid=getdotnetcore

Of course you need to choose the right one, usually it will be "Run desktop apps" and "X64".

**Comment by mateusmedeiros** [comment] 2022-07-21 17:44
Calling the .NET runtime in the context of a Windows Desktop GUI app a "bloated runtime" unfortunately shows that you don't really know anything about what you're complaining.

Which is ok per se.

Unfortunately, it ends up really deligitimizing your criticism when you don't put yourself in a position of trying to understand what happened first and if the problem is indeed with this app just because the other one works for you and this one doesn't.

And yes, "this one works for me and that one doesn't therefore that one is doing something wrong and this one isn't" is NOT accurate. It's an unintentional fallacy at best. You have to understand WHY one works for you and the other one doesn't to then be able to judge if there's something wrong with the one that doesn't or if it's just a lucky combination of factors that makes the other one work in the first place.

And since your issue isn't easily reproductible, you have to give something more than "Why am I prompted every time this app launches to install a specific runtime only once installed, feel like its Groundhog Day & when relaunching AFTER the runtime install & reboot told to repeat the exact same steps?". It's not like anyone would know why just from that, else that bug would have been fixed already.

I'm also intrigued by this statement:

>It just gets confusing cuz I thought the Jays2Kings version was the one updated when the notice came lol but it wasn't the original DS4Windows (Jays2Kings version) that was updated unfortunately.

because I imagined Jays2Kings version would not show an update popup for Ryochan's version, which means that you probably were using Ryochan's version and it's just the new version that isn't working for you.

All that said, if you don't want any feature of Ryochan's version and Jays2Kings original one works for everything you need, then it's probably a good idea to stick to Jays2Kings' since it works fine with old .NET versions.

**Comment by AsheX1** [comment] 2022-08-09 23:26
how is this still not closed...

**Comment by Masamune3210** [comment] 2022-08-10 03:25
Only people who can close it are moderators, project owner, or the person who opened it. I don't see OP closing it giving the tone of the issue, and all the admins are either busy with life or just haven't gotten around to it yet.

**Comment by mika-n** [comment] 2022-08-10 13:12
@PiMPSoFT  There is a reason why there is the pinned post on the landing page of "Issue" tickets. 

![image](https://user-images.githubusercontent.com/35538525/183909927-f2c64b3f-9386-4dbc-8b49-fe0844667ce8.png)

**Closed** 2023-03-02 05:35 UTC
