### ISSUE TITLE
Any version above 1.5.8 crashes randomly while playing games in Cemu

### ISSUE THREAD

**Issue by reecespieces** [Ryochan7/DS4Windows#454] opened 2018-10-11 03:27 UTC
First time this has ever happened to me using this program. The program just crashes right in the middle of playing and has to be re-started, although it will end up happening again after restarting. This has only ever happened on version 1.5.9.

On Windows 7

**Comment by Overload86** [comment] 2018-10-18 15:57
Why are you not using the newest version then? I am confused.

**Comment by reecespieces** [comment] 2018-10-18 22:30
> 
> 
> Why are you not using the newest version then? I am confused.

Well if you pay attention to the dates, you will see that version 1.5.10 came out 4 days ago, and I submitted this 8 days ago. So, it was the latest version when I initially posted this issue.


I'll try version 1.5.12 (which is currently the latest at the time of me typing this) and see if crashes and report back here.

**Comment by reecespieces** [comment] 2018-10-20 00:31
This is still happening on version 1.5.12

![ds4windows crash](https://user-images.githubusercontent.com/15993751/47249111-b7d19900-d3dd-11e8-9fa6-08a32eefcf14.png)


This issue was introduced in version 1.5.9 and seems to affect every version after that.


So I'm sticking with 1.5.8 until this gets some recognition.


I wouldn't be surprised at all if this only happens on Windows 7

**Comment by Overload86** [comment] 2018-10-21 00:56
I stand corrected. Sorry for the stupid question then, I was not aware those versions all came in such a short timeframe. What are the problem details in your screenshot? If I remember correctly, windows 7 should give you a bit more info there. Haven't had an issue like that on Windows 10 64 bit with any version of DS4 Windows.
Maybe it is the Xbox driver?

**Comment by Ryochan7** [comment] 2018-10-22 06:04
Are you using the UDP server when DS4Windows crashes? That might narrow things down a bit since the UDP server was one main change made with version 1.5.9.

I will try the latest DS4Windows on Windows 7 just to narrow down that possibility. It has been a little while since I tested on Windows 7.

**Comment by reecespieces** [comment] 2018-10-23 02:45
Yes, I have UDP server enabled, although it only seems to happen when using Cemu. I haven't been able to reproduce the crash using PCSX2. It usually crashes right after moving the dpad or analogue stick in any game in Cemu.

`Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	DS4Windows.exe
  Problem Signature 02:	1.5.13.0
  Problem Signature 03:	5bcb7284
  Problem Signature 04:	System
  Problem Signature 05:	4.6.1055.0
  Problem Signature 06:	563c0ff8
  Problem Signature 07:	20bc
  Problem Signature 08:	2a
  Problem Signature 09:	System.InvalidOperationException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	1ab9
  Additional Information 2:	1ab9622599fe9b5608875cd9c2646947
  Additional Information 3:	5aad
  Additional Information 4:	5aadc777430304b616ce8a541dede374

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
`


It

**Comment by Ryochan7** [comment] 2018-10-24 15:36
One minor tweak seemed to be all that was needed on my end. Without the most recent commit, DS4Windows would usually crash in a matter of 2 minutes while Cemu was running. With the most recent change, I have run Cemu multiple times with one test run lasting over an hour without a problem.

**Comment by jvn10** [comment] 2018-10-27 08:34
I believe this is the same problem I have, when I use cemu with udp/motion controls enabled my ds4windows program will crash after a few minutes. I can play with udp disabled without any issues

Also I have seen ds4windows.exe stop working when I open padtest to see if motion controls are working

**Comment by elemelek** [comment] 2018-10-30 17:21
Using the version 1.5.14 for a while. Application not closing by itself anymore.
Seems to be fixed for me.

**Comment by reecespieces** [comment] 2018-11-01 00:09
It doesn't happen so quickly anymore but it did just happen to me on 1.5.14.

Again, on Windows 7

```
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	DS4Windows.exe
  Problem Signature 02:	1.5.14.0
  Problem Signature 03:	5bd4abc9
  Problem Signature 04:	System
  Problem Signature 05:	4.6.1055.0
  Problem Signature 06:	563c0ff8
  Problem Signature 07:	20bc
  Problem Signature 08:	2a
  Problem Signature 09:	System.InvalidOperationException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	1ab9
  Additional Information 2:	1ab9622599fe9b5608875cd9c2646947
  Additional Information 3:	5aad
  Additional Information 4:	5aadc777430304b616ce8a541dede374

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```

**Comment by fehmi1907** [comment] 2018-11-03 04:34
I just had a crash while using CEMU with UDP server enabled on Windows 10. Below are the logs from Event Viewer -

`Application: DS4Windows.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Net.Sockets.SocketAsyncEventArgs.StartConfiguring()
   at System.Net.Sockets.SocketAsyncEventArgs.SetBufferInternal(Byte[], Int32, Int32)
   at DS4Windows.UdpServer.NewReportIncoming(DS4Windows.DualShockPadMeta ByRef, DS4Windows.DS4State)
   at DS4Windows.ControlService+<>c__DisplayClass42_0.<Start>b__2(System.Object, System.EventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at DS4Windows.DS4Device.performDs4Input()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()`

`Faulting application name: DS4Windows.exe, version: 1.5.14.0, time stamp: 0x5bd4abc9
Faulting module name: KERNELBASE.dll, version: 10.0.14393.2457, time stamp: 0x5b7e2adb
Exception code: 0xe0434352
Fault offset: 0x0000000000033c58
Faulting process id: 0x19dc
Faulting application start time: 0x01d473215d797455
Faulting application path: C:\Users\Fehmi\Documents\DS4Windows\DS4Windows.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 096ccb86-8536-43e3-935f-a0db8d416bb4
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by fehmi1907** [comment] 2018-11-03 04:36
I just had a crash while using CEMU with UDP server enabled on Windows 10. Below are the logs from Event Viewer -

>Application: DS4Windows.exe
>Framework Version: v4.0.30319
>Description: The process was terminated due to an unhandled exception.
>Exception Info: System.InvalidOperationException
>   at System.Net.Sockets.SocketAsyncEventArgs.StartConfiguring()
>   at System.Net.Sockets.SocketAsyncEventArgs.SetBufferInternal(Byte[], Int32, Int32)
>   at DS4Windows.UdpServer.NewReportIncoming(DS4Windows.DualShockPadMeta ByRef, DS4Windows.DS4State)
>   at DS4Windows.ControlService+<>c__DisplayClass42_0.<Start>b__2(System.Object, System.EventArgs)
>   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
>   at DS4Windows.DS4Device.performDs4Input()
>   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>   at System.Threading.ThreadHelper.ThreadStart()

>Faulting application name: DS4Windows.exe, version: 1.5.14.0, time stamp: 0x5bd4abc9
>Faulting module name: KERNELBASE.dll, version: 10.0.14393.2457, time stamp: 0x5b7e2adb
>Exception code: 0xe0434352
>Fault offset: 0x0000000000033c58
>Faulting process id: 0x19dc
>Faulting application start time: 0x01d473215d797455
>Faulting application path: C:\Users\Fehmi\Documents\DS4Windows\DS4Windows.exe
>Faulting module path: C:\Windows\System32\KERNELBASE.dll
>Report Id: 096ccb86-8536-43e3-935f-a0db8d416bb4
>Faulting package full name: 
>Faulting package-relative application ID:

**Comment by romeodeng007** [comment] 2018-11-03 06:07
I can reproduce this problem in every 2 minutes by using 1.5.14 while using CEMU with UDP enable. Also tried 1.5.12, the same issue occurred. Let me know how can I provide you more information.

**Comment by romeodeng007** [comment] 2018-11-03 06:16
Otherwise, I tried 1.5.8 DS4Windows, it didn't crash in 8+ minutes at least

**Comment by Ryochan7** [comment] 2018-11-03 19:44
Can you try out this test executable and see if the problem still happens? This version uses the ReaderWriterLockSlim instance to provide a safeguard around the pool index. Hopefully this ensures that the same SocketAsyncEventArgs instance is not used in multiple threads at the same time. I hesitated implementing any type of safeguard before due to performance concerns. The previous version did work on my system though.

http://ryochan7.xyz/ds4windows/test/DS4Windows_20181103.zip

**Comment by romeodeng007** [comment] 2018-11-04 00:10
Hi @Ryochan7, I replaced the 1.5.14 executable file by your test one from above. Looks like the issue is resolved, I played about 1 hour without any crash by using wired connection and UDP enable. I will test it later on with wireless connection but I think it should work as the same way as wired connection in theoretically. Thank you

**Comment by Ryochan7** [comment] 2018-11-05 21:09
That is good news. I might perform a few more experiments before releasing a patch version. I will try to get a new build released in the next couple of days.

**Comment by Ryochan7** [comment] 2018-11-08 06:18
Version 1.5.15 includes the fix.

**Closed by Ryochan7** 2018-11-08 06:18 UTC
