### ISSUE TITLE
Mouse Sensitivity Joystick Half Working

### ISSUE THREAD

**Issue by mmillar-bolis** [Ryochan7/DS4Windows#133] opened 2017-10-16 08:17 UTC
When setting the right stick's axis to mouse movement and specifying mouse sensitivity for each direction, only the negative axis' sensitivity changes.

It appears that if a negative axis is set, the positive axis functions only at the overall sensitivity. If the negative axis' sensitivity is not set, then the positive axis will operate at it's specified sensitivity.

For example, if I set a general sensitivity of 25, but then macro mouse movement left and right to RS left and right respectively, with sensitivities of 100 each, only RS left is affected by the sensitivity change. RS right still acts like it's sensitivity is 25. despite being set to 100 explicitly. If I unset RS left's sensitivity, RS right now functions at it's specified sensitivity.

The desired result, in my use case, is to have more sensitive horizontal movement when compared to vertical movement.

**Comment by Ryochan7** [comment] 2017-10-17 02:59
I have never played with setting a mouse speed per direction. I always just use the Mouse Sensitivity option in the Other group when mapping RS to mouse movement. First the behavior in the old DS4Windows will have to be checked to see if the behavior worked there. That functionality has not really been modified in the code so it might not work as expected there either.

**Comment by Ryochan7** [comment] 2017-10-17 03:08
It has been confirmed that this functionality did not work in the old Jays2Kings version either. Change Mouse Sensitivity will work in the positive axis direction only if the negative axis direction has not been modified. Otherwise, the setting for the positive axis direction will not work.

**Comment by Ryochan7** [comment] 2017-10-26 07:44
Extras execution was being done out of order. I switched the code to have extras parsed before actions instead of afterwards. Now Change Mouse Sensitivity works as expected. I will wait before closing this issue because I am not sure whether there will be regressions due to this change.

**Comment by Ryochan7** [comment] 2017-10-28 03:49
It seems like this works fine.

**Closed by Ryochan7** 2017-10-28 03:49 UTC
Labels: bug

**Comment by mmillar-bolis** [comment] 2017-10-30 18:39
My apologies for the late response! I just tried out your changes and they appear to function correctly. Thank you so much for this!
