### ISSUE TITLE
Rumble doesn't work in-game

### ISSUE THREAD

**Issue by NagisaFawkes** [Ryochan7/DS4Windows#651] opened 2019-04-09 00:34 UTC
Rumble works when testing inside the profile editor, but doesn't work in any non-Steam games I've tried  (tried Origin and Gog games so far). It doesn't work either via bluetooth or USB, and the batteries are far from being low.

**Comment by Ryochan7** [comment] 2019-04-09 03:00
Unfortunately, that is completely intentional. From the version 1.7.3 Changelog:

> Disabled force feedback support for now

There are some unresolved problems with the ViGEm client library that cause some rumble state changes to not get transmitted to the application. That can cause the DS4 controller to constantly rumble until the controller is disconnected from your PC. I wanted to get a new release out that resolved the issues with the x86 builds introduced by the library so I commented out the force feedback hooks. Other rumble features are still available to use in DS4Windows.

This is still a work in progress. So far, no solid technique has been found that would work without possibly having to change the ViGEmBus driver.

**Comment by mika-n** [comment] 2019-04-09 05:47
@Ryochan7 Take a look at the pull request https://github.com/Ryochan7/DS4Windows/pulls

It has a watchdog timer to stop the potentially stuck rumble motor plus fix to "loadProfile special action locked down to one level" issues.

If someone wants to completely disable rumble motor then they could set the rumble level to 0% in DS4Win rumble options. This way both "no rumble" vs "workaround to stuck rumble motor" functionalities can be set per profile.

One way to improve this pull request would be to add a customized "N secs timeout" option in DS4Win rumble options. If the now fixed 2secs timeout is too short for some games (GTA?) then user could modify it per profile.

In my tests this change workarounds the ViGem rumble feedback bug well enough and it is a simple change in code logic and doesn't have any effect in performance.

**Comment by Ryochan7** [comment] 2019-04-09 08:53
Had a brainstorm earlier and took a few attempts at tackling this again. Based on my tests, I think I stumbled upon a reasonable workaround in the library. It even works fine in the ParallelN64 Retroarch core and that core does some weird things.

@mika-n I still have not pulled and reviewed that pull request. Other issues have kept me from checking it out.

**Comment by Ryochan7** [comment] 2019-04-09 19:34
I posted my findings to the ViGEm Discord server. It will have to be reviewed and Nefarius will likely want to make a cleaner version of the change.

https://gist.github.com/Ryochan7/f41bd345c5592d88f37ff24773e1e882

Nefarius posted a little snippet about the Inverted Call Model that was interesting and showed that the approach used for the workaround is a standard technique that can be used when using that model.

>  If it’s important for the application to not miss any event notifications, it will need to be sure to always keep one or more IOCTL_OSR_INVERT_NOTIFICATION Requests pending in the driver.  The application would do this by calling DeviceIoControl multiple times, most likely using asynchronous completing with an OVERLAPPED structure for each request, and by immediately re-issuing the IOCTL each time it is completed by the driver to notify the application of an event occurrence.

https://www.osr.com/nt-insider/2013-issue1/inverted-call-model-kmdf/

**Comment by mika-n** [comment] 2019-04-10 07:40
This is excellent news if the fix can be done in a user mode client driver side instead in the kernel mode driver (ie. faster and easier to release generally available fix). Good work.

**Comment by Ryochan7** [comment] 2019-04-11 23:24
Luckily this type of tweak should help with other programs using the ViGEmClient library once it goes upstream. I am guessing Nefarius would probably want to use a proper queue instance and maybe a struct to hold the references. This version is fine for me and it has a little less overhead. I want to get a new version of DS4Windows out in a couple of days with the change.

**Comment by DaRkL3AD3R** [comment] 2019-04-12 13:56
Looking forward to the update. For future reference, might it be possible to implement some kind of warning message when an intended feature regression is made so users like myself don't go on a wild goose chase trying to figure out why rumble doesn't work? I know it's in the changelog but let's be honest it's not exactly in your face when you run the updater for DS4Windows.

**Comment by Ryochan7** [comment] 2019-04-16 20:44
The most I would consider doing would be to add the Changelog text to the updater prompt window. It can sometimes be inconvenient that people are dependent on my executive decisions. At least most of those decisions have been in the attempt to get better application performance.

**Comment by Ryochan7** [comment] 2019-04-19 11:27
Version 1.7.4 is now out and force feedback has been re-enabled.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.7.4/DS4Windows_1.7.4_x64.zip

**Closed by Ryochan7** 2019-04-19 11:27 UTC
