### ISSUE TITLE
Connecting a DualShock 4 Stops DS4Windows

### ISSUE THREAD

**Issue by Dinir** [Ryochan7/DS4Windows#3063] opened 2023-08-27 13:29 UTC
**Describe the bug**
DS4Windows is running. I press PS button to connect it wireless to the system.
As I think it's connected by now, after seeing it cycling through few light colors, the controller turns off. I check DS4Windows and see the Start/Stop button is showing 'Start'.

It happens one time, then never happens again until I reboot the computer. Then it happens one time again.

**To Reproduce**
1. Have the program running.
2. Connect the controller. In my case, I have a Bluetooth dongle on, so it was pressing the home button to wake the controller up.

**Expected behavior**
Controller is connected and ready. Without DS4Windows stopping itself.

**Screenshots and Logs**
[Log](https://github.com/Ryochan7/DS4Windows/files/12448069/connecteded.txt) `ViGEm Device Plugin Failed.`

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2G)
 - OS: Windows 10 Pro x64 10.0.19045.0
 - DS4Windows Version 3.2.13

**Comment by Ryochan7** [comment] 2023-08-27 19:43
`08/21/2023 00:17:39: ViGEm Device Plugin Failed. Likely an internal ViGEmBus problem. Closing connection. If the issue persists, please close DS4Windows and then reboot Windows.`

This is a persistent issue that comes up so rarely that it has been impossible to diagnose. I cannot remember the last time I have encountered the error myself; it would tend to happen on attempting to resume from suspend when suspending did not work on my PC. It has to be some bug in the C++ ViGEmClient library. The routine is returning an error code that is getting pushed up to the DS4Windows code. My mistake is not passing that error code to the Log which should be corrected.

As an aside, I just found an oversight in the ViGEm.NET code regarding a couple function calls. Doubt it would matter for this issue but it looks like the next version of DS4Windows will have an updated Nefarius.ViGEm.Client.dll library file.

**Comment by Ryochan7** [comment] 2023-08-29 17:19
Both changes have been made. It seems to be better than however .NET handles the argument otherwise. There is no default argument when it comes to the final LPVOID variable in the C++ code.

Display Windows error code for unknown ViGEmFailure in the Log:
https://github.com/Ryochan7/DS4Windows/commit/1f032605357e6f459ff0efdaec42b86b971fd372

Fixed function arguments for feedback notification hooks:
https://github.com/Ryochan7/ViGEm.NET/commit/25febf4cb1995bed0054a0c806f7acd7321113e2

**Comment by Dinir** [comment] 2023-09-11 14:23
I got the updated version so it shows Error Code when it happens. Hope this helps.
[Log](https://github.com/Ryochan7/DS4Windows/files/12577250/connectatwo.txt) `Error Code -2147467259.`

**Comment by Ryochan7** [comment] 2023-09-14 04:47
Same. Happened when starting DS4Windows after it working just a minute before on the previous launch. It worked fine after clicking Start manually in that case.

> 2023-09-13 00:03:54.1099|WARN|ViGEm Device Plugin Failed. Error Code -2147467259. Likely an internal ViGEmBus problem. Closing connection. If the issue persists, please close DS4Windows and then reboot Windows.

If only there were a way to have this problem occur on demand. As it is, I am pretty sure this is not my problem but I cannot attempt to debug it without being able to reliably reproduce the problem.

**Closed** 2023-09-28 21:31 UTC

**Comment by Dinir** [comment] 2023-09-29 14:05
It always happens once every boot on my computer. Would be great if I can help.
I started getting a log entry saying `read failure: 995` recently.
[Log](https://github.com/Ryochan7/DS4Windows/files/12766360/connectthree.txt)
