### ISSUE TITLE
rumble + lightbar not working on copycat ds4

### ISSUE THREAD

**Issue by commander282** [Ryochan7/DS4Windows#2643] opened 2022-10-17 02:14 UTC
How can I fix the rumble and lightbar not working on my copycat ds4 to the newest version?

**Comment by Yohoki** [comment] 2022-10-19 01:16
Rumble (and I believe lightbar) is not enabled on current version if you are in DS4 mode. If that doesn't answer your question, we may need some more info.

**Comment by Yohoki** [comment] 2022-11-10 00:56
This thread is outdated and should probably be closed.

Rumble and Lightbar should both be working again, as these features have been added back in after some fixes were provided for the drivers. If you are still having this issue on the newest version, let us know and we can give you some instructions on how to get your third party controller added.

___

There's a lot of open issue tickets like this. It might be helpful, @Ryochan7, if someone could go through and get rid of some of these older threads. I wouldn't mind going through the open threads for you and closing most of the ones that have outdated info, if you would like to give me that option.

**Comment by Skcyte** [comment] 2022-11-13 11:11
Yeah mine is still not working. Any solution/help to this is much appreciated.

**Comment by psycodeoday** [comment] 2022-12-31 01:46
> on the software side DS4Windows supports DS4 Rumble and lightbar without any issues(even in copycat mode) The problem might be that your copycat controller either doesn't support Rumble and lightbar, or they're broken/missing

oh don't go that way, please.

**BTW.** When I connect those two copycat pads via/trough usb cabe (bypassing Bluetooth), then all issues disappear (vibration and lights works fine), so the issue is not with lights and vibration health or compatibility itself, but with bluetooth comuniaction/translation only.
.
.
.
> This thread is outdated and should probably be closed.
> Rumble and Lightbar should both be working again, as these features have been added back in after some fixes were provided for the drivers. If you are still having this issue on the newest version, let us know and we can give you some instructions on how to get your third party controller added.
> 
.
.
No this case is not outdated, we still have issues with it. 

in 3.1.18 everything was perfectly fine (color lights and vibration works on my both pad (copycats))
From 3.1.1 to 3.1.10 no lights (only white color with no reaction during color-picking/changing) and no vibration.

Since **3.1.11, and 3.1.12** still no lights, but vibration start to work again but with different behaviour: 
During "test heavy" or "test light" it gives me only one quick shot and stops itself. I have to click on and off repeatedly to produce constant vibration test. (in 3.0.18, one button click produce constant vibration, until I click again to stop it)
(copycat checkbox in settings-device options gives no changes)

**Closed** 2023-11-10 21:25 UTC

**Comment by THE-EXP** [comment] 2023-11-11 15:47
> > on the software side DS4Windows supports DS4 Rumble and lightbar without any issues(even in copycat mode) The problem might be that your copycat controller either doesn't support Rumble and lightbar, or they're broken/missing
> 
> oh don't go that way, please.
> 
> **BTW.** When I connect those two copycat pads via/trough usb cabe (bypassing Bluetooth), then all issues disappear (vibration and lights works fine), so the issue is not with lights and vibration health or compatibility itself, but with bluetooth comuniaction/translation only. . . .

Well at least my comment was helpful
