### ISSUE TITLE
5/11/2019 9:59:18 PM: Could not connect to ViGEmBus. Please check the status of the System device in Device Manager and if Visual C++ 2017 Redistributable is installed.

### ISSUE THREAD

**Issue by TheDizee** [Ryochan7/DS4Windows#699] opened 2019-05-12 03:19 UTC
Was working last night, now its giving me that error. Tried uninstalling the drivers and such, no luck

**Comment by mika-n** [comment] 2019-05-12 07:46
Take a look at this issue: https://github.com/Ryochan7/DS4Windows/issues/697
- reboot the pc
- make sure you have the latest ViGem driver version
- cleanup existing config and profile files to test if there is something weird in existing config files

And general troubleshooting tips (especially make sure in DeviceManager there are no HID and ViGem driver in disabled state:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

**Comment by Qoyyuum** [comment] 2019-05-24 03:09
I also have the same problem but I don't know if @TheDizee have gone through the Troubleshooting process as I have.

My PC is a fresh install of Win10. Proceeded to run Step 1, it downloaded and tried to install but it failed.

![image](https://user-images.githubusercontent.com/971309/58299406-b653cd80-7e11-11e9-8d07-2ad5435fefb6.png)

Log says:

```
2019-05-24 10:46:17 AM: DS4Windows version 1.7.8
2019-05-24 10:46:17 AM: LinkedProfiles.xml can't be found.
2019-05-24 10:46:18 AM: Could not connect to ViGEmBus. Please check the status of the System device in Device Manager and if Visual C++ 2017 Redistributable is installed.
```

- I have rebooted my PC several times
- I can confirm that the necessary C++ is installed.
![image](https://user-images.githubusercontent.com/971309/58299365-90c6c400-7e11-11e9-8688-049afeaad3ec.png)

- I can confirm that my controller can connect and have tested that its working through control panel and other tests.

![image](https://user-images.githubusercontent.com/971309/58299566-2bbf9e00-7e12-11e9-86b2-88a42a463d86.png)
![image](https://user-images.githubusercontent.com/971309/58299598-46921280-7e12-11e9-8c4d-d4a607b77936.png)

- I have already tried deleting my profile folder and other files in the %APPDATA%/DS4Windows and restarting DS4Windows
- I then manually tried to install ViGemBus manually from https://github.com/ViGEm/ViGEmBus/releases

Then retried to install and it its now working.
![image](https://user-images.githubusercontent.com/971309/58300240-5d396900-7e14-11e9-85fb-b1778b9f43a0.png)

Hope this helps.

**Comment by mika-n** [comment] 2019-05-24 07:26
This issue may be because of a small bug in the previous version of ViGem driver and DS4Win app installer. Sometimes the installer reported a false "failed to install ViGEm driver" status. The latest version of ViGem installer solved that issue, but the current V1.7.8 DS4Windows installer uses one step older version of ViGem driver. The latest development version of DS4Win already uses the newer version but that DS4Win version is not yet released as an official version..

The workaround to this installer issue is to install ViGem driver separately BEFORE running DS4Win app installer for the first time. And this is what you did. DS4Win does detect if there is an existing version of ViGem driver and doesn't try to re-install it.

**Comment by Ryochan7** [comment] 2019-05-25 07:10
Unfortunately, very little of my time has been spent on projects lately. Other personal issues have taken higher priority. Physical therapy has been the top priority and has been a major time investment each day for the past few weeks. There would only be a couple of other changes that I would like to test before pushing out another release.

**Comment by Ryochan7** [comment] 2019-05-27 20:04
I am in the middle of doing a fresh install of Windows 10. The Welcome Dialog ends up showing an Install Failed message while the ViGEm installer is still running. The ViGEm installer was still able to install ViGEmBus and DS4Windows updated showing that the installation completed. This failed message issue will be looked at once I get Visual Studio and other tools installed and configured.

**Comment by zykezero** [comment] 2019-07-09 03:39
for anyone else coming here, to fix this issue for me I downloaded the ViGem driver from the link above, used that to uninstall the driver and then installed it through DS4Windows and now it's working.

 https://github.com/ViGEm/ViGEmBus/releases

**Closed** 2019-08-17 03:35 UTC
