### ISSUE TITLE
DS4Windows keeps crashing when trying to edit profile

### ISSUE THREAD

**Issue by misterright1** [Ryochan7/DS4Windows#1337] opened 2020-06-11 16:01 UTC
Whatever I do, reinstall. Delete all the stuff then paste it again. %AppData% folder everything. I installed all the required software. Tried different versions still nothing, it still crashes when I click to edit a profile.

**Comment by mika-n** [comment] 2020-06-11 20:21
Log files?  Please read the "Read this before posting a new ticket" pinned post. It explains what information to provide.

**Comment by misterright1** [comment] 2020-06-11 20:23
[ds4windows_log_20200608.3.txt](https://github.com/Ryochan7/DS4Windows/files/4767121/ds4windows_log_20200608.3.txt)
[ds4windows_log_20200610.0.txt](https://github.com/Ryochan7/DS4Windows/files/4767122/ds4windows_log_20200610.0.txt)
[ds4windows_log_20200610.1.txt](https://github.com/Ryochan7/DS4Windows/files/4767123/ds4windows_log_20200610.1.txt)
[ds4windows_log_20200610.2.txt](https://github.com/Ryochan7/DS4Windows/files/4767125/ds4windows_log_20200610.2.txt)
[ds4windows_log_20200610.3.txt](https://github.com/Ryochan7/DS4Windows/files/4767126/ds4windows_log_20200610.3.txt)
[ds4windows_log_20200610.4.txt](https://github.com/Ryochan7/DS4Windows/files/4767127/ds4windows_log_20200610.4.txt)
[ds4windows_log_20200611.0.txt](https://github.com/Ryochan7/DS4Windows/files/4767128/ds4windows_log_20200611.0.txt)
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/4767129/ds4windows_log.txt)

**Comment by mika-n** [comment] 2020-06-11 20:31
The main issue is the following message. Data writing to the gamepad fails, so the app thinks the gamepad is gone and does a "disconnect" routine. The crash message there is just an additional "bug message" (should be fixed) but it is not the root cause.

`2020-06-11 18:03:29.5558|INFO|Gamepad data write connection is lost. Disconnecting the gamepad. LastErrorCode=1167
`
Try unticking "Enable Data output to DS4" option in profile settings. Does it help? By unticking this option lightbar and rumble doesn't work but it will be interesting to know how it goes.

Also, Is this a genuine Sony DS4 revision1 gamepad or a Chinese fake copy? The gamepad seems to announce itself as Sony DS4 v1 gamepad, but there are lots of fake gamepads with that hardware ID. Those often work over USB connection, but struggle over BT.
 
Is this 5-6 years old DS4 v1 gamepad or did you purchased it recently? If you have purchased it within 4-5 years then it is probably a fake copy because Sony haven't manufactured those rev1 gamepads in years. When the PS4 Slim was released all DS4 gamepads have been DS4 rev2 versions.

**Comment by misterright1** [comment] 2020-06-11 20:46
I purchased it on 1st of December 2017, been using it ever since. It is a genuine controller, used it on a ps4 a couple of times, everything worked fine. It stopped working with my latest Windows 10 2004 version reinstall. When I click a profile or try to edit a profile the whole program hangs for 4 seconds and shuts down, so I am unable to untick enable data output to ds4.

**Comment by mika-n** [comment] 2020-06-11 20:51
Even when you edit a profile without DS4 gamepad installed?
Do you try to edit profiles via "Profiles" tab page or via "Controllers" tab page (if a gamepad is connected)?

**Comment by misterright1** [comment] 2020-06-11 20:53
yes it crashes during all those situations.

**Comment by mika-n** [comment] 2020-06-11 20:57
Veeery weird. Try editing the profile in Notepad and set OutputDataToDS4 option to false.

Or try removing all files (backup to zip file old files) and sub folders i %APPDATA%\DS4Windows (ie. don't paste back anything from an existing configuration). This would tell us if there is something wrong in existing files.

**Comment by misterright1** [comment] 2020-06-11 21:20
I have done the part of removing all files before with no avail. I made that option false. Just made it hang a bit more than it would normally.
[ds4windows_log_20200611.3.txt](https://github.com/Ryochan7/DS4Windows/files/4767413/ds4windows_log_20200611.3.txt)

**Comment by mika-n** [comment] 2020-06-11 21:33
I guess one last hope would be to run the debug version and see if the logfile there tells more about the issue.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

And you didn't install DS4Windows under c:\program files folder, did you? In some PCs the app doesn' work there because it was not installed via "a real installer" and this way setting certain file permissions below programFiles folder. Try to run the app from c:\apps\ds4windows (or whatever) custom folder.

**Comment by misterright1** [comment] 2020-06-12 01:33
I ran it from desktop still the same, ran the debugger, these are the logs from it. 
[ds4windows_log_20200612.1.txt](https://github.com/Ryochan7/DS4Windows/files/4768173/ds4windows_log_20200612.1.txt)
[ds4windows_log_20200612.2.txt](https://github.com/Ryochan7/DS4Windows/files/4768174/ds4windows_log_20200612.2.txt)
[ds4windows_log_20200612.3.txt](https://github.com/Ryochan7/DS4Windows/files/4768175/ds4windows_log_20200612.3.txt)
[ds4windows_log_20200612.0.txt](https://github.com/Ryochan7/DS4Windows/files/4768176/ds4windows_log_20200612.0.txt)

**Comment by misterright1** [comment] 2020-06-15 13:32
Apprently Jayz2Kings version works properly, but lacking all the features of your version of course. This is a big pickle.

**Comment by mika-n** [comment] 2020-06-15 19:06
There has been some "null check" fixes, so hopefully the next version fixes the issue. However, it is a bit weird why the app keeps throwing the NULL error in your setup. Some weird permission issue. All I can suggest is
- Install the app somewhere else than c:\program folder or progarmfolder(86)
- Use appdata path to save config and profile files instead of program folder

**Comment by Ryochan7** [comment] 2020-06-15 20:29
Looking at the one log file, the code is supposedly failing around the following call.

```
ImageSource temp = sourceConverter.
  ConvertFromString("pack://application:,,,/DS4Windows;component/Resources/rainbowCCrop.png") as ImageSource;
```

https://github.com/Ryochan7/DS4Windows/blob/8ce44e5d6c18dcf29cc14766c0071576e4591e69/DS4Windows/DS4Forms/ViewModels/ProfileSettingsViewModel.cs#L1561

Did you try to build DS4Windows from the source yourself? That resource should be available in the main binary. I would suggest you perform a fresh install of DS4Windows either way. Purge the install folder and the %AppData%\DS4Windows folder if you are using the AppData option

**Comment by misterright1** [comment] 2020-06-15 20:45
@Ryochan7 I did not try to build the with the source code, I downloaded the release versions. I deleted the data folders many times, still to no avail. I tried launching it from d:/ds4windows directory, just hangs longer as apposed to when it's in program files.

**Comment by misterright1** [comment] 2020-06-18 08:27
Created a new administrive account, and it works now.

**Closed** 2020-06-24 20:28 UTC
