### ISSUE TITLE
DS4 Windows Typing keys

### ISSUE THREAD

**Issue by TimTheNerdTV** [Ryochan7/DS4Windows#252] opened 2018-04-02 20:51 UTC
When DS4 windows is connected Windows thinks its typing keys uncontrollably. How do I fix this?

**Comment by vpontin** [comment] 2018-04-02 23:01
Perharps you have a profile with button > keys activated?

**Comment by TimTheNerdTV** [comment] 2018-04-02 23:03
I don't think that's it. I opened a brand new profile.

**Comment by Ryochan7** [comment] 2018-04-03 06:41
One possible reason is that no dead zones are set. Opening a brand new config should not act like that. The default config is more suited for mapping to an Xbox 360 controller although the default config is not optimal. Adding keyboard key actions to some inputs, such as LS, would likely cause keys to be activated immediately since the analog stick would likely not get completely re-centered. Another possibility is mapping keys to gyro controls without increasing the dead zone.

An issue that I just stumbled across is regarding how profile resetting occurs when selecting the **New Profile** option. Dead zones are reset but actions are not returned to default values. Using a KB+M profile and then attempting to create brand new profile can cause keyboard key actions to get activated unintentionally.

**Comment by dreamcat4** [comment] 2018-04-03 19:16
Hello @Ryochan7, 

During the last few days I have also been experiencing the exact same issue on the latest version of your fork 1.4.116. With much frustration. These unwanted keypresses occurs immediately and for the full duration while DS4Windows is operational. Anytime it is in the 'Started' mode. The problem stops immediately when clicking the 'Stop' button in the corner. Tried removing / reinstalling all gamepad devices. It made no difference whatsoever.

This is also on the very latest version of windows 10. After fully updating windows, I also thought to update DS4Windows program itself too. The previous version seems like it might have been `DS4Windows_1.4.107_x64`, or `DS4Windows_1.4.88_x64`. However I updated DS4Windows without actually bothering to re-test any of it's current functionality (since doing my windows 10 update). So until now I was not sure which software was causing this problem (windows 10 updates itself, or DS4Windows itself). Anyhow, thanks for your comment above. This has lead to great progress !

My report as follows:
===

While still being able to edit a profile, I just discovered that (by clicking for any key reassignment in the profile edit screen), it seem to be only the `ESC` key that is constantly being depressed and activated all the time. Hope that information is useful.

The other thing is you said above @Ryochan7 was to try creating a new profile instead. However while this bug is occuring, we cannot use the GUI properly to do most tasks. Even to switch the remembered profiles of the controlers list in the 1st tab. Because controllers onl appear in that list while DS4Windows is in 'Started' mode.... and of corse that is all the time when the `ESC` key is constantly depressing and so preventing any re-selection of a different user profile. Or to create / save a new profile from that place either (for same reason, the `ESC` key bug is interfering).

So instead:

I edited by hand the settings file located at: `C:\Users\USERNAME\AppData\Roaming\DS4Windows\Profiles.xml`. To just change the currently selected / rememberd profile to be a newly created blank 'New profile'. Which was created in the GUI while DS4Windows was in 'Stopped' mode.

Unfortunately that did not stop the Bug. Same problem still happening. So the issue must lie elsewhere in the user setting folder.

Then I searched the entire user settings folder for the substring `esc` and didnt find anything existing assigned whatsoever which matched that keypress (the ESC key).

So this seems to me like some genuine bug in DS4Windows. When one of settings file(s) is screwed up, or there is some upgrade from previous version. Or the XML is re-saved incorrectly. Then the program is not reading the settings correct anymore? Leading to this bug?

When I completely moved (disappeared the entire user settings folder) `AppData/Roaming/DS4Windows`. Relaunch, it ask me, and create again from scratch a new folder in AppData. Finally it stopped happening.

So that is the solution it seems... **wipe out the entire settings folder @ `C:\Users\USERNAME\AppData\Roaming\DS4Windows\`**

Until it can be narrowed down anything more than that. Here I have zipped up my settings folder for you to example / try to reproduce the bug also yourself on your local system.

Link to BAD Settings user folder:

https://www.dropbox.com/sh/yt8fpt92i5pfequ/AADt_lMJsFK0vuj-EEeAH_uGa?dl=0

Kind Regards,

**Comment by Ryochan7** [comment] 2018-04-04 06:16
Looking over some of your profiles shows that you should have experienced problems earlier on. I cannot remember if there were implied dead zones set in the source code of the old versions if the set profile dead zone is 0.0. It looks like ESC is likely always activated when it is mapped to a direction on RS. Maybe the right stick on your controller is starting to get worn out? Having no dead zone is place could cause the output event to always get generated if the stick is slightly stuck in the direction that corresponds to a control.

On my profiles, I usually use a value of 0.09 (11 for the profile XML representation) for the dead zones for the two sticks. I usually do that for XInput profiles as well and then play around with the anti-dead zone values depending on the game. As an example of a heavy KB+M profile that I use, I will share my profile for Warhammer 40K: Space Marine.

http://ryochan7.xyz/ds4windows/temp/war40k.xml

**Comment by dreamcat4** [comment] 2018-04-04 09:53
Hi again @Ryochan7. This specific issue (as being reported here, in this instance) does not seem to be related to the other known thumb stick issue AFAIT.

The following piece of configuration XML was found to be causing this issue:

```
    <Key>
      <RXPos>27</RXPos>
    </Key>
```

It is normally found near the bottom of the xml file, such as maybe the default profile. It is not removed automatically (but maybe it should be?).

I noticed that other xml keys are automatically added. For other default values population (which is different from older versions. But specifically it is the extra presence of this key element. I honestly dont know why it is there.

Here is the full XML location / context from top level node (with all other keys removed):

```
<DS4Windows>
  <Control>
    <Key>
      <RXPos>27</RXPos>
    </Key>
</DS4Windows>
```

Kind Regards,

**Closed** 2018-06-04 16:05 UTC
