### ISSUE TITLE
No longer running at startup as of 1.5.15

### ISSUE THREAD

**Issue by lewisohn** [Ryochan7/DS4Windows#487] opened 2018-11-14 09:34 UTC
Since updating to 1.5.15, DS4Windows does not run at startup, despite the option being selected. I've tried deselecting and reselecting it, and I've also tried both the program and task modes, to no avail. It's still listed in the Start-up tab of Task manager. Never had this issue before.

I use a DualShock V2 connected by USB and I'm running Windows 10 Home, version 10.0.17134.

**Comment by jimybobo** [comment] 2018-11-14 13:41
Same here hasn't worked since the last update to windows build 10.0.17134

**Comment by Ryochan7** [comment] 2018-11-14 15:42
This looks like a side effect of the second executive decision made with that version. DS4Windows requires administrator privileges now as having the application's manifest set to automatically launch as admin makes the app run better than choosing to launch as admin. I was expecting Windows to start prompting people with UAC security pop ups on startup but it looks like Windows actually blocks such applications from automatically launching at startup. Both startup methods use a startup link that points to DS4Windows.exe so neither method works.

It looks like some form of indirect launching would have to be performed to get this functionality working again. I could look again into whether using the requireAdministrator execution level really makes things better compared to using Explorer to launch the application as admin.

**Comment by Ryochan7** [comment] 2018-11-14 23:21
Testing shows that the execution level setting does matter. Implementing requireAdministrator in the manifest file makes the app perform better than using the **Run as administrator** option.

**Comment by Ryochan7** [comment] 2018-11-16 21:50
This latest attempt to change functionality goes to show how brittle DS4Windows is. Just wanting to change a couple of string allocations is enough to make DS4Windows perform poorly. No amount of tweaking has helped. This issue might seriously remain unresolved.

I don't feel like I can just revert the previous decision either. Running the app as admin is really needed as a safeguard for the **Hide DS4 Controller** routine to help prevent devices from getting permanently disabled. Better output performance has been nice as well.

**Comment by mika-n** [comment] 2018-11-16 22:15
Does it work if DS4Windows is launched via "When I Log On/When computer boots up" TaskScheduler job which is tagged as "run with elevated priviledges" option? 

If Steam causes problems then the same taskScheduler BAT/CMD batch job could first launch DS4Windows process and then after few secs Steam client.

**Comment by Ryochan7** [comment] 2018-11-17 00:49
The current Task method uses DS4Windows to launch the task instead of having the task run itself upon startup. I cannot remember if that decision was made due to a UAC issue or to avoid a cmd window. I would have to test it directly as there are no comments.

**Comment by Ryochan7** [comment] 2018-11-17 00:50
The real issue here is due to built in Windows security features.

**Comment by Ryochan7** [comment] 2018-11-17 23:54
Tried again for several hours and got nowhere.

**Comment by Ryochan7** [comment] 2018-11-18 02:50
I gave up and reverted back to using asInvoker for the public build.

**Comment by mooms06** [comment] 2018-11-18 21:41
Why not using the same workaround than CCleaner to run elevated without UAC prompt ?

This program can create a scheduled task for this purpose:

https://www.majorgeeks.com/files/details/uac_pass.html

**Comment by Ryochan7** [comment] 2018-11-19 03:34
I cannot duplicate some of the problems that I encountered around the time the Task based startup method was introduced. UAC issues are not a problem with various approaches used for the Task. It looks like I set the Task to run a cmd prompt so that the underlying Task would end after that command prompt was done launching DS4Windows. Using a Task to launch the DS4Windows executable directly would cause the Task to remain active until DS4Windows is terminated. I am guessing the startup .lnk file is written more for convenience then anything else.

**Comment by mooms06** [comment] 2018-11-19 17:01
> Using a Task to launch the DS4Windows executable directly would cause the Task to remain active until DS4Windows is terminated.

And what's the issue with that ?

**Comment by Ryochan7** [comment] 2018-11-20 03:36
I just tested both versions of Run At Startup and they both work for me. Did you check the Startup tab in Task Manager and see if the entry is enabled? Deleting and writing a new shortcut file will not affect that setting if it was disabled at one point. Minimize to Taskbar also works for me.

**Comment by mooms06** [comment] 2018-11-20 13:42
> 
> 
> It just seems like extra overhead that is not necessary. The Task only needs to launch the program and go away. There is no need to have it keep tracking the status of DS4Windows.exe to see when a user quits the program.

I really fail to see the problem with it.
Updated to 1.5.16, logged out, logged in, DS4Windows is launched with admin rights without flashing cmd window and no unneeded shortcut in startup, seems better to me.

Unrelated, but the UDP server fail often at the startup (AddressAlreadyInUse), I have to stop DS4Windows, wait few seconds, then start it, sometimes 2 or 3 times (see the log).
Maybe delaying the startup of the UDP server for 10 or 20 seconds can avoid the error.

Thanks for the update.




20/11/2018 14:30:54: DS4Windows version 1.5.16
20/11/2018 14:30:54: LinkedProfiles.xml can't be found.
20/11/2018 14:30:54: Starting...
20/11/2018 14:30:54: Connection to Scp Virtual Bus established
20/11/2018 14:30:54: Searching for controllers...
20/11/2018 14:30:54: Using Exclusive Mode
20/11/2018 14:30:54: UDP server listening on port 26760
20/11/2018 14:30:54: Couldn't start UDP server on port 26760, outside applications won't be able to access pad data (AddressAlreadyInUse)
20/11/2018 14:30:59: Stopping X360 Controllers
20/11/2018 14:30:59: Closing connection to Scp Virtual Bus
20/11/2018 14:30:59: Stopping DS4 Controllers
20/11/2018 14:30:59: Stopped DS4Windows
20/11/2018 14:30:59: Closed UDP server
20/11/2018 14:31:00: Starting...
20/11/2018 14:31:00: Connection to Scp Virtual Bus established
20/11/2018 14:31:00: Searching for controllers...
20/11/2018 14:31:00: Using Exclusive Mode
20/11/2018 14:31:00: UDP server listening on port 26760
20/11/2018 14:31:00: Couldn't start UDP server on port 26760, outside applications won't be able to access pad data (AddressAlreadyInUse)
20/11/2018 14:31:01: Stopping X360 Controllers
20/11/2018 14:31:01: Closing connection to Scp Virtual Bus
20/11/2018 14:31:01: Stopping DS4 Controllers
20/11/2018 14:31:01: Stopped DS4Windows
20/11/2018 14:31:01: Closed UDP server
20/11/2018 14:31:01: Starting...
20/11/2018 14:31:01: Connection to Scp Virtual Bus established
20/11/2018 14:31:01: Searching for controllers...
20/11/2018 14:31:01: Using Exclusive Mode
20/11/2018 14:31:01: UDP server listening on port 26760
20/11/2018 14:31:01: Couldn't start UDP server on port 26760, outside applications won't be able to access pad data (AddressAlreadyInUse)
20/11/2018 14:31:02: Stopping X360 Controllers
20/11/2018 14:31:02: Closing connection to Scp Virtual Bus
20/11/2018 14:31:02: Stopping DS4 Controllers
20/11/2018 14:31:02: Stopped DS4Windows
20/11/2018 14:31:02: Closed UDP server
20/11/2018 14:31:06: Starting...
20/11/2018 14:31:06: Connection to Scp Virtual Bus established
20/11/2018 14:31:06: Searching for controllers...
20/11/2018 14:31:06: Using Exclusive Mode
20/11/2018 14:31:06: UDP server listening on port 26760
20/11/2018 14:31:06: Couldn't start UDP server on port 26760, outside applications won't be able to access pad data (AddressAlreadyInUse)
20/11/2018 14:31:12: Stopping X360 Controllers
20/11/2018 14:31:12: Closing connection to Scp Virtual Bus
20/11/2018 14:31:12: Stopping DS4 Controllers
20/11/2018 14:31:12: Stopped DS4Windows
20/11/2018 14:31:12: Closed UDP server
20/11/2018 14:31:17: Starting...
20/11/2018 14:31:17: Connection to Scp Virtual Bus established
20/11/2018 14:31:17: Searching for controllers...
20/11/2018 14:31:17: Using Exclusive Mode
20/11/2018 14:31:17: UDP server listening on port 26760
20/11/2018 14:31:17: UDP server listening on port 26760

**Comment by fersnake** [comment] 2018-11-21 23:11
I updated to from 1.5.3 and it stop working too, the funny thing that I rolled back but the issue percist. Gonna update to 1.15.16 and see if that works.

I'm on windows 10 x64 1809 with Uac disable

**Comment by Ryochan7** [comment] 2018-11-24 08:18
I tested both ways of executing the task. Having the Task launch DS4Windows directly causes some very noticeable slowdown. The process priority is changed to High priority by DS4Windows at launch and Task Manager confirms that it is running with High CPU Priority. Using Process Explorer shows that both memory and IO priority are set to low though. Having the Task launch cmd and then launch DS4Windows works fine for me even though memory and IO priority are still set to low.

I never heard of being able to change the memory priority of a process before. It looks like the WinAPI calls that you linked to work in Windows 8 and above though.

**Comment by rabrad5** [comment] 2018-11-24 16:44
Hi. I too, have the program not running at startup after updating to latest release. It's active in task manager's startup, tried both with task and program mode and also tried reinstalling the app. Running it in admin mode.

**Comment by Ryochan7** [comment] 2018-11-28 19:22
I just tried this with a fresh 1.5.16 folder. It worked for me just fine. I guess I should mention that it will take about a minute or two in order for DS4Windows to fully launch at startup especially when launched as a Task. There is nothing that I can do about that as it seems the issue is more with the .NET Runtime than anything else. Make sure to check the Task Manager for a DS4Windows.exe process as Task Manager should show that the process has already been launched even if it is not fully initialized.

**Comment by rabrad5** [comment] 2018-11-29 10:09
I've replicated your steps and it didn't work. It might be something to do with my computer in specific (Anti Virus probably, I dunno). The workaround that I've found to make it work was to create a task to run the exe at login. Working like a charm now! 👍

**Closed** 2018-12-09 19:36 UTC

**Comment by Ryochan7** [comment] 2019-03-13 03:15
I ended up looking into the IO and memory priority issue for tasks that was brought up before. The SetProcessInformation WinAPI call is only supported for Windows 8 and later so I didn't end up using that. Instead, the internal NtSetInformationProcess call is used since that seems to have been available since Vista. Normal IO and memory priority can be set even when DS4Windows is launched as a task. Performing the calls actually helps when the application is launched normally as well.

**Comment by Ryochan7** [comment] 2019-03-18 01:58
Version 1.6.14 has the change to force Normal IO and Memory priority for the DS4Windows process. Besides the benefits mentioned already, it fixes a long standing problem that I have experienced with slow startup time. DS4Windows now launches from a Task as quickly as using the Run As Program option.
