### ISSUE TITLE
Xinput Controller Order

### ISSUE THREAD

**Issue by Brandhor** [Ryochan7/DS4Windows#744] opened 2019-06-27 08:10 UTC
sometimes while playing a game I pull the usb cable connected to the ds4 but when I reconnect it it gets assigned as xinput controller number 2, what's weird is that if I do it again it always gets the number 2

now this is not a problem with most games but some of them only works with the first controller which means that I need to reboot to play it again, is there a way to avoid this?

**Comment by VladWinner** [comment] 2019-06-28 22:01
Confirm this problem since Version 1.7.11
This is very stressful in Rocket League for example, when another (real Xbox One) gamepad is not detected before connecting DS4 (xinput or dinput), and then real xbox gamepad works as a second gamepad, not as the first like early times (before 1.7.11)

**Comment by Ryochan7** [comment] 2019-06-29 23:50
The first post might indicate an issue with ViGEmBus. I just had ViGEmBus leave a dead virtual controller behind after an unplug event. The only way to get access to XInput slot 1 again was to reboot. That is a bit troubling and I doubt I will be able to reproduce this kind of problem intentional. Unfortunately, that means that there is nothing to report.

The second post just sounds like normal XInput functionality. If it worked differently before then the old behavior was wrong. XInput will assign slots as requested. In that scenario, the virtual Xbox 360 controller should have access to slot 1 while the Xbox One controller, that was plugged in later, would end up assigned to XInput slot 2. One other possibility for a difference in behavior could be due to Steam. Due to the way it handles XInput passthrough and emulation, you can re-arrange the controller order presented to a game launched from Steam. That might be a factor regarding a change in behavior.

**Comment by teeedubb** [comment] 2019-07-06 11:57
Hi,

I have been experiencing this issue with multiple versions of SCP + DS3, nefarious' new DS3 drivers and ds4windows. Its happens quite often during normal use. A scenario of this happening is you stop playing, do something else on the computer and then play later, you will be unable to get a controller assigned to #1 without a reboot. It is easy to replicate the issue, simply keep turn the controller on and off until it occurs.

**Comment by Ryochan7** [comment] 2019-07-06 18:50
The old ScpToolkit has not been supported for a long time. The fork of ScpVBus used by the toolkit likely had the same problems that the older build had especially regarding leaving dead virtual controllers behind. It is not a valid test target. It is interesting that the problem happens when using the FireShock driver though.

As it is, DS4Windows might not be the culprit in that case. Any problem would have to be narrowed down before something could be done to fix it. I don't own a DS3 controller and I didn't really like the controller the few times that I have used it. The problem would have to occur in a predictable way when using DS4Windows and ViGEmBus.

**Comment by Brandhor** [comment] 2019-07-06 19:07
I just want to add that this happens with both scp and vigem versions of ds4windows

**Comment by teeedubb** [comment] 2019-07-07 00:37
Agreed that its not DS4Windows, but I haven't been able to find much discussion on this problem... I thought it might be just my setup.
I have been able to force it happening in the past by turning on and off the controller - but it is random. It happened to me yesterday during normal use but this morning I wasn't able to force it happening.

**Closed** 2019-07-31 21:56 UTC

**Comment by Brandhor** [comment] 2020-06-17 18:23
I found out that as a workaround killing WinStore.App.exe fixes this issue and it's faster than rebooting
