### ISSUE TITLE
Can anyone confirm that on DualSense, changing color and rumble(games and ds4windows testing) works via Bluetooth on win7 x64?   10x!!!

### ISSUE THREAD

**Issue by Whatsup12345** [Ryochan7/DS4Windows#1689] opened 2020-12-24 00:49 UTC

**Comment by Whatsup12345** [comment] 2020-12-24 10:19
Is anyone else having the same problem? ....works fine on USB,.... but no rumble or color changing via Bluetooth,.... just to know to return it.

**Comment by magmadragoon** [comment] 2020-12-26 10:42
Same thing here, works via cable but not USB.

**Comment by mika-n** [comment] 2020-12-26 11:14
@Whatsup12345  There is not much information in your post. Please see the pinned "Read this before posting a new issue ticket". 
- Logfile?
- Gamepad version and model/revision?
- WinOS?
- Even the app version is missing from your post.
- Zip the profile file and place it here as an attachment with the logfile (rename logfile as .TXT before attaching here, not copy-pasting but drag-n-drop attach the logfile).

**Comment by Whatsup12345** [comment] 2020-12-26 12:33
Sorry for the lack of information :(,
- I'm running win7 x64;
- I had a Dualsense;
- I tried ds4windows Version 2.1.18 and Version 2.1.22
Everything worked perfectly with USB, but no Rumble and color changing on Bluetooth, I returned yesterday in the idea that it may have a problem with BT connection:(

**Comment by mika-n** [comment] 2020-12-26 21:46
okey, I don't have DualSense controller so someone with the DS5 and Win7 should test if that combination works.

**Comment by magmadragoon** [comment] 2020-12-26 23:47
I have the same problem with DS4 V1. OS is Windows 7. Light and rumble stopped working when connected via BT about a week ago (that's several versions, I got autoupdate on). Everything works in 2.1.16 I'm using right now.

**Comment by mika-n** [comment] 2020-12-27 00:02
Hmm.... 2.1.20 has this change and it may have something to do with this (i guess no one tested Win7 because Win7 is ancient history) .
https://github.com/Ryochan7/DS4Windows/commit/514538bc06b2dd20ced564506b68ec2646c766fd

How about if you try 2.1.19 version? Does it work?
https://github.com/Ryochan7/DS4Windows/releases

And 2.1.18 version had "Rumble and lightbar support for DualSense now work over BT" change.

**Comment by magmadragoon** [comment] 2020-12-27 00:59
Just tested. Works in 19, doesn't work in 20. So something broke in 2.1.20.

**Comment by Whatsup12345** [comment] 2020-12-27 02:30
I tried 2.1.18 and it didn't worked...I already returned it assuming that it may have a BT connection problem:(, I.m still on win7 becasue I have many software installed and it wont be easy to switch to win10.

"magmadragoon" ...DS4 V1 worked fine, but I broke it in Sekiro last week....the question seems to be .... if rumble and color change work on DualSense and win7 via Bluetooth...can anyone confirm that...?

**Comment by magmadragoon** [comment] 2020-12-27 08:23
Sorry, I don't own a DualSense controller so I can't test it for you.

Funny you should mention Sekiro. My problems started about the same time when I wanted to play Sekiro again and noticed it no longer recognizes my pad. Turns out it was because hiding DS4 doesn't work anymore, but I didn't know it at the time and went on to mess with DS4Win, gamepad drivers etc. Probably just a coincidence tho.

**Comment by Whatsup12345** [comment] 2020-12-27 11:02
"magmadragoon" I played Sekiro with DS4 on "DS4Windows by Jays2Kings" and everything worked fine, when I got the DualSense I had to switch to "DS4Windows - GitHub Pages" and I had the same problem, Sekiro didn't recognized my DualSense, also because "hiding" is not working properly on "DS4Windows - GitHub Pages" version, not for all games at least..., the solution was to install "HidGuardian", after that just find HidGuardian in "Registry Editor" and on "Affected Devices" just added my DualSense hardware id. I can give you more information's if you needed.

**Comment by Ryochan7** [comment] 2020-12-28 02:51
It will likely be several more days before I am able to test this for myself. Going to have to backup the data on my current Fedora install and nuke it. Then I can make a small Windows 7 partition for testing on real hardware.

**Comment by Whatsup12345** [comment] 2020-12-28 11:18
"Ryochan7"  10x man, I'll wait your testing,....for me it will likely be several month until I can move to win10, and if your test succeeds, than it means that my DualSense had some problems, so I will buy another one :)

**Comment by Ryochan7** [comment] 2020-12-31 17:13
Rumble with the DualSense when connected via BT is confirmed to **not** work on Windows 7. It is an issue with the way the Microsoft BT stack works on Windows 7 more than anything else. Rumble and lightbar support for the DualSense do not even work in Steam Input when running Windows 7 so it is not just a problem with DS4Windows.

DS4 BT rumble and lightbar support in Windows 7 was fixed in the latest DS4Windows release though. The Control endpoint is used again if DS4Windows detects that it is run on Windows 7.

**Closed by Ryochan7** 2020-12-31 17:13 UTC
