### ISSUE TITLE
8BitDo SN30 Pro+ drifting even while deadzone is active

### ISSUE THREAD

**Issue by OsoaGitHub** [Ryochan7/DS4Windows#2182] opened 2021-05-30 18:47 UTC
This is the exact same issue as shown in #1913, although changing the deadzone does not help at all.
[This](https://www.reddit.com/r/cemu/comments/nnig6e/what_is_causing_this_small_drift/gzxfnzt/?context=3) Reddit post I made demonstrates how a deadzone can cover the drifting and yet still occur even if it isn't shown in Cemu settings. I would tell you this on the last issue about this, but it was locked so I've had to create another.

**Comment by Ryochan7** [comment] 2021-05-31 20:55
Would probably need the profile XML file in question to have any chance of testing this. If those shots are to be believed, the mapping routine is not even being run at all and the raw input values are just being passed through.

The CEmu display makes it looks like it does not receive input at all. I am going to assume that CEmu has the virtual Xbox 360 controller open and the game in question is using the raw input controller values instead. This seems like multiple issues are happening and only one of those issues might be DS4Windows related.

**Comment by OsoaGitHub** [comment] 2021-05-31 21:39
[Link](https://pastebin.com/Hje98spw): here is my profile XML

**Comment by Ryochan7** [comment] 2021-06-04 19:07
So the controller is in Switch Pro output mode? The only way that I can see the mapping routine being skipped would be if somehow the JoyCon Joined workaround mode was active but that should not be happening. I am pretty sure I have tested the official Switch Pro controller support since that was implemented. JoyCon support has a way to ignore the mapper routine entirely for one of the two JoyCon controllers and just grabs the current controller state; the input loop for the other device (more likely JoyCon L) would run through the mapping routine.

Does DS4Windows actually state that the SN30 Pro+ is a Switch Pro controller in the main controller list? How is it being exposed in the list?

Also, I tested your profile with a DS4 and it is working as intended with a normal DS4. I will have to test it out with a Switch Pro controller as well.

**Comment by Ryochan7** [comment] 2021-06-04 19:24
The profile works as intended with a real Switch Pro controller. At this rate, I can only assume that somehow DS4Windows might actually be detecting the SN30 Pro+ as a pair of fake JoyCon controllers rather than a fake Switch Pro controller.

**Comment by OsoaGitHub** [comment] 2021-06-05 16:00
The controller is shown as a Switch Pro controller

**Comment by Ryochan7** [comment] 2021-06-05 16:16
Okay. So it is using the proper Switch Pro VID+PID combo. Those flags should not come into play then. Something else is making the mapping routine get skipped. Not sure if the Debug version of DS4Windows would help diagnose the root problem. Debugging in Visual Studio is probably out of the question.

There probably isn't much I can do without the actual hardware to test and play with.

**Comment by OsoaGitHub** [comment] 2021-06-05 16:25
Ah ok, that's annoying. I loaded it up in debug mode however there is nothing in the logs, so bump I guess

**Comment by Ryochan7** [comment] 2021-06-22 15:54
Closing. Can't do this anymore.

**Closed by Ryochan7** 2021-06-22 15:54 UTC
