### ISSUE TITLE
Error at startup with 2.0.14 and 2.0.15

### ISSUE THREAD

**Issue by subz6972** [Ryochan7/DS4Windows#1208] opened 2020-04-08 10:32 UTC
i have this weird error about denied access on DS4Updater.exe since 2.0.14, i dont have it when using 2.0.13 or previous ones 
(controler was working fine with that error so i realize it lately)
This is my logs :
[ds4windows_log_2.0.15.txt](https://github.com/Ryochan7/DS4Windows/files/4449886/ds4windows_log_2.0.15.txt)
[ds4windows_log_2.0.14.txt](https://github.com/Ryochan7/DS4Windows/files/4449887/ds4windows_log_2.0.14.txt)
[ds4windows_log_2.0.13.txt](https://github.com/Ryochan7/DS4Windows/files/4449888/ds4windows_log_2.0.13.txt)

**Comment by subz6972** [comment] 2020-04-10 01:25
a little reminder ... no idea about that case : 

2020-04-08 11:58:37.0806|INFO|DS4Windows version 2.0.15
2020-04-08 11:58:37.0806|INFO|Logger created
2020-04-08 11:58:37.1118|INFO|LinkedProfiles.xml can't be found.
2020-04-08 11:58:38.6896|INFO|Starting...
2020-04-08 11:58:38.6896|INFO|Connection to ViGEmBus 1.16.112.0 established
2020-04-08 11:58:38.6896|INFO|Searching for controllers...
2020-04-08 11:58:38.6896|INFO|Using Exclusive Mode
**2020-04-08 11:58:38.7365|WARN|System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Program Files\DS4Windows\DS4Updater.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at DS4WinWPF.DS4Forms.MainWindow.UpdateTheUpdater()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Program Files\DS4Windows\DS4Updater.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at DS4WinWPF.DS4Forms.MainWindow.UpdateTheUpdater()
   at System.Threading.Tasks.Task.Execute()<---**

2020-04-08 12:03:27.6763|INFO|Found Controller: 28:C1:3C:43:5D:BC (BT) (DS4 v.2)
2020-04-08 12:03:27.7232|INFO|Plugging in X360 Controller for input #1
2020-04-08 12:03:27.7232|INFO|Controller 1 is using Profile "Default"
2020-04-08 12:04:25.8584|INFO|Stopping X360 Controllers
2020-04-08 12:04:25.8584|INFO|Closing connection to ViGEmBus
2020-04-08 12:04:25.9833|INFO|Unplugging X360 Controller for input #1
2020-04-08 12:04:25.9833|INFO|Stopping DS4 Controllers
2020-04-08 12:04:25.9833|INFO|Stopped DS4Windows
2020-04-08 12:04:27.2480|INFO|Starting...
2020-04-08 12:04:27.2480|INFO|Connection to ViGEmBus 1.16.112.0 established
2020-04-08 12:04:27.2480|INFO|Searching for controllers...
2020-04-08 12:04:27.2480|INFO|Using Exclusive Mode
2020-04-08 12:04:27.2636|INFO|Found Controller: 28:C1:3C:43:5D:BC (BT) (DS4 v.2)
2020-04-08 12:04:27.2636|INFO|Plugging in X360 Controller for input #1
2020-04-08 12:04:27.2636|INFO|Controller 1 is using Profile "Default"
2020-04-08 12:07:37.4321|INFO|Request App Shutdown
2020-04-08 12:07:37.4321|INFO|Stopping X360 Controllers
2020-04-08 12:07:37.4321|INFO|Closing connection to ViGEmBus
2020-04-08 12:07:37.5104|INFO|Unplugging X360 Controller for input #1
2020-04-08 12:07:37.5104|INFO|Stopping DS4 Controllers
2020-04-08 12:07:37.5104|INFO|Stopped DS4Windows

**Comment by deadair3210** [comment] 2020-04-10 05:28
Put DS4Windows somewhere other than C:/Program Files.

**Comment by subz6972** [comment] 2020-04-10 12:03
> 
> 
> Put DS4Windows somewhere other than C:/Program Files.

Am i dumb ... that was the point ... i dont know why older releases worked in Program Files but all is fine now in a different folder ;-)

Thanks for your help.

**Comment by mika-n** [comment] 2020-04-10 12:25
The recent version of DS4Windows has some changes in permission logic of DS4Windows auto-updater feature. I'm sure it has something to do with the issue (elevated admin privileges vs user privileges).  C/ProgramFiles folder tree doesn't allow "normal user privileges" to write anything there (unless you tweak those folder permissions). 

https://github.com/Ryochan7/DS4Windows/commit/90f5a1b5d748ea1ba6ed42cd90fb9cdc26a38e88

**Comment by subz6972** [comment] 2020-04-10 17:10
Thanks for the explanation mika-n

**Comment by Ryochan7** [comment] 2020-04-12 09:34
It is an issue directly caused by resolving issue #1113. Currently working on changing how copying of DS4Updater.exe is done. I think I have a usable solution but it has not been tested yet. Once it is tested then I will push out a new version of DS4Windows. Also, I ended up adding a updater routine check that I had removed with DS4Windows 2.0 because I thought it was superfluous.

Since DS4Windows does not use a traditional installer, I would not recommend placing DS4Windows in the Program Files folder. I would use either a subfolder in C:\ or a subfolder in the Downloads folder.

**Comment by Ryochan7** [comment] 2020-04-12 15:59
Looks like the current approach should work. Ended up making a couple of other changes while I have been editing the updater routine. DS4Windows will now properly check for an updated DS4Updater version and download before attempt to run the updater. Beforehand, the latest version number was a const in the DS4Windows source code but now the latest version number is pulled from the DS4Updater repository.

**Comment by Ryochan7** [comment] 2020-04-12 16:39
Pushing this out

**Closed** 2020-04-17 18:20 UTC
