### ISSUE TITLE
Recurring issue with xinput setting itself to controller #2

### ISSUE THREAD

**Issue by CSeriesJTYPE** [Ryochan7/DS4Windows#1983] opened 2021-03-21 22:18 UTC
Hard to determine when and how this happens, but occasionally I'll lose all controller input and eventually discover the problem is the controller setting itself to #2, as indicated by going into the XInputChecker function. So far the only fix for this has been to uninstall and reinstall the ViGEmBus driver.

**Comment by DaRkL3AD3R** [comment] 2021-03-22 04:33
Yep known issue. I've been getting this for awhile, and the only solution for me so far is to reboot my PC. The trigger to reproduce it seems to be disconnecting a real controller and Vigembus not disconnecting the virtual one to match. It stays there, like a ghost device, lingering until you reboot and clogging up that slot #1.

**Comment by Ryusennin** [comment] 2021-03-22 11:26
Logging off/on is enough to recover slot 1. You do not need to reboot or reinstall ViGEm.

It only happens to me if I quit DS4Windows. Disconnecting the controller is ok, as long as I configure it to stay permanent (instead of dynamic) in the "Output Slots" tab.

**Comment by Ryochan7** [comment] 2021-03-22 12:44
It also depends on the version of ViGEmBus you are running. The problem was more likely to occur with older versions of ViGEmBus but it almost never happens with the current 1.17.333.0 driver. I have encountered it before as mentioned in issue #1597 and the only recourse to fix the problem was to reboot Windows; I think I have run into the issue twice total.

https://github.com/Ryochan7/DS4Windows/issues/1597#issuecomment-779407414

I don't know which version of DS4Windows you are using but more recent versions will close the connection to ViGEmBus if this error pops up and give a message telling you to reboot Windows; the changed message was added recently (2.2.11). The change was very helpful when I encountered the problem the second time around while working on some JoyCon updates; it might have been when working on implementing Gyro Directional Swipe.

**Comment by CSeriesJTYPE** [comment] 2021-03-24 13:57
Thanks for letting me know, I'll check which version of ViGEmBus I'm running.

**Comment by Ryochan7** [comment] 2021-03-30 17:21
Haven't had this happen in a while. As a reminder for myself, if it happens again, attempt to delete the associated Xbox 360 controllers in the Device Manager and see what happens.

Maybe I should test this out with the ViGEmBus 1.16.112.0 driver and see if I can force it to happen. Then maybe I can try that test.

**Comment by DaRkL3AD3R** [comment] 2021-03-30 17:25
Definitely still occuring on latest versions. I'm back to setting up a permanent xinput device and having DS4Windows run on boot and stay running in the background. If I disconnect my controller even once, problem appears again. Having the permanent device attached and never disconnecting it is a bandaid for now.

Also, I have tried removing the fake controller from device manager and somehow the issue persists. It will continue to plug in a controller to virtual port 2 instead of 1. I don't understand where it's getting hung up since there is no other xinput device physically or virtually installed on the PC at the time vigembus decides to set the new device to port 2, it almost makes me think this is some kind of miscommunication between the Windows xinput api and vigembus. It has to be.

**Comment by Dr4goonDemon** [comment] 2021-03-31 01:28
Same Problem Here, and the issue is that in windows games nothing happends but on emulators like cemu, yuzu or retroarch it stop working because theres no controller on port 1 so if my controller suddenly disconects while I'm playing when I reconect the controller again, I lose my game before the last save, if is a game that dont save its progress I loose all my playtrough, please fix this soon!

**Comment by twamer64** [comment] 2021-04-02 00:14
To me this happens very consistently every time I press to stop the application from the button on the bottom right of the window. When I press start again, it always goes to controller #2. It also happens on its own after a while even if I don't press to stop the application but that's more random. Either way, the only solution I have found is to reboot windows. Setting the thing to permanent instead of dynamic doesn't seem to do anything. I have the latest versions of DS4Windows and VGEmBus driver. I am on Windows 10.

**Comment by Gianlucas94** [comment] 2021-04-27 04:51
There's a way to force the vigem bus to close connection? maybe theres something that closes on a reboot that make it workaround for this problem?

**Comment by mika-n** [comment] 2021-05-21 06:42
Make sure you have the latest ViGem version installed (1.17.333 at the time of writing this). 
https://github.com/ViGEm/ViGEmBus/releases

But, other than that there is not much you or we can do if Windows and/or ViGem decides to rotate xinput slots. DS4Windows app has Slots feature and you can use it to set a certain slot as "Persistent" instead of the default "Dynamic". In Persistent mode a virtual output controller is kept alive even when a physical gamepad is disconnected and this way fooling Windows and/or game to think the same gamepad (and xinput slot#) is still in use. But, if even that doesn't help then that's it.

**Comment by Kanuan** [comment] 2021-05-21 06:46
On some tests, I noticed that Google Chrome, for some reason, keeps XInput slots alive sometimes.

Basically, closing Chrome and whatever game I'm currently playing, then stop/starting DS4Windows has been having a good chance of success in clearing the active XInput slots without needing to reboot the PC

**Closed** 2021-06-22 21:21 UTC
