### ISSUE TITLE
'Flash Lightbar at High Latency' sticking

### ISSUE THREAD

**Issue by OptimalJew** [Ryochan7/DS4Windows#126] opened 2017-10-06 21:46 UTC
Updated to 1.4.96, and shortly after pairing, my lightbar (which is normally disabled/0-0-0 RGB) turned red and stayed that way. Checked the log and as expected, I had a latency spike, but the log reported about a second later that it went back under the threshold. The light, however, remained red.

I'm not sure if this is intended behavior, since it seems to be at odds with the wording, so I figured I'd throw up an issue.

**Comment by Ryochan7** [comment] 2017-10-07 02:20
It should not work that way. The only time that I can get a guaranteed latency spike is when connecting or disconnecting a controller from the Sony dongle. I will have to test if the lightbar stays red in that case.

Looking at the routines, there might be one circumstance when a newer output report will not be sent to the controller which would cause the lightbar color to stay stuck.

**Comment by Ryochan7** [comment] 2017-10-08 03:43
The one scenario that I was thinking might be the cause actually could not happen due to the locking that was being done. I have tried to artificially test the lag lightbar flashing and the routine seems to work on my system. The only progress that I have made is that the routine for sending output reports has been tweaked and performance has improved.

**Comment by OptimalJew** [comment] 2017-10-08 13:25
I've been testing this by walking away from the receiver and tapping X until I get a red light, and the bar flashes momentarily and turns off as expected. When I originally had the problem, I had paired the pad and immediately opened Retroarch a second or two later, and then the light turned red and stayed that way. Could RA have interfered with the flash function? I am using exclusive mode.

**Comment by TristanYoung** [comment] 2017-10-13 12:52
This is happening to me too.

The light bar will turn red and stay red.  At first, I thought it was a low battery issue, since I use red to signify low battery (20%).  Since it was initially happening with older controllers shortly after I started gaming, I thought the battery wasn't able to hold much of a charge, and was on its way out.  I switched to a newer controller, and same thing started happening.

I try to use exclusive mode, but notice that recently it's been more difficult to obtain exclusive mode.  I don't run Steam, Origin, etc. at startup.

I'm using the latest Windows 10 insider preview (fast ring) always with the latest DS4Windows.

I don't use Retroarch, so I doubt the problem is due to Retroarch.

**Comment by Ryochan7** [comment] 2017-10-14 01:14
I am guessing it is just some weird runtime quirk between releases. I have tried to reproduce the issue on my end but the lightbar always reverts back to the assigned color when it is supposed to. How output reports are sent to the controller has been tweaked with the latest release so you might want to give version 1.4.97 a try. The only benefit that I have seen is that response time has improved a bit since there is less aggressive locking happening.

**Comment by TristanYoung** [comment] 2017-10-20 04:57
Just confirming that it is happening still.

When the "Flash lightbar when latency is..." setting is activated, I assume (will test tomorrow night) that it uses the low battery color?  If the battery gets super-low, does it also flash?  I want to make sure I'm not confusing the status.

Today I got more red light flashing using 3 controllers, the fourth controller was fine.  I leave 2 on my charging stand, and 2 off, with rotations.  2 are the original DS4 controllers, and 2 are the newer DS4 controllers.

Maybe it would be good to have a different color for flashing during low latency, if it is adopting the low battery color.

This was tested on the latest Windows 10 fall creator's update that was just pushed out to everyone.  I've been getting this during the insider preview fast channel updates.  Would be interesting to know if this has something to do with the Windows update.

**Comment by Ryochan7** [comment] 2017-10-21 01:59
I just installed the Windows 10 fall creator's update and the behavior has not changed on my system.

The lightbar is set to flash when latency gets too high along with changing the lightbar color. I believe that the latency lightbar routine has higher priority in the DS4LightBar::updateLightBar method; I checked and that does have priority over any lightbar settings in the profile. The lightbar color is a fixed color (R: 50, G: 0, B: 0) set in code. No setting in DS4Windows will change the color that is used when latency gets high.

**Comment by Ryochan7** [comment] 2017-10-26 09:11
Although the situation is different, I found a way to duplicate a similar lightbar problem. Changing the lightbar color via extras can cause the lightbar color to get stuck at the activated color in some situations. Debugging the code has shown that the actual data is up to date although the lightbar color on the controller is using the previously assigned color.

**Comment by Ryochan7** [comment] 2017-10-31 19:54
The most recent change involved sending out multiple output reports whenever the backend data changes instead of sending just one report to the controller. The workaround seems to work fine on my system. Since there has been no update on this issue, I am going to assume that it is safe to close this issue.

**Closed by Ryochan7** 2017-10-31 19:54 UTC
