### ISSUE TITLE
Hide DS4 not working for me on 1.4.118_x64

### ISSUE THREAD

**Issue by Nikorasu95** [Ryochan7/DS4Windows#270] opened 2018-04-27 14:30 UTC
I'm using Windows 10 Pro x64 (OS BUILD 16299.371) and connected my DS4 the one that comes with the PS4 PRO and Hide DS4 isn't working. Both wireless controller and Xbox 360 controller shows up in "Game Controllers". Also, I don't have STEAM or any program open that uses the controller before I launch DS4Windows.

**Comment by Ceril-Skye** [comment] 2018-04-30 19:35
Did you install the HIDGuardian files?

I had trouble with the ones on the wiki, and ended up installing the ones from InputMapper instead:
https://inputmapper.com/downloads/download/5-tools/76-inputmapper-hidguardian

After installing, make sure you run DS4Windows as administrator, and under the settings click on "Write HIDGuardian Device List"

**Comment by aidenn** [comment] 2018-05-02 11:28
Did you install WDK (https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian---Install-and-Setup-Guide)?

**Comment by InfinitePondera** [comment] 2018-05-03 05:13
Having the same issue as the guy above, reinstalling HIDGuardian doesn't work either. Only started happening after updating to Windows 10's April 2018 Update

**Comment by aidenn** [comment] 2018-05-03 11:08
I am on the April update and everything works fine, exclusive mode all the way. I am not using WDK or HIDGuardian though. WDK isn't exactly the smallest of downloads and most of the time DS4Windows catches the controller on startup before something else does anyway. On the off chance it fails, I turn off Steam, restart the service and it's fine again.

I'm using default settings + Hide DS4 Controller + I run DS4Windows as admin and in task mode, not program. Haven't had any issues with this, with both wired and wireless connections.

**Comment by InfinitePondera** [comment] 2018-05-03 18:05
Yeah, I've tried it without HIDGuardian because I had na older version of DS4Windows that didn't ask for it but Always worked flawlessly, but after the update it refused to hide the DS4 controller.
Thing is, it still finds my DS4 and connects it as "Xbox 360 Controller" just fine, it's just not able to hide it despite any other instructions.

**Comment by InfinitePondera** [comment] 2018-05-03 18:37
Hmm, it seems like using that experimental version of HIDGuardian worked, I went back to check the batch files from the stable release and it seems like they aren't installing it properly while the experimental installer is. Tested with a few games that were showing Steam's controller prompts instead of Xbox and now they're displaying correctly again.

**Comment by nalabrie** [comment] 2018-05-11 19:34
I'm having the same issue. I was using the original program and after a recent Windows update it wouldn't connect in exclusive mode. I found Ryochan7's version here and hoped it was fixed here but it isn't. Steam or any other game platform isn't started when the computer boots. I tried auto starting as a task but that isn't helping either.

**Comment by aidenn** [comment] 2018-05-13 21:03
Did you try the experimental version of HIDGuardian linked above and/or other steps listed in the wiki?

**Comment by nalabrie** [comment] 2018-05-14 00:57
I planned to but didn't have time and haven't been home since, I will try that next chance I get. Either way, I just wanted to chime in and let everyone know that they aren't the only ones with this issue. I thought it might help narrow down the problem.

**Comment by aidenn** [comment] 2018-05-14 09:16
Yeah, but it has to be something more specific than just the last update. I'm also on 17134 and exclusive mode is working fine without any HIDGuardian or WDK. From what I've seen so far, it seems that previous HIDGuardian releases seem to interfere with the process somewhat, but that's just my guess.

**Comment by Ryochan7** [comment] 2018-05-24 20:51
I have read posts on the InputMapper forums about the latest Windows update breaking HidGuardian in some way. I am wondering if the Windows update just happened to update the UpperFilters registry key and removed HidGuardian support as a result. Lately, I have not been running Windows much so I have not tested HidGuardian on my end lately. The older exclusive mode workaround works for me.

**Comment by MatTroiChanLy** [comment] 2018-05-30 11:08
I have the same issue after update Windows 10 to april update. I turn off steam, uplay and Nvidia geforce share overlay but still can't get Hide DS4 function working.

**Comment by aidenn** [comment] 2018-05-30 11:47
Well, if you've read this thread then you would know that there are two workarounds so far: use the experimental HidGuardian (link in this thread) or remove HidGuardian altogether (this one works for me).

**Comment by Nikorasu95** [comment] 2018-05-30 16:55
Even with hidgaurdian it's still finicky. The best thing that could happen would be both DS4Windows and InputMapper to release a update without anything extra needing to be installed. Bad thing another Windows 10 update just might break support again

**Comment by MatTroiChanLy** [comment] 2018-06-03 14:38
@Ceril-Skye Thank you very much. I just install HidGuardian from inputmapper website now hide DS4 controller function is working now. I'm about to give up and order a Xbox one controller.

**Comment by clayne** [comment] 2018-06-11 22:10
BTW: I did some of my own troubleshooting on this and found that Microsoft Edge has a handle into things for some reason. After killing the process (and children) via task manager exclusive mode works. I figured this out after explicitly disabling anything that could cause an issue (Steam, Geforce Experience, etc) yet something still had held access open. I then started nuking non-essential processes until I found out that Edge was involved. It may be indirectly involved (i.e. it uses a subsystem that gets involved with HID explicitly) but either way this was the sole remaining problem process.

This is with Windows 10 + latest updates and Sony wireless adapter.

**Comment by FirionHope** [comment] 2018-06-29 06:32
Which processes are related to edge?

Also how can you auto start ds4 windows as a task, you can't make startup programs run as administrator to my knowledge,

I can't get exclusive mode to work for the life of me, and a surprising amount of games need it to work or the controls don't work right, even with ds4 windows closed entirely

**Comment by Ryochan7** [comment] 2018-06-30 03:11
Running DS4Windows at Startup as a program does not allow elevated privileges. UAC prompts will still pop up if the exclusive mode trick has to be performed. There is some work done to ensure that DS4Windows can be run with elevated privileges when using the Task option. I double checked and using the Task option does work for launching the program with elevated privileges.

I avoid using Microsoft Edge so I would not now how it might interfere. It might grab HID devices in advance for sites that support the HTML 5 Gamepad API. Problems with Exclusive Mode will heavily depend on the software that is installed on your system. In my case, using GeForce Experience, uPlay, or playing a game like Broforce will cause exclusive mode to fail every time. The only sure way to get around the problem is to use HidGuardian. I have not been using HidGuardian on my system lately though.

As for games not working with the DS4 after closing DS4Windows, that is an issue with Bluetooth connections. Once DS4Windows opens the device and changes the input report type being received so that the touchpad data and gyro data are accessible, the DInput device is not usable anymore unless an application already had the device open. The DS4 would have to be disconnected and then re-connected in order to work with games that support the DS4 directly; USB and Sony Wireless Adapter connections do not have this problem. I have to try to see if the mode change can be reversed so that maybe the old DInput device can be used again.

**Comment by FirionHope** [comment] 2018-06-30 21:16
Thanks for the response. I have it as a task too apparently, but I've tried everything I can and can't get it to work as a task (though I'm not very good at it)

With geforce experience is it enough to just close the program? I like to use it and don't want to disable it entirely if I don't have to.

Good info on the bluetooth thing though, I'll try that out.

**Comment by Ryochan7** [comment] 2018-07-09 09:36
I tried to use different feature reports to try to get the DirectInput controller to work again but nothing worked.

**Closed by Ryochan7** 2018-07-09 09:36 UTC
