### ISSUE TITLE
Window size DS4Windows is not saved

### ISSUE THREAD

**Issue by maximus105** [Ryochan7/DS4Windows#1447] opened 2020-08-16 10:34 UTC
**Describe the bug**
The window size DS4Windows v2.1.5 is not saved even when the "keep this window size after closing" option is pressed.
I also checked DS4Windows v1.4.112. In this version also the window size DS4Windows is not saved even when the "keep this window size after closing" option is pressed. But there is also something in DS4Windows v1.4.112, that is not in DS4Windows v2.1.5:
1. Ability to test the left and right vibration motors at the same time (in DS4Windows v2.1.5, only one vibration motor can be tested at the same time. If, while the left vibration motor is running, press the test of the right vibration motor, the left vibration motor will stop. And vice versa).
2. In DS4Windows v1.4.112 everything is translated in the Russian language pack, while in DS4Windows v2.1.5 many words are not translated into Russian.
Please add these fixes to the next versions of DS4Windows.

**Comment by maximus105** [comment] 2020-08-24 07:04
The ability to test the left and right vibration motors at the same time is necessary in order to determine the correct vibration strength in relation to the center of the controller. It is also needed to distinguish an original gamepad from a fake one. In a fake gamepad, when testing two vibration motors at the same time, there is a noticeable rattling of the case, which indicates that the vibration motors are poorly fixed, etc. It is also needed to determine if the gamepad vibration is faulty. For example, when the controller is dropped and you need to adjust the vibration correctly when repairing the controller.

**Comment by mika-n** [comment] 2020-08-24 07:22
but (at least not yet) there is no separate left/right rumble strength setting, so trying to "center" the strength must be a bit difficult? But in theory and technically DS4Windows could have this master strength and optionally separate values for those two motors.

**Comment by maximus105** [comment] 2020-08-24 07:29
It's just enough that when you press the "test of the left vibration motor", and then when you press the next "test of the right vibration motor", the left one does not stop. (and vice versa). In DS4Windows v1.4.112, this is exactly how it works. (And that was right.)

**Comment by maximus105** [comment] 2020-08-29 10:54
I have checked DS4Windows v2.1.6 version. The window size is not saved even if you click the "keep this window size after close" option. What am I doing wrong? Or is this bug not fixed in v2.1.6 yet?

**Comment by Ryochan7** [comment] 2020-08-31 20:36
Two completely separate issues. No wonder the initial post didn't make sense. The button is doing exactly as intended and keeps the DS4Windows window the same size after closing the Profile Editor. After that, the option is no longer relevant as the current window size has been saved to the config. The real issue is that you want the window size to remain a larger size but the Profile Editor shrinks the window to a specified default size.

Never had to worry about the problem before as it did not bother me. The old WinForms GUI might have kept the current window size if larger than the Profile Editor default but I cannot remember. I will get on this shortly.

**Comment by maximus105** [comment] 2020-09-02 15:39
And the vertical borders of headers (ID, Status, Ex, Battery, Link Profile/ID, Selected Profile, etc) configured for themselves are still not saved after closing and then launching DS4WINDOWS:
![2020-09-02_183141](https://user-images.githubusercontent.com/58270614/92004492-f448dc80-ed4a-11ea-9bcc-3746c3497555.png)

**Comment by Ryochan7** [comment] 2020-09-02 18:18
The size of those headers have never been saved and there is no need to do so. It is too bad that WPF does not directly support relative sizing for those headers, using a GirdViewColumn, like WPF does for a normal Grid.

**Closed by Ryochan7** 2020-09-02 18:18 UTC

**Comment by maximus105** [comment] 2020-09-15 15:01
The finger drawing is drawn below the lightbar drawing, although in theory it should be the other way around (the finger drawing should be drawn on top of the lightbar).
![2020-09-15_175022](https://user-images.githubusercontent.com/58270614/93227787-6c68c680-f77d-11ea-9318-6859d6c1c134.png)
