### ISSUE TITLE
DualSense lightbar stays off when the controller is restarted (turning the pad off and on)

### ISSUE THREAD

**Issue by Feranthur** [Ryochan7/DS4Windows#1841] opened 2021-02-03 23:35 UTC
On version 2.2.4 (and possibly 2.2.3), the dualsense controller lightbar turns off when i restart it. Meaning, at first boot it all works fine, but when i turn the gamepad off (with PS+start) then turn it back on again in the same session the lightbar turns off after connecting to bluetooth (everything else seems to continue to work fine, however).

**Comment by giuseppe3349** [comment] 2021-02-04 21:40
it does so to me too

**Comment by TheMasterDingo** [comment] 2021-02-06 22:08
i have encountered this problem also, closing and opening ds4win fixes it

**Comment by h1riz** [comment] 2021-02-07 06:51
i have this problem too, i need to restart my controller again and restart ds4win tu fix it

**Comment by pablobolanos01** [comment] 2021-02-09 15:30
the problem is even worse when an output is set as permanent
multiplayer lights always work if its dynamic, but being permanent makes both lightbar and multiplayer lights turn off

**Comment by pablo5425** [comment] 2021-02-09 15:31
the problem is even worse when an output is set as permanent
multiplayer lights always work if its dynamic, but being permanent makes both lightbar and multiplayer lights turn off

**Comment by Ryochan7** [comment] 2021-02-18 23:01
This was fixed in version 2.2.6. Different reset flags are used when disconnecting from the DualSense now.

**Closed by Ryochan7** 2021-02-18 23:01 UTC
