### ISSUE TITLE
RDP kills DS4Windows from tray

### ISSUE THREAD

**Issue by Trihy** [Ryochan7/DS4Windows#2510] opened 2022-08-09 19:18 UTC
**Describe the bug**
Connecting through RDP, makes DS4Windows crash or disappear from tray.

**To Reproduce**
1. Connect to your Windows 11 PC using RDP from other Windows PC.
2. DS4Windows is not anymore on tray.
3. Still you can see a DS4Windows process on task manager.

**Expected behavior**
Stay on tray.

**Screenshots and Logs**
No needed

**Desktop (please complete the following information):**
 - Controller Make and Model: No need to connect any controller
 - OS:Windows 11 Pro
 - DS4Windows Version 3.1.2

**Additional context**
Didnt try previous builds.

**Comment by Diz-57** [comment] 2022-08-12 03:41
exactly the same issue here but im on win 10 enterprise 21h2 so its not a win 11 only thing

**Comment by Trihy** [comment] 2022-08-14 01:54
Hi. Thanks. Probably happens with most windows versions and RDP.

**Comment by Ryochan7** [comment] 2022-08-15 20:41
Confirmed. Key point: Start DS4Windows on a normal user session and then remote login via RDP. The tray icon will disappear after that but the main DS4Windows app will still work. Starting DS4Windows in an RDP session will work fine.

**Comment by Ryochan7** [comment] 2022-08-15 23:04
Confirmed as being a purely H.NotifyIcon package issue. Haven't completely diagnosed the problem but it looks like the routine hooked to the TaskbarIcon Unloaded event is what causes the tray icon to disappear and errors from user32.dll to occur during the later Loaded event. Disabling the Unloaded event keeps the error from occurring but that change would probably change the behavior of the tray icon in undesired ways.

Going to play with it some more. But I can say: I did nothing wrong. I did everything correct. Ack Ack Snort

**Comment by Ryochan7** [comment] 2022-08-16 06:03
I think I have found a minimal way around the issue. Seems to be working so far but I won't be committing anything just yet.

**Comment by Ryochan7** [comment] 2022-08-16 20:46
Should be fixed with commit b9bb9f7e1413c8069e7cbc0f0929d02862ea49dd

**Comment by Diz-57** [comment] 2022-08-17 17:36
yeah thats fixed it

**Closed** 2022-09-04 16:44 UTC
Labels: bug
