### ISSUE TITLE
lightbar coming back on

### ISSUE THREAD

**Issue by shogunreaper** [Ryochan7/DS4Windows#240] opened 2018-03-18 15:35 UTC
After idle disconnect/manually turning the controller off the lightbar will come back on ignoring the profile settings.

this is only a recent change, i went back and installed a bunch of old ones (tried 1.4.109-1.4.115) and it starts happening on 1.4.114

**Comment by Ryochan7** [comment] 2018-03-19 04:07
Duplicate of #238 

I will push a new release out tomorrow (2018-03-19) that fixes the problem. The build will mainly serve to acknowledge the one year anniversary of maintaining this project.

**Comment by Ryochan7** [comment] 2018-03-20 04:44
This issue should be fixed now.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.4.116/DS4Windows_1.4.116_x64.zip

**Closed by Ryochan7** 2018-03-20 04:44 UTC
