### ISSUE TITLE
DS4Windows Keeps Defaulting my Settings

### ISSUE THREAD

**Issue by MonfGeiger** [Ryochan7/DS4Windows#1995] opened 2021-03-26 21:54 UTC
**Describe the bug**
DS4Windows resets all custom settings back to default values (version 2.2.7)

**To Reproduce**
All I do is set ds4windows in my default windows firewall app and mcafee firewall to block al internet access

**Expected behavior**
I expect it to not reset my settings (theme choice, turning off the swipe profiles box AGAIN for the nth time in a row, etc...)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.1 (CUH-ZCT2U)
 - OS:Windows 10 Pro Version 20H2 (Build 19042.870)
 - DS4Windows Version [2.2.7 during the last instance of this problem, but I have now since updated to 2.2.15; yes I do have the .net runtime for it installed]

**Additional context**
More than once this problem with DS4Windows has caused it to forcefully restore all my chosen settings back to their default values, forcing me to set the theme back to dark, unchecking/rechecking boxes in settings, and when using a controller, I have to use the dropdown box and set my profile back to my custom made one. No matter what version number it was, 2.1.4, 2.2.5, 2.2.whatever, every version has (after a seemingly random amount of time, but feels close to 2 weeks, maybe a month of runtime after the previous instance) constantly taken all my custom chosen settings (excluding regular non-auto profile(s) ) and reset them to default. I have complained about this on the discord when it was up (sad to see it gone, R.I.P.), and so far beyond being buried under other users, no solution was proposed. So now I am forced to come here and bemoan this app and its way of doing things without my consent.  So far, I have not seen this problem with 2.2.15, but I just downloaded it and had it running for a short time

If this continues to happen even on 2.2.15, then there has to be a problem with it because I have done the holy trinity of windows cmd error commands, repair installs, the whole nine yards, and nothing. I'm tired of seeing this, and while I do wish ryochan and everyone contributing to this program safety in all forms and good tidings and all that, I would love it if whatever is causing this can be fixed. Closest github example I found that relates would be issue #1879

**Comment by Ryusennin** [comment] 2021-03-27 14:36
DS4W has no "way of doing things". If systematically resetting settings was a "feature", the forum would be swarmed with bug reports. That's not the case, _ergo_ the problem is on your side.

A shot in the dark: if you've installed DS4W in a system-protected directory (namely Program Files), try a customer folder or another drive. Windows 10 prevents any settings from being saved in Program Files if the application was installed manually.

**Comment by Ryochan7** [comment] 2021-03-27 17:52
I have not experienced issues with app settings being reset. There have been Profile specific issue that have been fixed as mentioned in that issue (commit 6c5cd50eca1bf981ab82030e7628fd7fa2f74ac5). Some recent controller specific settings have been fixed as well.

As it is, unless you have something more specific to report then there is nothing to do. Without some data or a case to reproduce the issue, either you have to narrow it down or wait for me to encounter the problem myself.

The most likely scenario at this point is the one that Ryusennin mentioned. You could have the app extracted to a write protected directory like Program Files so an updated settings file cannot be written. Another scenario is that the old settings file could have been corrupted so there is nothing to read and revert to defaults. It would probably occur too early in the process to show up in the Logger but an error about invalid XML characters at line 1 would indicate a corrupt XML profile.

**Comment by MonfGeiger** [comment] 2021-03-27 17:58
I have used both the appdata folder, and a folder on my desktop at separate times. Both have encountered this when I turn off ds4windows option to check for updates. Also, if I sent you my settings file, could you see if its indeed corrupted?

**Comment by Ryochan7** [comment] 2021-03-27 18:37
Commit 70cb0fb5720b6c574358d743f519249637b8acb0 now at least moves the app config loading to a point after the Logger is created. Not sure how much that will help.

If there is an issue anywhere, it would probably lie in the Global.FindConfigLocation method. That is one of the first methods run and it tries to determine if the application config files are found in either the DS4Windows installation directory or in the DS4Windows AppData directory; more specifically, it looks for the existence of the "Auto Profiles.xml" file rather than "Profiles.xml" for some reason. If that file exists in both directories, the app is set up to bring up the SaveWhere window asking which to use and it will delete the other version if you don't opt to skip that step.

**Comment by MonfGeiger** [comment] 2021-03-28 03:49
checking my auto profiles section, I do see that I had one set so if rpcs3 was on while ds4windows was still running, ds4windows would switch off while rpcs3 uses its own native ps4 controller support. I have since backed up my altdefault profile, deleted my ds4windows app data folder and made a fresh new one after importing my profile backup

all I got left now is to wait and see if that pops up again. if by some miracle what I did was the solution I needed, then I apologize for my behavior and frustration here, I just take umbrage against stuff like this and it only happens to me because reasons

**Comment by kjp949** [comment] 2021-04-04 22:00
I had this happen this morning with 3.0.1.  Did some gaming last night and no troubles.  Turned on my PC this morning and ds4windows was reset to default.  DS4Windows is installed @ C:\Users\myuser\DS4Windows 

Log from this morning:
> 2021-04-04 09:51:06.7538|INFO|DS4Windows version 3.0.1
2021-04-04 09:51:06.7573|INFO|DS4Windows exe file: DS4Windows.exe
2021-04-04 09:51:06.7573|INFO|DS4Windows Assembly Architecture: x64
2021-04-04 09:51:06.7573|INFO|OS Version: Microsoft Windows NT 10.0.19042.0
2021-04-04 09:51:06.7573|INFO|OS Product Name: Windows 10 Pro
2021-04-04 09:51:06.7573|INFO|OS Release ID: 2009
2021-04-04 09:51:06.7573|INFO|System Architecture: x64
2021-04-04 09:51:06.7573|INFO|Logger created
2021-04-04 09:51:06.8561|INFO|LinkedProfiles.xml can't be found.
2021-04-04 09:51:07.7094|INFO|Running as Admin
2021-04-04 09:51:07.7094|INFO|HidGuardian in use. Launching HidGuardHelper.
2021-04-04 09:51:08.9632|INFO|Starting...
2021-04-04 09:51:08.9632|INFO|Connection to ViGEmBus 1.17.333.0 established
2021-04-04 09:51:08.9632|INFO|Searching for controllers...
2021-04-04 09:51:08.9632|INFO|Using Shared Mode
2021-04-04 10:49:27.4241|INFO|The gamepad DualShock 3 (DS4 mode) (USB) uses custom feature set (NoGyroCalib)
2021-04-04 10:49:27.4241|INFO|Found Controller: 00:26:43:6B:BF:CD (USB) (DualShock 3 (DS4 mode))
2021-04-04 10:49:27.4902|INFO|Controller 1 is not using a profile. Battery level is 100%
2021-04-04 10:50:08.2121|INFO|Controller 1 was removed or lost connection
2021-04-04 10:50:45.9762|INFO|The gamepad DualShock 3 (DS4 mode) (USB) uses custom feature set (NoGyroCalib)
2021-04-04 10:50:45.9762|INFO|Found Controller: 00:26:43:6B:BF:CD (USB) (DualShock 3 (DS4 mode))
2021-04-04 10:50:45.9762|INFO|Controller 1 is not using a profile. Battery level is 100%
2021-04-04 10:51:37.5353|INFO|Controller 1 is using Profile "Default". Battery level is 100%
2021-04-04 10:51:37.5486|INFO|Plugging in virtual X360 Controller
2021-04-04 10:51:37.5486|INFO|Associate X360 Controller for input DS4 #1
2021-04-04 11:05:34.3480|INFO|Disassociate X360 Controller for input DS4 #1
2021-04-04 11:05:34.3480|INFO|Unplugging virtual X360 Controller
2021-04-04 11:05:34.3480|INFO|Controller 1 was removed or lost connection
2021-04-04 11:31:08.6366|INFO|Request App Shutdown
2021-04-04 11:31:08.6390|INFO|Stopping Virtual Output Controllers
2021-04-04 11:31:08.6390|INFO|Closing connection to ViGEmBus
2021-04-04 11:31:08.6390|INFO|Stopping DS4 Input Controllers
2021-04-04 11:31:08.6390|INFO|Stopped DS4Windows

Log from last night:
>2021-04-03 09:57:30.3134|INFO|DS4Windows version 3.0.1
2021-04-03 09:57:30.3134|INFO|DS4Windows exe file: DS4Windows.exe
2021-04-03 09:57:30.3134|INFO|DS4Windows Assembly Architecture: x64
2021-04-03 09:57:30.3134|INFO|OS Version: Microsoft Windows NT 10.0.19042.0
2021-04-03 09:57:30.3134|INFO|OS Product Name: Windows 10 Pro
2021-04-03 09:57:30.3134|INFO|OS Release ID: 2009
2021-04-03 09:57:30.3134|INFO|System Architecture: x64
2021-04-03 09:57:30.3134|INFO|Logger created
2021-04-03 09:57:30.4398|INFO|LinkedProfiles.xml can't be found.
2021-04-03 09:57:31.3257|INFO|Running as Admin
2021-04-03 09:57:31.3257|INFO|HidGuardian in use. Launching HidGuardHelper.
2021-04-03 09:57:32.5837|INFO|Starting...
2021-04-03 09:57:32.5837|INFO|Connection to ViGEmBus 1.17.333.0 established
2021-04-03 09:57:32.5837|INFO|Searching for controllers...
2021-04-03 09:57:32.5837|INFO|Using Shared Mode
2021-04-03 11:32:55.8096|INFO|The gamepad DualShock 3 (DS4 mode) (USB) uses custom feature set (NoGyroCalib)
2021-04-03 11:32:55.8096|INFO|Found Controller: CD:BF:6B:43:26:00 (USB) (DualShock 3 (DS4 mode))
2021-04-03 11:32:55.8673|INFO|Plugging in virtual X360 Controller
2021-04-03 11:32:55.8673|INFO|Associate X360 Controller for input DS4 #1
2021-04-03 11:32:55.8788|INFO|Controller 1 is using Profile "Default". Battery level is 90%
2021-04-03 12:17:56.0733|INFO|Disassociate X360 Controller for input DS4 #1
2021-04-03 12:17:56.0733|INFO|Unplugging virtual X360 Controller
2021-04-03 12:17:56.0733|INFO|Controller 1 was removed or lost connection
2021-04-03 14:45:55.1383|INFO|The gamepad DualShock 3 (DS4 mode) (USB) uses custom feature set (NoGyroCalib)
2021-04-03 14:45:55.1383|INFO|Found Controller: 00:26:43:6B:BF:CD (USB) (DualShock 3 (DS4 mode))
2021-04-03 14:45:55.1383|INFO|Plugging in virtual X360 Controller
2021-04-03 14:45:55.1383|INFO|Associate X360 Controller for input DS4 #1
2021-04-03 14:45:55.5481|INFO|Controller 1 is using Profile "Default". Battery level is 100%
2021-04-03 14:46:08.8665|INFO|Disassociate X360 Controller for input DS4 #1
2021-04-03 14:46:08.8665|INFO|Unplugging virtual X360 Controller
2021-04-03 14:46:08.8665|INFO|Controller 1 was removed or lost connection
2021-04-03 14:52:18.4132|INFO|The gamepad DualShock 3 (DS4 mode) (USB) uses custom feature set (NoGyroCalib)
2021-04-03 14:52:18.4132|INFO|Found Controller: 00:26:43:6B:BF:CD (USB) (DualShock 3 (DS4 mode))
2021-04-03 14:52:18.4132|INFO|Plugging in virtual X360 Controller
2021-04-03 14:52:18.4132|INFO|Associate X360 Controller for input DS4 #1
2021-04-03 14:52:18.4132|INFO|Controller 1 is using Profile "Default". Battery level is 100%
2021-04-03 15:30:35.2338|INFO|Disassociate X360 Controller for input DS4 #1
2021-04-03 15:30:35.2338|INFO|Unplugging virtual X360 Controller
2021-04-03 15:30:35.2338|INFO|Controller 1 was removed or lost connection
2021-04-03 16:40:03.7375|INFO|The gamepad DualShock 3 (DS4 mode) (USB) uses custom feature set (NoGyroCalib)
2021-04-03 16:40:03.7382|INFO|Found Controller: 00:26:43:6B:BF:CD (USB) (DualShock 3 (DS4 mode))
2021-04-03 16:40:03.7382|INFO|Plugging in virtual X360 Controller
2021-04-03 16:40:03.7382|INFO|Associate X360 Controller for input DS4 #1
2021-04-03 16:40:03.7382|INFO|Controller 1 is using Profile "Default". Battery level is 100%
2021-04-03 16:48:52.3934|INFO|Disassociate X360 Controller for input DS4 #1
2021-04-03 16:48:52.3934|INFO|Unplugging virtual X360 Controller
2021-04-03 16:48:52.3934|INFO|Controller 1 was removed or lost connection
2021-04-03 18:14:56.5545|INFO|The gamepad DualShock 3 (DS4 mode) (USB) uses custom feature set (NoGyroCalib)
2021-04-03 18:14:56.5545|INFO|Found Controller: 00:26:43:6B:BF:CD (USB) (DualShock 3 (DS4 mode))
2021-04-03 18:14:56.5545|INFO|Plugging in virtual X360 Controller
2021-04-03 18:14:56.5545|INFO|Associate X360 Controller for input DS4 #1
2021-04-03 18:14:56.5664|INFO|Controller 1 is using Profile "Default". Battery level is 100%
2021-04-03 18:15:08.9085|INFO|Disassociate X360 Controller for input DS4 #1
2021-04-03 18:15:08.9085|INFO|Unplugging virtual X360 Controller
2021-04-03 18:15:08.9085|INFO|Controller 1 was removed or lost connection
2021-04-03 18:20:38.6589|INFO|The gamepad DualShock 3 (DS4 mode) (USB) uses custom feature set (NoGyroCalib)
2021-04-03 18:20:38.6589|INFO|Found Controller: 00:26:43:6B:BF:CD (USB) (DualShock 3 (DS4 mode))
2021-04-03 18:20:38.6613|INFO|Plugging in virtual X360 Controller
2021-04-03 18:20:38.6613|INFO|Associate X360 Controller for input DS4 #1
2021-04-03 18:20:38.6613|INFO|Controller 1 is using Profile "Default". Battery level is 100%
2021-04-03 18:44:13.9356|INFO|Disassociate X360 Controller for input DS4 #1
2021-04-03 18:44:13.9356|INFO|Unplugging virtual X360 Controller
2021-04-03 18:44:13.9356|INFO|Controller 1 was removed or lost connection
2021-04-03 18:50:18.9535|INFO|The gamepad DualShock 3 (DS4 mode) (USB) uses custom feature set (NoGyroCalib)
2021-04-03 18:50:18.9535|INFO|Found Controller: 00:26:43:6B:BF:CD (USB) (DualShock 3 (DS4 mode))
2021-04-03 18:50:18.9535|INFO|Plugging in virtual X360 Controller
2021-04-03 18:50:18.9535|INFO|Associate X360 Controller for input DS4 #1
2021-04-03 18:50:18.9581|INFO|Controller 1 is using Profile "Default". Battery level is 100%
2021-04-03 19:08:21.6731|INFO|Disassociate X360 Controller for input DS4 #1
2021-04-03 19:08:21.6731|INFO|Unplugging virtual X360 Controller
2021-04-03 19:08:21.6731|INFO|Controller 1 was removed or lost connection
2021-04-03 19:34:41.5208|INFO|The gamepad DualShock 3 (DS4 mode) (USB) uses custom feature set (NoGyroCalib)
2021-04-03 19:34:41.5208|INFO|Found Controller: 00:26:43:6B:BF:CD (USB) (DualShock 3 (DS4 mode))
2021-04-03 19:34:41.5208|INFO|Plugging in virtual X360 Controller
2021-04-03 19:34:41.5208|INFO|Associate X360 Controller for input DS4 #1
2021-04-03 19:34:41.5208|INFO|Controller 1 is using Profile "Default". Battery level is 100%
2021-04-03 20:01:07.4593|INFO|Disassociate X360 Controller for input DS4 #1
2021-04-03 20:01:07.4593|INFO|Unplugging virtual X360 Controller
2021-04-03 20:01:07.4593|INFO|Controller 1 was removed or lost connection
2021-04-03 22:23:55.8641|INFO|User Session Ending
2021-04-03 22:23:55.8641|INFO|Stopping Virtual Output Controllers
2021-04-03 22:23:55.8641|INFO|Closing connection to ViGEmBus
2021-04-03 22:23:55.8641|INFO|Stopping DS4 Input Controllers
2021-04-03 22:23:55.8641|INFO|Stopped DS4Windows

**Comment by Thabuki** [comment] 2021-04-09 16:44
I was having the same problem. My profiles.xml wasn't updating with my settings preferences. I would adjust them and, in the next boot, it would be default.

What I did to solve it was just manually shutting down DS4Windows once I changed the settings. I noticed the profiles.xml updated after that. Probably has something to do with how my pc has been turning off weirdly. 

Let me know if you need any more details about that.

**Comment by schroef** [comment] 2021-04-21 18:21
> FindConfigLocation

PS if the exe and the auto profiles both in appdata/roamingds4windows doesnt that still say both are true and therefor states firstrun and shows dialog savewhere?

**Comment by Ryochan7** [comment] 2021-05-10 04:13
Really, **NOBODY** should be using DS4Windows (or pretty much any Windows app) that way. Just because you can put a program in a config file folder like an AppData sub-folder doesn't mean you should. This isn't even a case that should have to be tested but I guess I have to.

**Closed** 2021-05-11 16:28 UTC

**Comment by schroef** [comment] 2021-05-15 12:42
Why did you state its better to put in AppData folder? am i mixing things up here, i a different issue you stated it was better to have the app in that folder due to rights?
