### ISSUE TITLE
Unique issue: DS4Windows seen as "dominant" Xbox 360 peripheral and cannot remove it?

### ISSUE THREAD

**Issue by TiredTeddybear** [Ryochan7/DS4Windows#1505] opened 2020-09-27 03:58 UTC
Hi, I have a strange issue. I normally have an off-brand Xbox 360 controller that I use to play games with, but I tried to use both Jays2Kings and Ryochan7's DS4Windows in order to use CEMU to emulate Fatal Frame V. However, it was too complex for me so I gave up. I have a problem now though where my video games won't recognize my off-brand controller unless they're running in Steam. However, they work with DS4Windows. I do not want to use DS4Windows, I want to use my Xbox 360 controller. Is there any possibility, short of a full system restart, that I could somehow remove DS4Windows entirely from my PC?

Edit - Solved the issue. I used a program called USBDeview to remove DS4Windows' USB entries on my PC, then I went to Start > Devices and Printers and set my X360 controller as the preferred device for older applications. So sorry.

**Comment by Ryochan7** [comment] 2020-10-16 18:52
This has been an odd recurring issue that is not inherently tied to DS4Windows. I have had it happen with the test mapper even when the app is not running. The last time this happened, XInput slot 1 was still reserved until I closed the Brave browser. At that point, XInput slot 1 was freed and available for use again. Odd.

**Comment by Ryochan7** [comment] 2020-12-31 17:40
Duplicate of #1163

**Closed by Ryochan7** 2020-12-31 17:40 UTC
