### ISSUE TITLE
DS4 possibly still being recognized as DS4 in exclusive mode?

### ISSUE THREAD

**Issue by stargoonman** [Ryochan7/DS4Windows#100] opened 2017-08-02 08:51 UTC
In One Piece: Pirate Warriors 3, with DS4Windows exclusive mode on, the game believes Dualshock 4 is on, and defaults the controller mode to dinput, mis-mapping most of the controls. (Remapping is not available for analog buttons).

So left and right trigger are somehow treated as pushing the right analog stick to left and right, and the X button on the controller is treated as A, and the Y button is being treated as B. All of the buttons are completely mismapped as well.

**Comment by Ryusennin** [comment] 2017-08-02 12:10
Might be a duplicate of issue #97, which seems specific to Win10.

**Comment by pedrovay2003** [comment] 2017-08-07 04:20
Do you have the Nvidia GeForce Experience installed, and is Sharing enabled? That's what caused the issue for me. Disabling Sharing and restarting DS4Windows fixed it.

**Comment by stargoonman** [comment] 2017-08-10 18:27
@pedrovay2003 When you say, Sharing, are you referring to a feature in GeForce Experience?
I uninstalled GeForce Experience quite long time ago.

**Comment by pedrovay2003** [comment] 2017-08-10 18:31
@stargoonman

Yeah, I was talking about the Sharing option in the GeForce experience; that's what was messing mine up, and it was also causing problems for a bunch of other people, thanks to a recent Nvidia update. Sorry, it was worth a shot.

**Comment by pedrovay2003** [comment] 2017-08-20 19:18
Hey, it seems like the latest version of the GeForce Experience fixes this issue; I have sharing on, and everything works in exclusive mode as it should now.

**Closed** 2017-10-05 22:50 UTC
