### ISSUE TITLE
NetBroadcastEventWindow and System Resource Notify Window Error on restart/shutdown. [Latest version]

### ISSUE THREAD

**Issue by Norbi095** [Ryochan7/DS4Windows#1343] opened 2020-06-12 20:45 UTC
The latest release has a bug/exception problem in connection with .Net runtime, etc.

It refers to NetBroadcastEventWindow & System Resource Notify Window on DS4Windows.exe when either shutting down, or just restarting the system with DS4Windows running in the background.

The problem is very random though, out of 10 tries reproducing it, only around 5 times that it happened, but the error window keeps popping up, preventing the system to shutdown/or restart proprely.

**Comment by mika-n** [comment] 2020-06-18 09:15
Do you have logfiles or screenshots from the error?

**Comment by Norbi095** [comment] 2020-06-18 17:41
Logs show nothing about the problem at all, but here's an a pic about when it happens on restart/shutdown:
And trust me when I say I've tried everything, I even reinstalled both my PC's completely in the last 3 days just because of this One problem, and it Still (!) persists!
![20200615_184659](https://user-images.githubusercontent.com/52379192/85053998-af75c680-b19b-11ea-9cdd-e8c7d7a31159.jpg)

**Comment by mika-n** [comment] 2020-06-18 19:52
Hmmm... Strange. Some internal wnd resource/event listener in WPF/.NET apps. Now what it does and why is it failing in your setup? Good question...
https://github.com/microsoft/PowerToys/issues/3333

Do you have some special multimonitor/monster resolution/zoom/blingbläng monitor or desktop theme settings?

How do you launch DS4Windows app? Automatically on system boot? If you run DS4Windows manually and then close it before shutting down the PC then is it giving the same message? Or if you leave it open while shutting down then how it goes?

**Comment by Norbi095** [comment] 2020-06-19 17:57
So here's some information regarding the issue:
The app is set to start when I start up the system, so it launches all the time automatically (which is guess shouldn't be a problem).
My main PC (which is a desktop build) indeed is a dual-monitor setup, but the other PC I have the same issue on is a laptop, which.... is a laptop with of course only one main screen, so that is not what is causing this issue that's for sure.

And the problem showed up today as well on my 1 day old, fresh installation of Windows 10 (ver. 2004), on my laptop, this time referring to .Net Framework, instead of SystemResourceNotifyWindow in the error message

Starting to get really frustrated, as its pretty random, but got caught that it usally happens when I start up the PC, and then Turn it Off (pressing Shut Down in Start Menu) after like 1 minutes of run/uptime, it triggers it 8 out of 10 times at least with this, or the other message:
![20200619_190037](https://user-images.githubusercontent.com/52379192/85165912-d0efb480-b266-11ea-8845-9641d439c30f.jpg)

**Comment by Norbi095** [comment] 2020-06-19 21:23
Also, I forgot to add that, yeah, that would be the probably greatest way to be able to reproduce the issue in the first place, as I written it: 
"got caught that it usally happens when I start up the PC, and then Turn it Off (pressing Shut Down in Start Menu) after like 1 minutes of run/uptime, it triggers this exception 8 out of 10 times at least with this, randomly"

**Comment by Norbi095** [comment] 2020-06-24 23:19
Here are some of the logs I've found on in the Event Log:


Application: DS4Windows.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean ByRef)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(System.Runtime.InteropServices.SafeHandle, Boolean ByRef)
   at Microsoft.Win32.Win32Native.SetEvent(Microsoft.Win32.SafeHandles.SafeWaitHandle)
   at System.Threading.EventWaitHandle.Set()
   at DS4WinWPF.App.CleanShutdown()
   at DS4WinWPF.App.Application_Exit(System.Object, System.Windows.ExitEventArgs)
   at System.Windows.ExitEventHandler.Invoke(System.Object, System.Windows.ExitEventArgs)
   at System.Windows.Application.OnExit(System.Windows.ExitEventArgs)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at DS4WinWPF.App.Main()


Esemény XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-06-24T23:08:17.6329558Z" />
    <EventRecordID>10316</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Norbert-Laptop</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: DS4Windows.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean ByRef)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(System.Runtime.InteropServices.SafeHandle, Boolean ByRef)
   at Microsoft.Win32.Win32Native.SetEvent(Microsoft.Win32.SafeHandles.SafeWaitHandle)
   at System.Threading.EventWaitHandle.Set()
   at DS4WinWPF.App.CleanShutdown()
   at DS4WinWPF.App.Application_Exit(System.Object, System.Windows.ExitEventArgs)
   at System.Windows.ExitEventHandler.Invoke(System.Object, System.Windows.ExitEventArgs)
   at System.Windows.Application.OnExit(System.Windows.ExitEventArgs)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at DS4WinWPF.App.Main()

</Data>
  </EventData>
</Event>

These are one of the only actual log's that I've seen being generated after the problem shows up, in the DS4Windows directory there are no other logs/dumps or anything else.
Hopefully it helps a bit though.

**Comment by mika-n** [comment] 2020-06-25 18:56
Exception stack leads to built-in MS .NET libraries. Have you tried to does it work better when WinOS "speech and handwriting" support is disabled? Or have you updated MS .NET Framework library?

**Comment by Norbi095** [comment] 2020-06-25 19:31
Just tried both, and the "Speech and Handwriting features" were disabled, because they aren't even supported on my PC's language (hungarian), so that wasn't the cause of the thing.
.NET Libary are also updated, setup says its already installed on the system of course.. (its part of it).
Completely out of luck here, I might do another full reinstall of Windows, its getting very annoying. : (
Is it 100% must be on my end though, and not something with the software itself, based on the Runtime error log I've posted?
It will be my 2nd reinstall just because of this.... annyoning bug.

**Comment by mika-n** [comment] 2020-06-28 08:28
Difficult to say where the problem is because here the same scenario (DS4Windows set to start automagically on boot and shutting down and powering on the PC repeatedly) seems to work just fine. 
Maybe it has something to do the localization version of the WinOS/.NETFramework.

**Comment by Norbi095** [comment] 2020-07-02 16:44
Is there anything I could check maybe to help sorting out the issue?
Its still happening from time-to-time on both of my two PC's..

Or is there a chance that it could get sorted out in the next update maybe?
(If you need any other info regarding the issue, I will upload it)

**Comment by Norbi095** [comment] 2020-07-02 18:14
In the meantime I've found a post back from May, in the post a User was experiencing the same exact issue as I am, and you've mentioned that it could be related to MS Office in that post.

Thing is that the "Speech and Handwriting" feature is for Office 2003, and I have the latest  Office 2019 (365 Edition because of the licence I have) on my PC's, and there's no such option available to turn off/on, because that was used to be in the old 2003 version of Office.

The post was this one: https://github.com/Ryochan7/DS4Windows/issues/1295

Again, if I could send any info/logs to help sorting this out, I am willingly do so.

**Comment by mika-n** [comment] 2020-08-29 08:50
closed as "probably non ds4windows app issue, but WinOS setup issue"

**Closed by mika-n** 2020-08-29 08:50 UTC
