### ISSUE TITLE
Windows 11 issue? Controller stops working after it disconnects once from either BT or wire

### ISSUE THREAD

**Issue by Shinigati** [Ryochan7/DS4Windows#2387] opened 2021-08-01 06:45 UTC
So no idea if its because my windows updated to windows 11 in from the insider program in the beta channel but now every time my controller disconnects just once then only ds4windows and windows game bar is able to recognize it, steam can still detect my controller but it is not reading any inputs from it whatsoever, the only fix i've found is to restart windows but losing connecting or accidental wire unplugging can happen and it really messes me up when i'm playing on a game server.. i have also found restarting steam helps but steam crashes trying to exit after the issue starts and i have to end the process in task manager, i've tried everything from completely uninstalling both steam and ds4windows and my controller drivers but i have not found a solution yet.

**Comment by VladWinner** [comment] 2021-08-01 12:30
I also have the latest Windows 11 dev build installed. Steam successfully sees the gamepad whenever X360 mode is selected, but does not see DS4 in the device list after enabling DS4Windows.

But I found a workaround in which Steam games finally receive commands from DS4, even if Steam itself does not see the gamepad as an available device. Here's what you need:
1. Installed HidHide Driver
![image](https://user-images.githubusercontent.com/13555921/127770819-47f75626-71d1-437b-9779-4f773507755a.png)
2. Settings for HidHide
![image](https://user-images.githubusercontent.com/13555921/127770856-a5c9fbe7-9612-4800-8b82-c9a1f6ec8b15.png)
![image](https://user-images.githubusercontent.com/13555921/127770860-08061062-c630-43ac-958b-bea40cd0cfd6.png)
3. Profile with DS4 virtual controller
4. Steam in Big Picture mode

**Comment by Shinigati** [comment] 2021-08-01 14:25
I'm trying to use X360 mode not DS4.. i have special actions assigned to my ds4windows profile that just will not work using steams controller settings so i need to have my controller emulated as an Xbox controller through ds4windows and not steam, steam can see my Xbox360 emulated controller, and the steam icons change to xbox buttons whenever i press something while in big picture mode but neither steam nor any game can read any actual inputs.

**Comment by Kanuan** [comment] 2021-08-01 14:55
Go to DS4Windows' `Settings` tab and open the `XInput Checker` tool. Check if, when the problem occurs, if the controller has changed to another XInput slot. Sometimes games require the controller to be in XInput Slot #1 on in the specific Slot they were when the game was first started.

You can use [process explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to investigate what is keeping Slot 1 alive (I always bet on Chrome) 
![image](https://user-images.githubusercontent.com/24910442/123340694-05a1e600-d523-11eb-9e83-8d90ea1738f4.png)

**Comment by Shinigati** [comment] 2021-08-01 15:14
> Go to DS4Windows' `Settings` tab and open the `XInput Checker` tool. Check if, when the problem occurs, if the controller has changed to another XInput slot. Sometimes games require the controller to be in XInput Slot nº 1 on in the specific Slot they were when the game was first started.
> 
> You can use [process explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to investigate what is keeping Slot 1 alive. Sometimes it is google chrome, sometimes another random process.
> ![image](https://user-images.githubusercontent.com/24910442/123340694-05a1e600-d523-11eb-9e83-8d90ea1738f4.png)

This definitely seems to be what's happening, my controller has been assigned to Slot 2.. so how exactly do i determine which process is using slot 1 and go about changing it back? i have process explorer installed but just can't seem to figure it out from the search results it gave me.

**Comment by Kanuan** [comment] 2021-08-01 15:25
Open windows task manager (`Ctrl + Shift + Esc`) -> DETAILS tab -> find the process, right click it and `Open File location` to see where that leads you (DO NOT DELETE ANYTHING THERE, it's just for checking purposes), or alternatively google the process name and see what it might be related to.

I never really had problems with anything NVidia related or steam actually causing this issue though, but maybe those could affect other people.

**Comment by Shinigati** [comment] 2021-08-01 16:08
Yeah idk i don't think this is what's causing my issue, every time i unplug the controller the slot is different, the only thing using my controller is steam ds4windows and nvidia web helper.

**Comment by Ryochan7** [comment] 2021-08-01 16:12
I have not looked into the current Windows 11 Beta. Guess I will have to get on that eventually. It probably won't be that long before the official public release happens.

**Comment by Shinigati** [comment] 2021-08-01 16:20
Yeah it could just be poor drivers on microsofts part as it was working fine before i got hit with the update so feel free to close this issue once you can confirm, that was a misclick just now not sure why there wasn't some sort of confirmation box.

**Comment by velocity7** [comment] 2021-08-01 16:49
Just a thought on my end, but another possibility could be changes on Microsoft's part that are breaking ViGEmBus.

**Comment by Ryochan7** [comment] 2021-08-01 17:01
Going to try to get Windows 11 working in a VM. It definitely looks like I will not be able to run it on my hardware natively (damn lock-in measure). No update for me when Windows 11 is released.

**Comment by VladWinner** [comment] 2021-08-01 17:04
> poor _drivers_ on microsofts part

> why there wasn't some sort of confirmation box

In this case, go to the update log and see what has changed, and then just roll back the driver. You don't tell us your DS4Windows settings, but for some reason you are in a hurry to make assumptions about degradation of drivers due to Microsoft. If I can't confirm the problem with the same Windows build as yours, then it's unlikely that the problem is in components that Microsoft hasn't even touched.
Why don't you assume that the problem is in the Steam update, for example?
Please provide more information instead of speculation.

**Comment by Kanuan** [comment] 2021-08-01 17:30
Are you using the `Hide DS4 controllers` option? If yes, disable it and check if it might be the culprit.

If it's the case, leave this option disabled and use HidHide instead to hide the controller

**Comment by Masamune3210** [comment] 2021-08-01 19:20
I am on latest dev channel build and having no issues with my DualSense other than the dead battery bug, so if it is a 11 issue its not a definite one

**Comment by mika-n** [comment] 2021-08-01 19:51
It is also known that dualshock4 output mode may give problems in Steam because of stupid things Valve has implemented into Steam client. See the following doc page:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

**Comment by Ryochan7** [comment] 2021-08-01 21:11
Guess I cannot run Windows 11 in a VM either. Not sure if the lack of SecureBoot support would affect running it in a VM as well. No matter what, I cannot test this.

**Comment by VladWinner** [comment] 2021-08-01 22:03
> It is also known that dualshock4 output mode may give problems in Steam 

I have already described the procedure for solving this problem in https://github.com/Ryochan7/DS4Windows/issues/2387#issuecomment-890512470 (see above), tested with Windows 11

**Comment by Kanuan** [comment] 2021-08-01 22:09
> > It is also known that dualshock4 output mode may give problems in Steam
> 
> I have already described the procedure for solving this problem in [#2387 (comment)](https://github.com/Ryochan7/DS4Windows/issues/2387#issuecomment-890512470) (see above), tested with Windows 11 and Rocket League (where it is actually of little use due missing haptic feedback support that related to game devs)

You are mixing 2 different issues.

Your issue with rocket league not correctly detecting controllers is related to the [double input issue](https://kanuan.github.io/DS4WSite/guides/solving-double-input/)

Mika-n was taking about [Steam's behavior of ignoring DS4 controllers when it detects DS4Windows is running](https://kanuan.github.io/DS4WSite/troubleshooting/steam-related/) (though if it detects or not usually doesn't matter for the game itself detecting it)

**Comment by VladWinner** [comment] 2021-08-01 22:14
> You are mixing 2 different issues.

No, I didn't have double input issue before, only ignoring DS4 controllers by Steam, as described.

**Comment by ividyon** [comment] 2021-08-02 20:59
I'd like to say that I am experiencing the same issues on Win10. My controller is arbitrarily assigned to a lower XInput slot (ex. #3) sometimes, while games (like PSO2NGS) seem to only respond if it's on #1.

**Comment by ividyon** [comment] 2021-08-02 21:35
![image](https://user-images.githubusercontent.com/1077140/127925868-3d2b5fcb-6287-4567-b23d-1c1c5b911cef.png)

This appears to be statically stuck in Controller Slot 2 despite me trying everything to remove it:

- Turn off Steam, Chrome, anything that might use a controller
- Make sure no handles for "Xinput" are found in Process Explorer
- Stop DS4Windows
- Remove all Bluetooth devices in the "Bluetooth & other devices" settings window which might have to do with the controller (physical & virtual)

Despite all that, that input keeps showing in the Xinput Checker.

Turning DS4Windows back on, re-pairing the device, and reconnecting the controller, input only shows for "Wireless Controller" in the gamepad menu, and not for the XBOX 360 virtual one. DS4Windows makes no "device connected" noises, the controller doesn't receive the colors from the profile, and generally doesn't seem to connect to DS4Windows at all.

After a bunch of stopping/restarting the service, the same input (with the same stuck values) has now moved to Controller Slot 3. I don't even know anymore.

Restarting will most likely resolve all this, but it constantly seems to break like this after a prolonged break or disconnect.

**Comment by Shinigati** [comment] 2021-08-03 06:20
> > You are mixing 2 different issues.
> 
> No, I didn't have double input issue, only ignoring DS4 controllers by Steam, as described. I don't focus on Rocket League game itself (it's only an example). I already indicated that the issues may be related to the Steam update, and not destructive actions on Microsoft side.
> We still don't know if @Shinigati installed HidHide or not. Until then, the discussion looks redundant if the author does not provide any information yet.

I installed HidHide and set it up the same way as shown in [#2387](https://github.com/Ryochan7/DS4Windows/issues/2387#issuecomment-890512470) i then restarted my PC and it was not working at that point, it wasn't until i changed the output slots and set my controller to permanent that it started working again without any issues, so i believe the problem is now solved.

![image](https://user-images.githubusercontent.com/17960201/127966639-ca392b61-8f25-4c7b-ad5c-0bd9f66d8cb6.png)

**Closed** 2022-07-07 12:30 UTC

**Comment by velocity7** [comment] 2022-07-17 04:33
Hello, wanted to comment on this just now. Just tested DS4Windows 3.1.0 with Windows 11 and it works fine, even with HidHide and all that jazz.
