### ISSUE TITLE
Issue with vigembus driver

### ISSUE THREAD

**Issue by GeraltV47** [Ryochan7/DS4Windows#1635] opened 2020-12-06 10:58 UTC
When i open the ds4windows app by ryochan7 first time i see a window with two options, install vigembus driver and x360, i click install vigembus driver and ds4windows crashes, i downloaded and installed vigembus manually but ds4windows doesnt detect it,

**Comment by mika-n** [comment] 2020-12-06 16:26
Please take a look at the pinned "Read this before posting a new issue ticket". Now your post really doesn't have any information.

**Comment by MediaMaquina** [comment] 2020-12-11 18:24
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5680888/ds4windows_log.txt)
Same. Nothing useful on log. it seems.

**Comment by mika-n** [comment] 2020-12-12 21:55
Make sure you have installed all pre-requisites. Download the latest ViGem driver package manually and try to run it before running DS4Windows. Go through the ViGem installation logfiles to make sure there are no errors.  Check Windows EventLog for potential errors.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

**Comment by Ryochan7** [comment] 2020-12-13 13:21
The option works fine on my end.

**Comment by Ryochan7** [comment] 2020-12-29 01:29
Looks like a Windows 7 exclusive problem caused by the update to .NET Framework 4.8.

**Comment by Ryochan7** [comment] 2020-12-29 02:07
https://medium.com/@kyle.gagnet/your-net-code-could-stop-working-in-june-afb35fbf29ca

**Comment by Ryochan7** [comment] 2020-12-31 17:31
This issue is fixed in version 2.2.1. This issue came about directly as a result of targeting .NET Framework 4.8.

**Closed by Ryochan7** 2020-12-31 17:31 UTC
